### ISSUE TITLE
No File System Found for UNIX V7 RL02 disk image on PDP-11 SimH 4.0

### ISSUE THREAD

**Issue by brett3am** [simh/simh#1009]
When running SimH 4.0 as a PDP-11 booting UNIX V7, as per exact instructions in the SimH Sample Software Package instructions, I get the following error below when running the command "att rl0 unix_v7_rl.dsk".  Everything works perfectly when I go back to SimH 3.9 using the exact same settings, disk file and procedures, the only difference is the version 4.0 of SimH.
==================================================================================
PDP-11 simulator V4.0-0 Current        git commit id: 0912a927
sim> set cpu u18
Disabling XQ
sim> set rl0 RL02
sim> att rl0 unix_v7_rl.dsk
RL0: No File System found on 'unix_v7_rl.dsk', skipping autosizing
sim>
==================================================================================

**Comment by markpizz** [comment]
> Everything works perfectly when I go back to SimH 3.9 using the exact same settings, disk file and procedures, the only difference is the version 4.0 of SimH.

The 4.x version of simh defaults to autosizing disks based on what it can find as a file system on the disk image.  If it can't find a file system (due to, in this case, it not knowing how to examine a Unix_v7 disk for file system information), then, as it says, it skips autosizing.  3.x of simh only used the actual size of a disk container to help it determine how to autosize disks.  Sometimes this could be problematic since, with 3.x, newly created disks started out as 0 size, and depending on whether the file system(s) on the disk actually wrote to someplace relatively near the end of the logical space on the drive, an incorrect result could be realized when attempting to autosize the drive type for a particular disk container.

That said, I guess that it wouldn't hurt to try and fall back to using the existing container size to attempt autosizing.

Apart from that, I'd be glad to accept file system detection logic for Unix V7 file systems from someone ambitious enough to explore how.  FYI, the Ultrix autosizing was quite simple since all it had to do was find an Ultrix partition table on the disk and walk through that table to detect the partition which reached the farthest into the disk.

**Comment by brett3am** [comment]
Thank you so much for replying!!  That totally makes sense.  Is there a solution to using that disk image on 4.0, or would you suggest I just fall back to 3.9 in light of what you have just told me.  This emulator is absolutely amazing.  I created a photorealistic 3d virtual reality server room that I can literally walk around in with numerous DEC PDPs and other similar computers and mainframes that are emulated through simh.  You can sit down at the terminal and as you type on the real keyboard, you also type on the virtual VT-100 terminal.  You can even physically grab tape and disks and change them out.   Thank you so much for your work!!!!!!

**Comment by markpizz** [comment]
There is no problem using the disk image on 4.x.  You just have to be specific about the disk type (RL01 or RL02) that you used when you initially used the disk container.  The message that is emitted is merely informational.  If you 
```
sim> SHOW RL0
```
You will see that it is happily attached and will work just fine.  If there was file system detection logic for the Unix v7 file system, then the logic would emit a message telling you that fact and how big it was found to be.
If you want to suppress the informational message you could:
```
sim> ATTACH -Q RL0 unix_v7_rl.dsk
```

This information can be found in the 4.x HELP system.

**Comment by brett3am** [comment]
Excellent... thank you SO much!!!!

**Comment by brett3am** [comment]
Okay, I tried with RL01 and RL02, but still get "RL0: No File System found
on 'unix_v7_rl.dsk', skipping autosizing".  Am I missing a step?  I am
following the exact
instructions in the SimH Sample Software Packages pdf.

sim> set cpu u18
sim> set rl0 RL02
sim> att rl0 unix_v7_rl.dsk
sim> boot rl0
@boot
New Boot, known devices are hp ht rk rl rp tm vt
: rl(0,0)rl2unix
#

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by markpizz** [comment]
Clearly the disk worked just fine for you, which is what I said.  The fact that autosizing wasn't done since there is no way for the current code to recognize a Unix V7 file system doesn't mean that the disk isn't useful.  It just means that it doesn't know what is on it or how much of it may be used.

As I said you could put a -Q on your attach command and the "informative" message about "No file system found" will be suppressed and your repeated worry about  the significance of this message will go away.

**Comment by brett3am** [comment]
gotcha... totally my misunderstanding, I think I only got half of your
previous message (pesky Gmail threading)... totally makes sense.  Thanks
again so much for your help, I am at a working prompt now.  One last VERY
minor question, I see in the past you answered a question about slow
command listing with unix on pdp-11... which is easily solved with a ^D and
a login of root.  Just curious if you ever figured out what within Unix was
causing that as it is obvious that it is NOT caused by Simh itself.  Either
way thanks again so much, you have no idea how valuable your knowledge is
to people like me who are trying to really dig into these old machines and
operating systems... you are incredibly important to us.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by markpizz** [comment]
This problem was solved completely in the above discussion.  Meanwhile, since this report, the messages emitted by commands entered at the sim> prompt now are prefixed with %SIM-INFO: for informative messages and %SIM-ERROR: for errors.  Hopefully the general meaning will be more clear for folks going forward.
