### ISSUE TITLE
Feature request: indirection in EXAMINE command

### ISSUE THREAD

**Issue by al20878** [simh/simh#1033]
- #### Context

I was using the ``EXAMINE`` command lately and found it very cumbersome to examine memory locations, which are stored in registers.  The naive approach like
```
sim> EX @R1
```
(or ``(R1)`` ) would not work. So the only way seems to be a two step thing:
```
sim> ex r4
R4:     157420
sim> ex 157420
157420: 177404
```
which is extremely unproductive and tiring, esp. when one has to do this repeatedly to see where the registers are pointing to.
Maybe the ``@`` thing can be allowed multiple times and with the single (or multiple) memory addresses as well, to allow double pointers etc...  So ``@@r4`` would print what the device register at ``177404``  has to offer.  I prefer the ``@`` notation because it requires one less keystroke compared to the parentheses.

I might be missing something and there's another way, which I simply don't know -- then I'd greatly appreciate a pointer.
I found the ``$`` thing so that I can use something like:
```
sim> ex r4
R4:     157264
sim> ex $
157264: 016700
```
But it is still a two stepper, which need not to be so.

On a side note, ``HELP EXAMINE`` is a bit confusing about the ``ALL`` keyword. 
```
...
            register[ALL]           all locations in the specified register array
...
            ALL                     all locations in the unit
```
As apparently this does not work:
```
sim> e R[ALL]
Invalid argument
```

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> sh ver
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Polled Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 10.2.0
        Simulator Compiled as C arch: x64 (Release Build) on Apr 12 2021 at 12:27:46
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap not installed
        OS: CYGWIN_NT-6.1 ANTON 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin
        tar tool: tar (GNU tar) 1.34
        curl tool: curl 7.75.0 (x86_64-pc-cygwin) libcurl/7.75.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.0.4) libssh2/1.7.0 nghttp2/1.37.0
        git commit id: 371c937e
        git commit time: 2020-03-12T02:17:19-0400
```
- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
A key issue here is avoiding breaking some existing functionality when adding things like this.  The '@' character already has specific meaning.  It provides a way to redirect the command output to a file.

Meanwhile, as you said, you found the $ mechanism, but you complain that it requires 2 commands.  Well, it actually doesn't.  For instance:
```
sim> deposit R4 157420
sim> deposit 157420 177404
sim> ex r4,$
R4:     157420
157420: 177404
sim>
```
ends up adding 2 characters to the initial query string rather than your suggested one, which already meant something else.

This would seem to solve your problem, right?

Meanwhile, You say:
> On a side note, HELP EXAMINE is a bit confusing about the ALL keyword.
> 
> ...
>            register[ALL]           all locations in the specified register array
>...
>            ALL                     all locations in the unit

You may like to think of the set of processor registers as an array, but the simulator code doesn't declare them that way.  Each is a separate REGister and thus trying to create an array reference from your imaginary array isn't meaningful.
Once again, you could list the specific REGisters you are interested in a comma separated list and get all the results in one command, or you could get all of a DEVICE's REGisters in one command via ```EXAMINE <dev-name> STATE``` where ```<dev-name>``` defaults to the first DEVICE defined by the simulator (usually CPU).

The PDP11 simulator declares the interrupt request array (IREQ) as a REGister array, so examining the whole array's contents can be done via:
```
sim> EXAMINE IREQ[ALL]
IREQ[0]:        00000000000
IREQ[1]-IREQ[7]: same as above
sim>
```

I agree that there is some question about the bare ALL which I'm looking into but that's not really the key questions you've raised.  I'll follow up later with that.

**Comment by al20878** [comment]
>This would seem to solve your problem, right?

Indeed, ``ex r4,$`` is a very nice hint, thanks!

> but the simulator code doesn't declare them that way

How do I see all general purpose registers in one command?  Do I have to type all of them?
``EX STATE`` produces too much, very little of which is needed in most cases.

**Comment by markpizz** [comment]
Several ways: 
1) create a file called regs.  In that file put ```EXAMINE R0,R1,R2...```  ```DO regs``` will produce the output with minimal typing
2) use an environment variable
```
sim> set env REGS=R0,R1,R2...
sim> ex %REGS%
```

**Comment by al20878** [comment]
Not very trivial, but thanks, I guess I can live with that :-)
