### ISSUE TITLE
Help with FrontPanel

### ISSUE THREAD

**Issue by alanlefor** [simh/simh#1038]
Version 4.0 SIMH

Very anxious to use the FrontPanel app. I am not an experienced programmer, so I'd appreciate some help. I compiled it with MS VC 2019, but have a bunch of LNK errors 'unresolved external symbol _pthread... and _imp....'

I assume thats because I dont have the pthread libraries. I cannot make heads or tails out of the instructions to make the libraries.

Would greatly appreciate help

**Comment by markpizz** [comment]
I'm not sure what you are expecting or what you're actually doing here.  You didn't answer the various questions the issue template spells out when you created this issue.

In any case, it seems that your desire to see a FrontPanel isn't what's provided here.  You may notice that the program name is "FrontPanelTest".  This program is a test of the simh API that can be used by an application to either implement a GUI front panel or a hardware interface to control a running simulator.  Notice the key word "Test".  This program tests the API and is NOT a working front panel application which users would want to play with.

**Comment by alanlefor** [comment]
I really understand what you’re saying but would appreciate some guidance.

I want to test this program. 

Could you help me at least get it running? I think I need the pthreads lib. 


I am not terribly sophisticated as a programmer but I am motivated. I’d really appreciate some help. 

I want to compile it on Windows. 

For example, if you would be so kind to send me a .zip file that would load as a VS app and actually run. 

Thanks for your consideration

**Comment by markpizz** [comment]
Had you actually looked closely at the various directories in the simh repository, especially since you are using Visual Studio, you should have noticed the directory "Visual Studio Projects".  In that directory there is a file called 0ReadMe_Projects.txt.  You might have been curious enough to open that file and read it.  Careful reading might have suggested that you:

1) Have git installed and available in your path.  Installing from https://git-scm.com/download/win would be fine
2) Use Visual Studio GUI to open the simh.sln file in the Visual Studio Projects directory.  VS will convert to the current version.
3) Build the VAX simulator (needed by the FrontPanelTest program).
4) Use Visual Studio GUI to open the FrontPanelTest.sln file in the same directory.
5) Build the FrontPanelTest project.

The burden of how to learn how to use the tools at your disposal is completely up to you.  

Good Luck.

**Comment by mgthompson** [comment]
I always retarget the solution after converting to VS2017 of VS2019.

Open the Solution Explorer, right click on Solution 'FrontPanelTest', left click on Retarget solution.
The Windows SDK Version should be set to the latest version installed.
Left click on OK

Now you can rebuild the solution and it will compile OK.

**Comment by markpizz** [comment]
From the little information he provided, it was pretty clear that he didn't even touch the solution, but most likely just opened the source module and tried to compile it.  He certainly didn't compile the pieces that are specifically mentioned in the project file since he mentioned various link errors which wouldn't happen if the solution was in use.

**Comment by alanlefor** [comment]
In fact I did look closely at the directories. I did read that file. Thanks to the list you sent below, which is quite clear, I was able to compile it as you suggested.

 

I ask no one to assume my burdens, but when someone hits a stumbling block, guidance from someone with experience is most helpful and appreciated to avoid having to reinvent the wheel. 

 

Question---how does one configure PuTTY for use with FrontPanelTest. I did not see anything written about PuTTY but when I run the program, it gives an error message

 

 

Thank you

**Comment by alanlefor** [comment]
Dear Mr Pizzolato

Condescension is not an attractive quality. Your remarks are unnecessary, unappreciated and downright insensitive when someone asks sincerely for help with something you have experience with. 

In line with your comment about learning to use tools oneself, please contact me next time you need surgery. I’m happy to mail you a scalpel and you can do it yourself.

**Comment by markpizz** [comment]
> In fact I did look closely at the directories. I did read that file. Thanks to the list you sent below, which is quite clear, I was able to compile it as you suggested.

ABSOLUTELY NOTHING in what you said when you created this issue gave us a clue about these facts which you only slightly refer to after mentioning vague messages without providing details about exactly what you did.  When you created this issue, you COMPLETELY IGNORED the various details you were asked for in the issue template.  Of course, those were there for everyone else but you.  If you were actually sincere, you would help yourself by providing as much information as possible.

> I ask no one to assume my burdens, but when someone hits a stumbling block, guidance from someone with experience is most helpful and appreciated to avoid having to reinvent the wheel.

It is interesting that you say this, but then you provide no clue about how others may actually most easily help you given since you don't actually spell out precisely what you tried and what happened and what you expected even though you were specifically asked for this information when you created the issue.

> Question---how does one configure PuTTY for use with FrontPanelTest. I did not see anything written about PuTTY but when I run the program, it gives an error message

It works for me!

ONCE AGAIN, you make some vague statement about something strange happening, but don't provide details.  Ask complete questions and maybe you can get some help.

AS I IS SAID WHEN YOU OPENED THIS ISSUE:  You are looking at the test program which, by design, exists solely to exercise the front panel API.  IT IS DOES NOT in any way provide a slightly useful front panel.
