### ISSUE TITLE
Mismatch in declaration and arguments of sim_clock_coschedule

### ISSUE THREAD

**Issue by eg90804** [simh/simh#1040]
In sim_timer.c the function is used as t_stat sim_clock_coschedule (UNIT *uptr, int32 interval), whereas in sim_tmxr.c it is is called as sim_clock_coschedule_tmr (uptr, tmr, ticks).

**Comment by markpizz** [comment]
> In sim_timer.c the function is used as t_stat sim_clock_coschedule (UNIT *uptr, int32 interval), whereas in sim_tmxr.c it is is called as sim_clock_coschedule_tmr (uptr, tmr, ticks).

Look closely at the two DIFFERENT routines you refer to here.  They have different names, and thus it isn't surprising that they have different arguments.

**Comment by eg90804** [comment]
Hello Mark.
You are absolutely right, I used the wrong name, my bad.
I did mean that the function tmxr_clock_coschedule_tmr (uptr, tmr, ticks) does call sim_clock_coschedule (uptr, tmr, ticks) with 3 arguments instead of 2.
There is also a function called 'sim_clock_coschedule_tmr', which uses the same 3 arguments & types. Could it be that this function was intended to be used?

**Comment by markpizz** [comment]
What is going on is certainly potentially confusing since the argument change is happening, BUT essentially every compiler would be complaining about what you are pointing out if there really was a problem.  

As it turns out, we're not seeing errors due to the fact that the line of code you identify as a problem isn't actually ever compiled due to SIM_ASYNCH_MUX not being defined.  That functionality was an early effort to minimize polling for mux traffic since the vast majority of mux polling produces no results.  Avoiding the overhead of these unproductive system calls was the goal.  This was all implemented before precise input and output baud rate modeling was added to tmxr functionality.  Adding baud rate support changed the model of this I/O and the value of avoiding polling system call overhead is, as yet, unrealized.  At some point, I'll probably rip out that code to simplify things somewhat.  Avoiding mux polling could in theory save some 60 to 100 system calls per second.

Thanks for looking.

**Comment by eg90804** [comment]
Ok, that explains a lot. Thank you.
