### ISSUE TITLE
Restore operation fails on the restore of Qbus configuration while the simulator has a Unibus configuration

### ISSUE THREAD

**Issue by friesga** [simh/simh#1051]
- #### Context
When the simulator state in which a Qbus system was configured  is restored while the simulator has a Unibus configuration, the RESTORE operation fails with the messages "Invalid unit number: VH5" and "Command not completed".

The cause of these messages seems to be the line "vh_dev.numunits = (vh_desc.lines / VH_LINES) + 3;" in vh_reset() with a definition for VH_LINES being "(UNIBUS?16:8)". 

I was expecting that a RESTORE would be able to restore the simulator state regardless the current state. 

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 19.28.29336.00
        Simulator Compiled as C arch: x86 (Debug Build) on Jun 18 2021 at 15:26:18
        Build Tool: simh-Visual-Studio-Project
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: npcap or winpcap not installed
        OS: Microsoft Windows [Version 10.0.19041.1052]
        Architecture: x86 on AMD64, Processors: 12
        Processor Id: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD, Level: 23, Revision: 7100
        tar tool: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
        curl tool: curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
        git commit id: 6d9d72b0+uncommitted-changes
        git commit time: 2021-06-18T15:25:48+02:00
sim>

- #### how you built the simulator or that you're using prebuilt binaries
This is a home built simh executable.

- #### the simulator configuration file (or commands) which were used when the problem occurred.
See below

- #### the expected behavior and the actual behavior
`sim> show cpu`
`CPU     11/73, NOCIS, autoconfiguration enabled, idle disabled
        256KB`
`sim> sav image.tmp`
`sim> set cpu 11/70`
`Disabling XQ`
`sim> rest image.tmp`
`Invalid unit number: VH5`
`Command not completed`
`sim>`

**Comment by friesga** [comment]
The original title and text were just the wrong way around. I corrected both. This issue occurs when a Qbus configuration state is restored in a simh Unibus configuration state.

**Comment by markpizz** [comment]
OK.  I see the failure you are reporting.  

The PDP11 simulator has more DEVICEs than any other simulator and in order for SAVE/RESTORE to work correctly in every theoretically possible case, precise review of all combinations of settings on each device would need to be explored.  This is a ton of work for what actually is very little gain.  I say very little gain since I believe (but can be convinced otherwise), that RESTORE is only ever really useful when performed under at most 2 cases.  These cases are:
1) As the first "state changing command" after the simulator starts - this is the ONLY really useful case
and
2) As the first "state changing command" immediately after a SAVE operation that the current RESTORE operation is restoring - not particularly useful since the RESTORE shouldn't change anything since nothing has changed.

By "state changing command" I mean that things like ECHO and SHOW don't change the state of anything, while SET, ATTACH and potentially various others change the internal state information within one or more DEVICEs.

So, please explain to me when you think the command sequence you used to create the failure actually would be useful?

**Comment by friesga** [comment]
My usage scenario is in testing the functionality of the ROM device. I have a test script that saves the simulator state, executes SAVE and RESTORE commands and verifies that these commands are executed properly. The consequence is that I cannot execute tests for the ROM type M9312 and then restore the original state of the simulator to verify the ROM device is restored to its correct state.

Another reason why I would argue for solving this issue is exactly because simh is such a fine piece of software! It's just a pity that three simple commands suffice to make it fail an operation. My motivation to report issues like this is to make this product even better than it already is.

**Comment by markpizz** [comment]
> My usage scenario is in testing the functionality of the ROM device. I have a test script that saves the simulator state, executes SAVE and RESTORE commands and verifies that these commands are executed properly. The consequence is that I cannot execute tests for the ROM type M9312 and then restore the original state of the simulator to verify the ROM device is restored to its correct state.

But you certainly can IF you exit the simulator and start it over BEFORE attempting the RESTORE.  This sequence is actually why RESTORE exists (so that simulator state can be suspended and then brought back to its previous state and execution continued with minimal consequences).

The core problem with "solving" this is, as I mentioned previously, is that all arbitrary combinations of options on all devices must be mixed to completely cover the test space.  There are currently 54 devices and approximately 1963 SET commands and hundreds of ATTACH commands.  These combinations with all possible values that the various SET and ATTACH commands can have is the combinatoric test space your suggestion desires to work.  

> Another reason why I would argue for solving this issue is exactly because simh is such a fine piece of software! It's just a pity that three simple commands suffice to make it fail an operation. My motivation to report issues like this is to make this product even better than it already is.

Flattery sometimes works :-), but there isn't enough time left in my life (or possibly the universe) to walk through all of these combinations. 

Historically (over the going on 3 decades of simh PDP11 device development), it has been "nice" to have each device fully validated for preserved state across SAVE & RESTORE, but "nice" was never anything rigorous.  It  has been more than sufficient to play wack-a-mole to solve "real" problems that may be discovered as they are encountered.  "real" problems are the ones which reasonably are observed when a working system configuration was SAVED, the simulator exited and subsequently restarted and a RESTORE attempted that didn't work.  If you have such a specific case in mind, please describe it and I'll wack at that one.

**Comment by friesga** [comment]
I already guessed you weren't keen on solving this issue :-). I'll take this behaviour for granted and will close the issue. Thanks in any case for your reaction.

**Comment by markpizz** [comment]
I considered specifically adding logic around command sequence processing to reject RESTORE commands that are presented after any state changing commands (SET, ATTACH, etc.), but that wouldn't solve the problem you raised, instead merely restate something said above.

**Comment by friesga** [comment]
It would still consider that a work around. In my opinion the VH device shouldn't mess with its number of units since that field isn't saved and restored, unless a change would be made in order to save and restore that field or the device would be given  a chance to set the number of units during or after a restore operation.

During the development of the ROM device I myself experienced that changing the number of units causes save/restore issues and I solved it at that time (before getting rid of the units) by disabling the superfluous units instead of changing the number of units.

The fact that this hasn't manifastated itself as an issue is just because the number of units in a Qbus configuration is larger than in a Unibus configuration and the default state of simh is a Qbus configuration.

So, in my view, this is just a design flaw in the VH device.

**Comment by markpizz** [comment]
If you can demonstrate a working simulator configuration that:
1) is stopped by ^E (or never started) 
2) SAVED to a snapshot
3) simulator exited
4) simulator restarted
5) RESTOREd from the snapshot mentioned in step 2

And, that restore fails, then it falls into the wack-a-mole set of cases that historically have been addressed and will also will be addressed now since it fails for a "useful" RESTORE case which we're concerned about.
