### ISSUE TITLE
PDP10 simulator can't boot from empty disk drive

### ISSUE THREAD

**Issue by robmayes69** [simh/simh#1067]
- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

git clone https://github.com/simh/simh.git
cd simh
make -j4 pdp10

<img width="329" alt="Capture" src="https://user-images.githubusercontent.com/71886692/128914948-d74920fa-9e1b-4e69-9fcf-9a77ce7bbef3.PNG">
- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Hi @robmayes69, What you've provided so far is now merely a rumor about a potential problem.  Given the detail you've provided, so far, this is expected behavior and not an actual problem.  

In order for us to recognize this as a problem, PLEASE answer ALL the questions initially about configuration AND the provide a means of accessing the input disk/tape images you're using AND what/why you expect to actually happen.

- Mark

**Comment by robmayes69** [comment]
![image](https://user-images.githubusercontent.com/71886692/128935581-6fd027ba-94fa-4514-ad3f-adc1ddc2bf09.png)


SimH should return the BOOT> prompt rather than HALT.

There are no disk/tapes images required until after the BOOT> prompt>

**Comment by markpizz** [comment]
Once again:

PLEASE Answer ALL of the questions asked when you created the issue!

> There are no disk/tapes images required until after the BOOT> prompt>

Really?

Notice that when I start the simulator I DO NOT get a HALT message:

```
PDP-10 simulator V4.0-0 Current        git commit id: e03c83bb+uncommitted-changes
sim>
```

From the output supplied when you opened the issue, you MUST have done something besides starting the simulator, however you seem resistant to providing those details!

If you insist that no other files (BEYOND the configuration file, which this message proves MUST exist), then you should provide me with precise method to reproduce the failure you are seeing without additional files, otherwise it is still a rumor or some other user error on your part.

The questions asked when an issue is created exist to explicitly avoid this pulling teeth process you are subjecting both of us to!

**Comment by robmayes69** [comment]
Mark -

I probably didn't make myself clear enough in the first instance. To recap, yes, SimH runs as expected, as it does on my Windows build, but when using the exact same .cfg file to configure SimH to get to the next step, the BOOT> prompt, SimH encounters a HALT error.

Maybe you are confusing the creation of the 't10.dsk' as another file I am using, this is not the case, this is normal behaviour, it's created on the fly when disk drive rp0 is attached.

Hope this resolves any unanswered parts. Apologies if I did not provide as many details as required in the first instance, this is the first issue I've raised on Github.

Rob.

**Comment by markpizz** [comment]
> Hope this resolves any unanswered parts. 

Nope. you haven't moved the bar any closer to a reproducible problem, or a user error!

> Apologies if I did not provide as many details as required in the first instance, this is the first issue I've raised on Github.

The details that the issue asks for is a way for someone who looks at the problem you're reporting to actually see the failure or the user error.  Any report (about any piece of software, not just simh) that doesn't provide reproducible details is rumor or whining...  Think about it this way, how could someone (myself or others) help you if you "it works for me" without enough information.

On my Linux/Raspberry/Windows/MacOS environments when I simply invoke the pdp10 simulator executable, I absolutely see ONLY:
```
PDP-10 simulator V4.0-0 Current        git commit id: dcbfba0f
sim>
```

That's absolutely what is expected UNLESS you are counting on the simh default behavior which executes a file with the same name as the simulator{.ini} located in the current working directory (i.e. pdp10.ini in this case).

If you are counting on that, then you need to provide its contents (in a usable text form if it contains more than 2 lines) in the comment text (no image cut and pasting).

**Comment by markpizz** [comment]
If you are invoking the simulator with a particular .cfg file (as you mention being exactly the same), then you MUST provide it!!!!!! I invoke the simulator with an empty .cfg file and I get what I provided earlier, you must have something different!  Get it?

**Comment by robmayes69** [comment]
Mark -

The .cfg file was clearly shown in the initial screen shot. I'll gladly provide it, again:

attach rp0 t10.dsk
attach am -dz 2020

I have no .ini file or anything else.

I'm really not sure what angle you are coming from regarding this. We both agree, it would appear, SimH appears to provide the expected outputs on executing. What I am trying to convey, which might not be coming over, is that the latest build does not act as previous builds have, which is to invoke the BOOT> prompt. I will have to provide the show version from the build on my Windows box later.

**Comment by markpizz** [comment]
Those commands may have been PART of the configuration file, but certainly not all of it.  This is REALLY pulling teeth here.

As indicated in the output you provided, "attach rp0 t10.dsk" was line 2 of pdp10.cfg and "attach am -dz 2020" was line 3.  I know that line 1 must have existed (but is somehow something you seem to not divulge) and there MUST be more commands after line 3 as well.  Otherwise the simulator would never have started executing which ultimately ended up having it encounter a HALT.

PLEASE PROVIDE ALL OF the pdp10.cfg configuration file you were using!!!!!!!

**Comment by robmayes69** [comment]
Mark - apologies, I rechecked the file

Line 1 - set tim y2k
Line 4 - boot rp0

**Comment by markpizz** [comment]
There are 2 relevant commands related to what you're seeing:
1:
```
attach rp0 t10.dsk
```
Which, since you insist isn't relevant to the problem you're seeing, must have been created the first time you tried this which produced this output:
```
sim> atta rp0 t10.dsk
RP0: creating new file: t10.dsk
sim>
```
Notice that the new file iis an empty disk container file (which effectively contains 0's throughout).
Later on, you try again using this same file containing only 0's, and you report that output at the beginning of the issue.
I say this since you insist that the contents of t10.dsk isn't relevant to the problem you're seeing.
2:
```
boot rp0
```
which is an attempt to boot from the completely empty disk.

Since there's nothing on the disk, attempting to boot from it can't possibly work.  If you move the t10.dsk file that you've previously prepared with some useful contents (via download or a separate OS install from other media) from whatever system you happened to already have working and attach that instead of the empty disk, I'm sure it will work just fine!

**Comment by robmayes69** [comment]
Mark - 

Yes, it was my error, skipping the page in my notes regarding having to actually build a disk drive from .tap files to enable it to boot. 

Apologies for my oversight (stupidity) and thank you for your patience.
