### ISSUE TITLE
DZ issues with telnet access

### ISSUE THREAD

**Issue by al20878** [simh/simh#1077]
- #### Context

See below

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
- #### how you built the simulator or that you're using prebuilt binaries

simh as built from the latest git sources "make pdp11"

- #### the simulator configuration file (or commands) which were used when the problem occurred.

Trying to run RSTS/7.0-7 from downloaded from https://www3.ispnet.net/pidp11/systems.tar.gz
(directory `systems/rsts7`) by using the provided boot.ini file (and excluding the realcons additions from there), but
adding this:
```
sim> att dz 5555
```
and booting (check that DZ is actually in hardware configuration as viewed by the OS, by entering "HA" and then "LIST" at the first prompt, then "EXIT" and Ctrl/J (a couple times to boot into timesharing).

Now if you "telnet localhost 5555" it works the first time (notwithstanding that the OS does not acknowledge anything by any output on that line, for some reason -- that's a different issue, even though I tried to use both modem (-m) and (-a) and (-v), and combinations -- it's all the same and not working from the OS POV).  But once the line is disconnected from the telnet session (Ctrl/] then "close"), it can't be re-connected any longer.  Telnet keeps returning "connection reset by peer".  I checked that the port :5555 still appears to be in the LISTENING state.

Is that expected?  I thought it would allow to reconnect, regardless.

- #### the expected behavior and the actual behavior

BTW, DZ "help" is somewhat incorrect / incomplete:
```
sim> help dz set

DZ device SET commands:

set DZ 7B                       7 bit mode
set DZ 8B                       8 bit mode
set DZ 7P                       7 bit mode - non printing suppressed
set DZ DISCONNECT=val           Disconnect a specific line
set DZ ADDRESS=val              Bus address
set DZ VECTOR=val               Interrupt vector
set DZ AUTOCONFIGURE            Enable autoconfiguration of address & vector
set DZ LINES=n                  Display number of lines               <===== This should be "Set", not "Display"
set DZ LOG=n=file                                                     <===== Description is missing entirely
```

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

See above

**Comment by markpizz** [comment]
> Trying to run RSTS/7.0-7 from downloaded from https://www3.ispnet.net/pidp11/systems.tar.gz
(directory systems/rsts7) by using the provided boot.ini file (and excluding the realcons additions from there), but
adding this:
> 
> sim> att dz 5555
> 
> and booting (check that DZ is actually in hardware configuration as viewed by the OS, by entering "HA" and then "LIST" at the first prompt, then "EXIT" and Ctrl/J (a couple times to boot into timesharing).

I don't think that just waiting gets it all the way to enabling timesharing.  I say this since adding the following to the boot.ini after the "att dz 5555", but before the boot.

```
set debug -f stdout
set dz debug
set dz nodebug=trc
```

Notice that the MSE bit in the CSR of each DZ never gets set to 1.  Only after that is set will the DZ device notice any input on an incoming telnet session (or any session on a physical serial port).

**Comment by al20878** [comment]
So it's an OS's problem (most likely configuration, DZ wasn't properly inited / enabled) , but why the :5555 port accepts a telnet connection only once?  Once I disconnect, I keep receiving "connection reset by peer", for all the following telnet attempts.

**Comment by markpizz** [comment]
The listen port is established at ATTACH time.  The DZ device is structured so that it periodically polls for incoming connections  (i.e. calls OS accept()), ONLY after CSR MSE bit is set.  The TCP stack connects to the listening socket, but accept is never called.  I'm not sure why telnet thinks the connection has been fully established, but I think a simple program that called listen() but never calls accept() would behave the same way.  In the end this isn't a simh problem.

**Comment by al20878** [comment]
Ah, that makes sense -- the connection was accepted by the OS on simh behalf, but since accept() was not called, that created a pending case, I suppose.   Since listen() is used with backlog of 1 (sim_sock.c), that pending connection causes connection rejects for all other until cleared (by accept() from the application).  Why the backlog value is so low, BTW?  Two (perfectly) simultaneous incoming connection requests may not be served well with such a restriction (even if everything was working on the DZ side) -- one will be kicked out with "connection reset".

Please also take a note of "help dz set" that I mentioned above.

**Comment by markpizz** [comment]
The backlog is 1 since devices operating normally are supposed to poll for new connections reasonably frequently, so, since with a limited number of lines on a terminal mux, these incoming connections will either find an unused line or be told that there are none.  They'll either get a reject from the OS (as you see when accept isn't called) or a call to accept may succeed, but then find no available lines to hook the new connection to and thus get a reject message on the tcp circuit if telnet is enabled.

**Comment by al20878** [comment]
OS may not allow two simultaneous incoming connections for the same port # with a backlog of 1.  simh won't get a chance to issue an accept(), even if everything is available, yet one of the two (or more) simultaneous requests will be rejected by the OS for no reason but the low backlog parameter.  You should only use backlog of 1 when you expect exactly one incoming connection at a listening port (example:  FTP server's data connection that is awaiting a client that has issued the PASV command).

**Comment by markpizz** [comment]
If the connection rate to these services was expected to potentially be multiples per second instead of possibly multiples per hour increasing the backlog might be useful.  Think about how the behavior you observed to start this session would have been fantastically better off with a larger backlog...  You might agree that it wouldn't have helped.

I'll think about adding logic to the general mux layer that keeps track of how long its been since the last time a polls was done for new connections and when this value exceeds some value (maybe 5 seconds), a poll is done anyway and if a waiting connection is found a message is emitted on that new connection which says something like: "The running simulator is not accepting connections on <DEV> device at this time".  This would be more wordy than the OS response "connect reset by peer", and come out on the initial connection you observed, but its not clear it would be much help for a user experiencing this.

**Comment by al20878** [comment]
It's not about a _rate_ (that is, some really persistent pounding) but about a _coincidence_.  Two connections at the same time is not something extraordinary, esp. with some sort of an automation involved (e.g. when a system boots up and gets connected to by, say, a terminal server with persistent telnet port mappings).  Hence, having a backlog being a reasonable (and not so low) number is important.

As for my experience, then your foreseen fix would have helped diagnose the issue that I had with the OS, more clearly.  So, yes, it def will help in cases like these when the connections are not being picked up by the devices.  A timeout in the range of 5 to 10 seconds should generally be enough.

**Comment by markpizz** [comment]
Commit 49902b830e29ef987454a925694e653f42fd6370 adds an option has been added to allow a user to specify a desired backlog for any listening TCP connection at attach time.   

See HELP <tmxr-device> ATTACH for details
