### ISSUE TITLE
Suggestion: Have a configuration option to nice by 10

### ISSUE THREAD

**Issue by tuklusan** [simh/simh#1096]
By default, the classic 3.9/3.11 simulator "runs as fast as possible (although at lower than normal priority) and will consume
all available processing resources on the host system. This will raise power consumption (and the operating
temperature) of many PC’s and drain the battery of a laptop." It basically sets itself to nice 10.

A configuration option would be nice in the new 4.x beta. It will provide a easy way to run all SIMH instances at the same priority in a mixed classic/new environment without having to write wrapper scripts to launch with nice -n 10.

**Comment by markpizz** [comment]
The right solution to what you're describing is:

1) If you're running more than one simulator on the same host system concurrently, then you should start each of them separately and let them run for about 10 seconds before starting another.  If your host system has more than one CPU core, then you could start NumberOfCores-1 simulators concurrently.  This allows each of the simulators to determine the real capabilities of the host system without competing with other simulators for resources.
2) Most of the interesting simulators you may want to run concurrently have a method or detecting when the system running within the simulator is actually "Idle" where Idle means that useful work really isn't being done with CPU cycles.  Idling should be enabled for these simulators and thus they will generally use only a few percent of the host's CPU cycles in this mode.
3) Simulators that aren't Idle capable should probably use throttling so that they run at a speed that approximates what the original systems actually ran at.

> This will raise power consumption (and the operating temperature) of many PC’s and drain the battery of a laptop." It basically sets itself to nice 10.

The above suggestions will let the host system run with minimal impact on power and heat generation.  I don't think that ```nice 10``` would actually help at all given that it merely lowers the priority of a CPU bound process, but doesn't actually stop that process's demand for CPU cycles.

**Comment by markpizz** [comment]
Lacking any further comments here, I'm closing this issue.  If anyone has other input, please reopen it.

**Comment by tuklusan** [comment]
@markpizz I read your response carefully and went away and ran a bunch of experiments. I am happy to report that I got where I wanted to: 20 SimH instances (including two with graphical desktops) taking up just about 100% of just one core of a 10th generation i7. This includes a bunch of different operating systems running of VAXen, PDP-10 KS10, PDP-11.

Thanks. Here is my worksheet if there is any useful information for others.

https://docs.google.com/spreadsheets/d/153GA8w912kuKaNiY2WiW2iVs0az97y4q354NViN467U/edit?usp=sharing
