### ISSUE TITLE
PDP11: Garbage in memory / PC on simh startup

### ISSUE THREAD

**Issue by al20878** [simh/simh#1105]
- #### Context

Just pulled fresh source from github and built with `make pdp11`
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> sh ver
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Polled Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 11.2.0
        Simulator Compiled as C arch: x64 (Release Build) on Dec 29 2021 at 23:54:25
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap not installed
        OS: CYGWIN_NT-6.1 ANTON 3.2.0(0.340/5/3) 2021-03-29 08:42 x86_64 Cygwin
        tar tool: tar (GNU tar) 1.34
        curl tool: curl 7.78.0 (x86_64-pc-cygwin) libcurl/7.78.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.1) libssh2/1.9.0 nghttp2/1.44.0 libgsasl/1.8.0 OpenLDAP/2.5.7
        git commit id: d8d324de
        git commit time: 2021-12-17T15:06:41-0800
```
- #### how you built the simulator or that you're using prebuilt binaries

`make pdp11`
- #### the simulator configuration file (or commands) which were used when the problem occurred.

none
- #### the expected behavior and the actual behavior

```
$ BIN/pdp11

PDP-11 simulator V4.0-0 Current        git commit id: d8d324de
sim> ex state
PC:     000110           <---- WHY IS THIS 110?
R0:     000000
R1:     000000
R2:     000000
R3:     000000
R4:     000000
R5:     000000
SP:     000000
...
```
Garbage in the interrupt vectors' area, too (other locations seem to be clear):
```
sim> ex 70:130
70:     000000
72:     000000
74:     000000
76:     000000
100:    005267
102:    000014
104:    005267
106:    000012
110:    000773
112:    000000
114:    000000
116:    000000
120:    067153
122:    067153
124:    000000
126:    000000
130:    000000
```
which is basically:
```
.=100
100: INC 120
        INC 122
        BR 100
.=120
120: .WORD 67153
122: .WORD 67153
```
why is this code there?
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
I thought that the simulator should start with a clean machine (everything cleared to 0, memory / registers).  And I'm almost sure it used to be the case.  Am I missing something?

**Comment by markpizz** [comment]
simh simulators run on all sorts of host systems which range in performance from very slow to very fast,  

Many devices implemented within a simh simulator have timing behavior relative to the cycle execution of the original hardware, while other aspects of simulated devices have timing requirements which need to track with wall clock time.  A simple example is the clock ticks implemented by the simulator.

Traditionally a simulator has an initial default clock tick size and this value is initially used for early clock ticks during the simulator execution while the timing layer provided by the simulation framework is used to calibrate the actual instruction execution rate of the simulator.  This calibration process takes some number of seconds before the framework comes to a reasonable approximation of the actual instruction execution rate of the simulator (the default as I recall is approximately 10 seconds).  This means that until calibration has successfully determined the instruction execution rate, clock ticks will not likely track wall clock time very well (possibly off by orders of magnitude).  While simulator execution continues, clock calibration continually checks and adjusts the actual execution rate relative to wall clock so that clock ticks will progress accurately.

This usually doesn't make much difference when the simulator will be running for a long time (i.e. when booting and running an operating system), but some programs run for very short amounts of time and the above mentioned calibration never gets a chance to complete.

The simulation framework provides a means for simulator timing activities to leverage a concept called pre-calibration.  The pre-calibration process involves the simulator's CPU initialization logic to provide a small sample program which provides a reasonable mix of typical instructions and memory references and the framework executes this this mix of instructions before the simulator gets to the first sim> prompt.  That pre-calibration then becomes the initial default for the instruction execution rate used by the timing layer for all wall clock base delays (clock ticks, etc.), while the normal calibration process will continue from this point.

You've found the secret program that provides the pre-calibration activities for the PDP11 simulator.  Other simulators each optionally have their own <sim-name>_cpu.c provided pre-calibration instruction sets.

If you need to have all of the memory and register contents to be 0 when you start your simulator, feel free to provide initial DEPOSIT commands in your simulator's configuration to achieve this.  You will then have 0 everywhere and also be able to leverage the information gained by the pre-calibration process.

**Comment by al20878** [comment]
Well, I've been finding *way too many* "_secret_" places in SimH lately...

I don't have anything against you doing any "measurements" or whatever the simulator startup logic may require, but once you're done with that, why don't you clear the contents of the memory / PC / PSW (if any affected), leaving the freshly started machine in the pristine state as it is supposed to be?

I don't think it's any user's concern or responsibility to do any explicit `DEPOSIT`s: after all we can't chase your code with anything you might decide to "secretly add" in the future, here and there.  PC is expected to be 0, and the entire memory -- cleared, that's how the things are when the machine is powered on.  It's in the documentation for PDP-11.  SimH does not simulate this properly, thanks to the "secret" addition.  It's a simulator BUG.  It needs to be addressed in the _simulator code_.

**Comment by markpizz** [comment]
Please use 3.x and you won't find unexpected things and not have to do anything special.

**Comment by al20878** [comment]
Whoa, thanks for the quick fix

**Comment by markpizz** [comment]
> Whoa, thanks for the quick "fix"

My initial response was inspired by your snarky comment like:
> > Well, I've been finding way too many "secret" places in SimH lately...
---
Meanwhile, the logic in the simulator framework which implements the pre calibration activities ends with the equivalent of the SCP command: RESET -P which, by definition is supposed to reset all devices (CPU included) to their power up state.  How that is implemented is simulator and device specific.

Consulting with the PDP11 simulator author (@archivisth) about exactly what should happen to memory and CPU registers when a power up reset is executed.

I asked:
> > On the PDP11 (and other simulators as well), should:
> >
> >         sim> RESET -P
> >
> > clear memory?
> > clear the PC?

He explained:

> Clear memory - on core memory models (very early), memory would have been intact. On MOS memory models, memory would have been indeterminate (cells could float to either 0 or 1). There is no memory clearing logic or power-up microcode on any model.
> 
> The PC was not determinate either. For the J11:
> 
> ;1305    ;    Option        Result
> ;1306    ;    ------        ------
> ;1307    ;      0    Vector through location 24.
> ;1308    ;      1    Enter ODT.
> ;1309    ;      2    Power up to 173000.
> ;1310    ;      3    Power up to user boot address.
> 
> The power-up options are not simulated; the simulator always enters "ODT" (SCP). The user can simulate options 2 and 3 with "RUN xyz" commands in the .ini file. Option 0 (power fail recovery) is more 
difficult, at least in v3.X, because it requires:
>
> a) RESET ALL
> b) putting the contents of 24 into the PC and the contents of 26 into the PSW
> c) then doing GO.

So, the current  behavior of the PDP11 simulator is not an error.

Meanwhile, some of the other behaviors relating to boot options will be enhanced when I get around to finally merging the updated ROM code implemented by @friesga.

As I mentioned earlier, if you want the same results you somehow need to exist, your ini file can contain:

> DEPOSIT ALL 0
> DEPOSIT PC 0

**Comment by markpizz** [comment]
Add the following to your ~/simh.ini file:

```
if "%SIM_NAME%" == "PDP-11" DEPOSIT ALL 0
if "%SIM_NAME%" == "PDP-11" DEPOSIT PC 0
```
