### ISSUE TITLE
"Last Unallocated Sector in File System" ?

### ISSUE THREAD

**Issue by al20878** [simh/simh#1106]
- #### Context

Rather freshly built version of simh as reported in #1105

- #### the simulator configuration file (or commands) which were used when the problem occurred.

none
- #### the expected behavior and the actual behavior

```
sim> set cpu 11/70 4m fpp
Disabling XQ
sim> set rq0 ra72
sim> sh rq0
RQ0     1000MB, not attached, write enabled
        RA72, UNIT=0, autosize
        AUTO detect format
sim> dir test.dsk
 Directory of rsts

08/25/2021  05:19 PM     1,000,090,112 test.dsk
               1 File(s)     1,000,090,112 bytes
               0 Dir(s)
sim> att rq test.dsk
RQ0: 'test.dsk' Contains a RSTS File system
RQ0: Pack ID: RSTS10 Revision Level: 1.2 Pack Clustersize: 32
RQ0: Last Unallocated Sector In File System: 1953280
```
"Last Unallocated Sector in File System" is a misnomer.  What does it even mean?  Was it supposed to be "First sector beyond the file system" or the "Number of Sectors in the File System"?  Or is it the first sector that the file system does use but it was left not allocated to the container (and all sectors beyond)?

Now, if I do the math right, the total container size shown (per "dir") is 1953301 sectors.  The file system uses 61040 clusters (with DCS/PCS of 32), which corresponds to the "magic number" shown, 1953280.  From this I conclude that the "unallocated" sector is in fact "allocated" to the container (as it lies within 1953301 sectors), but it is certainly **NOT** in anyway "in File System", as it's the first sector _past_ the file system boundary.

**Comment by pkoning2** [comment]
Your arithmetic is correct as far as I can see, and yes, that number is the number of sectors assigned to RSTS, or alternatively the sector number of the first sector beyond the file system.  And yes, since the container length is not a multiple of 32 sectors the last few sectors are unused.
So it seems to be a description that could be clarified; as you said "first sector beyond the file system" is appropriate.  "Number of sectors in the file system" is not exactly right, because the first cluster is technically not in the file system (it's the boot block plus PCS-1 sectors after that for alignment).

**Comment by markpizz** [comment]
In the end, the point of that file system detection exercise is to determine if the file system in the disk container will fit within the disk type that the container is being attached to.  The answer displayed is less than precise since there in fact may be sectors in use that are beyond the last free sector.  However, in that case, these sectors in use will have been written with some sort of data and as such the container will have been written beyond the last free sector and the container size will more reliably indicate the file system size and that can then be used to determine if the filesystem/container will fit within the drive type it is being attached to.

**Comment by al20878** [comment]
"Last unallocated sector" on itself is inconsistent and misleading.  The mentioned sector does not belong to the filesystem.  So "last sector used by the filesystem" would have been more appropriate (as sectors past that are still _allocated_ to the disk image but they do not belong to the filesystem).  Or "Only the first n sectors (out of m sectors in disk image) are used by the filesystem".

**Comment by pkoning2** [comment]
Al, with the off by one error fixed, the description is correct.  It is the highest sector number within the file system that is not currently allocated (not in use).  The sector does belong to the file system, more precisely it currently belongs to its free space.
As for Mark's comment, even if the container was created without pre-extending, it certainly is normally true that any allocated sector is contained within the container file size.  That isn't 100% guaranteed with RSTS: if you have a SIMH that doesn't pre-extend, and you create a file system, then allocate a file with pre-extending such that the FS allocates blocks near the end of the disk address space, but you never write those file blocks, then the container would not cover those file blocks.  It's not a common case, but there actually are real application scenarios where this might happen.
Because of all this, the SIMH machinery to match container sizes against file system information are not entirely foolproof for RSTS.  It's possible to do better but it probably isn't worth the fairly substantial code that would be needed.  Especially since current practice, I believe, is to pre-extend containers so the container size normally does reflect the device size.

**Comment by al20878** [comment]
It's not "last unallocated", it's the "last allocated" to the file system.  Or, it's the first unallocated to the fileystem (if +1).

**Comment by markpizz** [comment]
It is ALLOCATED to the file system.  It is UNALLOCATED to any file in the file system.

**Comment by al20878** [comment]
And oh, BTW, the filesystem size calculation for an RSTS/E filesystem is NOT correct.  First DCN sectors do not belong to any PC, so the filesystem size is "DCN + PCS * PCN" (DCN1 is aligned with PCN0).

**Comment by al20878** [comment]
> It is ALLOCATED to the file system. It is UNALLOCATED to any file in the file system.

Okay, so why does it say "unallocated"?  I don't understand:
```
RQ0: Last Unallocated Sector In File System: 1953280
```

**Comment by markpizz** [comment]
Please use simh v3 or ATTACH -Q to avoid this horrible problem and stop arguing for the sake of arguing.

**Comment by al20878** [comment]
Please stop being rude, that's not nice, you know?
