### ISSUE TITLE
Use of 'zap'

### ISSUE THREAD

**Issue by mike632t** [simh/simh#1117]
https://github.com/simh/simh/issues/1094

Am I right is assuming that 'zap' be used to clean disk images as well as ISO images?

Thanks

**Comment by markpizz** [comment]
Zap will remove any simh added meta data from one or more disk containers.  If a disk container doesn't have simh added meta data zap does not change the file.

**Comment by rcornwell** [comment]
Mark,

   How about adding a command to add in metadata. Or an option to allow
   this if the user chooses. Rather than force the user to clean up
   after SCP has mucked with his data. For the novice user this is not
   something he would know to do.

Rich

> Zap will remove any simh added meta data from one or more disk
> containers.  If a disk container doesn't have simh added meta data
> zap does not change the file.
> 



-- 
==========================================================================
Richard Cornwell
***@***.***
http://sky-visions.com
LinkedIn:   https://www.linkedin.com/in/richard-cornwell-991076107
==========================================================================

**Comment by pghardy** [comment]
Will Zap reduce ISO images back to their original smaller than full sizes? I was annoyed to find that an ISO image of a CD with about 50MB of data on that had previously only been 50MB on disk had been auto-resized to 650MB by SimH, and as I did dated backups, I had wasted many GB of disk space unnecessarily.

 

 

-- 

Paul  Hardy

web:  <http://www.pghardy.net> www.pghardy.net

**Comment by markpizz** [comment]
> Will Zap reduce ISO images back to their original smaller than full sizes? I was annoyed to find that an ISO image of a CD with about 50MB of data on that had previously only been 50MB on disk had been auto-resized to 650MB by SimH, and as I did dated backups, I had wasted many GB of disk space unnecessarily.

In general, yes.

The odd thing here is that the VMS distributions that may have been captured from CDROM's, but they aren't actually ISO structured file systems.  They merely happen to be ODS2 file systems written to a CD.  Whatever tool DEC used when creating these CDROM masters put the disk contents into a 600mb sized file system container.  You could attach any such CDROM image to a simh VAX simulator RQ device (not specified as a CDROM) and add files.

If the ISO images you happened to be working with happened to truly have an ISO file system on it, then the attach would not have recognized the file system and told you so since there is no ISO file system recognizer in simh.

**Comment by markpizz** [comment]
When DEC first started distributing things on CDROM, there was no support for recognizing ISO file systems.  That ability came very late in the VMS lifecycle.

**Comment by pghardy** [comment]
Not very late. Mounting of 9660 CDROMs came in 6.0 and was actually available in 5.5 if you installed the Infoserver support which included the CD file system ACP.

 

 

-- 

Paul  Hardy

web:  <http://www.pghardy.net> www.pghardy.net

**Comment by al20878** [comment]
> In general, yes.

Be aware that it's only "in general".  But the 100% right answer is "no".  If the container file was under-allocated (in the assumption that any unwritten blocks are to be read as 0), then "ZAP" won't restore the original size of the file, in general.  That has been pointed out in #1059.

**Comment by markpizz** [comment]
The ZAP in the current codebase addresses the under allocated case by trimming all zero sectors at the end of the container (prior to the meta data) if ZAP is invoked with a -Z switch.  The commit I just pushed just now trims trailing zero sectors back to the size the container had when the meta data was added.  Any sector written with other than zero contents stops the backwards trimming.  Trimming now occurs without regard to a -Z switch.

**Comment by al20878** [comment]
Take a look here, for example:
https://github.com/simh/simh/issues/1059#issuecomment-955599918

**Comment by markpizz** [comment]
That is a nice example which should be completely fixed by the latest code.  Please try.

**Comment by al20878** [comment]
Thanks.

But as a developer to a developer: if you write something to a file (in this case, a signature) and then you truncate the file to take it out, even if you patched the mod timestamps and everything like that, the file is going to be _different_, in general.  Even if the size matches, even if everything on the outside from an unsuspecting eye looks "the same", the underlying structure of the file on the hosting file system can be quite different!  And that will be noted, for example, by a backup software, or some other things, like "apparent file size" for gapped container files (file with "holes").

Please be honest with *yourself*: if you can't be absolutely positively 100% sure what you mess up with when you write to user data directly from the simulator code (that is, not on behalf of the software that runs _under the simulator_) -- then just DON'T!  As simple as that.

A mere "attach" / "detach" / "zap" sequence these days (no need to run any software under the simh in between, or if the software has not modified any data in the container) leaves the user with a file, which is **NOT** equal to the original, in general.  Just **not**, admit it!

**Comment by al20878** [comment]
> be completely fixed by the latest code

You understand that you commit 99c5f2a76318f4236c699cdb62f6c5f921832786 does not help any people whose disk images have been previously tainted by v4.x signatures, right?  Since there was no original file size recorded, the recovery is, in general, impossible.  Those files are complete loss!

Here it goes time and again: **Please stop messing with user's data!**  As simple as that.

**Comment by markpizz** [comment]
> You understand that you commit 99c5f2a does not help any people whose disk images have been previously tainted by v4.x signatures, right? Since there was no original file size recorded, the recovery is, in general, impossible. Those files are complete loss!

Actually, the worst consequence for previously modified disk containers would be that too many zero containing sectors being trimmed from the end of the container during the zap process.  This is precisely equivalent to the under allocated case that such disks may counted on as you mentioned previously.

ZAP is intended as a tool to help address bugs in the disk meta data implementation before they are fixed.  In normal contexts it will be used **very rarely**.  

If you (@al20878 ) were to use this unmodified, and you were worried about your external (non simh) use of the containers, then you would use this frequently, but the current implementation will restore the containers to as pristine as possible contents.

**Comment by al20878** [comment]
> address bugs in the disk meta data implementation before they are fixed

There's only bug here: the modification of user data without consent and/or knowledge of what you are doing.  If you fixed this one first, as you should, none of other actions would have been ever required.
