### ISSUE TITLE
SIMH pdp8 Fails to Build on Raspberry Pi Linux

### ISSUE THREAD

**Issue by mkatzpdp** [simh/simh#1180]
Trying to build the latest SIMH from:

git clone https://github.com/simh/simh ​

with the following build command in the SIMH directory:

make BIN/simh​

​Causes a bunch of compiler warnings which then causes the build to fail.

Building on Raspberry Pi OS:  

Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv71 GNU/Linux

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

![SIMHBuild](https://github.com/simh/simh/assets/112441148/78ba9e9e-5592-46f8-83bc-6235070a4ef0)

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
Mike Katz

**Comment by mkatzpdp** [comment]
Thank you for your response.

My work around was to use open-simh.

**Comment by markpizz** [comment]
The pdp8 code here and it open-simh is identical.

Building using open-simh happened to avoid the compiler bug with gcc 10.2.1 on Raspian.  It avoided it since the simh UNIT structure is a few words smaller than that structure in here due to functional general simh additions in this repo.

The gcc compiler bug has been reported along with a test case that demonstrates the root cause: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111049.  This zip [ptr_diff_err.zip](https://github.com/simh/simh/files/12388904/ptr_diff_err.zip) contains the failure demonstrating test case.


The latest Raspian still contains gcc 10.2.1.  Maybe gcc 11 will fix this problem.  We're not sure.

Meanwhile, the build using this repo has be adjusted to avoid the larger sized UNIT structure for simulators which don't need  additional asynch I/O info and as a result of that, the pdp8 simulator now builds without warnings with the latest code.
