### ISSUE TITLE
Feature idea: "universal front panel"?

### ISSUE THREAD

**Issue by dylanmc** [simh/simh#168]
I'm interested in using SIMH as part of a computer science class, and
something that I thought that would broaden its appeal is to connect it
to the old kind of front panel with lights and switches, like the
PDP8e or Altair 8800. It would be pretty neat to have a "generic" panel 
with enough lights and switches to control a 16-bit processor.

I think this would be pretty do-able, and a fun development project for
me (using and Arduino to drive the LEDs and switches, connecting via
USB to a computer running SIMH), but enough work that I wouldn't want
to do it if it's been done before.

I figured folks here would be in the position to know whether anyone has done
anything like this, and also whether it'd be an appreciated resource
for the SIMH community (I'd open source the hardware and software, of
course).

Thanks for any advice, comments or pointers!
Happy New Year!

![digital_pdp8-e2](https://cloud.githubusercontent.com/assets/768946/5579927/e4281c74-8ff6-11e4-9413-1d21ef159a38.jpg)

**Comment by markpizz** [comment]
Dylan,

I've looked through the frontpanel stuff that Stefano has been working with.  It has a very general way of presenting a user interface which is already quite universal.  The configuration of what UI is presented and how the displayed components interact with a simulator is configured by a configuration file.  The file describes what components exist (switches, buttons, lights) and what bitmap file is presented as a picture for each, etc.  

The current implementation of the frontpanel examples he has each have significant pieces of code which are embedded within the simulator.

My goal is to  design an API which allows a program external to a running simulator to provide a front panel interface to display and control the simulator state and operation.  Such a front panel program can be a modified version of the existing code Stefano has been working with (extracted from the simulator) OR it could be a program leveraging the same API which interfaces to a hardware panel as you have suggested OR any of the several other 'Blinkenlights' implementations which have been glued to a simh simulator.

- Mark

**Comment by dylanmc** [comment]
Mark, 

You write: *"... OR it could be a program leveraging the same API which interfaces to a hardware panel as you have suggested OR any of the several other 'Blinkenlights' implementations which have been glued to a simh simulator."*

This sounds great! I'm not aware of other Blinkenlights implementations - could you point me to any of them? I'd like to avoid reinventing wheels, if it's not too late. 

Finally, what's the timeframe for your API? I'd be happy to be an early adopter of it.

thanks!
dylan

**Comment by markpizz** [comment]
A Google search for "Blinkenlights PDP11" reveals various interesting pages.

http://hackaday.com/2012/04/19/controlling-blinkenlights-with-modern-computers/

http://www.retrocmp.com/projects/blinkenbone

http://vmsnet.pdp-11.narkive.com/Ba0LfVle/blinkenlights-for-everybody-not-only-for-pdp-11

http://ancientbits.blogspot.com/2013/01/blinkenlights-not-so-difficult-as-i.html

**Comment by dylanmc** [comment]
Mark,

The last one is particularly helpful.  It would be great if https://github.com/jguillaumes/simh was merged with simh - it seems like a flexible and powerful way of integrating a panel like mine into SIMH. Thanks!

**Comment by leobru** [comment]
Please take a look at BESM6/besm6_panel.c - it is crude but blinks well in SDL. 
The front panel of BESM-6 was enormous, full of lights and buttons; implementing it to reproduce an authentic look and feel will be a major undertaking even within the universal front panel infrastructure.

**Comment by jguillaumes** [comment]
At this moment a merge would not be posible since it uses UDP in a nonportable way (it would not compile under windows), and the serial implementation should also be rewritten to use the current available mux access provided by simh. I also doubt the 'device' implementation is a good idea, since it breaks the unwritten rule that any simh device has to correspond to a real iron one (the PDP-11 was not a 'device' but something attached to the computer without any of the attributes of a real device).

The idea of providing several 'transports' (in my implementation I made a UDP, a serial and a Raspberry Pi specific GPIO) is something that could be used in a more generic panel solution, and I'm willing to contribute to a development in that direction.

Jordi Guillaumes i Pons
Barcelona - Catalunya - Europa

El 15/01/2015, a les 6:41, Dylan McNamee <notifications@github.com> va escriure:

**Comment by jguillaumes** [comment]
Just in case someone is interested, I've merged the last HEAD into my
BlinkenLights branch (at git://github.com/jguillaumes/simh). To compile the
blinky PDP11 it is necessary to grab the contents of git://
github.com/jguillaumes/retroutils and to compile and install the contents
of the BlinkenServer subdirectory. The makefile is intented to run under
OSX. To install it under Linux you need to run make as:

$ make GOWNER=root -e install

(the makefile installs under the guid wheel, which does not exist in linux)

The arduino sketch is also there, as well as the java virtual panel. A
breadboard based circuit can be found here:

http://1.bp.blogspot.com/-GHr4tx4syWk/UPX-hnxX-mI/AAAAAAAAFAA/3Kvfbdfswtg/s1600/BlinkenLights_bb.png

I'm not sure that circuit is exactly what is working now. I ended doing a
patchy and clumsy solder work in a bakelite protoboard, which is now happy
showing me the RSX idle loop pattern just on my table, besides the computer
in which I'm typing :) I think I even completed a schematics and tried to
do a PCB layout using fritzing. If someone is interested I could dig around
my file system to find it.


2015-01-15 18:10 GMT+01:00 Guillaumes i Pons Jordi <jguillaumes@gmail.com>:

> At this moment a merge would not be posible since it uses UDP in a
> nonportable way (it would not compile under windows), and the serial
> implementation should also be rewritten to use the current available mux
> access provided by simh. I also doubt the 'device' implementation is a good
> idea, since it breaks the unwritten rule that any simh device has to
> correspond to a real iron one (the PDP-11 was not a 'device' but something
> attached to the computer without any of the attributes of a real device).
>
> The idea of providing several 'transports' (in my implementation I made a
> UDP, a serial and a Raspberry Pi specific GPIO) is something that could be
> used in a more generic panel solution, and I'm willing to contribute to a
> development in that direction.
>
> Jordi Guillaumes i Pons
> Barcelona - Catalunya - Europa
>
> El 15/01/2015, a les 6:41, Dylan McNamee <notifications@github.com> va
> escriure:
>
> Mark,
>
> The last one is particularly helpful. It would be great if
> https://github.com/jguillaumes/simh was merged with simh - it seems like
> a flexible and powerful way of integrating a panel like mine into SIMH.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simh/simh/issues/168#issuecomment-70042364>.
>
>


-- 
Jordi Guillaumes i Pons
Barcelona - Catalunya - Europa

**Comment by markpizz** [comment]
Take a look at sim_frontpanel.h in the top directory of the simh repo.

I'm envisioning that sim_frontpanel.h and the code behind it, would be behind ANY program which wants to provide a GUI or a hardware front panel interface.

This is certainly an initial rough cut, so I'm interested in any and all questions and feedback.

I'm working on a first cut of this functionality.

- Mark

**Comment by zx70** [comment]
Jordi,

 

>> At this moment a merge would not be posible since it uses UDP in a 
>> nonportable way (it would not compile under windows)

 

I'm just cursious: I noticed that to compile some SIMH option under Windows it is necessary to include "WinPCAP".

Did you twist the UDP protocol so badly that WinPCAP cannot handle it ?

 

Stefano
 		 	   		  =

**Comment by jguillaumes** [comment]
I hope I did not! It is simply I used the Unix sockets API instead of using the SIMH Network layer, which provide OS Independence. AFAIK (I am mostly windows-ignorant) the win32 socket calls are not 100% compatible with the BSD ones.

----- Missatge original -----
De: "Stefano" <notifications@github.com>
Enviat el: ‎16/‎01/‎2015 8:21
Per a: "simh/simh" <simh@noreply.github.com>
A/c: "Jordi Guillaumes Pons" <jguillaumes@gmail.com>
Tema: Re: [simh] Feature idea: "universal front panel"? (#168)

Jordi, 



>> At this moment a merge would not be posible since it uses UDP in a 
>> nonportable way (it would not compile under windows) 



I'm just cursious: I noticed that to compile some SIMH option under Windows it is necessary to include "WinPCAP". 

Did you twist the UDP protocol so badly that WinPCAP cannot handle it ? 



Stefano 
=

**Comment by dylanmc** [comment]
Mark wrote:
> Take a look at sim_frontpanel.h in the top directory of the simh repo.
I did - it looks like a good initial cut. If a blinkenlights project's main task were to implement these functions to interface to a real/virtual panel, that would be a really nice and straightforward design. How can I help?

**Comment by markpizz** [comment]
A recent discussion on the simh list about octal vs hex on computer systems mentioned that some of the this detail was related to the grouping of information on the front panels of the machines.  Pontus Pihlgren sent along a link which discussed the details of various DEC panels:  That link was part of several pages with detailed discussion about panel functions and drawings of a good number of them.  I'm including this link here since it may be usefully relevant when this project moves on.

http://www.quadibloc.com/comp/panint.htm

**Comment by zx70** [comment]
Thankyou Mark !
I think I saw it already, but it is an interesting overview.
I must apologise for having pushed this project and then disappearing, but the z88dk project is facing a major review and I need to stay focused on it.   I’ll get back and test your proposal as soon  as possible,  I’m sure it will raise a number of crazy projects in parallel !

Stefano

**Comment by markpizz** [comment]
I've fleshed out the sim_frontpanel API and provided an example program which uses this API.  The example program merely exercises the API and runs in as a command line app.  This API now exists for those who want to directly develop a GUI panel interface.

It would be absolutely fantastic if Stefano or Dylan wanted to connect the GUI side of things to this.

The simple test program exists in frontpanel subdirectory of the simh source tree.  The makefile will build it.

It ONLY depends on sim_frontpanel.c(&.h) and sim_sock.c(&.h).

There certainly may be a few more pieces needed, but this should be a good starting point...

Please look around, and ask questions.

- Mark

**Comment by zx70** [comment]
Cool.   It's a busy period, but I'll have a look  :)

 

Stefano
 



Date: Wed, 11 Feb 2015 17:19:52 -0800

**Comment by dylanmc** [comment]
Mark,

My blinkenlight panel / switches are now talking over USB to my host computer, so now I'm ready to start the integration with SIMH and your helpful ``frontpanel`` API.

I got it building (had to copy ``clock_gettime`` from sim_timer in the Unix ``ifdef`` case), and it runs but I can't figure out how to invoke, say, the PDP11 simh in a way such that ``frontpaneltest`` can connect to it. (checked through the manuals, and the simh> help topics) Feeling silly to ask - but how do I get it going?

thanks!
dylan

**Comment by markpizz** [comment]
Hi Dylan,

Great News!

Please pick up the latest code from github.  I've been polishing the details and have made several updates since my initial message.

About clock_gettime()...what host platform are you working on?

Next, The target simulator MUST be:
- built with the latest code from github.  There is no simulator specific code needed to support the frontpanel API, but the simulator framework and the API must be current.
- The sim_path argument to sim_panel_start_simulator MUST either contain the full path to the desired simulator OR the desired simulator must be in your current path.
- The frontpaneltest program is specifically a pseudo VAX front panel.  It merely exists to exercise the API.   There are VAX simulator specific assumptions in the frontpaneltest program which include: A) the list of CPU registers.  B) The BOOT command on the VAX simulator starts the console ROM running and doesn't actually boot from a device,  A running simulator (even only running a console ROM) is good enough to exercise a RUN vs HALT situation.   The PDP11 simulator will need an target device name to be supplied to get it to boot,.  Never having used a PDP11 with a front panel, I don't know how a boot device would be selected...  As I understand things, sometimes folks manually entered a boot program via the frontpanel.  As I recall, some VAX systems had a knob on the front of the machine which could be selected to one of 4 positions that each enabled a different boot device...

Please provide the configuration file you would like to uses for the PDP11 and I'm sure I'll have some feedback.  I'd like to document the rules/guidelines/suggestions for configuration files and starting with what you're using would seem reasonable.

**Comment by dylanmc** [comment]
Mark,

I'm running/building on OSX. I don't see #ifdef's for OSX, so just stuck my changes in the #else. It's probably not the right solution, so I won't submit a pull request.

With your advice, I got the VAX frontpanel working -- woohoo! I think this is great! It would be cool to have the frontpanel running and also have a console available, but that's an aside for my purposes. I think I can handle creating a frontpaneltest for the PDP11, since (as you say) it's mostly about getting the right registers. I've never used a PDP11 with a front panel either, so I'll be making this up. If someone steps in to help it be accurate, that would be great. In the meantime, my goal is to be able to toggle in a short program and run it from the panel. A bonus goal would be to be able to use the Unix v7 configuration in this mode (e.g., https://sites.google.com/site/jamestownson/unix-7-on-simh)

Thanks -- this is totally great!

**Comment by markpizz** [comment]
Dylan,

When I put this together I didn't bother to test on my OS X box.  I'll get that clean when I get back from traveling next Sunday and can test the changes.

As for a console, well you certainly can have a 'console terminal'.   That terminal will precisely be the console port of the simulated system.  It will not be an interface to simh.  

-Mark

**Comment by markpizz** [comment]
Dylan,

The 'console port' on the VAX front panel test program is accessible if you telnet to port 1927 on the local system.

- Mark

**Comment by dylanmc** [comment]
> The 'console port' on the VAX front panel test program is accessible if you telnet to port 1927 on the local system.

It sure is. That is so cool.

**Comment by markpizz** [comment]
Dylan,

I've potentially added OS X support to sim_frontpanel(.c & .h).  Please let me know if this doesn't work (I can't test directly until I get back from this trip).

Thanks.

- Mark

**Comment by dylanmc** [comment]
OS X support works great. Time for me to look into PDP 11 integration as well as connecting to my blinkenlights.

**Comment by dylanmc** [comment]
It just occurred to me that you're probably part-way along a possible route to simulating the DEC KY11 remote console device. I'm not sure if that matters, or what the right way to proceed along that route, but I like the idea of integration with SIMH in which you use ``attach ky11 <portnum>`` to fire up the remote console.

**Comment by markpizz** [comment]
Hi Dylan,

Actually I'd never heard of a DEC KY11 until just this morning.  It does seem to be some sort of front panel interface (I'm sure that there were others which may not have been devices from the system's point of view).

As for how to interface such a device via the sim_frontpanel API well, one approach would be for a frontpanel application to implement the whole front panel interface and to drive the simulation as closely as possible to provide the same behavior that the original font panel hardware performed.  It would seem that, for the most part, this could be done completely by a front panel application using the existing sim_frontpanel API.

Although there is specific mention of the KY11-LB being a board in a Unibus system, it really isn't a 'device' from a simh point of view since simh devices exist to implement devices which the simulated system software could control.  The KY11 device controls the simulated system and isn't controlled by the simulated OS or software. 

So a front panel application could be a KY11-LB which controls a PDP11 simulator using the sim_frontpanel API.  It might be useful for this application (and the general class of other front panel implementations) to have a little more functionality in the sim_frontpanel API.  Once a couple of front panel implementations get done, what would be useful will become more apparent.

**Comment by zx70** [comment]
>(..)  It would seem that, for the most part, this could be done completely by a front panel application using the existing sim_frontpanel API.


I totally agree.
I began looking at what you've done and I must thank you for providing a full working example: to be actually able to see it running before peeping at the code helps a lot.
My first thought is to integrate the "libfrontpanel" code directly in sim_frontpanel.c making it optional with #ifdefs, but I suspect you will complain  :S

On the API side ATM I noticed I'd still miss a platform identifier (i.e. "PDP8") to associate it to the proper configuration set to be loaded (led and switches position and attributes, panel skin picture, etc..).

Stefano

**Comment by markpizz** [comment]
> My first thought is to integrate the "libfrontpanel" code directly in sim_frontpanel.c making it optional with #ifdefs, but I suspect you will complain  :S

Get something working first and we'll see what changes need to be made where.  Dylan's use of this functionality is fundamentally different than yours (i.e. Dylan is interfacing to a hardware front panel, you are looking at a software one).  The existing sim_frontpanel API can support both semantics. 

> On the API side ATM I noticed I'd still miss a platform identifier (i.e. "PDP8") to associate it to the proper configuration set to be loaded (led and switches position and attributes, panel skin picture, etc..).

Since the frontpanel application gets to specify the simulator to run (as an argument to sim_panel_start_simulator()), it would be presumed that the calling application knows what simulator is being run.  In a generic frontpanel application (driven by a panel interface description file), the simulator that should be run would naturally be a parameter in the configuration/description file.

**Comment by markpizz** [comment]
The sim_frontpanel API has been polished.  Please use the latest code and the FrontPanelTest  program as an example.

**Comment by markpizz** [comment]
A while back I said:
> > The 'console port' on the VAX front panel test program is accessible if you telnet to port 1927 on the local system.

And Dylan responded:

> It sure is. That is so cool.

Since then the FrontPanelTest program has been enhanced to automatically start up a terminal/xterm window which connects to the console port on the simulator.  This is an example which folks may use similarly with any other simulator with a console port.

Alternatively, the simulator's console port could be connected to a serial port on the host system and a physical terminal (VT100, LA120, etc...) could be connected to that serial port.

**Comment by dylanmc** [comment]
Mark - the FrontPanel files seem to be out of sync in the the current commit. When I `make frontpaneltest`, I get errors about mismatched number of arguments, such as:

```code
frontpanel/FrontPanelPDP11.c:222:58: error: too few arguments to function call, expected 5, have 4
if (sim_panel_add_register (panel, "PC",  sizeof(PC), &PC)) {
    ~~~~~~~~~~~~~~~~~~~~~~                               ^
./sim_frontpanel.h:139:1: note: 'sim_panel_add_register' declared here
int
^
```

**Comment by markpizz** [comment]
It works for me....

How did you get the code you are working with?

Are you using git directly or are you pulling down a zip/tarball archive of the repo and expanding it?

**Comment by dylanmc** [comment]
I've been checking the repo out with git, but I must have had a local change that git merged somehow, and broke it. I'll keep a fresh checkout in addition to my working copy. Thanks, and sorry for the erroneous report.

**Comment by dylanmc** [comment]
Mark - you've added so many features to the front panel API and sample program - wow! I see that your VAX example runs nicely (though I don't have an interesting image for it to boot). From the logs, it looks like you've added "examine" and "deposit" commands, but I don't see how to invoke them (I'd have expected them to be available when the machine is in the halt state). A rough tour or high-level description of what's going on would be handy. I'd also be interested in your recommendation for binding the front panel to a different simulator (e.g., the PDP11). I have made a number of failed attempts - probably due to my lack of architectural understanding. Thanks! 

By the way: I guess you've already seen the PiDP8 project, also based on SIMH: http://hackaday.com/tag/pidp/ - he's taking a rather different approach to interfacing SIMH to lights and switches...effective, though!

**Comment by markpizz** [comment]
Hi Dylan,

The VAX simulator is used in the sample program since that simulator will actually run without any other external media since it "Runs" an internal console ROM, thus setup for the sample program is minimized.  This allows the simulator to transition into and out of a Run state without any external effort to load a program.

The sample program uses each of the available APIs, including the examine and deposit ones.  As you suggest these only succeed when the simulator is in a halt state.  The sample program exercises these APIs only at startup and doesn't expose them via a command interface.  The point of the sample program is to provide a simple API example and to provide a simple test to debug the frontpanel API, not to provide a fully fleshed out user command experience.

Feel free to engage me directly at mark@infocomm.com to send over details of your how you were trying to start a PDP11 and we can get you over the startup hump.

I did see the PiDP8 project that Oscar implemented.  It seems that he started his effort right around when this discussion started here and before the frontpanel API was very far along.  It seems that the bulk of his work was the design and construction of the physical front panel and generic packaging issues.  He said that he only found out about the sim_frontpanel API in the github codebase half way through his project, so he wasn't in a position to leverage it.  He said he come back and look at it soon.

- Mark

**Comment by dylanmc** [comment]
I'm going to close this issue -- Mark's API more than fulfills my original request. (I'll take my own questions off-line). Thanks!
