### ISSUE TITLE
Problems in Save/Restore

### ISSUE THREAD

**Issue by archivisth** [simh/simh#197]
1. Save and Restore break backward compatibility with 3.9.X save files.

The current SCP still shows the save/restore version as "3.5". However, the file format has been changed by adding additional items into the save/restore file, for example, the unit dynamic flags. Thus, restore of a 3.9.X file will get "out of sync" and fail.

Prior to 4.0, SCP maintained compatibility with save files going back to 2.10. This is now broken.

Fix: update the save/restore version to 4.0. Add tests in restore and bypass restore of items that were newly added to the save file in 4.0.

Issue: some number of 4.0 save files are already out there and will be broken by this fix.

    2. VAX and VAX780 simulator name changes break backward compatibility with 3.9.X save files.

Restore uses the simulator name string as an initial "key match" to make sure that the file is intended for the current simulator. The VAX and VAX780 names were changed, breaking backward compatibility for these two simulators.

Fix: divorce the displayed simulator name from the save/restore string. Create a "weak global" pointer to a "save/restore" name; this only needs to be filled in by the VAX and VAX780 simulators. Change restore to look for a match on the simulator name or, if filled in, the save/restore name.

Issue: This fix only makes sense if the first issue is fixed as well. Otherwise, old save files are toast.

    3. Save/restore resets network connections by forcing a detach/re-attach cycle.

Save/restore has always had two purposes. The first is to allow the user to "roll back" time for repeated investigation of a problem in either the simulator or a simulated program. The second is to save a configuration as a configured initial environment. This has largely been superseded by .ini files and DO command scripts.

 For debugging purposes, the detach/re-attach cycle is deadly, because it breaks terminal sessions. This was the reason that DEV_NET devices were exempted from the detach/re-attach cycle. On the other hand, intersystem network connections should be re-established when a saved configuration is hauled out of mothballs.

The detach/re-attach cycle can also hurt other devices, if these actions have side-effects. For example, the PDP-10 RP simulator will clear "spin down" the pack on detach and "spin it up" on attach, causing an interrupt that wasn't there before.

Fix: Not really sure, but perhaps a switch to bypass the detach/attach cycle in restore would work. I'm concerned about side effects.

**Comment by markpizz** [comment]
Thanks for bringing this up.  I knew that there would be some issues here.

Another issue with respect to compatible save/restore images has to do with more precision on the actual 'version' of the simulator.  The embedded version speaks to the global baseline of the simulator which made significant sense when user visibility of versions was in relatively static releases which were infrequent in nature.  With open user access to all of the source, incremental changes to specific devices within any particular simulator could change saved/required register sets or the significance of certain state information for a particular device and thus break restore functionality.  Usually, additionally registers are added to fix missing state so that save/restore will actually work, but there is no guarantee of this.

As for the details you point out:

    1. Save and Restore break backward compatibility with 3.9.X save files.

Good Point.  Fixing now.

    2. VAX and VAX780 simulator name changes break backward compatibility with 3.9.X save files.

This problem exists for the MicroVAX1, MicroVAX2 and VAX 8600 as well since there is code to change the simulator name for these as well.  The suggested fix makes sense.

    3. Save/restore resets network connections by forcing a detach/re-attach cycle.

I had to read your comments 3 times before I really understood the concerns.  

First, I'll add that another variant of the use of SAVE/RESTORE actually combines BOTH of the purposes you mention.  Specifically a running simulator state can be dynamically "SAVED" and the simulator immediately exited.  The previously saved state is then RESTOREd immediately when the simulator is next started.  I've had a VAX simulator running this way on my Windows server environment for the last 10 years.  When the host system is shutting down, the simulator state is SAVED and when the host system reboots the simulator state is RESTOREd.

As I understand what you're saying while debugging, you'd like:
  - MUX devices to retain existing connections during a RESTORE operation.  
A switch could be added to enable this specifically for MUX devices.
  - Maybe you'd also like this generically for other devices as well (the disk example you give).  The same switch maybe.

The existing sim_rest() code does a detach_all() before restoring any unit state so that the, in general the simulator will look like it was just started prior to executing the RESTORE command.  This lets any RESTORE command start from the same state and thus reliably end up with the same simulator state without regard to what may have happened prior to the restore command execution.

A RESTORE operation makes a best effort at making everything which existed when the SAVE was performed look like it did at the time of the SAVE.  Given that socket connections are ephemeral, in general, they can't be precisely restored since the state what has happened on the other end of a socket connection can't be specifically saved and/or restored.  

The PDP10 RP disk example you give would seem to have the same issues without regard to any explicit detach that is there now.  Starting a new simulator and then performing a restore operation for a simulator which happened to have a RP device attached when the SAVE image was made will have to do an attach.  Would not the interrupt that you describe have to happen for this simulator as well?  Would that have been any different on 3.9?

**Comment by markpizz** [comment]
Points 1 and 2 were fixed earlier.
Point 3 "Save/restore resets network connections by forcing a detach/re-attach cycle." is now fixed:

A -D switch has been added to the RESTORE command.

    PDP-10 simulator V4.0-0 Beta        git commit id: d75ec666
    sim> att dz 1234
    Listening on port 1234
    sim> set ry ena
    sim> sh ry
    RY      address=3777170-3777173, vector=264, 2 units
      RY0   512KB, not attached, write enabled
            double density
      RY1   512KB, not attached, write enabled
            double density
    sim> att ry0 test0.ry
    RY: creating new file
    RY: buffering file in memory
    sim> att ry1 test1.ry
    RY: creating new file
    RY: buffering file in memory
    sim> save pdp10.sav
    sim> rest pdp10.sav
    RY: buffering file in memory
    RY: buffering file in memory
    Listening on port 1234
    sim> rest -d pdp10.sav
    warning - leaving RY0 attached to 'test0.ry'
    warning - leaving RY1 attached to 'test1.ry'
    warning - leaving DZ attached to '1234'
    restore with the -Q switch to suppress warning messages
    sim> det ry1
    sim> det ry0
    sim> att ry0 test1.ry
    RY: buffering file in memory
    sim> att ry1 test0.ry
    RY: buffering file in memory
    sim> rest -d pdp10.sav
    warning - leaving RY0 attached to 'test1.ry'
    warning - leaving RY1 attached to 'test0.ry'
    warning - leaving DZ attached to '1234'
    warning - RY0 was attached to 'test0.ry', now attached to 'test1.ry'
    warning - RY1 was attached to 'test1.ry', now attached to 'test0.ry'
    restore with the -Q switch to suppress warning messages
    sim> rest -qd pdp10.sav
    sim>

Please reopen this issue if you have other related input.

Thanks.
