### ISSUE TITLE
Feature-request: DZ11 "virtual modems"

### ISSUE THREAD

**Issue by b4** [simh/simh#215]
Had a random idea that would be neat for UUHECnet...

"Virtual modem" device attaches to a DZ line
This would be configured through SET commands to open a socket when it receives a dial command matching a pre-defined "phone number".

This would be useful for say, UUCP delivering mail on a 4.1BSD box due to the KDP only doing DDCMP,

After ATTACH <modem number> <dz number>:<line number>:
Emulating a modem speaking the Hayes command set one could do:
SET <modem number> DIALPEER 5555551212 localhost:2020
which would open a socket to localhost, post 2020 after receiving ATDT5555551212 on a modem line of the DZ.  Several of these could be configured.
SHOW <modem number> (possibly SHOW <modem number> DIALPEERS?)

**Comment by markpizz** [comment]
Hmmm...

Interesting idea.  There would be some work to get something like this working.

Since simh DZ lines are very cheap and you can have a large number of them on a Unibus simulator (256 lines), you could have dedicated virtual null modem connections for each line,  A configuration file describing these connections would look something like:

    sim> set dz lines=256
    sim> att dz line=0,2000,connect=remotehost1:2000
    sim> att dz line=1,2001,connect=remotehost2:2000

Getting back to the specifics of your suggestion, essentially all of it could be implemented in a relatively complicated simh script using combination of EXPECT, SEND, SET ENV and conditional expressions.  In fact, the only way I could see to implement anything which tried to act on data passing through a virtual serial port would be to use EXPECT.

**Comment by b4** [comment]
Hmmm, yes.  That makes much more sense - could quite easily be passive to the OS that way, too.

That syntax for ATTACH seems reasonable, too.

Yeah - I can already think of an EXPECT hack to do that. ;)

**Comment by markpizz** [comment]
The Virtual Null Modem capability and the attach syntax are part of the 4.0 functionality which was implemented before the DMC, KDP, DUP devices were added.

In any case, on the EXPECT subject, I'm referring to the built in EXPECT functionality which is part of simh.  EXPECT and SEND commands observe and deliver data to data flowing out of a single line on a MUX.  The default MUX is the simulator console, but any line on any supported MUX can have EXPECT commands filtering the traffic.

Please close this issue if these ideas are sufficient.

Thanks.

**Comment by b4** [comment]
Ahhh - it's a case of me missing some documentation somewhere, then.  Does that respond to modem control telling it to open/break?

Ahh - thanks.  I was wondering how much of an EXPECT system was implemented.

**Comment by markpizz** [comment]
Well, I'm pretty sure that if a port's DTR is dropped the TCP circuit will drop, and attempts to connect it won't happen until DTR is asserted.  DCD will indicate a connection is present.  RI may precisely track DCD or it may only be asserted when a connection is initially established (I don't recall).

See sim> HELP EXPECT and sim> HELP SEND for some info about EXPECT and SEND commands.
