### ISSUE TITLE
Baseline RSX-11M+ systems boot on Qbus but not on Unibus systems

### ISSUE THREAD

**Issue by JohnForecast** [simh/simh#216]
If I copy the baseline system onto an RA60 it will boot fine on a Qbus system (set cpu 11/73) but fail on a Unibus system (set cpu 11/70). I've tried it with versions from 3.0 to 4.3 and the result is the boot times out with various errors depending on the version, but always indicating a failure to bring the controller online. Version 4.2 gives:

>boo du1:[1,54]
RSX-11M-PLUS V4.2   BL58  

Fatal error -- Driver didn't return control after controller online call
Driver error -- If DEC driver, please submit an SPR!
HALT instruction, PC: 010632 (BR 10630)

Note that version 4.6 does not have this issue but the entire save/boot system was re-written to allow booting from virtual disks so it may not be relevant. In any case, the baseline system should always be able to boot on any supported system.

I'm trying to build a DECnet level 1 router and I would like to use a DMC-11 rather than a DPV-11 since this will be running on a Raspberry Pi which doesn't have much in the way of spare CPU cycles.

**Comment by markpizz** [comment]
John,

I don't know why I never noticed this issue.

From your description here you have a range of disk images "3.0 to 4.3" which fail to boot on an 11/70 but boot on an 11/73.  Can you provide a way for me to pick up these images along with configuration files for working and failing cases and any description of the input needed to create/observe success or failure.

Thanks.

- Mark

**Comment by JohnForecast** [comment]
Mark,
   I forgot that I had entered this problem. I worked around it by building a Unibus system on dual RK07 drives. You can get a zip file contains the RA60 disk image and a pair of .cfg files from:

           https://www.dropbox.com/s/7u8exfi3qrgq0yo/problem.zip?dl=0

If you start with the Qbus configuration file (pdp11-q.cfg) it will boot correctly into RSX-11M+ V4.2. If you start with the Unibus configuration file (pdp11-u.cfg) it will sit there and then produce the error messages I reported above. All versions between 3.0 and 4.3 that I tried failed in the same manner, let me know if you want copies of their system disk.

  John.

**Comment by markpizz** [comment]
Hi John,

I made the following observation:

    sim> b rq0
    SAV -- Booted device cannot be brought online
    HALT instruction, PC: 134022 (BR 134020)
    sim> e rq state
    UBASE:  000
    SA:     010222
    SAW:    111233
    S1DAT:  111233
    COMM:   00000000
    CQIOFF: 37777777774
    CQBA:   00000000
    CQLNT:  00000000000
    CQIDX:  000
    RQIOFF: 37777777776
    RQBA:   00000000
    RQLNT:  00000000000
    RQIDX:  000
    FREE:   01
    RESP:   00
    PBSY:   00
    CFLGS:  100000
    CSTA:   02
    PERR:   000
    CRED:   15
    HAT:    000060
    HTMO:   000060
    ITIME:  200
    I4TIME: 10
    QTIME:  200
    XTIME:  500
    PKTS[0]:        000000
    CPKT[0]:        00
    UCNUM[0]:       00
    PKTQ[0]:        00
    UFLG[0]:        000000
    sim> dep rq itime 2000
    sim> dep rq i4time 100
    sim> dep rq qtime 2000
    sim> dep rq xtime 5000
    sim> b rq0
    
    
    
    RSX-11M-PLUS V4.2  BL58   1920.KW  System:"Baseline"
    >RED DU:=SY:
    >RED DU:=LB:
    >RED DU:=SP:
    >MOU DU:"RSX11MPBL58"
    [...]

So, the boot code has different timing expectations on Unibus vs Qbus systems.

I just changed the 4 time values and increased them by 10X, and the boot was 
successful.  Will you walk backwards and determine which actually need to be
changed for success and what the minimum values are to achieve that success.

Knowing the correct timing values we can either change the the default value 
or change the boot code to be more accommodating since the boot code that 
isn't happy might actually be provided by the RQ device simulation.  If it is not 
the device provided boot code but a secondary loader that isn't happy, then 
the default device timing needs to change.  The preference to change the 
boot code is due to the fact that any change to the device timing changes 
that timing for all I/O operations on all operating systems, not just the boot 
activities.

Thanks.

Mark

**Comment by JohnForecast** [comment]
Mark,
   Thanks for taking a look at this. I'll try to find which one(s) are causing the problem. Do you know if these parameters are documented anywhere? A quick scan through the documents available on bitsavers doesn't give any hits.

  John.

**Comment by markpizz** [comment]
Hi John,

These are not parameters of the original hardware.  They are arbitrary 
simulator delays which exist to give some semblance of delay that reflect 
the fact that on real hardware I/O was slow compared to instruction execution.  
In the simulator I/O happens “in-between” simulated instructions and as such 
“could” complete in zero time.  These values (and similar values for other 
devices) provide a way for the simulated software to see non instant response 
from devices.  Many device drivers don’t expect device state to change very 
quickly (like the one which isn’t happy here).  In general, we strive to have 
the simulators run as fast as possible, as long as the behaviors meet the 
minimal expectations of real software that ran on the original hardware.  
The delays are in number of instructions executed and, in general, since 
they occur at precise times in the flow of simulated instruction execution 
provide very deterministic behavior.  Real hardware certainly performed 
I/O vastly slower than instructions were executed and usually with 
significantly different times from one activity to another (imagine disk 
rotational position…).

Mark

**Comment by JohnForecast** [comment]
Mark,
   Right after posting that last comment I realized that the parameters were Simh settings rather than device/protocol settings. Unfortunately, the timing requirements change depending on the RSX-11M+ version but if ITIME is set to 450 it boots successfully on all the versions I have. I think you will have to change the default setting in Simh since M+ is using its own driver embedded in the "sav" utility.

  John.

**Comment by markpizz** [comment]
Hi John,

Thanks for the testing.  The ITIME value is only used in the register handshake exchange when the device is first initialized by a driver so increasing it, in general won't change simulated system performance.  A normal system boot may involve 2 or 3 init sequences as each driver loads something and then passes control to what was loaded and ultimately the OS driver performs the last initialization and things proceed normally.  One of the boot drivers or something related to it may get involved if the system ends up generating a crash dump while going down, but still this is not a problem.

- Mark
