### ISSUE TITLE
Help on TU tape drive is incomplete (found in VAX780)

### ISSUE THREAD

**Issue by vaxorcist** [simh/simh#228]
The help on the TU tape drive says:
"TU options include the ability to select the formatter type (TM02 or TM03), to set the drive type ..."
There is no description on how to select the formatter typ.

**Comment by markpizz** [comment]
The simulator only supports setting the formatter type when the TU device is used in the PDP11 simulator.  I didn't write this, but it might be due to the fact that the TM02 was never supported connected to any VAX system.

I've fixed the wording of the help to describe that the option only exists on the PDP11 simulator.
