### ISSUE TITLE
Visual Studio 2015 - duplicate definition of timespec

### ISSUE THREAD

**Issue by EJMarr** [simh/simh#233]
I recently downloaded the Windows development kit for simh, and also Visual Studio 2015 to run it.

Import worked, bar some warnings, but build failed big-time, due to duplicate definitions of timespec in windows.h, sim_timer.h and pthread.h.

As a simple test I commented out the definitions in the last two of these two files, and most things built OK, including PDP11.EXE, which is what I was after. I did not chase issues with the few other systems that did not compile. The PDP11 runs ok, apart from some detailed communication issues that are almost certainly not related to this problem. I will advise further on those when I have a clearer picture.

Windows.h was found located in c:\Program Files (x86)\Windows Kits\8.1\Include\um\ and was dated 21/8/2013.

Running on 64 bit Windows 7.

**Comment by markpizz** [comment]
I was already aware of this issue when using Visual Studio Community (aka 2015).  

The timespec problem can be addressed without too much trouble, However, going all the way to getting clean builds for all targets is much more complicated problem.  There are link time libraries which are used by some simulators that depend on externals visible in prior versions of the C runtime library.  These exports are different in Visual Studio 2015.

This could be solved with two separate project sets.  One for Visual Studio prior to 2015 and another for for 2015 and later.  I really DON'T want to maintain yet another build configuration (currently we have makefile, descrip.mms, and Visual Studio Projects).  Alternatively support for older Visual Studio build environments could be abandoned and Visual Studio Community could be the only supported platform going forward.  I hesitate to force that approach since I know that some simulator developers are still using XP on their development systems and I wouldn't want to abandon them.  Beyond the simulator developers still on XP, there are likely MANY MORE simulator users still using the pre-built binaries on XP and I'd have to verify if binaries produced with Visual Studio Community will actually run on XP  I'm pretty sure that Microsoft has not tested any of the Visual Studio Community issues on their no-longer supported XP platform.

So, for now you can keep using whatever you've hacked to get a build working OR you can install Visual Studio 2008.  A URL for the Installation ISO for that is in the "Visual Studio Projects\0ReadMe_Projects.txt".

- Mark

**Comment by EJMarr** [comment]
Mark,

 

I think I’ll just use my simple hack – the no effort option.

 

Ed

**Comment by markpizz** [comment]
Testing reveals that the binaries produced when building using Visual Studio Community (2015) DO NOT run on Windows XP.

I'm not yet prepared to drop support for users running simh simulators running on XP.  Therefore a generic migration/upgrade of the Visual Studio support to only the Community (2015) edition is not a viable approach.

I'll update here as I work towards a more complete solution.

- Mark

**Comment by markpizz** [comment]
For the record:  Testing has confirmed that Prior versions of Visual Studio Express (before 2015) do produce binaries which will run on Windows XP.
