### ISSUE TITLE
QVSS interrupt controller not simulated with 8-bit

### ISSUE THREAD

**Issue by m4j0rd0m0** [simh/simh#239]
As discussed on NetBSD's [port-vax mailing list](http://mail-index.netbsd.org/port-vax/2015/09/23/msg002606.html) recently, QVSS (VCB01) simulation of SIMH seems incomplete.
The 8-bit nature of the interrupt controller is not simulated correctly which causes the NetBSD driver to panic, as it (still) relies on the hardware to mask interrupt vectors down to 8 bit. SIMH's QVSS allows 16 bit vectors at the moment.

NetBSD runs OK on the real hardware, but code admittedly needs to be improved, too. The question is if SIMH should also be fixed to better reflect the real hardware.

Regards,
Felix

**Comment by markpizz** [comment]
Hi Felix,

Can you put your full name on your github profile (not your email address).

I've followed the discussion about this on the NetBSD list and there certainly a problem here.

I presume that the suggestion is that line 569 in vax_vc.c:
            vc_intc.vec[vc_intc.ptr] = data & 0xFFFF;   /* Vector */
should be changed to:
            vc_intc.vec[vc_intc.ptr] = data & 0xFF;   /* Vector */

Well, maybe....

The QVSS is one of several Qbus devices which have programmable interrupt vectors.  The other cases are: pdp11_rq, pdp11_tq, and pdp11_xq.  There is an internal algorithm in VMS's auto configuration logic which is used to allocate vectors.  All vectors are longword aligned (hence have 2 low bits which are always 0).  There are cases where VMS will allocate a vector exceeding 0xFC to the QVSS device.  The QVSS being the last device in the list to get an allocation it will get the highest vector value.  The Qbus adapter on the VAX systems will add 0x200 to the vector the device puts on the bus for dispatching into the OS vector table, but that resulting vector value is NOT what drivers on VMS or other operating systems program these devices with (they use the assigned vector less this 0x200 offset).

The cases which would assign a QVSS a vector address exceeding 0xFC possibly never could be put together in hardware and thus a vector exceeding 0xFC might not actually be used, but that would be quite strange since each of the other vector programmable devices could support a vector value greater than 0xFC.

So, I'm not suggesting that a change shouldn't be made to reflect the behavior of real hardware, I'm just trying to understand the actual limits...

DEQNA (XQ) has 8 bits of vector, but that is 8 bits PLUS the 2 low bits so a total vector range of 10 bits.
The RQ and TQ devices pass 7 bits of variable vector data PLUS the 2 low bits so a total vector range of 9 bits.

**Comment by m4j0rd0m0** [comment]
> I presume that the suggestion is that line 569 in vax_vc.c:
> vc_intc.vec[vc_intc.ptr] = data & 0xFFFF; /* Vector /
> should be changed to:
> vc_intc.vec[vc_intc.ptr] = data & 0xFF; / Vector */

Yes, I found that line, too.

> The cases which would assign a QVSS a vector address exceeding 0xFC possibly never could be put together in hardware and thus a vector exceeding 0xFC might not actually be used, but that would be quite strange since each of the other vector programmable devices could support a vector value greater than 0xFC.

This is what happens with the unfixed NetBSD driver, I guess you also read it on port-vax list: It writes the VAX interrupt > 0xFC (with 0x200 offset) into the vector register, and while real hardware masks it, SIMH does not yet.

> So, I'm not suggesting that a change shouldn't be made to reflect the behavior of real hardware, I'm just trying to understand the actual limits...

After studying different Q-Bus devices, I can support your description that there is no universal layout of vector registers. Some contain the vector without the 2 LSBs, some with (although it is redundant), and total bitlengths are different.
What also seems to be a common and allowed implementation is to not drive BDAL<1:0> on the Q-Bus during interrupt cycle.
Browsing through specs and testing real hardware seems the only way here.

As common denominator for the hardware, I took [DEC STD 160](https://archive.org/details/bitsavers_decstandar160LSI11BusSpecificationSep91_2047975) on interrupt cycle for granted:
*"Because the vector is the first of a pair of addresses and because vectors are constrained to addresses between 0 and 777, only bits TDAL\<08:02\> are involved and no others should be asserted."*

Now what is interesting and harder to find out is what does the processor (real and simulated) do when a vector beyond 777 is driven? Physically it is easily possible for a (specially prepared/broken/...) Q-Bus device to also assert BDAL\<15:09\>...!
My guess is a real CPU masks the upper "wrong" bits, maybe even the two LSBs, then it could make sense to also let the simulator do it on this level already.

Felix

**Comment by m4j0rd0m0** [comment]
And now the short answer to your question...

> DEQNA (XQ) has 8 bits of vector, but that is 8 bits PLUS the 2 low bits so a total vector range of 10 bits.
> The RQ and TQ devices pass 7 bits of variable vector data PLUS the 2 low bits so a total vector range of 9 bits.

According to [AZ-GLFAB-MN (VAXstation II Technical Manual - BA23 Enclosure)](https://archive.org/details/bitsavers_decvax630AITechnicalManualBA23EnclosureOct85_15635013), the QVSS has 8 bits of vector. The 8-bit limitation is due to an 8-bit data path of the whole interrupt controller, e. g. ICDR is only 8 bits. Relevant section is C.2.2.5 (or Appendix C altogether).

And as proved by the NetBSD driver and hardware, the total vector range is also 8 bits (i. e. the 2 low bits are **not** implicit), as unshifted vector addresses from the pool must be written to the vector registers.

Hence the QVSS seems to be an exception in not supporting 9 significant bits of programmable vector.

**Comment by archivisth** [comment]
The four VAX chips differ slightly in their interrupt behavior.

1. MicroVAX II - and ONLY MicroVAX II - will mask the incoming interrupt vector down to 10bits. Bit<1> is ignored, and bit<0> is treated as the 'Qbus' flag; if set, it forces all device interrupts to IPL 17.

2. CVAX and Rigel use a WORD (16b) read to get the interrupt vector. Bit<1> is ignored, and bit<0> is treated as the 'Qbus' flag; if set, it forces all device interrupts to IPL 17. To quote the chip spec about an interrupt acknowledge cycle:

        Bits <15:02> of the incoming data are used to create the vector offset within the
        System Control Block.

3. NVAX uses a WORD (16b) read to get the interrupt vector. Bit<1>, if set, forces a passive release, and bit<0> is treated as the 'Qbus' flag; if set, it forces all device interrupts to IPL 17.

Thus the base VAX simulator, which is a CVAX (MicroVAX 3900), is correct. When the interrupt and exception code incorporated into the MicroVAX II simulator without change, it's not.

QVSS was probably only used on MicroVAX II systems; by the time CVAX came out, there were dedicated VAX workstations and better graphics chips.

The "fix" would be to parameterize the interrupt mask in the 'model.h' file and use that parameter in place of the fixed constant 0xFFFF in module intexc.

The problem is moot on the 780. The SCB vectors are for Nexus interrupts and are determined algorithmically. Unibus device vectors are read by accessing registers in the UBA. No masking is needed. The 750 is very similar, and it's likely that the 8600 behaves the same way.

I cannot speak for the 730 and MicroVAX I, which connect directly to IO busses. The MicroVAX I technical manual says that read vector returns a word, but it also says that vectors beyond 0x1FC (9 bits) are not allowed.

**Comment by markpizz** [comment]
Bob,

Thanks for your explanation about how the vector a device provides gets passed into the processor.  I;ll look into any changes needed to correct what isn't being done right.

The problem in this issue is somewhat different.  The question is how much of the data value passed through the 16 bit Qbus register is actually stored in the QVSS interrupt controller and then subsequently passed out to the Qbus when an interrupt vector is requested during interrupt dispatching.

This problem, along with what you just said above (about bit<0> being a Qbus flag), suggests that the way essentially all Qbus devices are currently implemented doesn't track with the hardware.  Specifically, the value stored in the DIB vector field is vector PLUS the VEC_Q offset value.  It would seem that the processor specific offset should be returned as part of fetching the vector AND it probably should be ORed into the value returned by the device's interrupt ack routine (that is OR vs PLUS).  

It would seem that the original problem observed during development of the NetBSD QVSS driver would go away if VEC_Q was always ORed into vector values instead of added to them...

As for QVSS and CVAX systems.  Display support for the QVSS as a console device was removed from the ROM due to lack of space for the required code.  CVAX systems with QDSS (VCB02) were certainly sold.  What folks (like me) in the field did was a different story.  :-)

**Comment by archivisth** [comment]
Well, yes and no. In a CVAX system, the CQBIC forces bit<9> and <0> of the device vector to be 1 before it is returned to the processor. So indeed, the value of 0x201 is OR'd into every Qbus vector before it is passed to the processor. The processor just takes the vector as is. The "prebias" is done in the 'vaxmod.h' file as it defines vectors. For devices with dynamic vectors, they must provide the bias themselves (see for example, pdp_rq.c).

I liked the prebias because you can take the vector displayed by all the status printouts and use it as a memory address without having to remember to set bit<9> yourself. That was helpful during debug to find drivers.

Right now, the prebias is incorrect in two respects.

1. It's done with adds rather than ORs, as the hardware would do. For fixed vectors, it doesn't matter; for dynamic vectors, it might.
2. Bit<0> is not set. It's not needed in the simulator, because all devices interact properly with a 4-level interrupt structure. The hack was there to cope with el cheapo devices from the early days of the LSI11; none of those devices were supported on the Qbus VAXen.

So, if you want to do major surgery:

1. Rip out the VEC_Q definition from vaxmod_defs.h and from its vector definitions.
2. Rip out the VEC_Q definition from all other VAX model definition files and from pdp11_defs.h and pdp10_defs.h.
3. Rip out the bias calculation from rq, tq, xq, xu, and any other dynamic vector devices.
4. Add an OR of 0x201 (make this a parameter) to the vector received in the get_vector routine, for DEVICES only (not for internal interrupts).
5. Prove that everything still works.

If you don't mind leaving code behind that no one will understand in a few years:

1. Zero out VEC_Q in vaxmod.defs.
2. Add an OR of 0x201 to the vector received in the get_vector routine in all Qbus VAXen, for devices ONLY. I don't know how the 730 does things.

You still need to prove that everything works. Lots of luck with that.

Or, you can just fix the bias calculation in QVSS to be vector | VEC_Q, instead of whatever they're doing now. QVSS was never shipped on anything but VAXen, but if it were inadvertently compiled with a PDP11 somehow, PDP11's always define VEC_Q as 0.

Line 863:

 result = (vc_intc.vec[i] + VEC_Q);

could be

result = (vc_intc.vec[i] & 0xFC / 0x1FC) | VEC_Q;

depending on whether the vector storage is 8b or 9b. You can OR in 1 as well if you want to simulate the IPL17 stuff.

**Comment by m4j0rd0m0** [comment]
> Bit<0> is not set. It's not needed in the simulator, because all devices interact properly with a 4-level interrupt structure. The hack was there to cope with el cheapo devices from the early days of the LSI11; none of those devices were supported on the Qbus VAXen.

Sorry to get off-topic: Could you explain why bit<0> helps with "el cheapo" devices? And what is the "el cheapo" part exactly?
If it has to do with a solely *position-dependent* configuration and *single-level* interrupt devices on level 4 (which is also what DEC's Chipkit does for example), I always thought this is indeed "el cheapo" but valid on the Q-Bus, too. It can (still) be found as variant in all the CPU manuals of Q-Bus VAXen at least.
It also seems possible to mix 4-level and single-level devices by placing the devices not monitoring higher levels last in the chain.

**Comment by archivisth** [comment]
I have no idea why the IPL17 hack helped. It certainly worsened the real-time responsiveness of Qbus VAX systems by locking out the timer during a device interrupt.

All Qbus devices in the VAX simulator are simulated as 4-level devices. They are "hacked" in the definitions file to be 1-level by forcing their IPLs to VAX 14 (PDP11 4) instead of their native Unibus level. The clock is the only non-IPL14 device.

**Comment by markpizz** [comment]
Bob said:

> None of my previous suggestions will
> work, due to the integration of internal (non-biased) and Qbus (biased)
> devices into a single interrupt structure. Therefore, the get_vector routine
> cannot blindly OR in 0x201; it would be wrong for the clock and console.

There already was a wholesale reworking/removal of vectors in the vaxmod_defs.h.  All of the address and vector assignments are now done in the auto configure code in pdp11_io_lib.c.  It seems that adding a int_vec_set[IPL_HLVL][32] can be used for each of the corresponding interrupt bits to reflect the bits to OR into the vector value returned by get_vector() and to mask off in the value returned by get_vector ().  This array can be built as devices are identified in the auto configuration process.   So, to let the compiler help find any stray uses of VEC_Q, I've removed VEC_Q and added a VEC_SET where VEC_Q was previously defined and removing it entirely in pdp11_defs and the pdp10 code.

> If you want to get to a technically 'correct' answer, then all you need to do is
> change VEC_Q from 0x200 to 0x201 for Qbus VAXes only. The ADD/OR
> question is meaningless, because vectors are limited to 9b with <1:0> = 0
> (specified in both U and Q documents).

Well, the ADD/OR does matter.  That subtlety is what started this discussion.  The NetBSD driver writer programmatically set the vector value to something which included the 0x200 offset.  That whole value was stored in the QVSS interrupt controller and when the interrupt was dispatched another 0x200 was added and the processor got a vector which didn't point at his interrupt routine...

In any case, ADD/OR isn't a factor any more since VEC_Q is gone and all vectors are assigned in the auto configure routine and any CPU model specific extra bits are explicitly set (via OR) in the model specific get_vector() routine.

> BTW, the technical manual for the 730 says explicitly that the microcode
> <adds> 0x200 to Unibus vectors, but vectors are confined to 9b, so it doesn't
> matter.

This suggests that the VEC_SET for the 730 should be 0x200, which corresponds to the previous value of VEC_Q for the 730.  The same for the 750 as described in Figure 3-25 on page 3-29 of the 750 Unibus Technical Description .

VEC_SET has the bit 0 set for all Qbus systems and 0 for the Unibus ones.   The logic in intexc() looks at the low bit of the vector (Qbus vector bit) and selects IPL 17 as needed.

> Autoconfigure should flag any configuration with a vector >= 1000 as invalid.

It already does.

You also said:

> I liked the prebias because you can take the vector displayed by all the status printouts and use it as a memory address without having to remember to set bit<9> yourself. That was helpful during debug to find drivers.

Certainly true, so the displays produced by those status printouts (all using show_vec()) include the appropriate bias values when producing the displayed output so nothing visible has changed.

**Comment by archivisth** [comment]
Bah. I disowned this autoconfigure everything approach ages ago.

As I said, this could have been fixed with a one line change in the QVSS code, changing the add to an OR and masking properly to conform to the Qbus spec. (NetBSD putting in 0x200 itself is clearly an error.) Without specs or schematics, there's no way to know how many bits the QVSS allocated for storing vectors. Further, if the simulation is correct, there's no way to read the vector after writing it, so it's not even feasible to "ask the hardware" how wide stored vectors are.
