### ISSUE TITLE
Problem with PDP-11 attaching .TPC files

### ISSUE THREAD

**Issue by MarkMatlock** [simh/simh#247]
I noticed Simh PDP-11 having a problem attaching .TPC files. I think this was working in an earlier V4 version but now does not seem to work. I don't have an earlier V4.0 but I did have a V3.9 that I can use to verify the integrity of the a test .tpc file.

The test file rsx82b.tpc comes from ftp://ftp.trailing-edge.com/pub/rsx_decus_tapes/don/ but I have seen many .tpc files fail to attach the same way. I have tested both OSX compiled Simh pdp11 emulators and also from Ubuntu both act the same. A simple example that illustrates the problem is below:

$ ls -l rsx82b.tpc
-rwxrwxr-x 1 mark mark 24924160 Nov 19 21:02 rsx82b.tpc
$ ./pdp11v39

PDP-11 simulator V3.9-0
sim> sh tq0
TQ0, not attached, write enabled, SIMH format, capacity=98MB
sim> set tq0 format=tpc
sim> sh tq0
TQ0, not attached, write enabled, TPC format, capacity=98MB
sim> att tq0 rsx82b.tpc
sim> sh tq0
TQ0, attached to rsx82b.tpc, read only, write enabled, TPC format, capacity=98MB
sim> exit          Note: I can boot RSX11M+ and read this tape
Goodbye
$ ./pdp11v40

PDP-11 simulator V4.0-0 Beta        git commit id: 4a1cf358
sim> sh tq0
TQ0	not attached, write enabled, SIMH format
	capacity=98MB
sim> set tq0 format=tpc
sim> sh tq0
TQ0	not attached, write enabled, TPC format
	capacity=98MB
sim> att tq0 rsx82b.tpc
TQ: unit is read only
Segmentation fault (core dumped)
$ 

The .tap files appear to work fine.

Thanks,
Mark Matlock

**Comment by markpizz** [comment]
Hi Mark,

Thanks for finding this issue.

What you are observing is due to a bug in the error path which is happening when a tpc format file is having its format validated.  This format validation occurs when the tape is being attached.
In this case, you are trying to attach a tape which fails the validation check.  The validation check is one which validates that all the records in the TPC file being attached have reasonable lengths and that the end of tape indication is a reasonable value.

The latest code in the github repo no longer generates a segmentation fault and properly exits with a "Format Error" message.

Thanks.

Mark
at tape open or attach time.
