### ISSUE TITLE
as of commit a18a4f4... build pdp11 on FBSD 10.2 only succeeds with c99 flag

### ISSUE THREAD

**Issue by decuser** [simh/simh#251]
The addition of the code:

    ifeq (HP-UX,$(OSTYPE))
      CC_STD = -std=gnu99
    else
      ifeq (,$(SUNC_VERSION))
        ifneq (,$(findstring error,$(shell $(GCC) -std=c11 -version /dev/null 2>&1)))
          CC_STD = -std=c11
        else
          ifneq (,$(findstring error,$(shell $(GCC) -std=gnu99 -version /dev/null 2>&1)))
            CC_STD = -std=gnu99
          else
            CC_STD = -std=c99 -fms-extensions
          endif
        endif
      endif
    endif

appears to have messed things up for building on FBSD using gcc48 or gcc49. In order to get to build, requires specifying c99:

    gmake CC_STD=-std=c99 pdp11

**Comment by markpizz** [comment]
You are correct.  

However, the code you quote above is not the latest.  I wrote that without an system I could test the results on.  

Please test with the latest code in the master branch and close this issue if there no longer is a problem.

**Comment by decuser** [comment]
Well, you're right, the code is no longer as above. However, the build still fails and requires the flag be specified or it errors out. The error is:

	In file included from /usr/include/_ctype.h:94:0,
					 from /usr/include/ctype.h:46,
					 from PDP11/pdp11_sys.c:69:
	/usr/include/runetype.h:92:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'const'
	 extern _Thread_local const _RuneLocale *_ThreadRuneLocale;
						  ^
	/usr/include/runetype.h: In function '__getCurrentRuneLocale':
	/usr/include/runetype.h:96:6: error: '_ThreadRuneLocale' undeclared (first use in this function)
	  if (_ThreadRuneLocale) 
		  ^

**Comment by markpizz** [comment]
I find it very odd that FBSD's gcc at a particular gcc version has different functionality in C dialects than the same gcc version on any other platform.

Hmm..  Looking at the errors above it isn't the C dialect anymore, but something in the FBSD include files which doesn't like the -std=c11 dialect.

It seems that -std=gnu99 is the best bet when the compiler is gcc since -std=c99 doesn't include the anonymous structure member support that the SLiRP code from qemu needs for the simulators which have ethernet devices (PDP11 and VAXen).

**Comment by decuser** [comment]
I don't pretend to know what's going on to cause the error, but setting the dialect, gnu99 allows the code to compile and if you say it's better than c99, I believe you. I can close the issue, if you like?

**Comment by markpizz** [comment]
Please satisfy yourself that the latest commit works for you and then close the issue.
