### ISSUE TITLE
Filename clash in expanding simh-master.zip on case-insensitive file systems (Windows and Mac OS X)

### ISSUE THREAD

**Issue by agn453** [simh/simh#264]
Hi Mark,

I downloaded the latest git snapshot in the simh-master.zip file to my Mac and noticed the following files in simh-master/Intel-Systems/common give overwriting warnings when expanding the zip file -

iSBC80-10.c   and   isbc80-10.c
iSBC80-20.c   and   isbc80-20.c
iSBC80-30.c   and   isbc80-30.c 

The problem also occurs when expanding the zip file under Windows (both operating systems have case-insensitive file systems).

I just chose to overwrite the files - but others may get confused by this.

Tony

**Comment by markpizz** [comment]
Thanks for noticing that detail.  I never use the zip file.  I just pull down the repository directly with git and don't see any complaints there.

This problem came up when the author reorganized his directories and ended up with copies of the same files with the name differences you observed.  I thought we'd fixed that at the time, but clearly it wasn't.  It should be fixed now.

**Comment by agn453** [comment]
Thanks again Mark!

Tony
