### ISSUE TITLE
No space for device specific unit flags in disk support library

### ISSUE THREAD

**Issue by JohnForecast** [simh/simh#268]
To be consistent with the tape support library I would expect disk device specific flags to start at DKUF_V_UF which is set to 32 and therefore outside the int32 space allocated to device unit flags. The disk support library seems to skip over the first 12 available bits. Is there a reason for DKUF_WLK being at (UNIT_V_UF + 12) rather than (UNIT_V_UF + 0)?

  John.

**Comment by markpizz** [comment]
The disk support library, unlike the tape support library, was a late addition to the code base.  Essentially all tape devices were originally written with device access via the tape support library.  On the other hand, all disk devices were originally written using direct file access I/O using the sim_fio APIs.  The disk support library was added for two primary reasons: 

1) To support alternate disk formats (SIMH, RAW and VHD).
2) To support asynchronous I/O

The pdp11_rq simulator was the original use case for development and testing of the sim_disk library and once that was working, the pdp11_rp simulator was used to discover the minimal effort migration test case to assure that an existing disk simulator could easily adopt the sim_disk APIs.

I have to admit that minimal effort was expended thinking through the detail of flags except the fact that they were in short supply, and they were heavily used by some disk simulators.  Ultimately the dynflags field was added to the UNIT structure to support other activities which previously might have leveraged bits in the flags field.  As I vaguely recall, I probably initially had the disk library flags starting at UNIT_V_UF which caused very strange problems since they overlapped with the flags already in use.  I probably just moved them beyond the existing flags in use with a few extra bits to cover other devices I hadn't looked closely at yet.

This should be fixed.
