### ISSUE TITLE
Unable to set CPU MODEL "VAXStation"

### ISSUE THREAD

**Issue by Analyzer123** [simh/simh#269]
Hi, I have problem with simh VAX license types, because licenses are type "D", and defaut cpu type VAXServer does not permit type "D" licenses. "B" is permitted. So I found this command "SET CPU MODEL" that could change my processor type. But only arguments "MicroVAX" and "VAXServer" are allowed. "MicroVAX" changes my permitted licenses from "B" to "C" but not "D"
I am using copied VMS 6.2 image in my test. I am trying to make emulator compatible with my image, not vice versa.
How should I manage this problem?

"MicroVAX 3900 has a SET CPU MODEL=(MicroVAX|VAXServer|VAXStation) command to change between system types"

**Comment by markpizz** [comment]
Hi Analyzer123,

Will you please put your full name in your GitHub profile?

The simulator in question (MicroVAX 3900) precisely simulates the KA655 CPU which was sold in two different system configurations:  1) The VAXServer type and 2) the MicroVAX type.  This CPU was never sold in a VAXStation configuration, however since it is a Qbus system someone could take a VCB01 Graphics board that they found laying around and plug it into the system chassis and the graphics hardware would actually work if software was installed to use it.  Merely plugging this graphics card into the system bus would not change the system configuration from a licensing point of view.  The SET CPU MODEL=VAXSTATION command is precisely equivalent to plugging in this extra board.

Meanwhile, this report has illuminated the fact that a simulator may or may not have been built with any graphics device support and therefore the SET CPU MODEL=VAXSTATION command may fail without a useful message.

The output of SHOW VERSION in your simulator will identify many details about your system and the build options provided when the simulator was built.  The output produced by "make" when building the simulator will also produce useful messages about some of these details.

I've changed the simulators to produce consistent messages when the CPU MODEL is being changed (or fails to get changed).

You say:
> I am using copied VMS 6.2 image in my test. I am trying to make emulator compatible with my image, not vice versa.

Given your goal, you don't actually identify the system that this VMS 6.2 disk image actually came from.  What was the hardware?

I suspect that it will work with the MicroVAX II simulator, but the 16MB of RAM vs 512MB of RAM might be a challenge.

Alternatively, you could get new licenses from the VMS Hobbyist program which will certainly run on the MicroVAX 3900 simulator.

- Mark

**Comment by Analyzer123** [comment]
Hi and thank you very much for your help!!
I got an idea to recompile simh, and noticed that SDL package was not installed. So I installed SDL and recompiled again. Now I can change "CPU MODEL" to "VAXSTATION" and license type changed to "D" :-) Original platform was Vaxstation 4000

**Comment by markpizz** [comment]
PLEASE put your name on your GitHub profile so we know who you are.  Thanks.
