### ISSUE TITLE
Pdp1 paper tape reader

### ISSUE THREAD

**Issue by totalegit** [simh/simh#282]
I've been playing with the pdp1 simulator trying to run Expensive Typewriter. I'm using this tape image
digital-1-4-s-mb_8-nov-65_ET.bin from here http://bitsavers.informatik.uni-stuttgart.de/bits/DEC/pdp1/papertapeImages/20031202/InsidePDP1_UTILS_box2.zip. The program runs, you can write in it, and punch out tapes. When you try to read a tape back in the program you get this error: 
PTR end of file
I/O error, PC: 000346 (IOH)  
The tapes i punched out are in bin format. It's like the ptr never stops reading. Since i don't have the manuals for ET, maybe i'm doing something wrong. I'm using PDP-1 simulator V4.0-0 Beta   git commit id: 9a7c46f5 in Linux. I've tried V3.9 and it gets the same error.

**Comment by archivisth** [comment]
I'll take this, because it's been reproduced on 3.9.

**Comment by archivisth** [comment]
This is probably a failure to think through consequences on my part. The paper tape reader does an ASCII to FIODEC conversion on input. I think this was done so that Macro1 could read editable text files. However, the punch simply outputs what it is given. Thus, the punched tape is in FIODEC and is getting converted to garbage when read back.

(The conversion routine won't work with Mac text files, so it needs to be rethought anyway.)

The simplest fix would be to make the reader and punch transparent (no code conversion) and require an offline ASCII to FIODEC utility for macro1. Alternately, I could add moded conversion (determined by a switch at ATTACH time). More thought required here.

**Comment by markpizz** [comment]
My vote would be to make txt or binary an attach time option.  

BTW, Mac and UNIX text have LF line ending these days.  Back in the 1990's Macs had different line endings, but none of those systems are useful host systems for simh simulators.

**Comment by archivisth** [comment]
Okay, analysis complete. There are two problems - the lack of symmetry in how the reader and punch deal with ASCII files; and the lack of translation for the FIODEC STOP character, which signals end of tape. The changes will be:

1. Add a translation for FIODEC STOP. The Bitsavers utilities use \f, which will work fine.
2. Add an ASCII output mode to the paper-tape punch.
3. Make the "moding" of the reader and punch consistent with the other 18b simulators. In particular, the mode will be selected by switches on ATTACH, not via SET statements.
4. Make the default FIODEC (binary), not ASCII. This is because surviving source tapes, particularly those in the Bitsavers collection, are all in FIODEC. In general, the simulator should be run in FIODEC mode to minimize errors introduced by translation. The Bitsavers collection has simple utilities for converting FIODEC source tapes to ASCII text and vice-versa.

The PTP ASCII output routine will output \r\n for FIODEC carriage return. This will work correctly on Windows and won't bother UNIX or MacOS.

At the same time, I may add some indication for the console output to indicate red ink/black ink, which is used in Expensive Typewriter.

**Comment by totalegit** [comment]
Sorry for the late post. From what I can see the ptr default mode was already FIODEC. The tape was read in fine, I examined Expensive Typewriter's buffer, it just didn't stop reading, it was just garbage after that. So the problem is with the FIODEC STOP?. In the source code for the ptr I see that it already checks for FIODEC STOP or I am mistaken? The tapes I punched out don't have FIODEC STOP at the end. I tried appending a FIODEC STOP at the end but it will still get the error. How was it in real life, the program must put FIODEC STOP at the end or the punch? Expensive Typewriter doesn't put one, is it the punch job?

**Comment by archivisth** [comment]
Please post a complete session to illustrate the problem. I have some draft changes but need a debug case.

**Comment by totalegit** [comment]
PDP-1 simulator V4.0-0 Beta        git commit id: 9a7c46f5
sim> sh dev
PDP-1 simulator configuration

CPU                   
CLK	disabled
PTR	SBS level 0
PTP	SBS level 0
TTI	SBS level 0
TTO	SBS level 0
LPT	SBS level 0
DT	SBS level 0, 8 units
DRM	SBS level 0
DRP	disabled
DCS	disabled
DCSL	disabled
sim> sh cpu
CPU
	64KW, standard CPU, no multiply/divide
	no SBS
sim> sh ptr
PTR	SBS level 0
	not attached, FIODEC     //default configuration
sim> att ptr digital-1-4-s-mb_8-nov-65_ET.bin 
PTR: unit is read only
sim> boo ptr
w              //write buffer,press Enter after command, buffer is empty
a              //append, enter text mode
random text
another line of random text //CR after a line of text

Simulation stopped, PC: 000122 (SZF1 I)
sim> d ss 40   //ET uses sense switch 1 to change between control mode and text mode, found this by accident
sim> c

Simulation stopped, PC: 000501 (SZF1 I)
sim> d ss 00   // channge switch back
sim> c
w              //control mode again
random text
another line of random text

Simulation stopped, PC: 000501 (SZF1 I)
sim> sh ptp
PTP	SBS level 0
	not attached
sim> att ptp testfile.bin
PTP: creating new file
sim> c
p              //punch tape
w
random text
another line of random text
k             //kill buffer
w             //buffer is empty 

Simulation stopped, PC: 000502 (JMP 501)
sim> att ptr testfile.bin 
sim> sh ptr
PTR	SBS level 0
	attached to testfile.bin, FIODEC //it's already in FIODEC
sim> c
w
r              //read tape
PTR end of file

I/O error, PC: 000302 (IOH)   
sim> e -c 1636/24
1636:	ran   //ET buffer starts at location 1636
1637:	dom
1640:	 te
1641:	xt
1642:	l
1643:	ano
1644:	the
1645:	r l
1646:	ine
1647:	 of
1650:	 ra
1651:	ndo
1652:	m t
1653:	ext
1654:	
1655:	\
1656:	   
1657:	   
1660:	   
1661:	

The tape doesn't have a FIODEC STOP.

**Comment by archivisth** [comment]
Thank you. I've been able to reproduce (but not solve) the problem. Expensive Typewriter is doing overlapped IO without interrupts, a PDP-1 IO mode that was dropped in later machines because of its complexity. ET issues an RPA 4000, meaning don't wait and issue a completion pulse. It then goes off and does some computation. When it's done, it issues an IOH, meaning, stall here until the completion pulse is generated. This works fine until the paper tape runs out.

The way the simulator is presently coded, running off the end of tape generates an error without generating a completion pulse. That means the IOH hangs forever. Clearly, this isn't how a real PDP-1 behaved. But I don't know how it really _did_ behave. The documentation doesn't describe this case, so more research is needed, probably in the schematics.

**Comment by archivisth** [comment]
Okay, some progress. If an input tape ends with a FIODEC stop code (013) and a couple of frames of trailer (all 0s), the read command (r) works correctly. The trailer would be there naturally, because you can't get a tape out of the punch without pushing the 'feed button' long enough to get the finished tape out from under the punch head. But where the stop code should come from remains a mystery.

You can prove this with the random text/another line of random text file. It ends up being 41 bytes long, more or less (I used some capital letters, I think). Using examine deposit, go back ~10 from the end and deposit 013, and then zero out the remaining frames. The r command will now stop properly.

If there isn't a command to "close up" the tape, then the simulator needs to at least append some trailer to the file at DETACH time.

**Comment by totalegit** [comment]
Yes it works. I tried appending a FIODEC stop before but I didn't put the trailer. I found this file http://bitsavers.informatik.uni-stuttgart.de/pdf/mit/rle_pdp1/memos/pdp07_flexowr_oct63.pdf it describes the operation of the off line Flexowriter, I see that it has a stop code switch, does the real console typewriter has this switch, I can't find a good picture of it. Maybe the user has to put a stop code?
