### ISSUE TITLE
TU58 REGister descriptions aren't correct

### ISSUE THREAD

**Issue by AK6DN** [simh/simh#286]
File pdp11_td.c, line 677. BLOCK register is only 8b, needs to be 16b. A TU58 cartridge is 512. blocks 0..511., the physical TU58 protocol implements a full 16b block number 0..65535.

```
static REG td_reg[] = {
    { DRDATAD (CTRLRS, td_ctrls,  4, "number of controllers"), REG_HRO },
    { HRDATAD (ECODE,  td_regval, 8, "end packet success code") },
    { HRDATAD (BLOCK,  td_regval, 8, "current block number") },   <=======================
    { HRDATAD (RX_CSR, td_regval,16, "input control/status register") },
    { HRDATAD (RX_BUF, td_regval,16, "input buffer register") },
    { HRDATAD (TX_CSR, td_regval,16, "output control/status register") },
```
should be:
```
    { HRDATAD (BLOCK,  td_regval, 16, "current block number") }, 
```

**Comment by markpizz** [comment]
OK.  The 8 vs 16 is indeed correct, However, there are other issues with the REG variables here..  They don't properly align with accessing the memory the register declarations are intending to describe.  This is a limitation of the current register declaration functionality which don't currently include the ability to reference an element of a structure.  The block element in the controller structure is actually a 32bit value which is produced from 16 bits (in 2 bytes) of the command structure.

This problem is a TU58 problem not limited to the PDP11 and given what I said here I'm changing the title of this issue to describe the general register problem.
