### ISSUE TITLE
BSD2.11PL448/PDP11/OSX Random Intermittent "cannot execute" errors in sh/csh scripts

### ISSUE THREAD

**Issue by WILLIAMCORCORAN** [simh/simh#289]
Hello, 

On my journey into BSD2.11, I encountered an awful nasty defect where /bin/sh or /bin/csh scripts or direct command line from stdin would randomly and intermittently fail with "xxx: cannot execute." 

Where xxx is the command that failed.  

Example:  (This problem shows up more with simultaneous access of any particular external command): 

while /bin/true
do
  . . . 
done 

After several loops, and usually immediately (during simultaneous execution of two or more scripts), you will get an unexpected error in OSX: 

/bin/true: cannot execute. 

@markpizz, Steven Schultz, Rhialto, and wfjm were extremely helpful in finding the solution here.  
Now, I respectfully ask that @markpizz confirm the viability of the proposed solution.  This solution was tested heavily and no regression type effects were discovered. 

Please modify PDP11/pdp11_rq.c as described below.  You will find this solution to completely and permanently fixes this problem.  Again, extreme caution should be followed until @markpizz provides his imprimatur.    Note: THIS WAS ONLY TESTED ON A NON-NETWORKED BSD2.11PL448 KERNEL.

corky:PDP11 williamcorcoran$ diff -u $LOC/*rq* $ROC/*rq*
--- /pdp11/BSD/11-70/dst/simh/simh/PDP11/pdp11_rq.c	2016-03-18 13:19:32.000000000 -0400
+++ /pdp11/BSD/11-70/dst/simh/simh_orig/PDP11/pdp11_rq.c	2016-03-12 15:59:12.000000000 -0500
@@ -110,35 +110,8 @@
 
 #else                                                   /* PDP-11 version */
 #include "pdp11_defs.h"
-
-/* 
-   18-Mar-16 WCORCORAN BSD2.11PL448 ENCOUNTERS RANDOM, INTERMITTENT 
-                       "cannot execute" errors  during stdin 
-                       and during sh/csh script execution
-                       under PDP11 SIMH under OSX.  
-
-                       Changing the default values for 
-                       RQ_QTIME and RQ_XTIME to ZERO completely 
-                       eliminates this defect.  Regression testing 
-                       did not reveal any adverse side effects.   
-
-                       Defaults (induce the defect above):
-                       #define RQ_QTIME        200
-                       #define RQ_XTIME        500
-
-                       Revised settings eliminate this issue 
-                       with BSD2.11 on PDP11 SIMH under OSX:
-                       #define RQ_QTIME          0
-                       #define RQ_XTIME          0
-
-                       Note: Only OSX was tested, there is no 
-                       evidence this defect is present on any 
-                       other OS than OSX. 
-
-*/
-
-#define RQ_QTIME          0
-#define RQ_XTIME          0
+#define RQ_QTIME        200
+#define RQ_XTIME        500

**Comment by WILLIAMCORCORAN** [comment]
Hello, at this point, I can confirm that changing RQ_QTIME=0 and RQ_XTIME=0 will prevent the "cannot execute error."    Moreover, I have been running BSD 2.11 with SIMH (after setting the parameters) has been running flawlessly.  

PLEASE USE THE RA driver (RQ DEVICES), set the RQ_QTIME=0 and RQ_XTIME=0 in pdp11_rq.c when using PDP11/SIMH/BSD 2.11.  

I will close this case for statistical purposes.   However, we may want to develop a table that conveys the optimum/tested settings of RQ_QTIME and RQ_XTIME for various operating systems.  

Moreover, @markpizz may want to create USER parameters for RQ_QTIME and RQ_XTIME in the same way @markpizz did for the RP driver.  

For the record, I want to say that BSD 2.11 is running beautifully with SIMH.  The following system was created to run under SIMH/PDP11/BSD 2.11:

o  Two DZ boards, providing 16 mux ports, fully accessible via SIMH telnet
o  Four (4) RA-81 Disk Drives supporting /, /usr, /tmp, /usr/adm.  
o  LP Line Printer --- Fully Functional with SIMH 
o  TM0 Tape Drive (800/1600) --- Runs smooth as silk! 
o  4 MB Memory
o  Kernel Relinking 100% working 
o  Traditional build of userland! 
o  vi (visual) works flawless on DZ ports 

Once again, this attests to the brilliant work of the SIMH team.   While standard Research 7 UNIX is a prize and it too works flawlessly with SIMH.  However, BSD 2.11 contains the genesis of the UNIX tools, games, and extensions that eventually evolved into more modern UNIXs.

**Comment by markpizz** [comment]
Bill,

Sorry I hav't gotten to explaining this yet.

I'll get to it by Monday.

- Mark

**Comment by WILLIAMCORCORAN** [comment]
Hi Mark,

It's working great!

Please don't rush.  This can wait.

I only closed it since my long term testing was PERFECT!




Truly,

Bill Corcoran


On Mar 26, 2016, at 5:14 PM, Mark Pizzolato <notifications@github.com<mailto:notifications@github.com>> wrote:


Bill,

Sorry I hav't gotten to explaining this yet.

I'll get to it by Monday.

 *   Mark

**Comment by markpizz** [comment]
While you're waiting, please repeat these tests using simh v3.9 WITHOUT changing the TIME values.

**Comment by WILLIAMCORCORAN** [comment]
Mark,

Confirmed.  I will run this evening when upon my return. 


Truly,

Bill Corcoran

>

**Comment by WILLIAMCORCORAN** [comment]
Hello Mark,

SIMH-V39 Test Results:

This email confirms that sh/csh scripts powered via  SIMH V39/PDP11/BSD2.11/OSX fails with “cannot execute.”

Again, by changing the xTIME “defines" to zero (pdp11_rq.c), by way of the latest version of SIMH, PDP11, BSD2.11, under OS X will eliminate this error.

Truly,

Bill Corcoran




On Mar 26, 2016, at 9:08 PM, Mark Pizzolato <notifications@github.com<mailto:notifications@github.com>> wrote:


While you're waiting, please repeat these tests using simh v3.9 WITHOUT changing the TIME values.

**Comment by markpizz** [comment]
Bill,

Changing the xTIME delay values to 0 creates simulated hardware which behaves like no hardware in real life.  Delay times of 0 make ALL disk I/O operations complete in the same instruction that the I/O actually started.  No one ever shipped a disk drive which could seek AND transfer data in less than the time the CPU which initiated the operation could fetch and execute another instruction.

The testing you are doing has every element of the Unix operating system doing all the things it did on real hardware.  The problem when you're testing with EVERYTHING fully engaged is that if there are bugs in the operating system software (independent of the precision of the behavior of the simulated devices in the system), those bugs can reveal themselves.  In fact since the simulation is precisely capable of consistent behavior, if some subtle timing bug exists in the system the consistency of the simulated behavior will likely encounter (or avoid) problems like this.  If setting the disk delay values to 0 makes these problems disappear then they are merely being avoided and not fixed.

If there was a problem with the details of hardware simulation, then a real test that executes the minimal components of the operating system can be created to reproduce the problem and then the simulation can be fixed.  The minimal components DO NOT involve anything which lets the OS use it's buffer cache.  A single user mode application which directly exercises the suspected devices (possibly multiple instances running concurrently) will create an opportunity to actually fix the problem.

The fact that you're seeing the same or similar failures when you move from one disk type to another also completely eliminates the disk device simulation from suspicion.  The common component between each of the failures you are observing is the simulated CPU, its interrupt dispatching and I/O bus.interactions.  Maybe there are assumptions about the behavior of these pieces of the system that this OS (and probably 32V) are making that the simulation isn't providing as expected.  These behaviors may not be expected by all the other operating systems which run without problem on these simulators.  There may, in fact, not be any incorrect behaviors by the hardware here, but some combination of the CPU/bus timing may not meet the presumptions that something in the OS is expecting.  Someone capable and interested in tracking down the details of the OS issues will need to pursue this from the OS side.  Steven Schultz might be the guy to do this digging.  Please discuss my reasoning for why setting the delay values to 0 are, at best, masking the underlying problem since they're getting the simulated disk I/O to complete faster than any hardware could possibly have behaved.

I know you were excited by what seemed to have been a fix, but this is really looking in the wrong direction.

I just re-read your original description above and you said:

    while /bin/true
    do
    . . . 
    done
    
    After several loops, and usually immediately (during simultaneous
    execution of two or more scripts), you will get an unexpected error in OSX:
    
    /bin/true: cannot execute.

You mention "you will get an unexpected error in OSX".  If OSX is issuing this error (rather than the simulated operating system), then you've got some other problem with something in your real hardware.  I suspect that you are merely saying that you happening to be running this whole exercise on an OS X host system.  The problem is in the simulator and has nothing to do with OS X.  You don't need to mention the host OS.

- Mark

**Comment by WILLIAMCORCORAN** [comment]
Hi Mark,

BSD 2.11 is different than say Research 7 in that its development continued into the 90's.

Thus, its kernel and drivers are hardened as compared to Research 7.

Your points are well taken. 

I am telling you with absolute certainty that, with the RQ device (RA 81) that BSD 2.11 appears to be well behaved.  I have stressed it so many different ways and the OS hasn't slipped a tick.  

Now, here are my four theories.  As you well know, I am not a simulator expert.  So, read with that in mind:

1. The xTIME subsystem is defective or BSD 2.11 can't cope with the artificial nature of the padding.

Well, my findings show the the RP driver xp() is hosed, with spurious data loss.  But, the RQ driver is stable. No data loss or RA 81 disk errors are present even when the system encounters the "cannot execute" error.  So, the xTIME system is probably not the culprit. 

2. A stray, or spurious interrupt is being thrown (virtually of course) devices are reacting to it, but for some reason the kernel is oblivious to it.  Your going to tell me that's impossible, right?  But, this issue has the look and feel of a stray interrupt.  But, the kernel would say otherwise. 

3. When I did my testing, I ran every conceivable xTIME parameter combination that was LARGER than the defaults. I found that Zero worked.  But, I never tried 100 (since it's less than the default).  Let me repeat my testing.  This time, I will try to find some values, larger than zero, but smaller than the defaults that will work.  Maybe, if I find values that are larger than zero, and they prevent the failure, you may be more willing to accept them?
 
4. We have discussed this similarly in the past, but maybe the reason the BSD 2.11 kernel is not adapting to the xTIME subsystem (that pads the disk device timings) is due to other parts of the simulator running so much faster than real hardware.  Lol, I can compile user land in 24 minutes.  It would take 24 hours on real pdp hardware.  Maybe this huge increase in processor speed doesn't work when then try to use devices at normal speed with BSD 2.11.

Anyway, let me re-run my tests.  I will see if I can find values, other than zero, that work.  Again, all of my previous testing increased the defaults (excepting zero).  Now, I will decrease them.  

Finally, I did not know that it wasn't relevant to identify the host OS when reporting a defect.  In my case, I only ever tested SIMH on Apple's OSX.  I thought it a tad disingenuous to say that the problem can be found on all SIMH supported platforms when I only ever saw the issue on OSX.  From now on, I will keep this in mind.   

Truly,

Bill Corcoran

**Comment by markpizz** [comment]
Messing with the xTIME values in the device simulator and INCREASING them should never produce unexpected results UNLESS the operating system has some means of implementing timeouts on disk I/O operations, they can take arbitrarily long times with the only negative effect being that disk I/O is slower.  I don't believe that any operating system actually implements timeouts on disk I/O.

The current xTIME values are already at the minimum values that the complete tested set of operating systems expect.  When we encounter an operating system which doesn't like the current value (because something completes faster than it was ready for it to), we increase the default values until we find an acceptable value and this becomes the default.  The net result should still be I/O which completes much faster than it did on original hardware but might be a little slower than previously.

You said:
> 1. The xTIME subsystem is defective or BSD 2.11 can't cope with the artificial nature of the padding.

The mechanisms which implement the delay concept is too trivially simple to not work, and there is nothing artificial about the padding except that the delays can be precisely consistent where with real hardware interacting with spinning media (with arbitrary rotational positioning) the timing will vary greatly.

Just to explain the simplistic delay model:
1) something the simulated software does starts an I/O activity by touching a register, for example. During execution of the instruction which touched the register, the device simulation gets activated to interpret that register write operation and prepares to perform the requested operation.  The time delay (actually instructions to be executed) for when the I/O activity will complete is computed and a delay value is stored.  
2) Instructions execute and this delay value is decremented as each instruction is dispatched.  
3) If the count decrement gets to 0, the part of the device simulation which completes the I/O activity is executed.  
All of these things happen completely sequentially in a single thread.



> Well, my findings show the the RP driver xp() is hosed, with spurious data loss.  But, the RQ driver is stable. No data loss or RA 81 disk errors are present even when the system encounters the "cannot execute" error.  So, the xTIME system is probably not the culprit.
> 
> 2. A stray, or spurious interrupt is being thrown (virtually of course) devices are reacting to it, but for some reason the kernel is oblivious to it.  Your going to tell me that's impossible, right?  But, this issue has the look and feel of a stray interrupt.  But, the kernel would say otherwise.

This may be beginning to point to where things aren't working well.  A spurious interrupt should be detectable by the OS software since the OS should be able to check device status to determine if something it was waiting for has completed or not and then be able to properly process the result or ignore an unexpected interrupt.  Given the internal implementation model of interrupt dispatching (which works correctly for all other operating systems) I don't believe that spurious interrupts are an issue.  

That said, interrupts arriving at unexpected times may indeed be the problem.  The way OS software manages the concept of interrupts arriving or not on the PDP11 leverages the concept of the processor IPL (Interrupt Priority Level).  The PDP11 has 4 hardware interrupt priority levels (4 thru 7).  The OS can set the processor IPL to block interrupts at a particular level (and below).  Some operating system drivers have explicit knowledge of the IPL that their device will interrupt at and will set the processor IPL to that value in order to block interrupts.   Doing this allows devices which have higher priority interrupts still receive interrupts while the OS is still processing a previous interrupt.  Other operating systems and/or drivers merely set the processor IPL to 7 to block all interrupts.  Some operating system drivers 'think' they know the interrupt level that their device interrupts and but this knowledge is incorrect.  The problems that you are seeing may be related to the last case I just described.  Careful examination of the device driver code may help illuminate this.
Some devices actually came with jumpers to select the IPL the device will interrupt at.  Some folks running some operating systems in the field may have changed some of these jumpers...
A test of this idea may be possible by changing the device driver code that disables interrupts by seting the processor IPL to a particular level and make it always set the IPL to 7.  If this produces working results you will have illuminated the real problem.

**Comment by WILLIAMCORCORAN** [comment]
Be advised: @markpizz has directed that "[I close this] issue[] now and reopen [this issue] when specific details that identify a root cause have been identified."  

I will close this case as directed.
