### ISSUE TITLE
Attaching ethernet to nat hangs sim when built from Homebrew

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [simh/simh#292]
Testing simh on OS X; setting INCPATH and LIBPATH to point to /usr/local (Homebrew) produces binaries that hang on `attach xq0 nat:` I'm trying to get SDL Video working by linking against Homebrew. 

```
sim> attach xq0 nat:
NAT args: 
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
Eth: opened OS device nat:
```
*(hangs)*

Builds: [simh-bad.txt](https://github.com/simh/simh/files/181566/simh-bad.txt) [simh-good.txt](https://github.com/simh/simh/files/181564/simh-good.txt)

**Comment by markpizz** [comment]
Building on OS X with MacPorts is supported.  

Package managers which place results in /usr/local are indistinguishable from folks building directly from the source components of various packages.  There is a VERY DELIBERATE reason we don't want to support folks expecting arbitrary builds of personally built packages.  This reason is that when folks build things themselves there is little or no testing of exactly what they've built and as such we get build complaints from users.

The strategy that is supported is to ONLY use packages which the OS vendor supplies with their OS since the OS vendor (or the folks who maintain the package system) actually test what they're packaging and the resulting libraries, etc work reliably.

**Comment by WIZARDISHUNGRY** [comment]
I appreciate the justification for not supporting an arbitrary user build. I was messing around with this hoping to get a Homebrew recipe for simh4 that works 100% correctly. Handling /usr/local like /opt/local in the makefile produces a vax binary that works for SDL graphics and nat networking.
 
Would a patch to the makefile that handles  /usr/local like /opt/local – **only** if homebrew is installed – be acceptable?

**Comment by markpizz** [comment]
Honestly, you're not the first to raise the issue for building with Homebrew.  Several other folks have had problems with this.  Allowing /usr/local just opens the door for problems.  14 years ago, the only external dependencies simh had was libpcap for networking.  At that time, a libpcap API that was needed by simh (pcap_sendpacket) wasn't present in most OS distributions of libpcap so we recommended that user build it locally.  This caused many problems during that time and as time went on all the common OSes included libpcap which was completely usable.  As this finally happened we migrated to depending on the OS provided package and all problems went away.  As more external dependent libraries have been added over the past few years, this strategy of explicitly requiring the OS packages has proven distinctly valuable EVERY TIME and many questions/problems have occurred due to users building packages on their own (libSDL being problematic most recently), but your hang above is merely another example of headaches we don't need.

If you want to build a simh package which "completely works" using Homebrew, and thus depends on various other Homebrew packages AND IS TESTED, feel free.  Then folks won't have to explicitly build locally, and the support problem is yours and not mine.
