### ISSUE TITLE
set cpu idle=all makes Ultrix 4.5 unbearably slow

### ISSUE THREAD

**Issue by hbent** [simh/simh#294]
Just as the subject says.  Keypresses take a few seconds to register, and overall CPU performance is pretty slow.  Changing it to set cpu idle=ultrix fixes things.  This is on a vax8600, I can do testing on other models if needed.

show version:
VAX 8600 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 6.0.0 20160323 (experimental)
                Simulator Compiled: Mar 24 2016 at 11:12:46
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: No Video Support
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: NetBSD aelfric 7.0 NetBSD 7.0 (AELFRIC) #0: Tue Dec 29 12:28:45 EST 2015  root@aelfric:/usr/src/sys/arch/amd64/compile/AELFRIC amd64
        git commit id: e7f7b10f

**Comment by markpizz** [comment]
No need to test.

What you are seeing is not surprising.  Setting the idle type appropriately based on the OS running in the simulator is a requirement for good behavior.  The idle type selects enables particular operational patterns to let the system sleep.  The different types have been carefully observed in the respective simulated OS environments to correctly characterize when that OS is in its idle loop AND that the observed characterization doesn't reflect other normal (non idle) behavior the OS.  Setting IDLE=ALL enables all the potential patterns to cause the simulator to sleep.  

The IDLE section of the VAX documentation and the HELP CPU say:

    If idle detection is enabled with an incorrect operating system 
    setting, simulator performance or correct functionality could be 
    impacted.  

If you visit your Doctor and complain that "it hurts when I do such and such", he'll probably say "don't do such and such".

I suggest that you don't say SET CPU IDLE=ALL.  Meanwhile, I asked Bob Supnik and he agrees that there is no value in IDLE=ALL so I'm removing it.

**Comment by hbent** [comment]
Sounds good to me.  Obviously there was an easy workaround, I just wanted to make sure that there wasn't an actual problem being triggered here.  I think this can be closed.

Also I just noticed that "help cpu" is missing several of the idle options: OPENBSD, ULTRIXOLD, OPENBSDOLD, and QUASIJARUS.

**Comment by hbent** [comment]
It looks like a few idles should be renamed:

ULTRIX-1.X: Works for 3BSD, 4.0BSD, 4.1BSD, 4.2BSD, Ultrix 1.1, etc.  Should probably be renamed BSDOLD.
QUASIJARUS: Works for 4.3BSD, 4.3BSD-Reno.  Should probably be renamed 43BSD.

**Comment by markpizz** [comment]
If you look at the code, there are the following definitions:

    #define VAX_IDLE_VMS        0x01
    #define VAX_IDLE_ULT        0x02    /* Ultrix more recent versions */
    #define VAX_IDLE_ULTOLD     0x04    /* Ultrix older versions */
    #define VAX_IDLE_ULT1X      0x08    /* Ultrix 1.x */
    #define VAX_IDLE_QUAD       0x10
    #define VAX_IDLE_BSDNEW     0x20
    #define VAX_IDLE_SYSV       0x40
    #define VAX_IDLE_ELN        0x80    /* VAXELN */

And the following table used in parsing the SET CPU IDLE=XXX:

    static struct os_idle os_tab[] = {
        { "VMS",        VAX_IDLE_VMS },
        { "NETBSDOLD",  VAX_IDLE_ULTOLD },
        { "NETBSD",     VAX_IDLE_BSDNEW },
        { "ULTRIX",     VAX_IDLE_ULT },
        { "ULTRIXOLD",  VAX_IDLE_ULTOLD },
        { "ULTRIX-1.X", VAX_IDLE_ULT1X },
        { "OPENBSDOLD", VAX_IDLE_QUAD },
        { "OPENBSD",    VAX_IDLE_BSDNEW },
        { "QUASIJARUS", VAX_IDLE_QUAD },
        { "32V",        VAX_IDLE_VMS },
        { "ELN",        VAX_IDLE_ELN },
        { NULL, 0 }
        };

Each of the VAX_IDLE_ masks relate to a different execution detection pattern that has been observed in the respective operating systems.  They were defined as flags since Bob originally supported ALL (which included all of the flags).  We want them to be disjoint, which will happen since there now is no way to set more than one flag.

I don't want to remove entries from the parsing table since there may be existing configurations files which use one of the currently defined names and I don't want to break them.  No problem adding additional names though, so rather than any renaming we merely increase the table to cover all of the OS versions you mention:

    static struct os_idle os_tab[] = {
        { "VMS",            VAX_IDLE_VMS },
        { "NETBSDOLD",      VAX_IDLE_ULTOLD },
        { "NETBSD",         VAX_IDLE_BSDNEW },
        { "ULTRIX",         VAX_IDLE_ULT },
        { "ULTRIXOLD",      VAX_IDLE_ULTOLD },
        { "ULTRIX-1.X",     VAX_IDLE_ULT1X },
        { "3BSD",           VAX_IDLE_ULT1X },
        { "4.0BSD",         VAX_IDLE_ULT1X },
        { "4.1BSD",         VAX_IDLE_ULT1X },
        { "4.2BSD",         VAX_IDLE_ULT1X },
        { "OPENBSDOLD",     VAX_IDLE_QUAD },
        { "OPENBSD",        VAX_IDLE_BSDNEW },
        { "QUASIJARUS",     VAX_IDLE_QUAD },
        { "4.3BSD",         VAX_IDLE_QUAD },
        { "4.4BSD-Reno",    VAX_IDLE_QUAD },
        { "32V",            VAX_IDLE_VMS },
        { "ELN",            VAX_IDLE_ELN },
        { NULL, 0 }
        };

OK?

What is 3BSD?  It isn't 32V, right?  Just a couple of months ago I observed the idle on 32V and it indeed has the same detection pattern as VMS.  VMS has actually done idling different across versions.  The early idle was actually an instruction which unconditionally jumped to itself.  This is an OS independent idle condition so there is no mask involved in the idle test for these cases.  Later VMS did some specific branch at an IPL which no version of Unix uses.  Given this the 32V case must be a branch to self.

There isn't actually a pattern which corresponds to the VAX_IDLE_SYSV mask value so I'll remove that one,

**Comment by hbent** [comment]
This all looks fine.  3BSD is the original version of BSD for the VAX, before 4BSD.  It is a 32V descendant but rewritten to support virtual memory.
