### ISSUE TITLE
MicroVAX 2: $set time, WTC, nvram.bin issue

### ISSUE THREAD

**Issue by wboerhout** [simh/simh#305]
Noticing "irregular behavior" on the MicroVAX2 with respect to preserving time across boots, I started the following investigation. Config details are below in the attachments. SYSGEN SETTIME parameter = 0 on all system disks involved.

**STEP 1** Starting with a VMS systems disk that has not been booted for a month, I started it up without the attached nvram being present. The disk booted without asking for time, although the date in the system image was off by a month:
```
VAXTCP::SYSTEM$ ana /sys

OpenVMS (TM) VAX System analyzer

SDA> exam /time EXE$GQ_TODCBASE
12-MAR-2016 11:45:40.01
```
Without the nvram file being present initially, should it not always ask for time? No nvram.bin present being the equivalent of "nvram not valid" in the physical world?

**STEP 2** Adjusted the time to today's value. Shut down VMS. removed the "att nvr" line from the config file. Booted VMS. Now it asks for date and time!

**STEP 3** Booted the MicroVAX into my VAXcluster via network boot, previous nvram.bin attached again. It boots into the cluster without asking for time.

**STEP 4** Shutdown, removed the nvram.bin file, but kept the "attnvr" line, so a new file would be created. Booted into the cluster again. With this "invalid", newly created nvram.bin, it does not ask for time as in step 1.

Now if I only had kept a real MicroVAX 2 around...

[buildlog.txt](https://github.com/simh/simh/files/216857/buildlog.txt)
[showvers.txt](https://github.com/simh/simh/files/216861/showvers.txt)
[testnvram.ini.txt](https://github.com/simh/simh/files/216864/testnvram.ini.txt)

**Comment by markpizz** [comment]
Will,
Good tests with a separate explanation for each:

While looking closely at the modeling of the behavior of the watch chip in the MicroVAX II, I discovered a couple of issues:
1) The mapping of the time (when in VMS mode) did not account for Leap Day during Leap when the current year is a leap year.  This is now fixed.
2) The value returned when reading the month, was always off by 1 (one month early) since the watch chip maintains the month as starting at 1 for January and the struct tm contains a tm_mon which starts at 0 for January.  This is now fixed.

There may still be issues with the NVR modeling but now the time is more meaningfully interpreted.

Please test this and comment on the current behavior.

Thanks.

- Mark

**Comment by wboerhout** [comment]
Thanks Mark.

Being new to the github management environment, I have to ask: are these fixes now in the master branch (master.zip), or do I need to download a separate fork?

Wilm

**Comment by wboerhout** [comment]
_assumed (by your comment) it's in the master branch_

I repeated all four tests, I could not see any change in behaviour. Notably, the result in step 1 is unexpected. I look like the newly created nvr is somehow "valid". What is expected on VMS is described below:

```
The system parameters SETTIME and TIMEPROMPTWAIT determine how the system
time will be set.

IF SETTIME = 0 and the TOY clock is valid 
THEN the contents of the TOY clock are compared to those of EXE$GL_TODR.
IF the TOY clock is more than a day behind EXE$GL_TODR 
THEN the TOY clock is presumed invalid.

IF the TOY clock is within a day of EXE$GL_TODR 
THEN the system time is calculated as follows:
EXE$GQ_SYSTIME = EXE$GQ_TODCBASE + ((TOY_CLOCK - EXE$GL_TODR) * 100000)

IF SETTIME = 1 or the TOY clock is invalid 
THEN the value of TIMEPROMPTWAIT determines how to reset the time of year.
IF TIMEPROMPTWAIT > 0 
THEN the user is prompted for the time and date,
for a length of time equal to TIMEPROMPTWAIT microfortnights.

IF TIMEPROMPTWAIT = 0 
THEN the time of year is the value of EXE$GL_TODR + 10ms.
IF TIMEPROMPTWAIT < 0 
THEN the user is prompted for the time and date
and unable to proceed until they do so.
```
[buildlog.txt](https://github.com/simh/simh/files/218718/buildlog.txt)
[showvers.txt](https://github.com/simh/simh/files/218719/showvers.txt)

**Comment by wboerhout** [comment]
identical behaviour confirmed on RHEL Linux 7.1
```
sim> show version
MicroVAX II (KA630) simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 4.8.5 20150623 (Red Hat 4.8.5-4)
                Simulator Compiled: Apr 14 2016 at 11:50:04
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 1.2.15
                RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: Linux vxds20.vxlabs.local 3.10.0-327.13.1.el7.x86_64 #1 SMP Mon Feb 29 13:22:02 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: b502558d
```

**Comment by markpizz** [comment]
You say that **STEP 1** still boots with a date that is off by a month.  It doesn't do that on my system.  
If I attach a new file to the NVR and I boot the system, I am not prompted for time AND the Month, Day and time are CORRECT for today's date.  The year is whatever the year I gave the last time I answered a time prompt OR I explicitly specified a time with a "SET TIME=somedate&time".  

Before yesterday's change to the Watch implementation the date was off by 1 month and the day of the month was also off.

The newly create NVR does indeed present a valid time to VMS when VMS asks the watch chip what time it is.  The mere fact that you've ATTACHed the NVR device to a file automatically sets the time in the clock chip and then has it behave like it was running all the time and is now properly connected to a battery which has a good charge.

So the current (newly corrected) behavior in the **STEP 1** case is "as designed".

In the **STEP 2** case, you're booting without the NVR being attached to a file to allow the RAM components of the chip to persist between stops and starts of the simulator.  This is equivalent to running a real MicroVAX II with a dead or disconnected battery.  The clock will need to be set when the system boots and will run while system power is present, but doesn't when the system is turned off.  I believe that this is the correct behavior.

As for **STEP 3** and **STEP 4**, see **STEP 1** above.

The fact that a file is attached to the NVR device merely provides the indication to the simulated system that the clock's battery is good and therefore that the NVR is in a reasonable state.  Nothing useful besides the time is provided by the watch chip on this system.  This behavior maps reasonably consistently to how the TODR on the VAX 3900 and VAX780 simulators work.  The difference here is that the VAX and VAX780 simulators default to always presenting what appears to be a good time (from VMS's point of view).  This default was established when these simulators were written.  Subsequent enhancements to these simulators added the ability to precisely track the programmatic behavior of the TODR if the CLK device is attached to a state file.  With one of those simulators having the CLK device attached to a state file, you could do a "SET TIME=someday&time" where "someday&time" might not be a current date and time, and shut the system and come back later and attach the same state file and boot the system and the system time will be the original set date & time offset by the amount of elapsed time between when you entered the "SET TIME" command and the current time.

Besides the date issues which I think I've fixed, how do you expect the MicroVAX II simulator to behave differently from how it does now and why?

**Comment by wboerhout** [comment]
Let's focus on step 1 because that is unxpected behaviour.

This virtual MicroVAX has been switched off for, let's say, 6 weeks. It has recorded its last known time in its system image on the system disk. This time happens to be March 1st, 2016, 00:00.

What is unexpected to me is, that when I boot from this disk with a valid time in the NVR, it continues its boot without adjusting the time. After boot, the time on the simh MicroVAX is still March 1st. I have always understood that the function of the watch chip / NVR on several VAXen is to keep record of the delta time when the machine is switched off, so that when booting, the time in the system image would be added to the time passed in the watch chip.

So a machine continuing its boot with the time from the system image is unexpected. I must now study and verify this:

```
EXE$GQ_SYSTIME
This is the OpenVMS VAX system time cell.
This cell contains the number of 100ns intervals since a known reference.
This cell is incremented by 100000 every 10ms by an hardware interval timer.

EXE$GQ_TODCBASE
This cell contains the time and date the system time was last adjusted by EXE$SETTIME.
It uses the same format as EXE$GQ_SYSTIME.
On adjustment of the system time a copy of EXE$GQ_SYSTIME is stored
in this cell in both memory and on disk.
This cell is used to get the year for the system time.

EXE$GL_TODR
This cell contains the time and date the system time was last adjusted by EXE$SETTIME.
It uses the same format as the time of year clock.
On adjustment of the system time this cell gets saved back to both memory and disk.
The contents of this cell are used to test the validity of the TOY clock.
The system parameters SETTIME and TIMEPROMPTWAIT determine how
the system time will be set.

IF SETTIME = 0 and the TOY clock is valid 
THEN the contents of the TOY clock are compared to those of EXE$GL_TODR.
IF the TOY clock is more than a day behind EXE$GL_TODR 
THEN the TOY clock is presumed invalid.

IF the TOY clock is within a day of EXE$GL_TODR 
THEN the system time is calculated as follows:
EXE$GQ_SYSTIME = EXE$GQ_TODCBASE + ((TOY_CLOCK - EXE$GL_TODR) * 100000)

IF SETTIME = 1 or the TOY clock is invalid 
THEN the value of TIMEPROMPTWAIT determines how to reset the time of year.
IF TIMEPROMPTWAIT > 0 
THEN the user is prompted for the time and date,
for a length of time equal to TIMEPROMPTWAIT microfortnights.

IF TIMEPROMPTWAIT = 0 
THEN the time of year is the value of EXE$GL_TODR + 10ms.
IF TIMEPROMPTWAIT < 0 
THEN the user is prompted for the time and date and the system
is unable to proceed until they do so.

When booting a CD-ROM containing an OpenVMS VAX system, the system
will typically be deliberately configured prompt the user to input the time;
this is necessary in order to boot with the correct time.
```

**Comment by markpizz** [comment]
I almost agree with almost everything you've said with one extra explanation:

    EXE$GL_TODR
    This cell contains the time and date the system time was last adjusted by EXE$SETTIME.
    It uses the same format as the time of year clock.
    On adjustment of the system time this cell gets saved back to both memory and disk.
    The contents of this cell are used to test the validity of the TOY clock.
    The system parameters SETTIME and TIMEPROMPTWAIT determine how
    the system time will be set.

I think it uses the same format as the TODR processor register on the systems which have such a register.  That 32bit register is usually battery powered and increments by 1 every 10ms.  VMS sets this register to the time of year (in 10ms units) offset by 0x10000000 (which is approximately 31 days).  The offset serves to distinguish a clock that has just been powered on (when system power was applied), but the system didn't actually boot for some time.  The presumption is that no one would power on a system and let it sit at the >>> prompt before booting it for 31 days, but if they did the other checks you describe would probably catch that.

The MicroVAX II doesn't have a battery backed up TODR register.  It does have this watch chip which can be twisted to serve the same purpose though.  This twisting happens on this system by code which replaces the attempts to write and read the internal TODR from the system with a routine which converts the computed 32bit TODR value to a time format the watch chip can contain.  The watch chip only maintains accuracy in seconds (we don't worry about precise 10ms units), but otherwise the mapping is pretty easy.  The TODR value has the 0x10000000 offset removed and the resulting time of year is converted to Month, Day, Hour, Minute and Second with a constant year of 1982.  This conversion is done in reverse when the register is read with an invalid date represented by some value less than 0x10000000 would indicate an attempt to read a clock that hadn't been set since it's battery had been connected.

By the way you can easily create a disk which appears to not have been booted in an arbitrary amount of time merely by doing a "SET TIME=arbitrary-date/time" and then shutting the system down.  Booting later from this disk with a simulator which has TODR (or watch chip) configured as if it was battery backed up should then exercise the time setting algorithms you mention and trigger a prompt for time when the TODR appears either unset or earlier in the year than when the system was shutdown.  If the TODR value is later in the year (but still less than 1 year) then the value is considered valid and unless SETTIME is set to 1 it shouldn't prompt for a time during a boot. 

The MicroVAX II simulator will have a battery backed up watch chip only if the system is booted with at ATT NVR somefile.  The other (VAX and VAX780) simulators will appear to have a battery backed up TODR without any special action.  This inconsistency is related to the fact that these simulators were written before any attempt to be precise about modeling the battery backup behavior was considered.  In order to avoid user confusion for folks following recipes about how to use  these simulators, the default behavior was retained.  The default behavior provides a strange clock value for operating systems other than VMS, so the "OS Agnostic" mode (hardware precise) is provided to allow all operating systems to use the simulated TODR just as they did with the real hardware. "OS Agnostic" mode is enabled by "ATTACH CLK someclockstatefile".

The 32bit TODR can describe approximately 497 days of 10ms ticks.  Reserving 31 days for invalid times still allows for about 15 months of valid times before the clock can wrap around.  Some hardware TODR registers will continue after the register overflows and others will stop incrementing.  In either case the invalid value should be caught for almost all reasonable (non contrived) scenarios on a subsequent boot.

**Comment by markpizz** [comment]
Will,

Do my prior comments make sense?  Given the designed behavior, do you still think there is something wrong with how it works for you?

Meanwhile, I've just added a change which makes the simulated access to the NVR memory precisely the same as how the real hardware works.  I wrote a test program which was run on real hardware and the recorded the results and that information was used to correct the simulation.  The details here were about the behavior of BYTE, WORD, and LONGWORD read and write access to the NVR and have nothing to do with the battery backup behaviors.

If you don't think things are broken, please close this issue.

Thanks.

- Mark

**Comment by wboerhout** [comment]
Thanks Mark, I believe we're on the same page (boundary) now.

Wilm
