### ISSUE TITLE
VAX Idling on Linux consumes non-trivial amount of CPU

### ISSUE THREAD

**Issue by hbent** [simh/simh#314]
I recently switched from NetBSD (7.0) to Linux (4.5.4) on my main machine and now simulators that would fully idle (CPU use at or near 0 on the host) consume 10% or more CPU while doing essentially nothing.  I tested some 4.xBSDs as well as Ultrix and the issue appears to be the same everywhere.  I tested vax8600 and vax780 and the issue appears in both.  I'm not sure where to start with providing useful information - what would be helpful here?  Gcov profiling?

sim> show version
VAX 8600 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 5.3.0
                Simulator Compiled as C: May 16 2016 at 10:02:29
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: No Video Support
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: Linux aelfric 4.5.4-gentoo #1 SMP Sun May 15 16:43:33 EDT 2016 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux
        git commit id: 03445f5f

**Comment by hbent** [comment]
This also seems to be happening on pdp11 - I tested V7M and Ultrix 3.1.  FWIW I also tested RT-11 V5.3 and it doesn't seem to want to idle at all, but I don't remember if it idled correctly before this.

**Comment by markpizz** [comment]
Hi Henry,

What was the SHOW VERSION:
```
OS clock resolution: 1ms
Time taken by msleep(1): 2ms
```
on the NetBSD system?

- Mark

**Comment by hbent** [comment]
According to some of my recent bug reports, it was exactly the same (1ms and 2ms) on both vax and pdp11 - I had a NetBSD kernel compiled with HZ=1000 per your suggestion.

**Comment by markpizz** [comment]
OK.

Then are you sure you're comparing apples to apples (i.e. running simulators with exactly the same device and network configurations)?

I ask since there may be some device which schedules itself for periodic polling which isn't properly synched with the clock ticks and as such adds extra load...

**Comment by markpizz** [comment]
The proper synching I'm referring to is not something you control but bug/feature of the device simulation.

**Comment by hbent** [comment]
Yes, the simulators are exactly the same.  I just moved the disk images and config files from one machine to another, and I didn't change anything.  I did have to set up tap networking on Linux, which was a little strange (at least as compared to NetBSD) - I can test without it and see if that makes any difference.

**Comment by hbent** [comment]
OK, testing on a vax8600 running Ultrix 2.0:
xu not attached to a host interface: no change
xu disabled entirely: no change
dz not attached to a host interface: no change
xu disabled, dz disabled, ts disabled, todr and cs not attached: no change

I can't strip my configuration down any further than that.  It does seem like something fishy is happening with idling in general on this system - I booted a pdp8 running OS/8 and it does idle but it's still consuming 3-4% cpu.

On the VAX I'm not really running anything I don't need.  My standard vax8600.ini:
set cpu idle=ultrixold
set cpu 260m
set rq0 ra81
att rq0 ra81.dsk
set rq1 dis
set rq2 dis
set rq3 dis
att cs consolerl
set cr dis
set rp dis
set hk dis
set ry dis
set lpt dis
set rl dis
set tq dis
set tu dis
set ts lock
set tti 7b
set tto 7b
set xu enabled
set xu MAC=08:00:2B:1C:86:00
set xu type=deuna
att xu tap:tap1 
set dz lines=8 
set dz 7b 
att dz 8600 
att todr vax8600.todr
boot rq0

**Comment by hbent** [comment]
I spun up an old VM with Ubuntu 10.04 on it (kernel 2.6.32) and the vax8600 simulator with a standard configuration idles around 1-2% cpu, which is more in line with what I would expect.  I'll get a NetBSD 7.0 VM ready to double check everything.

**Comment by markpizz** [comment]
What you'er observing may merely come down to how the OS kernel manages its bookkeeping for being busy.  One OS (BSD) may count 'busy' as when a clock tick happens and the system isn't idling.  Another (new Linux) may count a busy tick if a process becomes runnable when a clock tick happens.  I vaguely remember something about tickless kernel behaviors which might be what is causing this bookkeeping change in the newer Linux vs the older one.

I don;t think this is a simh problem.

**Comment by hbent** [comment]
OK, seems reasonable, I'll investigate tickless kernel options and see if it makes a difference.  Thanks.

**Comment by hbent** [comment]
I turned off tickless idle but it doesn't seem to have made a difference.

strace shows that there is a flood of identical syscalls coming from the simulator:
futex(0x844bc0, FUTEX_WAKE_PRIVATE, 1)  = 0
read(0, "", 1)                          = 0
futex(0x844b84, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 116619, {1463418364, 400441540}, ffffffff) = -1 ETIMEDOUT (Connection timed out)

over and over, and it looks like this is causing non-maskable interrupts.

**Comment by markpizz** [comment]
Even when idling, the simulator will sleeping for 9-10ms and be polling for input on the console and any sockets with active telnet sessions.  This will be 100 times per second.  Like I said before, what you're seeing may merely be a kernel level bookkeeping issue.

You might be able to actually measure the available cycles by running a process which runs at a lower priority than the simulator and merely sucks up all available cycles and counts how much it is able to achieve while the simulator is idling.  Confirming that while that program is running in the background, the CPU % used by the idling simulator should be the same.  If that is true, then running that exact same binary on different OSes will help to determine if this is a bookkeeping problem (if the same amount of work is done by the background program on both OSes while the simulator CPU % is different).

**Comment by hbent** [comment]
OK, I ran a CPU stress tester at a lower priority than SIMH, and there was no appreciable change in the reported CPU use of the simulator.

**Comment by markpizz** [comment]
I didn't expect the simulator's CPU usage to change.  That you are now convinced of that is good.

Whatever the low priority CPU consumer is doing is clearly the compliment of what the simulator is doing .  All you need is some way for the CPU consumer to display the amount of 'work' it is accomplishing every n seconds.  If that work is closer to the same on one OS vs another then the simulator's apparrent difference in usage is due to a change in bookkeeping as I suggested.  

If I was writing the CPU consumer program, I'd have 1 thread for each Core and Hyperthread available on the system merely incrementing a per thread 64bit counter and a single higher priority thread which sleeps for n seconds and whenever it wakes up it displays the total change of all the consumer thread increment values.

**Comment by hbent** [comment]
Commit 253e9deea7023104931fbca8e409388bbbd75336 seems to have substantially fixed this problem - I now see 2-3% CPU use, which is not quite to the level where NetBSD was but is fine for my purposes.  Mark, I'm fine with closing this if you are.

**Comment by markpizz** [comment]
That is quite surprising.

#315 was the original problem report that illustrated that the logic implementing idle detection and infinite loop at IPL 31 needed to be fixed by providing the infinite loop case.

I'm trying to wrap my mind around how the problem that was fixed could increase the CPU cycles used while actually idling.  If anything, I'd expect the opposite.

The improperly detected infinite loop case is too hard to miss since it causes the simulator to stop executing instructions and return to the sim> prompt.  Improperly detected idling condition would be much harder to find, but the consequence would not seem to be consuming only slightly more CPU....

**Comment by hbent** [comment]
Perhaps that wasn't what fixed it, but something that changed in the last few days on my end (including pulling up to the latest git sources) seems to have made the problem much better.  I did also upgrade to Linux 4.6.0, so maybe that was what did it.

**Comment by markpizz** [comment]
Too many changes at the same time..  Can you try some git bisect activity to see if the problem really was a change to the simulator?

**Comment by hbent** [comment]
After a lot of testing with git-bisect, various versions of GCC, and various compiler flags, it appears that "-flto -fwhole-program" is what is causing the increased CPU use.  I am at a total loss to explain why this would be the case, and perhaps it is not for other OSes or GCC versions (I tested with 5.3 and a 7.0 prerelease).  So this is definitely not a SIMH bug.  I don't currently have a position on whether or not LTO should be enabled by default if the compiler supports it, as is currently the case - perhaps I will do some testing to see whether there is any overall speed bonus/penalty to using those options, separate from the idle issue.

**Comment by markpizz** [comment]
Good idea to see what the potential benefit of LTO is or not.

That functionality came into the makefile a few years ago when Sergey Oboguev did his Multiprocessor VAX simulator (https://github.com/oboguev/vax_mp).

Recent errors building with clang on some platforms (which didn't occur previously), caused it to be removed entirely when building with clang.  If there is truly a benefit from the LTO optimizations then I'll look for a better ways to see if it is available.

**Comment by hbent** [comment]
I was seeing this issue again and was actually going to revisit it because I changed my mind about it being a compiler issue, but it appears that either commit 2b61a9a92d7a88995c0f8d6c35a221fd0296415b or commit da3f5359bb20fe6a7d124e17317b6d1026a5ec8a made a significant improvement.  Mark, any further comments before I close this?

**Comment by markpizz** [comment]
That is great news.  

I'm working on general timing issues right now.  That work wasn't deliberate.  I'd recently visited the timing code to solve the problem that clock ticks were unrelated to wall clock time when throttling was enabled.  That got my mind warmed up to start to tackle finishing asynchronous clocks.  Before I started that, a strange report which hung the Nova simulator actually drove me into the finding the subtle bugs in the timing code fixed by those commits.  The Nova simulator handled timing more or less like most other simulators with 2 exceptions.  1) The hardware clock was specifically started by programmed activities (rather than always being on as is the case for other simulators), This initial lack of an internal clock caused the timer code to run an internal timer which served to provide a measurement of instruction execution rates so that explicit wall clock event scheduling would have a proper reference, and 2) The Nova clock code has several programmatically settable tick rates, and as such, based on the the set clock tick rate, it examined the calibrated timer tick interval (not done by most other simulators) and then used that interval to compute the appropriate polling rate for MUX character input.  Due to the subtle bug (only visible when multiple clocks were enabled), the computation produced a polling delay value of 0 which once the first poll happened, would cause continuous polling without any instruction execution.

So, how could this affect the VAX simulator.  Well, there are 2 calibrated clocks used by the MicroVAX 3900 (aka VAX) simulator which, in general, aren't both part of the other VAX simulators.  One is the standard 100Hz clock tick and the other is the interval timer.  Both of these are used programmatically during the boot ROM's startup diagnostics.  The subtlety of this allowed this problem to exist for so long, had the problem produced more drastic problems, it would have been obvious earlier.

Please close this issue.
