### ISSUE TITLE
Shift Key Doesn't work with QVSS video on MicroVAX II

### ISSUE THREAD

**Issue by raywjewhurst** [simh/simh#320]
I am using git commit id: e05de3e5 Windows prebuilt binary.  I have a Dell Inspiron 15R running Windows 10 64-bit.  I have tried multiple keyboards and this only happens when QVSS is enabled, otherwise key input works fine.

**Comment by markpizz** [comment]
Please provide your configuration file.

**Comment by raywjewhurst** [comment]
;
; Load CPU microcode
load -r ka630.bin
;
; Attach non-volatile RAM to a file
attach nvr nvram.bin
;
; Define disk drive types. RA92 is largest-supported VAX drive.
set rq0 ra92
set rq1 ra92
set rq2 ra92
set rq3 cdrom
;
; Attach defined drives to local files
attach rq0 d0.dsk
attach rq1 d1.dsk
attach rq2 d2.dsk
;
; Attach the CD-ROM to its file (read-only) 
attach -r rq3 openVMS.iso
;
; Disable unused devices. It's also possible to disable individual devices,
; using a construction like "set rq2 disable" if desired. 
;
set rl disable
set ts disable
; 
; Attach Ethernet to a network interface
set xq mac=08-00-2B-AA-BB-CC
attach xq eth0
;
; Now start the emulator
set qvss enable
boot cpu

**Comment by markpizz** [comment]
Well, the shift key does work, but it doesn't work as you would expect it to.

Specifically, it works sometimes....  I'm exploring why....

**Comment by pghardy** [comment]
I'm getting the same effect of the shift key only intermittently working, using the latest prebuilt Windows VAX.exe, git commit id: bce72b2b on an i7 PC under Windows 10 (incidentally, why no builds since 11 February?).
I note that the effect seems to depend on the time interval between hitting shift and hitting the primary key - if I hold down shift and count to three before pressing the key, it always fails, while if I hit shift and then the key straight after, it usually works.
