### ISSUE TITLE
scp comment character...

### ISSUE THREAD

**Issue by JonathanBelanger** [simh/simh#323]
If a semi-colon or hash is in the first character position, it is considered a comment character.  Are either of these characters used anywhere else in a command line?  If so, then is there a character that can be considered a mid-line start of comment to end-of-line?

**Comment by markpizz** [comment]
semi-colon(;) or hash(#) in the first NON-whitespace character positions are the only formal comment characters.  This syntax goes back to the original scp design AND due to the flexibility of how and where commands are parsed, adding a middle of the line comment character would certainly break existing simulator code somewhere.

Additionally, lines starting with the colon character are labels which can be the target of GOTO or CALL commands, OR they could merely be comments.

    ;                                   This line is a comment
    #                                   This line is a comment
    ::::::::::::::::::::::::::::::::::::This line is equivalent to a comment :::::::::::::::::

**Comment by JonathanBelanger** [comment]
If I came up with a end of line comment character string, say $$, can I do this or is this something forbidden?

**Comment by markpizz** [comment]
The problem is that you can't fix every place a line's contents is parsed in every simulator and every device in each simulator to be sure that it doesn't break anything.which is already allowed.

It would be easy to add yet another beginning of line character which starts a comment since when that happens, dispatching to the many places parsing is done hasn't yet started. Once the first token on the line is separated from the line dispatching to arbitrary places begins and they allowed syntax in any of those places may include whatever you may come up with.

It is a nice desire, which really can't be done at this time.  If it was first implemented then the rules could have been defined then.  Now is too late.

If you were writing your own simulator, you could certainly implement such a thing for the commands that your simulator defines, but a general solution isn't possible at this time.

**Comment by JonathanBelanger** [comment]
That's too bad.  I ran into this problem trying to load an example configuration from a document that used the semi-colon (;) to comment each line.  I didn't realize that this was not allowed and it took a while for me to figure it out.  Thanks for the background.

**Comment by Rhialto** [comment]
What I imagine could be done is the toplevel parser (at the place where
it looks for the current first nonspace ; or #) to look for the magic
### string (or whatever), and remove that and the rest from the line
before passing it on to the sub-parsers.

What remains is the compatiblity issue, so the marker should be fairly
unique.

**Comment by markpizz** [comment]
What you're suggesting is how it would be done IF all of the parsing had the same rules as the first component that now strips lines starting with # or ;.  However the point is that there are no rules beyond the extraction of the first token, As such,,whatever 'fairly unique' rest of line comment indicator that is chosen could be completely meaningful content for some deeper parsing logic.  Short of exhaustively digging through all of the currently published and currently unpublished simulators and validating the details of their parsing rules there would be no assurance that breaking things won't be happening.  Since we have no control over all of the unpublished simulators AND the effort to exhaustively analyze the parsing details of each of the current simulator components is a non-trivial task, AND the fact that everything that could be explained with end of line comments can also be explained with start of line comments (with arbitrary leading white space), the pain to implement a correct solution far outweighs the potential gain.
