### ISSUE TITLE
VAX Read-only G-Floating operand decoding question...

### ISSUE THREAD

**Issue by JonathanBelanger** [simh/simh#327]
I was looking through the VAX decoding code and masks and noticed that the G-Float is different than the other types for short literals.  The .rg access and type is defined as having set the SP flag, the ocatword length, and the modify access.  It is the modify access that I'm questioning.  If .rg is for read-only, is it expected that the modify access is set or should this be read-only.  The comment for special dispatches in the vax_defs.h indicate that f-, d-, g-, h- floating are handled like other types of the same size, except for short literals.  The problem is that f-, d-, and h- do not have the modify access (just read-only) and g-floating is different.  Am I missing something?  If so, how is this working?  If there is a reference to this being the way it is supposed to be, I'd appreciate seeing it.

Thanks,

~Jon.

**Comment by archivisth** [comment]
If the special flag is set, then the access type field is irrelevant (the length field matters; hence RG must have a quadword length). If you look at the specifier flows, specifier type|RG is used to define a unique entry point, always grouped with the read operand flows.

In short literal, in particular, RG invokes special formating but is otherwise identical to RQ. All true modify operand short literal specifiers end up faulting (they have no CASE point in the specifier flows).

**Comment by JonathanBelanger** [comment]
OK, the special flag meaning that the access type is not relevant make sense.

As for the second paragraph, I'm not sure that is the case.  There is 1 set of case statements that look like the following:
`case SH0|RG: case SH1|RG: case SH2|RG: case SH3|RG:`

> 
SH0 = 0x000
SH1 = 0x010
SH2 = 0x020
SH3 = 0x030
>
RG = (DR_SPFLAG | MQ) = (DR_SPFLAG | DR_M | DR_QUAD) = 0x008 | 0x100 | 0x003 = 0x10B

It is the RG that bothers me.  As you can see it has the modify bit set, so it won't end up faulting.  If the access type should be ignored when the special flag is set, then shouldn't the access field get cleared or should all possibilities for the access flag be treated as equals?

I'm still a bit confused, but the light is starting to shine.

Thanks,

~Jon.

**Comment by archivisth** [comment]
Let me try this again. The "access mode" field has no independent meaning. The simulator is using the decode ROM and the actual specifier to put together a 10b code which is a dispatch point in a gigantic CASE statement. If the special flag is NOT set, then the dispatch point is:

access mode'specifier mode'0'length

If the special flag IS set, then the dispatch point is:

special type'specifier mode'1'length

This provide a unique set of dispatches, all of which have bit<3> set.

If it bothers you that the special dispatches are defined in terms of access modes, then just think of them as:

#define VB              (DR_SPFLAG|0x200|DR_BYTE)                  /* .vb */
#define RF              (DR_SPFLAG|0x000|DR_LONG)                  /* .rf */
#define RD              (DR_SPFLAG|0x000|DR_QUAD)                  /* .rd */
#define RG              (DR_SPFLAG|0x100|DR_QUAD)                  /* .rg */
#define RH              (DR_SPFLAG|0x000|DR_OCTA)                  /* .rh */
#define BB              (DR_SPFLAG|0x206|DR_BYTE)                /* byte branch */
#define BW              (DR_SPFLAG|0x206|DR_WORD)                /* word branch */

This should make clear that THERE IS NO MEANING to the bits in the access field for special specifier types. They are just defining CASE points in the code. To understand how these are treated, you have to read the specifier flow code. There are four entry points for RG short literal, because short literal is specifiers 0x0n thru 0x3n: 0x10B, 0x11B, 0x12B, 0x13B. All are unique CASE points. All act just like the other short literal cases, except for formatting the literal as a floating point number.

**Comment by JonathanBelanger** [comment]
Thanks, that makes sense now.  I've been decoding these case statements with the goal to speed them up using calculated branching.  I saw what looked like an anomaly and questioned it.

Jon.
