### ISSUE TITLE
Not a simulator issue: Mapping a PC keyboard in DECwindows...

### ISSUE THREAD

**Issue by JonathanBelanger** [simh/simh#328]
Hi All,

I've tried all kinds of things with only limited success.  Here is my configuration:

- simh v4.0 (VAX) running on a Windows 10 PC
- 101/102 PC keyboard
- xMing Version 6.9.0.31
- OpenVMS VAX V7.3
- DECwindows V1.2-6

I am able to start a DECwindows session manager on the PC and log in without any issues.  When I try to use any of the editors (EDT and LSE in particular), I cannot get the Num-Lock key to behave like the PF1 key.  I really don't want to use xterm (which allows overriding the keys), as I like the Session Manager.  I think I need one of two things.  Either, a DECW$KEYMAP formatted file for the PC keyboard, or a way to configure xMing to translate the PC keypad keys into the equivalent LK keypad keys.  Any help would be appreciated.

~Jon.

**Comment by markpizz** [comment]
Hi Jon,

A solution for your problem here will certainly depend on proper resolution to #320.  In the end, there may be a way to map the 101/102 PC keyboard to the original LK401 keyboard, but as I recall, the numeric keypad has one less key on the standard PC keyboard layout than the original LK and VT100 keyboards.  You can probably get used to the missing key.  I know I managed to get by years ago when using WRQ Reflection as a terminal emulator.

**Comment by JonathanBelanger** [comment]
Hi Mark,

Well, that issue was not mine, but I did read it and think my problem was related.

As it turned out, the default keyboard definition had the entire keypad messed up.  This is probably and artifact more of the fact that I'm running a VAX simulator on a Windows PC using an open source xWindows server on the same Windows PC.  Once I defined the keypad completely and loaded it with xmodmap, all worked as desired.  This may also be similar fix for #320.

~Jon.

**Comment by markpizz** [comment]
Hi Jon,

#320 is a real bug in handling of modifier keys (right-left shift, right-left control, etc.).  They work sometimes and not others.  I haven't isolated the conditions, but this is at a lower level than X since these details are implemented in the QVSS device simulation.

- Mark
