### ISSUE TITLE
VAX - FATAL Bad Memory Block.

### ISSUE THREAD

**Issue by lukeb1961** [simh/simh#341]
# Windows 10 - 14915.rs_prerelease.160826-1902

# note the line 
# WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002)
# this is saying I have Win10Pcap installed (http://www.win10pcap.org/)

D:\SIMH>vax

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: b73afbb9
sim> sh eth
ETH devices:
 eth0   {3EA65083-9E51-4E08-AB64-C81E8309728A} (Microsoft)
 eth1   {FB3C1368-004F-46C5-9BEC-5AA024D3DDFC} (Realtek PCIe GBE Family Controller)
 eth2   {73CF73E6-DC90-47DF-9152-28991F7EE51C} (Realtek USB NIC)
 eth3   {DF78EFE4-14FB-4F80-96E3-B22DE2D79EE0} (Microsoft Corporation)
 eth4   {D15700F1-7E84-41F5-B36C-C4CD9CCF81AA} (Microsoft)
 eth5   nat:{optional-nat-parameters}          (Integrated NAT (SLiRP) support)
 eth6   udp:sourceport:remotehost:remoteport   (Integrated UDP bridge support)
WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
sim> attach xq eth3
Eth: opened OS device {DF78EFE4-14FB-4F80-96E3-B22DE2D79EE0} - Microsoft Corporation
FATAL Bad Memory Block.
FATAL Bad Memory Block.
sim>

uninstall Win10Pcap
uninstall Wireshark
reboot
install wireshark-win64-2.2.0.exe
(yes, install WinPcap 4.1.3)
reboot

Microsoft Windows [Version 10.0.14915]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>d:

D:\>cd simh

D:\SIMH>vax.exe

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: b73afbb9
sim> sh eth
ETH devices:
 eth0   \Device\NPF_{3EA65083-9E51-4E08-AB64-C81E8309728A} (Local Area Connection* 12)
 eth1   \Device\NPF_{FB3C1368-004F-46C5-9BEC-5AA024D3DDFC} (Ethernet)
 eth2   \Device\NPF_{6D5B3C7A-877D-4976-9936-6C16E4860320} (WiFi)
 eth3   \Device\NPF_{73CF73E6-DC90-47DF-9152-28991F7EE51C} (Ethernet 22)
 eth4   \Device\NPF_{DF78EFE4-14FB-4F80-96E3-B22DE2D79EE0} (vEthernet (External))
 eth5   \Device\NPF_{D15700F1-7E84-41F5-B36C-C4CD9CCF81AA} (Bluetooth Network Connection 2)
 eth6   \Device\NPF_{CC45739C-99B0-40C9-B478-5ACCE5F3FFCC} (Network Bridge)
 eth7   nat:{optional-nat-parameters}                      (Integrated NAT (SLiRP) support)
 eth8   udp:sourceport:remotehost:remoteport               (Integrated UDP bridge support)
WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
sim> attach xq eth4
Eth: opened OS device \Device\NPF_{DF78EFE4-14FB-4F80-96E3-B22DE2D79EE0} - vEthernet (External)
sim>

**Comment by markpizz** [comment]
If win10pcap happens to work, that is fine, but I have absolutely no plans to attempt to get it working or ever recommend its use.

This is for 3 reasons:

1. WinPcap (4.1.3) does work under Windows 10 and all earlier versions of Windows.  There may have been problems with Pre Release/Developer versions of various windows versions, but Microsoft fixed these problems before each version was formally released and WinPcap continues to work fine.

2. I’ve been working directly with Yang Luo.  Yang has been working for more than a year on updating/reworking WinPcap as part of the Nmap project (https://github.com/nmap/npcap).  The current sim_ether has specific support which will leverage npcap in preference to WinPcap if both are installed.  My interactions with Yang have:
   -      Cleaned up subtle network stack interactions with the install/uninstall
   -      Feature refinement and testing to get optimal range of functionality
   -      Full drop in replacement for WinPcap for all versions of Windows going all the way back to XP.
My discussions with Yang have encourage him to engage the libpcap team and bring the latest libpcap codebase into npcap and to bring the various windows needs that are specific to just the libpcap components back into the libpcap codebase.

3. Win10pcap is GPL, and we've got no plans to specifically taint the BSD style simh license by creating a dependence on Win10pcap.  The original WinPcap and npcap retain the BSD style license that is part of the underlying libpcap.


At this point, since WinPcap does work just fine under Windows 10, I’m sticking with what is known to work fine and not recommending anything else.  Some folks have been messing around in strange ways:  #332 probably with some variant of another packet capture package OR they’ve picked up installers from somewhere else or some malicious software which has been known to mess with packet capture attempts.

Yang is still adding functionality to Npcap and tends to come out with a new release version every few days or weeks, so there isn’t a rush to change any recommendations, but with it happens I’ll be recommending npcap.

**Comment by lukeb1961** [comment]
Excellent. All is now clear. 
NPCAP will be installed in preference. 
A hearty thank you!

**Comment by markpizz** [comment]
Since you're running a prerelease of windows, if you're having problems getting npcap working at all with that version of windows, you should probably create an issue at HTTPS://github.com/nmap/nmap/issues.

**Comment by hsluoyz** [comment]
@lukeb1961 , you can refer to the docs here: https://htmlpreview.github.io/?https://github.com/nmap/npcap/blob/master/docs/npcap-guide-wrapper.html#npcap-issues before creating an issue at: https://github.com/nmap/nmap/issues
