### ISSUE TITLE
i1401 tape usage on arm processors

### ISSUE THREAD

**Issue by compunut** [simh/simh#345]
I have seen this issue on two boards, one is a 32 bit and one is a 64 bit.  Both run an arm version of debian (not the same distribution).

I downloaded the most recent version of the sources from the github repository (zip format) and compiled all the simulators in the default set.  I have done lots of work with the pdp8 and the pdp11 and they seem just fine.  I tried to test all the others in a basic way by following the document off of the trailing edge site that shows how to use all the software packages.

When I got to the i1401 I had an issue.  I can make the hello world koan work fine.

However, when I try to boot the diagnostic tape I get a segfault.

Results are:
debian@pine64:~/emu/ibm/1401/ceo1401$ i1401

IBM 1401 simulator V4.0-0 Beta        git commit id: e2a8f0fc
sim> attach mt1 1401diag.mt
sim> attach lpt errorlist.txt
LPT: creating new file
sim> boot mt1
Segmentation fault
debian@pine64:~/emu/ibm/1401/ceo1401$

I get this same behavior on both the 32 bit and 64 bit systems.
However, on my AMD64 system it works perfectly fine.

Not sure how to determine the cause of the segfault from my end.  any input would help as to determine where things are going awry.

**Comment by markpizz** [comment]
Please provide a link to the tape image you're using.

Thanks.

**Comment by compunut** [comment]
http://simh.trailing-edge.com/kits/ceo1401.zip

**Comment by markpizz** [comment]
Thanks for the test data.

Meanwhile, Please put your full name on your github profile (no need to make your email public).

This allows folks to know who you actually are.

Thanks.

**Comment by markpizz** [comment]
Hmmm...  This is an interesting problem.  It is interesting why it only shows up on your ARM platform and not on AMD64 since it also shows up on my Windows (in debug mode anyway).

As it turns out the platform issue comes down to the extensive inlining of code which happens with the AMD64 compiler you're using (I see it not failing on AMD64 Linux with GCC 5.4).  There is a null pointer dereference which, when a debug function is inlined, doesn't actually get executed due to an if condition which isn't true unless you've enabled debugging.

The real problem here is that this device uses the functions in the sim_tape library, but doesn't use the sim_tape_attach() API which sets up data structures correctly to support debugging (and other things).  I have to dig through all the other simulators that use the sim_tape library and this is the only one which doesn't use sim_tape_attach.   Since Bob wrote this, he gets first crack at providing a fix.

**Comment by markpizz** [comment]
The latest code should fix the problem.  Please test and confirm you get what you expect and then close this issue if you're happy.

Thanks.

**Comment by compunut** [comment]
Thanks.  I can now boot the MT1 device with the diag tape attached.  I see the expected responses from the sim.  Good work guys.  I set the diags for one pass (I think), logging to a file, logging everything, no loop on error and no repeat, halt on error.  it's been running quite a while, but I am going to let it go to see if it finishes.  If so I will close this issue.

**Comment by compunut** [comment]
Ok, looks good to me, thanks guys!  You're awesome!
