### ISSUE TITLE
The display emulator doesn't build.

### ISSUE THREAD

**Issue by leobru** [simh/simh#367]
The file display/xy.h is missing

**Comment by larsbrinkhoff** [comment]
Get it from the source: http://www.ultimate.com/phil/xy/

**Comment by markpizz** [comment]
Please don't get it from elsewhere if you are intending to use it in a simulator.

About a year ago I merged the latest available stuff from Phil and Doug into the simh codebase and cleaned up the interfaces that were in use by the simulators that then used it (94a0629134c28ef410bd138c96d0e6a245a65692).  I picked the commonly used cases display.h was the interface which was in use (vs a slightly different xy.h)  xy.h was removed.  Meanwhile, there were ambiguities and duplicate code and variable performance issues on different platforms using the code which made direct calls to X11 or Windows APIs a new interface layer was implemented using SDL via sim_video was provided which made behavior consistent and burdened the platform problems on SDL.

If the contents of display.h are insufficient for what you may be attempting, please explain your needs.

**Comment by leobru** [comment]
The source and the Makefile still refer to xy.h, and no rule to construct it from display.h is provided.
(My ultimate goal is to implement the Terak display someday).

**Comment by markpizz** [comment]
I honestly didn't look at all the files in that directory as candidates to be removed.  

I worked through all of the simulators that used the display code in an earlier commit (b8049645147e18c42585cbb4ff62b38bc290435c) and each used the APIs defined in display.h and not xy.h.  

The relevant simulator examples are PDP1 (device DPY), PDP11 (device VT), and TX-0 (device DPY).  So if you're making a new simulator or adding a device to an existing one, the code and simh makefile setup should be examples you need.

**Comment by markpizz** [comment]
A simple live example of the using the display functionality is visible by starting the PDP11 simulator and entering the following commands:

    sim> set VT enable
    sim> boot VT

**Comment by markpizz** [comment]
Can we close this issue?

**Comment by leobru** [comment]
After removing or modifying the misleading makefile from the display
directory, I think.

**Comment by markpizz** [comment]
The makefile(s) are there for the basic test programs that are included in the event that they're ever necessary or otherwise useful.  They have nothing to do with building any simulator.   I've never used or compiled them.  My goal is to keep this stuff as close to the original work that Phil and Doug did, rather than discarding the pieces which we're not actually using.  This goal was explicitly stated by Phil when we interacted a while back.  If you read the README file, you'll see that they expect you to be happy about manually editing the provided makefile to get it to be useful on your environment.  Right now it is completely broken due to the references to xy.h and xy.c rather than display.h and display.c.  If you want to tweak the makefile to get each of the test programs working, I'll be glad to accept the change.

**Comment by leobru** [comment]
I see. I was under a wrong impression that it was supposed to be a standalone tool connecting to SIMH via telnet.
