### ISSUE TITLE
System Failure #16 seen in HP3000

### ISSUE THREAD

**Issue by keelak** [simh/simh#370]
The attached file records a session that results in "SYSTEM FAILURE #16"

simh version is 4.0 - Beta compiled with gcc 4.8.2

[system_failure_16.zip](https://github.com/simh/simh/files/689909/system_failure_16.zip)

**Comment by markpizz** [comment]
Please identify the precise simulator you're using by providing the output of:

    sim> SHOW VERSION

Thanks.

**Comment by keelak** [comment]
Okay, here are two such files. One built with gcc-4.8.2 and the other with gcc-6.1.0.

[system_failure_16_with_show_version.zip](https://github.com/simh/simh/files/691488/system_failure_16_with_show_version.zip)

**Comment by markpizz** [comment]
Couple of things:
1) Will you please put your full name in your Github profile (email absolutely not necessary) so we know who you are.
2) I've reformatted your prior message so that the details of your reported information directly visible in the text of the issue.  Packaging up stuff in a zip file is only necessary when it may contain unusual data (binary), or when it may be excessively large.  Simple text information is best presented directly in the issue so anyone who wants to read it doesn't have to got through a several step process to download, unpack, and then open the contents locally just to read the text.  It is also simpler for you to merely cut and paste rather than having to zip and upload.
3) It often makes things simple for the folks who are trying to help with your problem if, besides precisely identifying the simulator version you are reporting a problem with, you also provide the configuration file you used when observing the problem so that someone else can easily reproduce it.

Meanwhile as to the issue at hand, Dave is looking into it.

**Comment by markpizz** [comment]
The latest HP simulator code should solve this problem.  Please review the release notes in the HP3000 directory.  Once you've confirmed that it is fixed, please confirm that here and  close this issue.

**Comment by keelak** [comment]
Confirmed that this has been resolved.
