### ISSUE TITLE
PDP-10: single step in DDT crashes ITS

### ISSUE THREAD

**Issue by aap** [simh/simh#373]
I've experienced a problem with the pdp-10 emulator, explained here: https://github.com/PDP-10/its/issues/401
This is indeed a bug of simh.

**Comment by larsbrinkhoff** [comment]
I believe there is some disk image format that both SIMH and KLH10 can use.  Then we can run the same test case in both emulators, and try to pinpoint where they diverge.

**Comment by larsbrinkhoff** [comment]
Ah, KLH10 calls it "SIMH".  Most convenient!

**Comment by R-Voorhorst** [comment]
Hi,

 

in Klh10 you can specify the simh format instead of dbd9 so that the image can be exchanged

 

 

Best regards

**Comment by larsbrinkhoff** [comment]
I have now prepared a SIM disk image, and a test case:

1. Get the files from https://github.com/PDP-10/its/tree/lars/1proc/1proc
2. Bzunip rp0.dsk.bz2.
3. Start the emulator, one of:
   - SIMH: `pdp10 boot`
   - KLH10: `kn10-ks-its dskdmp.ini`, and type `go` at the KLH10# prompt
4. Type 'its' and press enter at the `DSKDMP` prompt.
5. Type Escape and `g`.
6. Type Control-Z after having seen "DB ITS 1648 IN OPERATION".
7. Type ":job x" and press Enter.
8. Type Escape `L sys; ts dump` and Enter; this loads a binary into DDT.
9. Type `start` Escape `b` to set a breakpoint.
10. Type Escape `g` to start the program.
11. Type Control-N to single-step.  This will fail in SIMH, but work in KLH10.

**Comment by larsbrinkhoff** [comment]
Output from a KLH10 session.  This is the expected behaviour.

    :job x
    !
    *$l sys; ts dump
    *start$b'DUMPER$:   $g
    $1B; START>>SKIPN MYNAME   ^N
    START+1>>.SUSET POPDJ+45   ^N
    START+2>>.SUSET POPDJ+46   ^N
    START+3>>.SUSET POPDJ+47   ^N
    START+4>>TLO A,LFDIR   ^N
    START+5>>.SUSET POPDJ+50   ^N
    START+6>>.OPEN N,POPDJ+51   ^N
    START+10>>MOVEI P,PDL   ^N
    START+11>>.CORE 27

**Comment by larsbrinkhoff** [comment]
Output from a SIMH session.

    :job x
    !
    *$l sys; ts dump
    *start$b'DUMPER$:   $g
    $1B; START>>SKIPN MYNAME   ^N
    ONE-PROCEED IN EXEC MODE 4000,,14601  
    BUGHALT.  FIND A WIZARD OR CONSIDER TAKING A CRASH DUMP.
    THE SYSTEM HAS CRASHED AND CANNOT BE REVIVED WITHOUT EXPERT ATTENTION.
    IF YOU CAN'T FIND HELP, RELOAD THE SYSTEM.
    YOU ARE NOW IN DDT.
    BUGPC/   SWSCP9+10,,ONEPRO+13   $Q-2/   SKIPA TT,105246

There is a monitor crash after typing the first Control-N.

**Comment by larsbrinkhoff** [comment]
I suppose the message `ONE-PROCEED IN EXEC MODE` is a good hint.

**Comment by archivisth** [comment]
KLH10 is a KL10 emulator, not a KS10 emulator. Is the ITS image you have truly CPU model independent? There are significant differences between the KL10 implementation of 1-proceed and the KS10. I wrote some of them down in the source code, but it's all lost in the mists of time. I see this comment, for example:

   A note on ITS 1-proceed.  The simulator follows the implementation
   on the KS10, keeping 1-proceed as a side flag (its_1pr) rather than
   as flags<8>.  This simplifies the flag saving instructions, which
   don't have to clear flags<8> before saving it.  Instead, the page
   fail and interrupt code must restore flags<8> from its_1pr.  Unlike
   the KS10, the simulator will not lose the 1-proceed trap if the
   1-proceeded instructions clears 1-proceed.

The actual spring of a 1-proceed trap occurs at the bottom of the single instruction decode loop:

if (its_2pr) {                                          /* 1-proc trap? */
    its_1pr = its_2pr = 0;                              /* clear trap */
    if (Q_ITS) {                                        /* better be ITS */
        WriteP (upta + UPT_1PO, FLPC);                  /* wr old flgs, PC */
        mb = ReadP (upta + UPT_1PN);                    /* rd new flgs, PC */
        JUMP (mb);                                      /* set PC */
        set_newflags (mb, TRUE);                        /* set new flags */
        }
    }                                                   /* end if 2-proc */

The set_newflag (..., TRUE) means that the processing is done like JRSTF - if in user mode, new flags are forced to user mode. If the new flags set 1_proceed, the flags bit is cleared and the side variable is set. In short, a 1_proceed trap cannot change mode from user to exec... or so it appears.

It should be possible to put a host breakpoint on the 1-proceed trap code and see what is going on. What is the mode when it is reached? What is the mode after it is sprung?

**Comment by larsbrinkhoff** [comment]
@archivisth
> KLH10 is a KL10 emulator, not a KS10 emulator. 

Sorry, I have to correct you there.  KLH10 can be built to emulate either KL10 or KS10.  For running ITS, only KS10 is supported.  The KL10 version don't emulate the ITS microcode.

Actually, KS10 was the first KLH10 target CPU.  See https://github.com/PDP-10/klh10/blob/master/doc/history.txt

As far as I know, no one has tried to run a KL10 ITS since MX was shut down in 1988.

**Comment by archivisth** [comment]
You are correct.

One problem appears to be
[code]
set_newflags (mb, TRUE);                        /* set new flags */
[/code]

Looking at the KS10 ucode, when JRSTF is executed, the flags field is "UPDATE USER" which means that the user flag can transition from exec to user, but not the reverse. When a one-proceed trap is taken, the flags field is "LEAVE USER" which means that the user flag can be cleared. So the TRUE should be FALSE, I'm fairly sure. A 1-proceed trap is like an MUUO, according to the microcode, and MUUO allows the flags to be updated arbitrarily.

Beyond that... the implementation of 1-proceed is extremely intrusive in the KS10 microcode, with hacks in all sorts of routines - fetch, apr traps, page faults, you name it. The same is true in KLH10. In contrast, the KS10 simulator uses a very confined approach by providing a special trap at the bottom of the instruction fetch loop, which takes precedence (in effect) over everything except faults and aborts; and wiping out a 1-proceed trap on a fault or abort, after storing the flags properly. I am not in the least confident that all the special cases that can occur - 1-proceeding across a page fault, interrupt, instruction trap, etc - are handled correctly.

Meanwhile, someone can try the one fix I suggested and see if it makes a difference.

**Comment by larsbrinkhoff** [comment]
At first glance, it appears changing TRUE to FALSE had no effect.

**Comment by larsbrinkhoff** [comment]
Here is the 1-proceed handling from the ITS monitor:

    SUBTTL KS-10 ONE-PROCEED

    IFN KS10P,[
    ONEPRO: SYSCTX                  ;SWITCH TO SYSTEM AC BLOCK
            SKIPGE U,USER
             BUG AWFUL,[ONE-PROCEED IN NULL JOB]
            MOVE T,1PROPC(U)        ;PC OF NEXT INSTRUCTION TO EXECUTE
            TLNE T,%PSUSR           ;NORMALLY USER MODE IS EXPECTED
             JRST ONEPR3
            HRRZ T,T                ;SEE IF IT'S FIRST INSTRUCTION OF EXEC ENTRY
            CAIE T,UUOH0
             CAIN T,MUUOTR
              SKIPA TT,[JRST ONEPR4]
               BUG AWFUL,[ONE-PROCEED IN EXEC MODE],OCT,1PROPC(U)
            MOVEM TT,UEXIT          ;CLOBBER EXIT TO RUN SYS CALL TO COMPLETION
            CAIE T,UUOH0            ;AND RESUME PROCESSING UUO
             JRST [ USRCTX
                    JRST MUUOTR ]
            USRCTX
            JRST UUOH0

    ONEPR3: MOVEM T,UUOH            ;PUT USER PC WHERE ONEFLS WANTS IT
    ONEPR4: SYSCTX                  ;COME HERE WHEN ONE-PROC'D UUO FINISHES
            MOVE U,USER             ;BE SURE U HAS RUNNING USER INDEX IN IT
            MOVEI T,%PI1PR
            IORM T,PIRQC(U)         ;GIVE USER INTERRUPT
            JRST ONEFLS
    ];KS10P

**Comment by larsbrinkhoff** [comment]
If the address 400014601 is in the monitor, the symbolic value is UUOH0+2.

The code at UUOH0 is a macro, but it should exand to this:

    UUOH0:
            CONSZ PI,77400
             BUG AWFUL,[UUO WITH PI IN PROGRESS]
            SYSCTX
            SKIPGE U,USER
             BUG AWFUL,[UUO IN NULL JOB]
            LDB T,[330300,,MUUOCX(U)]
            CAIE T,1
             BUG AWFUL,[UUO WHILE IN AC BLK ],DEC,T

**Comment by archivisth** [comment]
Found it... I think.

```
MUUO:
   its_2pr = 0;                                        /* clear trap */ <<< delete this line
    if (T20PAG) {                                       /* TOPS20 paging? */
```

Clearing its_2pr is not correct. The MUUO should take the 1-proceed trap at the end, like any other instruction. That's why the ITS code has the specific tests for the first instruction at the MUUO entry point(s).

When that line is deleted, the test case appears to work correctly on SimH. The other fix (for the TRUE/FALSE value in the call on set_newflags) is also necessary.

The vital clue was that the value of the trapped PC was off by 2 from the expected value. This indicated that the first instruction in the handler, a successful skip, was executed before the 1-proceed trap was sprung.

Please verify the fixes in the 4.0 code stream and then mark the issue as closed.

**Comment by larsbrinkhoff** [comment]
Confirmed.  SIMH now behaves identically with KLH10 in this regard, as far as I can see.  Thank you!

**Comment by larsbrinkhoff** [comment]
Adding some information here for completeness, in case someone comes looking in the future.

On a KS10 processor running ITS, single stepping (^N in DDT) over a CORBLK system call doesn't work.  This is *not* a bug in th emulator.  I have confirmed this happens on a real hardware KS10.

It does work on a KA10, so likely this is a problem in the KS10 specific parts of ITS.
