### ISSUE TITLE
`cpu_astop` unused?

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#387]
While investigating diffs between the PiDP-8/I version of SIMH and upstream, I saw that we removed this block near the top of the `while()` loop in `pdp8_cpu.c`:

    if (cpu_astop != 0) {
        cpu_astop = 0;
        reason = SCPE_STOP;
        break;
        }

I wondered what could cause `cpu_astop` to be nonzero, but was surprised to find that I could find no way to accomplish that, not only in our code, but in the upstream SIMH code as well! This seems to be true in all the other simulators that have a `cpu_astop` variable as well.

Is this an abandoned remnant of a removed feature, or is it an appendix of unclear function, whose [function](https://en.wikipedia.org/wiki/Appendix_(anatomy)#Immune_and_lymphatic_system) we will learn only after we start removing them en masse? :)

**Comment by archivisth** [comment]
cpu_astop is intended for use by a simulator writer to halt the simulator through a host-code debugging package, like MS Visual Studio. When debugging, I place host-code breakpoints in the simulator code. Sometimes, I want to bring the simulator to a clean stop as a result of what I see at a breakpoint. I then use the debugger to set cpu_astop to 1 and proceed from the host-code breakpoint. The simulator will return to SCP at the end of the current instruction.

cpu_astop is not universal, but it is present in most simulators that I have written.

**Comment by tangentsoft** [comment]
In that case, may I suggest that it be documented in the code, like so?

    // Allow clean exit to SCP: https://github.com/simh/simh/issues/387

I've put this block back into the PiDP-8/I version of the simulator, with that comment.

**Comment by markpizz** [comment]
You guys started and finished this discussion before I woke up.

FYI, Bob's use of sim_astop could equivalently be achieved by setting the simh global variable stop_cpu.
This variable is examined at the entry to sim_process_event() and will exit with SCPE_STOP which is equivalent to the code segment which contains cpu_astop.  The only difference is that the sim_process_event() code doesn't 'immediately' clear the observed value when SCPE_STOP is returned, since the need for this is addressed by an explicit 'stop_cpu = 0' just prior to calling sim_instr().

In theory, the sim_astop code could go away as long as someone who used this for debugging was remembered to use stop_cpu instead.  Bob wrote the code it is his decision to make any adjustment in how he wants to do this.

**Comment by archivisth** [comment]
I don't think it works.

stop_cpu is set by the ^C signal/interrupt handler, as a sort-of pseudo 
^E. When sim_process_event is next called, stop_cpu will be recognized 
and the simulator brought to a halt. That could be many instructions later.

To use stop_cpu, the programmer would have to a) set stop_cpu and b) 
clear sim_interval.

Many simulators have to suppress ^C traps themselves, because it is a 
legitimate character. I'm not sure under what circumstances the current 
code gets invoked.

/Bob

**Comment by markpizz** [comment]
Oops.  I forgot about the sim_interval needing to be cleared.  I usually put a breakpoint on the spot where sim_interval is decremented and set it to zero when I want to short circuit the wait for an event.

The other (real) purpose of stop_cpu is, as you point out, actually set by the WRU character being types on *nix platforms.  This happens by some unix specific tty code in sim_console that declares whatever the WRU character happens to be set to as the interrupt character (the interrupt character is specifically programmable on these host environments).  The interrupt signal handler then merely sets stop_cpu.

When the BESM6 simulator first came along it didn’t have any code in its console port code to handle a non-character return from sim_poll_kbd() and ^E was working just fine to get back to the sim> prompt.  While getting that simulator working on Windows, ^E didn’t work, but the simulator otherwise seemed to work.  I looked at why and saw that the code structure would be quite messy to change to support exiting from where that keyboard polling was done.  To solve this problem, since other simulator developers might also work/test only on non Windows platforms, sim_poll_kbd() was changed to explicitly set stop_cpu when the WRU (^E) character was received and then to merely return 0 (i.e. no character).
