### ISSUE TITLE
PDP-11 RHC RS04/RS03 device address range has a hole and is two words too long

### ISSUE THREAD

**Issue by PDP-1170** [simh/simh#396]
- #### Context
When configuring an 11/70 with RP,TU,RS - the RS device register range (on RHC) is two words too long and the last two registers appear to be shifted by two words leaving a hole in the address space.
It looks like RHBAE and RSCS3 (the last two registers) are shifted by two words.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
PDP-11 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: Microsoft Visual C++ 15.00.30729.01
                Simulator Compiled as C arch: x86 (Release Build) on Jan  5 2017 at 13:32:39
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.5
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Microsoft Windows [Version 10.0.14393]
                Architecture: x86 on AMD64, Processors: 4
                Processor Id: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel, Level: 6, Revision: 2a07
        git commit id: 0db0236b

- #### how you built the simulator or that you're using prebuilt binaries
Pre-built Windows simulator.

- #### the simulator configuration file (or commands) which were used when the problem occurred.
See below.

- #### the actual behavior
PDP-11 simulator V4.0-0 Beta git commit id: 0db0236
sim> set XQ dis
sim> set CPU 11/70
sim> set TM dis
sim> set TU ena
sim> set RS ena
sim> sho RHC
**RHC address=17772040-17772077**, vector=204
sim> ex 17772040-17772077
17772040: 004200
...
17772066: 000002
Address space exceeded
sim> ex 17772072
Address space exceeded
sim> ex 17772074-17772077
17772074: 000000
17772076: 000000
sim>

- #### the expected behavior
The Massbus registers for a real RS04/RS03 are at **17772040-17772073** not 17772040-17772077.
It's likely that RHC was cloned from either RHA or RHB and the device registers are in a different place.

**Comment by markpizz** [comment]
Mike,

When you get a chance, please confirm that this problem no longer occurs and, if you're happy, close the issue.

Thanks.

- Mark

**Comment by PDP-1170** [comment]
Thanks, Marc.   The reported problem no longer occurs.

**Comment by markpizz** [comment]
@PDP-1170 commented on the commit which fixed this:

After some further testing, it seems that there may be some undesired side-effects of this change.
The following output is directly after starting pdp11 without an .ini file:

sim> sh rha
RHA     address=17776700-17776753, vector=254
sim> set rp dis
sim> set rp ena
sim> sh rha
RHA     address=17776700, vector=254
sim>
Note that after re-enabling RP, the RHA address range has been lost. The line of code at 852 in pdp11_rh.c dibp->ulnt = dibp->lnt = 0; breaks the ability to disable and re-enable Massbus devices. Commenting out this line seems to fix the issue. Moving Massbus devices to different controllers still works with this line commented out.

It is also possible that you wanted to say '=ulnt' instead of '=lnt' in line 926. It seems to work either way, so it may be moot. Before the change, ulnt was set the same as lnt directly in the mba dibs - but this may have been unnecessary.
