### ISSUE TITLE
PDP8: Resume from ADVENT is...difficult

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#399]
The following transcript of a SIMH `pdp8` session shows OS/8 failing to be re-entered at its normal 7600 address while running Adventure from [a common OS/8 disk image](https://tangentsoft.com/pidp8i/doc/trunk/media/os8/os8.rk05):

<pre>pdp8 boot/0.script

PDP-8 simulator V4.0-0 Beta        git commit id: d980bcd7
Loading OS/8 from the RK05 cartridge disk...

FIELD SERVICE PDP-8 DIAGNOSTIC SYSTEM    . . .  VERSION 8.03

OS/8  V3D		DECX8   REV. D

RESTART ADDRESS =07600

TYPE <CTRL> C TO ABORT THIS PRINTOUT

TYPE:
	.R PROGNAME		-	TO RUN A SYSTEM PROGRAM
	.R PROGNAME.DG		-	TO RUN A DIAGNOSTIC PROGRAM
	.HELP FILENAME		-	TO TYPE A HELP FILE ON THE TERMINAL
	.HELP FILENAME - L	-	TO LIST A HELP FILE ON THE LINE PRINTER
	.SU BOOK		-	TO PRINT A COPY OF THE DIAG. HELP FILES

"FILENAME" / "PROGNAME"  = THE FILE OR PROGRAM TO LIST OR RUN

.RUN RKB0:ADVENT

WELCOME TO ADVENTURE!!  WOULD YOU LIKE INSTRUCTIONS? 

Simulation stopped, PC: 12055 (NOP)
sim> d pc 7600
sim> d ma 7600
sim> d ac 0
sim> d l 0
sim> d ion 0
sim> c

Simulation stopped, PC: 00511 (PSKE)
sim> c

Simulation stopped, PC: 00453 (JMP 476)
sim> d pc 7600
sim> c

.
</pre>

Here's the boot script for loading the above-linked RK05 disk image:

<pre>reset
echo Loading OS/8 from the RK05 cartridge disk...
set cpu 32k
set cpu noidle
set nothrottle
att rk0 /path/to/os8.rk05
boot rk0</pre>

The `DEPOSIT` commands shown approximate what a PDP-8 does when you load 7600 into the PC via the front panel's Load Address switch then press the PDP-8/I's START switch. On later PDP-8 models which lack a START switch (e.g. PDP-8/e) it should be the same as CLEAR + CONT.

Properly, START (or CLEAR + CONT) should also set DF to 0, but that seems to tickle a bug which I've filed separately, #398. However, this seems to be irrelevant to the present problem, since I'm working with [a variant of SIMH](https://tangentsoft.com/pidp8i/wiki?name=Home) which *does* have a way to set DF to 0, and it isn't helping.

The expected behavior is to get the OS/8 prompt (just a dot) back after the first SIMH `c` command. For some reason, it takes *two* loads of the PC to make this happen.

I think it's clear that some internal PDP-8 state is being affected between the two `c` commands which allows the second one to succeed. If we can isolate what's needed here, then we can consider whether it's something SIMH's PDP-8 simulator needs to be doing or if it's something I need to make part of the START implementation in the PiDP-8/I software.

(Our current START implementation follows DEC's docs, but that doesn't mean those docs are complete!)

**Comment by archivisth** [comment]
Doing

`RUN 7600`

_does_ work, so the differences between your deposit commands and the actions of the cpu_reset routine are the key. Among the differences I see, cpu_reset:

- does not touch L'AC (this doesn't matter - OS/8 clears L'AC immediately).
- clears ION and sets the 'no CIF pending' flag. (no CIF won't matter because OS/8 doesn't use interrupts)
- sets IB and DF to IF. 
- clears UB, UF, GTF, emode.

In this case, IB is the problem. When interrupted, the simulator is in field 1, meaning both IF and IB are 1. When you CONTINUE at 7600, the JMS there jumps off to field 1 instead of field 0, and everything falls apart.

RESET CPU is intended to be the analog of the CPU's CLEAR signal, and RUN is intended to be the analog of the CPU's START switch. Please use them. If you want to do discrete commands, then you will need to go through the schematics of the various PDP-8 models to understand where the CLEAR signal did, and did not go.

This issue can be closed.

**Comment by tangentsoft** [comment]
> cpu_reset does not touch L'AC

I've got two different editions of DEC's Small Computer Handbook that says it should, if that's equivalent to CLEAR + CONT. In the 1967-1968 edition for the PDP-8/I it says START "clears AC, L, MB and IR", and the 1973 edition for the 8/e, 8/m, and 8/f says CLEAR "loads a binary 0 into bits 0-11 of the AC, the link, all I/O device flag registers and all interrupt system flip-flops. This is equivalent to executing a CAF instruction." Your CAF implementation does clear L'AC.

> In this case, IB is the problem.

There seems to be more to it than that, since setting IB=0 didn't help here, even after a call to cpu_reset() on START.

Anyway, your "RUN 7600" argument is enough to tell me that the solution must be in PiDP/8-I space, not in SIMH space. Thank you.
