### ISSUE TITLE
I1620: SET REMOTE TELNET=nnn connects but commands don't work

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#442]
- #### Context

The following,

```
sim>set remote telnet=23
sim>
```
will make a connection to PuTTY doing telnet to localhost on 23, but typing in PuTTY does nothing except echo.  There's no banner, no command prompt.

Adding the following in the local window,
```
sim>set remote master
```
prints the banner followed by an error message, the connection breaks, and SIMH exits.  There was also a message in the local window but it disappeared before I could read it.
```
jaksldf
ajklsdfjk;asdfjkl;asdf

Connected to the IBM 1620 simulator REM-CON device

IBM 1620 Remote Console
Enter single commands or to enter multiple command mode enter the ^E character
Console port must be Telnet or Serial with Master Remote Console
Goodbye
```

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

```
IBM 1620 simulator V4.0-0 Beta        git commit id: b5a5aec5
sim> show ver
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Apr 24 2017 at 13:48:57
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 36
        Processor Id: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel, Level: 6, Revision: 3f02
        git commit id: b5a5aec5
sim>
```
- #### how you built the simulator or that you're using prebuilt binaries

20170424 prebuilt binary, running on Windows 7 Enterprise 64

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
This doesn't work due to my initial comments in #436 about sim_poll_kbd() being called directly in the code path of instruction execution.  It needs to be called in the context of a unit service routine executed from sim_process_event().  Once the tty input side is implemented that way, it will play well with other simh activities which include the remote console functionality.

**Comment by DaveWise2** [comment]
Turns out I was unwittingly misusing the feature.  It behaves the same on PDP11 and VAX.  (So maybe the I1620 tag should be removed from the title.)  The error message was telling me but I didn't listen.

SET REMOTE requires the Console to also be non-local.

It also won't work unless the Remote is master.

If I do this,
```
sim>set console telnet=23
sim>set remote telnet=24 master
```
it works.

Now, why is that so?  The documentation doesn't say it's required.  What is a non-master remote connection useful for?  When I set one up, the connection is established but the remote window doesn't do anything except echo input.  When I set up two remote connections, one master and one not, SIMH aborts.

**Comment by markpizz** [comment]
The initial call for remote console functionality was from folks who wanted to have a simple way to reach in and change media in a disk or tape device while the simulator was running, when they possibly weren't sitting at the session which may have initiated the simulator's execution (possibly due the simulator running in the background).  So the common usage is actually the non master mode functionality.

Master mode functionality was added to provide a means of completely controlling a well behaving simulator.  As mentioned in #436, the I1620 currently isn't well behaving.

Master mode wasn't really intended for direct user use.  It is the facility that the front panel API uses under the covers to implement the functionality that the API exposes.  The front panel API runs the simulator in a background process, and as such the console must be TELNET (or possibly serial).

**Comment by DaveWise2** [comment]
Non-master remote mode failed for me on PDP11 and VAX the same way it fails on I1620.  Can you lead me by the hand in setting up a non-master connection?

**Comment by markpizz** [comment]
Non master mode does something when the simulator is running (i.e. executing instructions).  

If you connect to a remote session before the simulator starts executing, the connection message won't appear until execution starts, and once execution starts (via BOOT, GO, RUN, etc.) you can perform one of two modes of command interactions: 1) single commands (entered directly) or 2) a series of commands preceded by ^E and then commands followed by a CONTINUE (or an automatic CONTINUE will happen after a timeout).

**Comment by markpizz** [comment]
Until #436 is fixed, Non-Master mode remote console won't be particularly useful on this simulator either.

**Comment by DaveWise2** [comment]
Okay.  So Non-Master mode only works if there's a unit service routine that calls sim_poll_kbd()?  Is that why I couldn't get SIMH's attention with ^E... because the target was stopped?  What's the easiest target to set up a demonstration of Non-Master mode?

**Comment by markpizz** [comment]
Start the PDP11 simulator and enter these commands:
```
sim> set vt enable
sim> set remote telnet=1234
sim> boot vt
```
Open a telnet session to locahost:1234

OR if you want to have a little less fun, you could start the VAX simulator and enter these commands:
```
sim> set remote telnet=1234
sim> boot
```
Open a telnet session to localhost:1234

**Comment by DaveWise2** [comment]
Thanks.  While you were typing I set up a minimum RSTS/E PDP-11 and was able to do a remote HELP command to SIMH.  QED.  I also tried your vt example above.  Heh!

However, in both cases, when I hit ^E, SIMH crashed.  That should be a separate bug report but I'm not competent for technical followup on PDP-11 troubles.  Do you want the report anyway?

Which target has the best source code to study to help me understand how to enable Non-Master mode in I1620?  Not that I'm really committing to a project, I would just like to understand.

**Comment by markpizz** [comment]
> Which target has the best source code to study to help me understand how to enable Non-Master mode in I1620? Not that I'm really committing to a project, I would just like to understand.

There really isn't any specific target that parallels this.  Most of the issues are around the details of the 1620's I/O model.

If I was messing with this, I'd leverage the existing tty_svc routine, and have the data that it gathers key off of the 'input state' of the tty.  There already is a tty_unlock() routine.  That does nothing but emit a prompt.  It should be changed to 1) record a 'reading' state and only if the reading state wasn't previously set emit the prompt.  The existing tty_svc() routine could uses the 'reading' state to save any data actually returned by sim_poll_kbd() and set a flag indicating that a character is available, if the 'reading' state isn't true, then any data read is discarded.  tti_read() should be changed to NOT call sim_poll_kbd(), but to check the character ready flag and if set, clear the flag and return the previously read character, if no character is available, it should call sim_idle() and and set PC to saved_PC and then return indicating that no character is available.  Code calling tti_read() should clear the 'reading' state when it has completed an active read request.
The code implementing OP_RN and OP_RA should be changed to rethink the loops "for (i = 0; i < MEMSIZE; i = i + 2) {           /* (stop runaway) */".  I say this since in general, there will be at most one character available each time through.

**Comment by markpizz** [comment]
> However, in both cases, when I hit ^E, SIMH crashed. That should be a separate bug report but I'm not competent for technical followup on PDP-11 troubles. Do you want the report anyway?

You've reported it here and it is now fixed.  That problem was introduced while cleaning up the remote console code to support the next version of the front panel API.  Thanks for finding it.

**Comment by DaveWise2** [comment]
Thanks!
