### ISSUE TITLE
I1620: Throttling ineffective when console is redirected to telnet

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#444]
This might be a widespread or global issue, but I only have the wherewithal to assess it on I1620.

If the console is also the local SIMH command window (the startup default), then SET THROTTLE visibly slows down program execution as expected.  After I SET CONSOLE TELNET=23, the program runs at full speed regardless of throttle.  SHOW THROTTLE continues to show whatever speed I last set.  After I return to the local console window using SET CONSOLE NOTELNET, the program again runs at throttled speed.

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

IBM 1620 simulator V4.0-0 Beta        git commit id: eea18400
sim> show ver
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on May  3 2017 at 12:13:10
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 36
        Processor Id: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel, Level: 6, Revision: 3f02
        git commit id: eea18400
sim>

- #### how you built the simulator or that you're using prebuilt binaries

Prebuilt binary and local build, same behavior.

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

~~~

IBM 1620 simulator V4.0-0 Beta        git commit id: eea18400
sim> set throttle 5k
sim> attach ptr c:\temp\fo005.pt
sim> boot ptr

1620 PRE-COMPILER  11/15/61
ENTER SOURCE PROGRAM
THEN PUSH START
HALT instruction, PC: 1460 (B 14860,00000)
sim> d sw1 1
sim> d sw4 1
sim> d arstop 0
sim> attach ptr c:\temp\non65.pt
sim> go

      DIMENSION FOM(130),IPER(130)
     C  RECORD FIGURE OF MERIT FOR EACH CANDIDATE
      DO 10 I = 65,130
      IPER(I) = I
      FREQ = I
      FREQ = 1.E6 / FREQ
      FINT = FREQ / 95. + 0.5
      ICYC1 = FINT
      FINT = FREQ / 162. + 0.5
      ICYC2 = FINT
      F1 = ICYC1
      F1 = FREQ / F1
      F2 = ICYC2
      F2 = FREQ / F2
      R1 = ((F1 / 95.0) - 1.0) * 100.0
      R2 = ((F2 / 162.0) - 1.0) * 100.0
      FOM(I) = R1 - R2
      IF (R1 - R2) 5,10,10
    5 FOM(I) = R2 - R1
   10 CONTINUE
     C  SORT BY FIGURE OF MERIT, BEST FIRST
     C  1 = NOT SORTED, 2 = SORTED
   20 ISRTD = 2
      DO 25 I = 65,129
      J = I + 1
      IF (FOM(J) - FOM(I)) 22,25,25
   22 T = FOM(I)
      FOM(I) = FOM(J)
      FOM(J) = T
      IT = IPER(I)
      IPER(I) = IPER(J)
      IPER(J) = IT
      ISRTD = 1
   25 CONTINUE
      GOTO (20,30),ISRTD
     C  ELIMINATE INFERIOR ENTRIES - SHORTER PERIOD WITH WORSE FOM
   30 DO 40 I = 65,129
      DO 40 J = I,130
      IF (IPER(J) - IPER(I)) 33,40,40
   33 IPER(J) = 0
   40 CONTINUE
     C  PRINT WHATS LEFT
      TYPE 90
      DO 50 I = 65,130
      IF (IPER(I)) 50,50,45
   45 FREQ = IPER(I)
      FREQ = 1.E6 / FREQ
      FINT = FREQ / 95. + 0.5
      ICYC1 = FINT
      FINT = FREQ / 162. + 0.5
      ICYC2 = FINT
      F1 = ICYC1
      F1 = FREQ / F1
      F2 = ICYC2
      F2 = FREQ / F2
      R1 = ((F1 / 95.0) - 1.0) * 100.0
      R2 = ((F2 / 162.0) - 1.0) * 100.0
      T = R1-R2
      TYPE 100, IPER(I),ICYC1,ICYC2,F1,F2,R1,R2,T
   50 CONTINUE
      STOP
   90 FORMAT (3X1HT,2X2HC1,2X2HC2,6X2HF1,6X2HF2,4X2HR1,4X2HR2,4X1HD)
  100 FORMAT (I4,I4,I4,F8.2,F8.2,F6.2,F6.2,F6.2)
      END

OBJECT PROGRAM DATA TABLE
`03080 STORAGE POSITIONS

PROCESSING COMPLETE

HALT instruction, PC: 9572 (B 01208,00000)
sim>
~~~
The program ran slowly, as expected.
Add this and do it again, with PuTTY doing telnet to localhost:23 ...
```
set console telnet=23
```
The program ran quickly; it should have run at the same speed as before.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Dave,

Please provide the paper tape image you used so I can reproduce this.

Thanks.

Mark

**Comment by DaveWise2** [comment]
Here you go.  The attached zip file (given .txt extension because github rejects .zip in spite of claims) contains the 1620 Fortran Pre-Compiler, part number FO-005, and a small Fortran source tape, NON65.PT .  If you throttle down to 5KIPS (this is actually optimistic!) with local console, it will take an obvious amount of time to lint the source tape.  But if you redirect the console to telnet, it will finish in an eyeblink.  At least it does for me.

If you like, point me to files and instructions to test this on some other target.  I don't have even a nodding acquaintance except with the 1620.

[temp.zip.txt](https://github.com/simh/simh/files/987246/temp.zip.txt)

**Comment by markpizz** [comment]
zip files work just fine for me and essentially most folks.  What browser are you using, OR maybe it is an issue with your work network proxy...

-------------

Back to the throttling question...

In order to throttle at any particular instruction rate, the actual simulated execution rate has to be measured against wall clock time.  When throttling is enabled, this process takes a series of measurements while the simulator is executing to determine how often and how much to sleep to achieve the specified execution rate.

The SHOW THROTTLE command provides useful information about how the simh framework is achieving the desired throttling.

On my system, after running your above test with the console in the same session/window as the simulator I see:
```
sim> sh throt
Throttle:                      5 kilocycles
Throttling by sleeping for:    10 ms every 50 cycles
sim>
```
This looks reasonable.

With the console presented in a telnet session, like you've pointed out, I see:
```
sim> sh throt
Throttle:                      5 kilocycles
Throttling by sleeping for:    1 ms every 160000 cycles
Throttle State:                Timing - wait: 160000
sim>
```
The "Throttle State" of "Timing - wait: 160000" indicates that the throttling calibration process hasn't completed yet.

So, the question is:  Why does calibration seem to work OK when the console isn't telnet and not when it is.

After looking under the covers as to why we see such a disparity, it comes down to the fact that single character I/O to the window the simulator is running in takes MUCH MORE time than the time it takes to merely buffer a single character which will ultimately be delivered across the network as part of a packet with many other characters.  This slower output rate allows an effective sleep vs execution ratio to be determined rather quickly.  The faster execution rate when merely buffering data to be transmitted over the network, happens so quickly that the clock resolution can't compute a useful execution rate until the sample size gets large enough.  The calibration algorithm picks an instruction count and if it expires sooner than the clock resolution can distinguish, the measured instruction count is doubled and a measurement is taken again.  This repeats until a useful execution ratio vs time can be measured so that the appropriate sleep vs instruction values can be determined.  The problem in this case, is that the simulation completes its run before the calibration has completed and thus you see the results you are seeing.  If the simulation ran continuously, or at least a good amount of time longer, then the calibration would succeed and the desired throttling would actually be achieved.

Since, on my system I've observed that when running at 5K instructions per second, the appropriate calibration numbers end up being to sleep for 10ms ever 50 instructions, you can manually set the throttling parameters and avoid the calibration step.  So, if, rather than "SET THROTTLE 5K", I "SET THROTTLE 50/10", I see rate limited behavior right from the get go.  Output is a little bursty, but that is due to output data being collected by the network layer before occasionally being flushed.  The total execution time is very similar to when telnet isn't part of the picture.

Does this make sense?

**Comment by DaveWise2** [comment]
Could be the work network, could be Chrome (Version 58.0.3029.110 (64-bit), running on Windows 7).  If an opportunity to attach from home appears, we'll see.

Your assessment makes complete sense to me.  Most targets BOOT once and then spin forever in their OS, giving SIMH plenty of time to calibrate.  I1620 is unusual in that in non-MONITOR scenarios it spends most of its time halted, running only to execute a program and then halting again.  (MONITOR will run program after program as long as you keep piling them in the hopper.  But it still halts after the last job.)

How about using T/I until its calibrated?

At least, the deficiency should be documented for the next user.  (T/I is in the main doc, but I think there should be a hint in i1620 recommending it instead of K.)

How realistic is SIMH throttling supposed to be?  5KIPS is the speed of a 1620 Model I when executing branches etc. that take ten machine cycles.  But a typical program will be slower, depending on how much data it moves around and how much arithmetic it does.  (And I/O, but that is so slow I can't imagine anyone wanting it.  Nevertheless I coded it in my peripheral emulator.)

**Comment by markpizz** [comment]
> Could be the work network, could be Chrome (Version 58.0.3029.110 (64-bit), running on Windows 7). If an opportunity to attach from home appears, we'll see.

It is not Chrome.  Chrome is the most popular browser and as such, absolutely gets tested.  That is what I've used to attach zip files.

> Your assessment makes complete sense to me. Most targets BOOT once and then spin forever in their OS, giving SIMH plenty of time to calibrate. I1620 is unusual in that in non-MONITOR scenarios it spends most of its time halted, running only to execute a program and then halting again. (MONITOR will run program after program as long as you keep piling them in the hopper. But it still halts after the last job.)
>
> How about using T/I until its calibrated?

And then what?

The SET THROTTLE command syntax selects a particular throttle mode amongst several.  If you're using the specific "no calibration mode (T/I)", then that is what you get.

> At least, the deficiency should be documented for the next user. (T/I is in the main doc, but I think there should be a hint in i1620 recommending it instead of K.)
>
> I just noticed that while SHOW is "sleep x ms every y cycles", SET requires y/x. It feels backwards.

I'll make the SHOW output say:
```
sim> set throt 100/10
sim> sh throt
Throttle:                      100/10
Throttling by sleeping for:    10 ms every 100 cycles
sim>
```

> How realistic is SIMH throttling supposed to be? 5KIPS is the speed of a 1620 Model I when executing branches etc. that take ten machine cycles. But a typical program will be slower, depending on how much data it moves around and how much arithmetic it does. (And I/O, but that is so slow I can't imagine anyone wanting it. Nevertheless I coded it in my peripheral emulator.)

When you're not running in I/T mode, the throttling is a running average of the possible mix of instructions and, as we've seen, short running programs can't really produce precise measurements of execution rates.  Meanwhile, as you point out the 1620 had vastly varying instruction execution times.  This could be modeled to reflect the original behavior by making exact adjustments to sim_interval for each instruction executed and then any particular program's instruction mix could model excution rate more precisely to how the hardware worked.  This is usually not encouraged for most simulators since most systems being simulated have some sort of system clock which ticks at rates somewhat consistent with wall clock times.  In order for the clock ticks for these simulators to be slightly precise, the adjustments to sim_interval need to be in line with the time the simulator actually takes to simulate an instruction.  For most simulators (and thus most instructions) the right answer is that most instructions take pretty much the same amount of time to simulate, so uniform (single value) adjustments to sim_interval is the right answer (i.e. simple decrement).

Apart for throttling, if you pick up the latest code, and run using a TELNET console, with the following command in effect:
```
sim> SET CONSOLE SPEED=134
```
Let me know what you think

**Comment by DaveWise2** [comment]
`And then what?`

I was suggesting SIMH use T/I during calibration, regardless of the actual mode selected by default or previous SET THROTTLE command.  For example, SET THROTTLE 5k would use 50/10 as an approximation until calibrated, then use whatever it came up with for 5k.

I like your SHOW THROTTLE idea.

`When you're not running in I/T mode`

I agree, it's a pity but that way lies the madness of perfectionism - it's not worth the effort.

`SET CONSOLE SPEED=134`

I'll try that out.  134 whats?  kbps equivalent?

**Comment by markpizz** [comment]
> I was suggesting SIMH use T/I during calibration, regardless of the actual mode selected by default or previous SET THROTTLE command. For example, SET THROTTLE 5k would use 50/10 as an approximation until calibrated, then use whatever it came up with for 5k.

Well, the 'right' initial guess is completely host platform dependent.  Not knowing that, the algorithm does start from some guess and the adjust as necessary from there.  

> SET CONSOLE SPEED=134
> 
> I'll try that out. 134 whats? kbps equivalent?

134.5bps is what I thought the IBM Selectric printed at.  Use whatever speed you think the real hardware runs at.  (it has to be one of (50, 75, 110, 134, 150, 300, 600, 1200, 1800, 2400, 4800, 7200) bps.

**Comment by DaveWise2** [comment]
>the 'right' initial guess is completely host platform dependent

So it doesn't start out at max per se, just a guess that happens to be max in I1620's case?  Does it come close to right for popular targets?  Can you improve the 1620 guess without breaking someone else?  How about basing the guess on the local-window character speed?  (I don't know how hard that is.)

>SET CONSOLE SPEED

Thanks.  I don't remember how fast the Selectric goes.  For my 10cps Model B typewriter, 75 is close.  But I know how painful it is, I'll probably only do it once. :/  Can I SET CONSOLE NOSPEED to go back to max?

**Comment by markpizz** [comment]
> > the 'right' initial guess is completely host platform dependent
> So it doesn't start out at max per se, just a guess that happens to be max in I1620's case? Does it come close to right for popular targets? Can you improve the 1620 guess without breaking someone else? How about basing the guess on the local-window character speed? (I don't know how hard that is.)

The initial guessing process is complicated by the fact that different hosts have varying sized minimal sleep times.  Calibration usually will complete in much less than 1 second, and, in case the actual instruction mix changes, calibration is redone once every 10 seconds.  At the end of the day, it works just fine given enough cycles to calibrate with.  

> > SET CONSOLE SPEED
> Thanks. I don't remember how fast the Selectric goes. 
Selectrics were sold as general purpose terminals across the market.  Apparently some folks tried to run them at 110bps, but that led to some mechanical failure in the device due to timing.  The industry added 134.5bps as a standard rate to support Selectrics. 
> For my 10cps Model B typewriter, 75 is close. But > I know how painful it is, I'll probably only do it once. :/ Can I SET CONSOLE NOSPEED to go back to max?

Actually SET CONSOLE SPEED=0 sets it back to unlimited (which is the initial default).

**Comment by DaveWise2** [comment]
It works very well, Mark.  Takes me right back to the acoustic coupler days.  However, it sharpens the need for interruptible IO, for that fool^H^H^H^Hexperimenter who lights off a 300-baud core dump.  I'm working on it.

**Comment by markpizz** [comment]
> Update: It works for go but not for step. step through a long TTY output spews at full speed.

Please provide explicit instructions (and data files) so I can reproduce this and then I can either fix or explain what is happening.

As for the detail you did provide, please provide the bad65.pt file in a zip attached here.

**Comment by DaveWise2** [comment]
Here's bad65.pt for the lint problem above.  It's a legal 1620 fortran program except one comment near the end has one space after 'C' instead of two.
[BAD65.zip](https://github.com/simh/simh/files/1038883/BAD65.zip)

And here is how I observe the non-throttle when stepping through an output instruction.
```
sim> set console telnet=23
<hook up PuTTY>
sim> set console speed=4800
sim> deposit 0 dnty 15000
sim> deposit 12 h
sim> go 0
<i1620 dumps 5000 chars of core at 4800bps, taking about 8 seconds>
sim> deposit 0 dnty 0
sim> deposit pc 0
sim> step
<i1620 dumps 20000 chars of core at maximum speed, done in an eyeblink>
```

I also noticed that 7200 didn't throttle even in the scenario where 4800 did.
```
sim> set console telnet=23
<hook up PuTTY>
sim> set console speed=7200
sim> deposit 0 dnty 0
sim> deposit 12 h
sim> go 0
<i1620 dumps 20000 chars of core at maximum speed, done in an eyeblink>
```

**Comment by markpizz** [comment]
> I also noticed that 7200 didn't throttle even in the scenario where 4800 did.

Well, back in the day, if you could have connected a terminal to a 1620 and have it output at 7200bps, it would have seemed like an eyeblink.  :-)

Seriously though, as discussed previously, there are programmed delays 
happening here (like in the trottling discussion) where the explicit delay relates 
to the observed simulation instruction execution rate.  Since not many 
instructions are getting executed, useful calibration doesn't get done.

This is more problematic now that Bob's moved TTY output to be processed 
in the event dispatch context.

**Comment by DaveWise2** [comment]
I remember the first time I saw 9600.  It seemed crazy fast.

7200 is about the speed of 1620 paper tape output via my peripheral emulator hardware.  Beats the real 15cps punch with a stick.  I included a "realistic speed" feature, but it's too painful to use more than once.  I only turn it on if I need to confirm it still works.

**Comment by DaveWise2** [comment]
Working okay as of simh-4.0-Beta--2017-06-06-c389573c.zip .

**Comment by DaveWise2** [comment]
Oops, I was testing it on local console, not telnet.  Telnet console still busted as described here.
"Update: Oh oh. When SPEED is not maximum, TTY input hangs. At the > prompt below, I started typing, and it hung after the first space."

**Comment by DaveWise2** [comment]
Stay tuned, seems to work on 12-June-2017 local build with Issue #474 changes, although still has problems as described in that issue.

**Comment by markpizz** [comment]
How does this problem look now?

**Comment by DaveWise2** [comment]
?Haven't had time to test it yet, unfortunately.

________________________________

**Comment by DaveWise2** [comment]
Sorry to bring bad news, but it looks like CPS got completely broken.  ;(

At least the original complaint is fixed, throttle works identically fine on local or telnet.


With console local or on telnet...


?Tti and Tto scale with throttle but ignore ICPS and CPS.

Ptr and ptp scale with throttle but ignore CPS.


Abbreviated transcript:


~~~

IBM 1620 simulator V4.0-0 Beta        git commit id: 8560c4a3
sim> set cpu cps=50
sim> d 0 dnty 19800
sim> g 0
/* Output blinks past at max speed */

00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000
Invalid instruction, PC: 12 (00)
sim> set throttle 50/1
sim> g 0
/* Goes at a medium pace, around 500cps */

0000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
Invalid instruction, PC: 12 (00)
sim> set cpu cps=10
sim> g 0

/* Same speed as previous run, did not slow to 10cps */
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000
Invalid instruction, PC: 12 (00)
sim>
~~~


David

________________________________

**Comment by DaveWise2** [comment]
?By the way, disregard the commit id, I copy stuff between my home and work systems and I guess something is corrupted.  But the code reflects your commits up to a93078cef972f1d9d228486e5d1b8a93ffba5c5f?.



________________________________

**Comment by DaveWise2** [comment]
Your f404343b56224865a80e5d3f7600191715a963b5 commit today restores CPS function.  I still see interaction between throttle and CPS, but is this the right issue to continue that discussion?

**Comment by markpizz** [comment]
Probably not.  #474 seems to be the place to pick that up.

**Comment by DaveWise2** [comment]
I have observed correct throttle action on the telnet console, so I think this issue can be closed.

**Comment by markpizz** [comment]
Before leaving this subject can you confirm that TELNET and non telnet behavior is consistent with CPS and various throttling modes...

**Comment by markpizz** [comment]
Oops I didn't see your most recent comment.
