### ISSUE TITLE
I1620: STEP/NEXT don't work on deferred IO

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#469]
STEP/NEXT don't do anything when deferred IO (paper tape, tty) is in progress.
   They should resume into the IO, and expire when the IO finishes, just like any other instruction.
   WORKAROUND: GO UNTIL `address of next instruction`
- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

IBM 1620 simulator V4.0-0 Beta        git commit id: c389573c
sim> show version
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Jun  6 2017 at 09:1
4:32
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 36
        Processor Id: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel, Level:
 6, Revision: 3f02
        git commit id: c389573c
sim>
- #### how you built the simulator or that you're using prebuilt binaries

Pre-built binary.

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

Expected:
~~~
sim> set throttle 50/10
sim> d 0 dnty 19900
sim> d 12 h
sim> step
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000
Step expired, PC: 12 (H   )
sim> g 0
000000000000000000000000000000000000000000000000000000000000000000
/* ^E pressed */
IO in progress
Simulation stopped, PC: 12 (H   )
sim> step
00000000000000
00000000000000000000
Step expired, PC: 12 (H   )
sim>
~~~
Actual:
~~~
sim> set throttle 50/10
sim> d 0 dnty 0
sim> d 12 h
sim> g
35000000010048000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000
IO in progress
Simulation stopped, PC: 12 (H   )
sim> step
0
IO in progress
Step expired, PC: 12 (H   )
sim> step

IO in progress
Step expired, PC: 12 (H   )
sim> step

IO in progress
Step expired, PC: 12 (H   )
sim> e par
PAR:    100
sim> step

IO in progress
Step expired, PC: 12 (H   )
sim> e par
PAR:    100
sim>
~~~
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
That just happens to be how the basic concept of STEP works in the simh framework.  Specifically, step is implemented using the internal event capability where a "STEP n" schedules an event to occur after 'n' simulator specific 'cycles' (n defaults to 1).  Given the current/new model of handling character input using the event system the simulator is implementing pseudo cycles while it executes the tty input instruction(s).  It is the passage of these pseudo cycles which allow the step to expire.

Your workaround is on the right track to providing functionality that you're typically expecting from STEP (when the I/O instruction is being executed).  What could be done would be to provide a simulator specific STEP command handler.  That handler could examine the current instruction and if it is an input instruction, actually execute the GO UNTIL, otherwise do what the internal STEP command does.  

This gets significantly messier when trying to support "STEP n" where n is greater than 1 AND the current instruction is not an I/O one, but one is encountered within the 'n' following instructions.

You may want to learn to live with this restriction an use GO UNTIL when necessary.

**Comment by DaveWise2** [comment]
I can accept the GO UNTIL workaround.  Mostly I was just alerting you to the fact that it doesn't do what the user manual says, that is, execute N instructions.  (To completion.)

I will see if I can follow your explanation of STEP internals at the detailed code level.

Actually, it doesn't even do the "correct" thing that you describe.  If I understand, STEP on a deferred IO instruction should transfer one character.  But actually, it doesn't do anything at all - see how PAR does not increment in my screenshot above?

**Comment by archivisth** [comment]
You can't have it both ways. Either the simulator counts cycles between IO events, or it doesn't. If it does, those cycles count against STEP. If it doesn't, you get instantaneous IO.

STEP n means step n ticks on the event timer. That worked fine for simple, synchronous machines like the PDP8. The correspondence is less obvious when an instruction can charge multiple ticks to the event timer.

**Comment by markpizz** [comment]
> STEP n means step n ticks on the event timer. That worked fine for simple, synchronous machines like the PDP8. The correspondence is less obvious when an instruction can charge multiple ticks to the event timer.

To be slightly more precise, a simulator 'could' have varying adjustments to sim_interval (i.e. different number of ticks for different instructions) and step would still work as expected (clock calibration would probably be hard to get right). as long as each instruction's execution was achieved in a single iteration of the instruction loop in sim_instr().   The problem here is that sim_instr() for this simulator executes the same instruction multiple separate times until it actually completes.

I agree that, you can't have it both ways if STEP is internally implemented using the simh framework provided mechanisms.

**Comment by DaveWise2** [comment]
Thanks for explaining that, Mark.

<If it does, those cycles count against STEP.>

So shouldn't STEP transfer one char?  (Even though it's not useful.  OTOH, completing the instruction is, but we have a workaround for that.)  If you feel it's working correctly as-is, please explain.  I think it's doing what the SIMH framework expects, but from the user's point of view it's malfunctioning.  (But not worth fixing.)

The physical 1620 does let you have it both ways.  There are two STOP/step buttons: SIE, Single Instruction Execute, and SCE, Single Cycle Execute.  I use both all the time, and each appears in at least one official procedure.
