### ISSUE TITLE
VAX780 BSD4.3 issue

### ISSUE THREAD

**Issue by vlazzarini** [simh/simh#480]
- #### Context
I am trying to set up BSD4.3 on a VAX780 emulation, using the instructions from 
http://gunkies.org/wiki/Installing_4.3_BSD_on_SIMH . I am stuck at an issue that may be
a problem with newer versions of SIMH. This is because the version used in the instructions
is 3.8. I have tried 4.0 and 3.9, having problems with both. The latter just halts when trying
to boot with 
Process PTE in P0 or P1 space, PC: 8002B82F (XORW3 @-7035(R8),@D0FF6436,@-70B0(R1))
on OSX.

Version 4.0.0, which is the one I want to try to use has a different problem, discussed below.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
VAX 11/780 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 4
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
        Simulator Compiled as C arch: x64 (Release Build) on Aug 28 2017 at 22:02:23
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin ligeti.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
        git commit id: ebf9489b
```
(OSX version. I have built similarly on Linux).

- #### how you built the simulator or that you're using prebuilt binaries
I have built the simulator with $make all on OSX and on Linux. The issue below happens on both
platforms.

- #### the simulator configuration file (or commands) which were used when the problem occurred.
```
set rq0 ra81
at rq0 miniroot
set rq1 ra81
at rq1 rq.dsk
set rq2 dis
set rq3 dis
set rp dis
set lpt dis
set rl dis
set tq dis
set tu dis
att ts 43.tap
set tti 7b
set tto 7b
load -o boot42 0
d r10 9
d r11 0
run 2
```

- #### the expected behavior and the actual behavior
I expected the miniroot prompt:
```
erase ^?, kill ^U, intr ^C
#
```
I get this instead:

```
panic: hard IO err in swap
syncing disks...
```
where the simulator hangs.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

All data files were retrieved as instructed in http://gunkies.org/wiki/Installing_4.3_BSD_on_SIMH

**Comment by markpizz** [comment]
I need the data files you were working with.  The instructions you point at have links to various tarballs which are no longer accessible at the links mentioned on the page you've pointed at.

**Comment by vlazzarini** [comment]
Sorry, I forgot to say I got them from another mirror:

http://unixarchive.cn-k.de/4BSD/Distributions/4.3BSD/

**Comment by markpizz** [comment]
Rather than me digging through some recipe with many pieces gathered from various independent places, I'll be glad to help determine the actual problem you are seeing if you give me the pieces that are referenced in the configuration file you're working with.  

These seem to be: 
1) miniroot
2) rq.dsk
3) 43.tap
4) boot42

Since you're doing an install from tape, I would guess that miniroot and rq.dsk are initially empty disks, so they'll be automatically created when the configuration file is executed, so we're down to 43.tap and boot42.  Please zip these files up and attach them to your next comment in this issue.  If my "guess" about miniroot and rq.dsk being empty is wrong, then please include them as well.

Thanks.

- Mark

**Comment by vlazzarini** [comment]
Ok, to be on the safe side, I've made an archive of my bsd43 directory with all files:

https://vlazzarini.github.io/tmp/bsd43.zip

thanks a lot for looking into this.

**Comment by markpizz** [comment]
I've looked at this and I do not see the behavior you claim.

Running various simh versions (3.8-1 thru 4.0Beta) and I get the same thing using your files.  

What I see is:
```
VAX780 simulator V3.8-1
loading ra(0,0)boot
Invalid SCB vector, PC: 000702A4 (MULL2 2190(R11),R0)
sim>
```

This failure is due to a divide by zero which doesn't have a trap handler.

What seems to be happening is that this is attempting to boot from the RQ disk while that disk doesn't have anything in it (i.e. it is all zeros).  A failure doing this would seem somewhat expected.

**Comment by markpizz** [comment]
Did you ever get any further along after you stopped attempting to boot from a disk containing zeros?  If you still have issues, please create a new issue here for general information start a discussion on the simh mailing list.

**Comment by vlazzarini** [comment]
What I did was to look for another BSD image for a VAX and ended up using a mini-VAX one. I could not figure where the problem was with the one I was using, since other people reported successs.

**Comment by markpizz** [comment]
It seems that you didn't follow the steps the others did in EXACTLY the same order they did.

When you handed this to me, with the instructions to reproduce the point of the failure, you gave me a completely uninitialized disk image, and the basic boot instructions to boot from a disk.  Booting from an empty disk can't work, so it isn't something I could help with.

Meanwhile, you reported different behavior with different simh versions,  The error might be reported in a slightly different way, but neither version could be expected to boot successfully from an empty disk.

**Comment by vlazzarini** [comment]
I am quite certain I followed all the instructions as prescribed. I did it more than once.

**Comment by markpizz** [comment]
I won't dispute what you say you did.
  
Meanwhile, when I followed the minimal instructions that you provided (used your configuration file with your disk images), I got exactly what I said on all versions of simh.  If I'm going to solve a hard error with a simulator, I need to be able to reproduce it.

If there is a problem you can reproduce, then I should also be able to reproduce it.  If I can, I can fix (or explain) it.

If you've got a configuration file and disk/tape images that actually produce the results you describe, then please reopen this issue and provide the files.

**Comment by DNied** [comment]
I've had this exact same problem, despite following the instructions at gunkies.org to the letter. I managed to fix it by adding to `install.ini` the following line:
```
set rq0 format=simh
```
before this line:
```
at rq0 miniroot
```
Don't ask me why it worked, though. My reasoning was that the system seemed unable to write to swap, so I just tried setting the disk to a different format.

**Comment by markpizz** [comment]
Hi Dario,

Thanks for walking through the steps to reproduce the problem that @vlazzarini was seeing.  What he gave me to start from didn't have a chance of working.

Meanwhile, after you added your comments to this issue, I realized that the problem he/you were seeing may have been related to logic in the the RQ device's attach routine which happened to 'auto size' the device to what the size of the miniroot disk image was rather than what the 3.8 and 3.9 default behavior which didn't auto size RQ disks.  The auto sizing logic ended up reducing the size of the disk to the size of the miniroot container file rather than the RA81 it was configured as.  As a result of this realization, I cleaned up the logic in the attach code and now use one of: 1) the size of the file system in use on the disk (not relevant with the miniroot disk), 2) when no file system (or Ultrix Partition Table) is detected on the disk, the MAX of the size of the container file or the current capacity of the disk being attached.

This should now do the right thing and avoid the original problem.

Can you confirm that the latest code in the master branch now works as expected (beginning to end) WITHOUT any changes to the gunkies suggested configuration file?

Thanks.

- Mark

**Comment by ZebraHedgehog** [comment]
@markpizz 

I am having the same issue and can confirm that the code in the master branch does indeed fix the issue.

**Comment by nigwil** [comment]
I'm seeing the Invalid SCB vector error:

`C:\Users\nw\Downloads\vax_4.3bsd>VAX780.exe install.ini

VAX 11/780 simulator V4.0-0 Current        git commit id: 52615e26
C:/Users/nw/Downloads/vax_4.3bsd/install.ini-3> at rq0 miniroot
RQ0: creating new file
C:/Users/nw/Downloads/vax_4.3bsd/install.ini-5> at rq1 rq.dsk
RQ1: creating new file
loading ra(0,0)boot
Invalid SCB vector, PC: 000702A4 (MULL2 2190(R11),R0)
sim>`

This is on Windows 10 64-bit with VS2008Express doing the build. I'm using the http://gunkies.org/wiki/Installing_4.3_BSD_on_SIMH directions. I tried previously with git commit id: aabb6897 - it had the same problem. Will try tomorrow on a few different systems see if the problem persists.

**Comment by neozeed** [comment]
You need to decompress the miniroot.gz file.

Since I've been able to host files on source forge for over a decade I need to copy stuff up there and rewrite those old tutorials.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by markpizz** [comment]
@neozeed is correct.

Notice the line:
```
C:/Users/nw/Downloads/vax_4.3bsd/install.ini-3> at rq0 miniroot
RQ0: creating new file
```
which therefore ends up being a blank disk (containing zeros) rather than the desired contents of the miniroot image file.  The early comments in this issue explain that running code loaded from a zeroed disk will certainly produce the error you are seeing.

**Comment by nigwil** [comment]
Thank you both for the suggestion, that fixed the problem. Yes the gunkies tutorials would benefit from some minor edits.
