### ISSUE TITLE
Commit 3f7f926 breaks `SET CONSOLE SERIAL`

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#545]
Shortly after merging the recent upstream SIMH changes into the PiDP-8/I project recently, I got [a report from one of my users](https://groups.google.com/d/msg/pidp-8/u4PQcbrn-t0/YJGmZnMfAwAJ) saying that his serial console had broken. On scanning through the changes made between our merges from upstream, I saw only [one plausible culprit](https://github.com/simh/simh/commit/3f7f92682dadc710326bc580e4fd98d2361770d7), and on backing that single change out, my user [reports](https://groups.google.com/d/msg/pidp-8/u4PQcbrn-t0/K1TYZuJlAwAJ) that the serial console is okay again.

It's not clear to me what element of this commit is wrong, so I can't propose a better fix than just "back it out." Sorry about that.

**Comment by markpizz** [comment]
The commit you're pointing at has several changes related to formatted output, which certainly would have no effect like your seeing.  There is only one functional change and that one will properly get the serial port scheduling delays to align with the specified port speed.

Can you confirm that the problem exists with the bare simh code (before you apply PiDP8 specific changes)?

Thanks.

**Comment by DavidJRichards** [comment]
I have downloaded and compiled the latest version today, I'm getting the same problem as on the pidp8i version.

`pidp8i@pidpd8i:~/simh $ ./BIN/pdp8

PDP-8 simulator V4.0-0 Current        git commit id: b0ff2978
sim> do /opt/pidp8i/share/boot/0.script
Loading OS/8 from the RK05 cartridge disk...

Simulation stopped, PC: 00203 (JMP 202)
sim> show mux
Multiplexer device: CON-TELNET, Output Unit: TTO,
    attached to Connect=/dev/ttyUSB0;4800-7e1, connected, sessions=0, Speed=4800 bps
Connecting to remote port /dev/ttyUSB0;4800-7e1
Connected to serial port /dev/ttyUSB0;4800-7e1
 Connected 00:01:34
  input (on) queued/total = 0/7
  output (off) queued/total = 0/382
  speed = 4800 bps
  bytes in buffer = 256
sim>
`

the contents of 0.script are:
`; This script initializes a populated OS/8 environment on an
; RK05 cartridge disk pack.  That's 2.5 whole megabytes, so big
; the OS requires that you split it into two partitions in order
; to address the whole disk!  Thus the "RKB0:" references you
; will find in tutorials, as that refers to the second half ("B")
; of the first ("0") RK05 cartridge disk.  The default location
; the OS uses is formally called "RKA0:", alias "SYS:".
;
; See 3.script if you want to load OS/8 via DECtape instead.
;
; This file is read on simulator startup when the IF switches are
; set to 0, so it defines the default starting environment for the
; simulator.
;
; If you need to soft-restart the simulator back into OS/8 from some
; other state -- that is, you initially started the simulator with
; IF != 0 -- you can set IF = 7 and toggle the Sing_Step switch on
; and back off, which restarts the simulator with 7.script, which in
; turn loads this one.  This somewhat clumsy arrangement is required
; because toggling Sing_Step with IF = 0 must not be made to restart
; the simulator, else there would be no way to use Sing_Step for any
; of its other functions.  See the PiDP-8/I instructions for details.
;

set console SERIAL=/dev/ttyUSB0;4800-7e1
;set console noserial

;set ttix lines=4
;attach ttix line=0, connect=/dev/ttyUSB1;9600-8n1
;set ttox0 8b
;set ttox0 disccnnect

reset
echo Loading OS/8 from the RK05 cartridge disk...
set cpu 32k
set cpu noidle
set df disabled
set nothrottle

; Override the default simulator throttle stabilization time.  See
; README-throttle.md for details.
deposit int-throttle THROT_DELAY 3

; The software was configured with either --lowercase=auto or =pass,
; so send all text input to the simulator as 7-bit ASCII, including
; lowercase.  Lowercase output from the simulator will be sent to the
; console unchanged, as will non-printing chars.

;set tti 7b
set tti 8b

att rk0 /opt/pidp8i/share/media/os8/os8v3d-patched.rk05

boot rk0`

Output on the serial terminal looks fine but it is not possible to see any results of commands typed at the terminal. In fact I do not think any commands are being interpreted at all but I cannot be sure and do not know how to check.

David.

**Comment by tangentsoft** [comment]
> The commit you're pointing at has several changes related to formatted output, which certainly would have no effect like your seeing.

I was attracted to this commit by the `SERIAL` tag and the checkin comment. I wonder if, for example, the now-conditional call to `sim_config_serial` is calling `tmxr_set_config_line` instead under the new code. Could that explain the symptom?

**Comment by markpizz** [comment]
It certainly is calling tmxr_set_config_line, which sets both timing parameters AND internally calls sim_config_serial.

When this change was made we were chasing down problems with host serial port connections to a MUX device line (DZ on the PDP11/VAX/PDP10) and not the system console line.  I'm traveling and don't have the setup to test from my laptop.  I'll get back to this after the weekend.

The output of SHOW MUX when the problem is occurring would possibly be useful.

**Comment by DavidJRichards** [comment]
I've now seen the problem on a PC too using the same latest version of simh running a copy of the pidp8i configuration files (disk etc). There is a show mux line in the message above taken when the problem exists.
hth David.

**Comment by markpizz** [comment]
Cross platform consistency (of success and failures) is good and expected.  It should make the ultimate solution simpler.

Do you see similar behavior if, rather than connecting the console to a serial line, you do:
```
   sim> set console speed=1200
   sim> set console telnet=nnn
```
And then connect a telnet session to port nnn?

**Comment by DavidJRichards** [comment]
Hi, I have tried the commands as suggested and there is a similar problem when speed is set to 1200, ok otherwise. sometimes a formfeed is received at the end of the displayed output.

when speed is set to 1200 and return is pressed, the dot prompt may appear once or twice before the console locks up, on actual serial port it always locks up on the first command.

**Comment by markpizz** [comment]
Can someone point me at a disk image and a initialization file which I can use to observe the problem?

**Comment by DavidJRichards** [comment]
Hi Mark,

Here is a file with serial console enabled:

set console SERIAL=/dev/ttyUSB0;4800-7e1
>
> reset
> echo Loading OS/8 from the RK05 cartridge disk...
> set cpu 32k
> set cpu noidle
> set df disabled
> set nothrottle
>
> ; Override the default simulator throttle stabilization time.  See
> ; README-throttle.md for details.
> deposit int-throttle THROT_DELAY 3
>
> ; The software was configured with either --lowercase=auto or =pass,
> ; so send all text input to the simulator as 7-bit ASCII, including
> ; lowercase.  Lowercase output from the simulator will be sent to the
> ; console unchanged, as will non-printing chars.
>
> set tti 7b
> ;set tti 8b
>
> att rk0 /opt/pidp8i/share/media/os8/os8v3d-patched.rk05
>
> boot rk0
>

Do you need the disk image too? it is the standard one from a pidp8i
installaltion.

**Comment by markpizz** [comment]
I'm not a user of the pidp8i stuff, so I ask for these things here so I don't have to go fishing through some prior emails or issue reports trying to locate the necessary pieces.  I'd normally also ask for steps to reproduce the problem, but that's already been described.

Thanks.

**Comment by DavidJRichards** [comment]
archived version of 
[os8v3d-patched.rk05.tar.gz](https://github.com/simh/simh/files/1868920/os8v3d-patched.rk05.tar.gz)
disk image attached for use with initialization above.

**Comment by markpizz** [comment]
Please try the latest code.  I think this problem is solved along with #508.

Note that there might be some serial port output data lost during the first few seconds of execution.  This lost data is due to the fact that the simulated execution rate hasn't yet been fully observed (throttled or unthrottled) and it is the actual simulation rate which serves as the 'clock' to control the data delivery rate to the host serial port.  The simulator likely starts with a incorrect (slow) value for the execution rate.  This will cause data to be delivered to the serial ports faster than it can actually be transmitted and the output might be lost depending on buffering in your system's hardware.  Once the actual execution rate has been computed, the output pacing will be correct.  If it is most important to get every byte out without overrunning the serial port, then you can 1) observe how fast instructions get executed on your system in the mode you're running (throttling or full speed).  Observe after running for a while and then CTRL-E SHOW CLOCK.  Lets say your execution rate is 130,000,000 (as mine is).  You can change your ini file to give the clock calibration a more correct starting point for its calibration and avoid the serial port overruns with:
```
    sim> DEPOSIT INT-CLOCK TICK_SIZE_0 2166667
    sim> DEPOSIT INT-CLOCK TICK_RATE_0 60
    sim> DEPOSIT INT-CLOCK INTERNAL_TICK_SIZE 13000000
    sim> DEPOSIT INT-CLOCK INTERNAL_TICK_RATE 13000000
```

The numbers would be different for your system, so use the output of SHOW CLOCK to determine yours, but once you do this, you shouldn't miss any serial port output.

**Comment by DavidJRichards** [comment]
Thanks Mark, the update has solved the problem.
I have tried it on PC and Raspberry Pi both now working.
Have not seen any characters missing either at 4800 bps.
Kind regards, David.

**Comment by tangentsoft** [comment]
Thank you, Mark. I've merged this into the PiDP-8/I trunk.

**Comment by markpizz** [comment]
The 'fix' to this problem introduced other problems that caused excessive CPU usage when mux devices (including the console) are being used.

I've just made a change which hopefully removes the newly introduced behaviors AND doesn't break this fix.

Can someone please test this for your system.  If things are good, please close this issue again.

Thanks.

- Mark

**Comment by tangentsoft** [comment]
The PiDP-8/I project just updated to 86294db3, and it appears to work with serial terminals still.
