### ISSUE TITLE
DHV11 performance severely compromised in PDP11 / RSX11M+ from commit 70d8f75

### ISSUE THREAD

**Issue by EJMarr** [simh/simh#566]
Prior to commit 70d8f75, DHV11 output speed performance to a telnet window in the Reflection terminal emulator (or PuTTy) was fast and smooth. From 70d... onwards it has become slow, but also lumpy, with a gap of circa 200ms between output segments (packets?). The application is RSX11M+ 4.6.

I can understand that some applications may require output at around the correct speed, but if a deliberate change, it would be good to have an option for the previous behaviour, e.g. an option of SPEED=*.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> sho version
PDP-11 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Feb 24 2018 at 17:48:21
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.5
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.16299.431]
        Architecture: x86 on AMD64, Processors: 2
        Processor Id: AMD64 Family 16 Model 4 Stepping 3, AuthenticAMD, Level: 16, Revision: 0403
        git commit id: 70d8f759

Those of the later commits that I have tested (most of them) all show the same behaviour.

All using pre-built binaries.

[RSXsystem.ini.txt](https://github.com/simh/simh/files/2014318/RSXsystem.ini.txt)

- #### the expected behavior and the actual behavior

The later commits produce the same output, just slower.

**Comment by markpizz** [comment]
The simulated serial port behavior, for devices which have simulator programmable serial port speeds (DZ and DH(VH) have this capability) is to deliver data effectively at the speed the ports have been programmed to.  The DZ does single character output so, each character's timing is regulated to the programmed port speed and data delivered over telnet connections is close to the programmed speed.  The VH (DHV11/DHU11) can do DMA I/O, so I'm thinking that the timing gaps you are seeing would reasonably map to the time that each specific DMA operation would take at the specified port speed since the whole DMA buffer is delivered to the telnet session at one time.

Give situations like yours, where you want something which is closer to 'full speed ahead', you can specify a speed factor that affects the timing of the output that is produced.  This speed factor can be specified on the device ATTACH command;
```
sim> ATTACH VH tcpportnum,SPEED=*n
```
Where n is the factor relative to the programmed port speed.  n be specified with any value from 1 thru 32.  For example, a line with a programmed port speed of 4800 with a speed factor of 4 should deliver output data at 19200 bps.  So if you specified a speed factor of 32 you should see behavior which is closer to what you saw before this strategy was implemented.

**Comment by EJMarr** [comment]
Hi Mark,

 

“Given situations like yours, where you want something which is closer to 'full speed ahead', you can specify a speed factor that affects the timing of the output that is produced. This speed factor can be specified on the device ATTACH command;

sim> ATTACH VH tcpportnum,SPEED=*n

 

That’s more or less what I though, and prior to 70d…, is what I thought I got, though experiments just now show it was not.

 

Current set up is

 

RSX:

 

>sho term

TT3:    [6,4]       [6,4]     18-MAY-18 07:34   1       E. MARR          

        CLI   = MCR     BUF   = 132.    HFILL = 0       SPEED=(9600:9600)

        LINES = 24.     TERM  = VT2xx   OWNER = none    NOPARITY

        CHAR_LENGTH = 8 NOPRINTER_PORT  NOPASTHRU       NOSERIAL

        LOWER   PRIV    NOHOLD  NOSLAVE NOESC   CRT     NOFORM  NOREMOTE

        ECHO    NOVFILL HHT     NOFDX   WRAP    NORPA   NOEBC   TYPEAHEAD

        NOCTRLC AVO     ANSI    DEC     EDIT    NOREGIS SOFT    NOBLKMOD

        HSYNC   BRO     NOABAUD TTSYNC

 

Ini file:

 

SET VH LINES=8

SET VH DHV

SET VH ADDRESS=17760500

SET VH VECTOR=440

SET VH FASTDMA

ATTACH VH 30110,speed=*16

 

Startup:

 

rsxsystem.ini-37> SET VH LINES=8

rsxsystem.ini-38> SET VH DHV

rsxsystem.ini-39> SET VH ADDRESS=17760500

rsxsystem.ini-40> SET VH VECTOR=440

rsxsystem.ini-41> SET VH FASTDMA

rsxsystem.ini-42> ATTACH VH 30110,speed=*16

Listening on port 30110

 

Executing a full file listing of the RSX system produces a file of 610 disc blocks (310k bytes) and takes

 

To a listing file    :  3s

To terminal         :  310 secs

 

demonstrating a speed of ~9600 bps. So it looks like the speed factor is broken. Changing to *32 does not change the timings.

 

Going back to the preceding commit c4e…, it takes 17 seconds at *32, and 17 seconds without the speed option.

 

Using the latest commit 4e5… , with no speed option it takes 310 secs, with speed=*32 it also takes 310 secs.

 

Also, I recorded some odd behaviour.

 

Using commit 4e5…, the console output gave this as the system shut down.

 

DMO DU0:/DEV/LOCK=V

DMO -- System disk being dismounted

DMO -- SYSTEM  dismounted from DU0:    *** Final dismount initiated ***

08:40:14  *** DU0:  -- Dismount complete

> 

SHUTUP operation complete

 

HALT instruction, PC: 126130 (CLRB @#177776)                                   [That’s the last thing RSX does, all is correct so far]

rsxsystem.ini-57> OO RQ0                                                                           [and that’s most of the BOO command that started this RSX]

Unknown command

sim>

 

The ini file contains only one BOO command. This does not seem to be repeatable, but I have seen some other strange input from the ini file with this commit.

 

Regards,

 

Ed

**Comment by EJMarr** [comment]
Mark,

 

From what I can see in sim_tmxr.c, the factor given ends up in lp->rxbpsfactor which is, so far as I can see, used only to affect receive speed.

 

It seems to me that prior to commit 70d… , output ran flat out; afterwards, it was at the speed set by the system.

 

Ed

 

From: Edmund Marr [mailto:edmund.marr@btopenworld.com] 
Sent: 18 May 2018 09:02
To: 'simh/simh'
Subject: RE: [simh/simh] DHV11 performance severely compromised in PDP11 / RSX11M+ from commit 70d8f75 (#566)

 

Hi Mark,

 

“Given situations like yours, where you want something which is closer to 'full speed ahead', you can specify a speed factor that affects the timing of the output that is produced. This speed factor can be specified on the device ATTACH command;

sim> ATTACH VH tcpportnum,SPEED=*n

 

That’s more or less what I though, and prior to 70d…, is what I thought I got, though experiments just now show it was not.

 

Current set up is

 

RSX:

 

>sho term

TT3:    [6,4]       [6,4]     18-MAY-18 07:34   1       E. MARR          

        CLI   = MCR     BUF   = 132.    HFILL = 0       SPEED=(9600:9600)

        LINES = 24.     TERM  = VT2xx   OWNER = none    NOPARITY

        CHAR_LENGTH = 8 NOPRINTER_PORT  NOPASTHRU       NOSERIAL

        LOWER   PRIV    NOHOLD  NOSLAVE NOESC   CRT     NOFORM  NOREMOTE

        ECHO    NOVFILL HHT     NOFDX   WRAP    NORPA   NOEBC   TYPEAHEAD

        NOCTRLC AVO     ANSI    DEC     EDIT    NOREGIS SOFT    NOBLKMOD

        HSYNC   BRO     NOABAUD TTSYNC

 

Ini file:

 

SET VH LINES=8

SET VH DHV

SET VH ADDRESS=17760500

SET VH VECTOR=440

SET VH FASTDMA

ATTACH VH 30110,speed=*16

 

Startup:

 

rsxsystem.ini-37> SET VH LINES=8

rsxsystem.ini-38> SET VH DHV

rsxsystem.ini-39> SET VH ADDRESS=17760500

rsxsystem.ini-40> SET VH VECTOR=440

rsxsystem.ini-41> SET VH FASTDMA

rsxsystem.ini-42> ATTACH VH 30110,speed=*16

Listening on port 30110

 

Executing a full file listing of the RSX system produces a file of 610 disc blocks (310k bytes) and takes

 

To a listing file    :  3s

To terminal         :  310 secs

 

demonstrating a speed of ~9600 bps. So it looks like the speed factor is broken. Changing to *32 does not change the timings.

 

Going back to the preceding commit c4e…, it takes 17 seconds at *32, and 17 seconds without the speed option.

 

Using the latest commit 4e5… , with no speed option it takes 310 secs, with speed=*32 it also takes 310 secs.

 

Also, I recorded some odd behaviour.

 

Using commit 4e5…, the console output gave this as the system shut down.

 

DMO DU0:/DEV/LOCK=V

DMO -- System disk being dismounted

DMO -- SYSTEM  dismounted from DU0:    *** Final dismount initiated ***

08:40:14  *** DU0:  -- Dismount complete

> 

SHUTUP operation complete

 

HALT instruction, PC: 126130 (CLRB @#177776)                                   [That’s the last thing RSX does, all is correct so far]

rsxsystem.ini-57> OO RQ0                                                                           [and that’s most of the BOO command that started this RSX]

Unknown command

sim>

 

The ini file contains only one BOO command. This does not seem to be repeatable, but I have seen some other strange input from the ini file with this commit.

 

Regards,

 

Ed

**Comment by markpizz** [comment]
Hmmm... It as you noticed, the speed factor was not considered for transmit data.

This change should fix that.

**Comment by markpizz** [comment]
Just for background on this.  The speed factor was initially provided for input processing only since simulated systems are often capable of running many times faster than the original hardware did.  This came along as a need due to the desire to actually rate limit input so that there was some sort of delay between data provided inbound into simulators.  This allowed the simulated OS/application to digest data before being overrun when someone used cut and paste into a simulator console or telnet session.  There were arguments against this since real hardware would have dropped/mangled data when input came in too fast, but with real hardware no one could type fast enough to do that or paste data into a physical terminal session.  Since cut and paste was a relatively common scenario today, we now allow it and deliver data at the configured or programmed data rate.

Rate limiting output data came along later when it was observed that output to host physical serial ports could get put into host OS serial port output buffers faster than the actual port speed and could then get overrun on the way out.  The side effect of this support to physical serial ports was that telnet sessions also have their output rate limited.  The initial implementation of this change didn't include the speed factor that was intended to be available for telnet sessions.

**Comment by markpizz** [comment]
Ed,

You mentioned:

> Also, I recorded some odd behaviour.
> 
> Using commit 4e5…, the console output gave this as the system shut down.
> 
> DMO DU0:/DEV/LOCK=V
> DMO -- System disk being dismounted
> DMO -- SYSTEM  dismounted from DU0:    *** Final dismount initiated ***
> 08:40:14  *** DU0:  -- Dismount complete
> 
> > 
> 
> SHUTUP operation complete
> 
>  
> 
> HALT instruction, PC: 126130 (CLRB @#177776)                                   [That’s the last thing RSX does, all is correct so far]
> 
> rsxsystem.ini-57> OO RQ0                                                                           [and that’s most of the BOO command that started this RSX]
> 
> Unknown command
> sim>
> 
> The ini file contains only one BOO command. This does not seem to be repeatable, but I have seen some other strange input from the ini file with this commit.

Is it possible that you changed the contents of the rsxsystem.ini file a little bit while the simulator was executing?  If so, when instruction execution stops, interpreting the ini file will start at the precise offset in the file it was at when the BOOT command started. After a file change, that might be in the middle of some unexpected command.

**Comment by EJMarr** [comment]
That is very likely – I was doing all sorts of tests, swapping exe files around, changing factors etc.

 

Report on test of recent fix following imminently.

**Comment by EJMarr** [comment]
Speed factor *32 tested on DHV11/PDP11, with success.
