### ISSUE TITLE
VAX8600 attach dz 8601,speed=0 still enables speed control first time around

### ISSUE THREAD

**Issue by sqkeith** [simh/simh#587]
I'm running vms7.3 under the new vax8600 simulator in SIMH 4 (see the attached ini file and the output of show version here
```
set cpu 512m
set cpu conhalt 
set cpu idle=vms
attach todr todr_clock.dat

set console telnet=8600
set console telnet=buffered

set rq enable
set rq0 ra92
set rq1 ra92
set rq2 ra92
set rq3 ra92
att rq0 d0.dsk
att rq1 user1.dsk

set rqb enable
set rqb0 cdrom
set rqb1 cdrom
set rqb2 cdrom
set rqb3 cdrom

set vh disable 
set hk disable
set ts disable
set tu disable

set tq enable
att tq0 mua0.tape

set dz enable,lines=16
att dz 8601,speed=0

set dmc enable,lines=1
set dmc0 peer=127.0.0.1:33962
att dmc0 33961

set xu enable
set xu mac=AA-00-04-00-10-04
att xu tap:tap10
```
and
```
VAX 8600 simulator V4.0-0 Current        git commit id: 221d72f0
sim> show version
VAX 8600 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 6.3.0 20170516
        Simulator Compiled as C arch: x64 (Release Build) on Jun  4 2018 at 19:00:42
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux debian1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
        git commit id: 221d72f0
        git commit time: 2018-06-01T07:10:57+02:00
sim> exit
Goodbye
```

It seems that the speed parameter on 
 *attach dz 8601,speed=0*
is ignored. When VMS has initialised, and I connect to port 8601, I experience a slow (9600baud) connection. The console port works fine at full speed without having to specify. I can get around the problem by breaking into the simulation, detaching dz then re-attaching dz with speed=0. I then experience a full speed connection.

Am I misunderstanding something or is there a problem with the dz mux initialisation?

Regards,

Keith H

**Comment by sqkeith** [comment]
Further to the above, the simh appears to ignore the speed multiplier too when executing the ini file, ie:

*attach dz 8601,speed=\*32*

but once running, I can break in and reattach with success.

**Comment by markpizz** [comment]
The ability to specify a MUX device's speed at attach time is determined by: 
1) whether the device being simulated has a programmatic means of specifying port speed
AND
2) whether the device simulation for that device implements the programmatic device commands that set the port speed.

The VAX console port does not meet either of these criteria, so the SET CONSOLE SPEED= command is the only way to influence the console port speed.

The DZ (and VH) devices meet BOTH criteria, so whenever an operating system driver in the simulator performs the device commands to set the port speed, that activity propagates to the port in question.  
The VMS driver's initialization logic sets all ports to 9600bps.  Hence, your attach command for these devices won't let you specify a speed.  Your request here identifies a bug in the command parsing for this case since it will allow a speed of 0 to be specified.  That has been fixed.

You can see the details of the current port configuration with the SHOW MUX command.

As you seemed to have been exploring.  When a MUX device programmatically sets port speeds, you may want to have things run faster than the programmed rate.  To achieve this you use the SPEED=*n factor mechanism, which does work as designed.

**Comment by sqkeith** [comment]
Hi and thanks for the quick response.

I am still seeing some strange behaviour:

I have gone back to a simple **attach dz 8601** and then boot vms. As part of startup, all TT terminal lines are set to **/speed=9600/permanent** and this is reflected in the simulator when I break in and do a *show dz statistics** and I see *speed = 9600 bps*

Logged into the simulated system via a dz line, I can set my line speed **set term/speed=19200** and this is also reflected in the dz statistics although there doesn't seem to be much of a visible speed increase when doing, for example a long directory listing.

The really weird bit is when I set my line speed **set term/speed=57600** and the dz statistics show *75 bps* (seventy five) with a corresponding drop in visible line speed.


Some other line speed settings, such as the top rate of 115200 are ignored completely by simh, leaving the previous speed set.

**Comment by sqkeith** [comment]
As an aside, VH has its own issues. Substituting VH for DZ in the above, with identical terminal settings (from VMS's point of view at least), when even a small amount of output is generated (the 6-7 line welcome message or a 10 line directory listing for example), I see the first few lines and the '$' command prompt and the latter portion is missing.

**Comment by markpizz** [comment]
The DZ hardware didn't support speed above 19200 since the programming interface it provides limits it to that.  What you're seeing at 57600 is the VMS device driver not returning an error for a speed value it can't process and the garbage result.  From the VMS point of view, a user specifying a speed which is not understood by the driver merely will result in a serial port being configured such that bits don't come out of the port at the expected rate and once the user sees that no useful data is transmitted they'll try something else.  The fact that a telnet session isn't actually sensitive to the programmed port speed for data integrity and that you still get data but at an unexpected rate is a bonus of the simulation environment.

As for the "doesn't seem to be much of a visible speed increase" between 9600 and 19200, you should take a reasonably long (say 30k bytes) text file and carefully time the time it takes to TYPE that file at different speeds.  Precise isolated measurements are always more useful that general impressions that involve many different parts of the system (a directory listing touches the disk possibly several times for each line it produces).  You could save a directory listing to a file and use that as your test data if it is long enough so that your timing method is precise enough.

The VH observation might be a real problem.  Please create a separate issue to report that.

Please put your full name on your GitHub profile.

**Comment by mike632t** [comment]
Using commit id 0fa5807e I configured the dz device as below.
```
set dz enable
set dz lines=4
attach dz 8192,speed=*32
```
As noted above after the system has booted the speed multiplier seems to be ignored.  
```
$ TYPE TEST.LIST
  :
  :
  :
```
Time to display file approx 1'35" 


I suspected that when the operating system (in my case VMS) was setting the baud rate on the DZ device the speed multiplier was also being reset.  

Breaking in to the simulator prompt and changing the DZ parameters results a speed increase as expected.

```
$
^E
sim> attach dz 8190,speed=*32
sim> cont

$ TYPE TEST.LIST
  :
  :
  :
```
Time to display file approx 0'02" 

If I then set the baud-rate from the operating system again the effect of the speed multiplier is again ignored, which suggests that resetting the baud rate also reset the speed multiplier
```
$ SET TERM/SPEED=19200
$ SET TERM/SPEED=9600
$
$ TYPE TEST.LIST
  :
  :
  :
```
Time to display file approx 1'35" 

If I've set a speed multiplyer I'd expect it to be independent of the baud-rate so this behaviour does seem unintuitive.

Mike T.

**Comment by mike632t** [comment]
After a bit of digging I found that in sim_txmr.c it says that the speed multiply factor will persist independent of any programatic action by the simulated system so I guess this should be is a separate issue?  
```
    fprintf (st, "If an attach command specifies a speed multiply factor, that value will\n");
    fprintf (st, "persist independent of any programatic action by the simulated system to\n");
    fprintf (st, "change the port speed.\n\n");
```
(Still haven't found where the speed multiply factor is defined or used but I can't be far off!).

Mike T.

**Comment by markpizz** [comment]
Mike,

Please put your full name on your GitHub profile.

> Does you comment above mean that the OS (VMS) resets the speed multiplier set in the .ini file or just the speed? (I think what you are saying is that it resets the speed, and that it should not reset the multiplier).

As you were thinking, the multiplier is manually configurable, and should not change once it is set.  Certain mux devices have device programmable port speeds and some such devices have device simulation logic that propagates simulator programming of port speed to reflect the operational behavior of the device.  The DZ and VH fit this mold.  

As you've demonstrated there are real problems right now with speeds in general.  Part of which is the speed factor.  I'm on this now.  I'm putting together an automatic script to precisely measure a range of actual speeds so that 1) something rigorous will exist to test this automatically while the problem is being chased down, and 2) this test can be run subsequently on demand to confirm reasonable behavior exists in the future.

**Comment by mike632t** [comment]
I'm not up to finding the bug in to code but I'm very happy to do anything I can do to help test stuff.   

Mike T.

**Comment by sqkeith** [comment]
Hi Mark, as a result of commit 4428d49 yesterday, dz's output rate (without a speed=*n) is quite accurate. There is a noticeable difference between 300 up to 19200, the latter more like I remember that speed being on a real VT100. With a speed multiplier, I can make 300 look like 19200. You may not have finished working in this area but thank you very much for fixing the issue.

(I checked out the previous commit around VH buffering but noted that VMS permanently stalled during, I think, autoconfigure. I didn't try much more because I ran out of hobby time)

**Comment by sqkeith** [comment]
I spoke too soon. With two concurrent DZ connections open, the speed issue returns. Once either connection is dropped, the surviving connection becomes *32 again.

**Comment by markpizz** [comment]
Please use ^E and then SHOW MUX at the "sim>" prompt to display what the current port configuration details are, and then be specific about what works or doesn't.  The VH is still broken, but the DZ should produce results which are pretty close to the specified port speeds.  That is the case from my testing.

**Comment by markpizz** [comment]
Please test this again.  My testing shows expected behavior to be good even with multiple ports active.

This script can be used to test speed behavior with VMS connected ports (VH, DZ and CONSOLE).  If someone wants to tweak it so that RSX can be tested in the same way, that would be appreciated.
[SerialSpeedTest.ini.txt](https://github.com/simh/simh/files/2130214/SerialSpeedTest.ini.txt)

**Comment by sqkeith** [comment]
I'll be able to run some tests (VMS) tomorrow. Thank you Mark for all the work you're doing here. It is very much appreciated.

**Comment by sqkeith** [comment]
I've tested DZ with the microvax3900 simulator
1-8 lines active, mix of line speeds from 1200 to 19200, mix of multipliers from default to *32.
No speed change issues as I increase the number of active lines from 1.
Without the multiplier, line speeds are well simulated though I only checked the relative difference between 1200, 9600 and 19200.
Low multipliers (*2, *4) I could predict the changes relatively.
Larger multipliers were fast - that's the best description I can provide :)

About 2-3 changesets back, connecting to a DZ line resulted in the simulator running at 100%, despite set cpu idle=vms. This is no longer an issue. 

Once again, thanks.

I'll see if I can do some testing with VH this evening.
