### ISSUE TITLE
VAX, PDP11: VH MUX drops large chunks of output (VMS7.3) irrespective of set speed

### ISSUE THREAD

**Issue by sqkeith** [simh/simh#588]
In swapping out the DZ MUX for the VH one:
```
set cpu 512m
set cpu conhalt 
set cpu idle=vms
attach todr todr_clock.dat

set console telnet=8600
set console telnet=buffered

set rq enable
set rq0 ra92
set rq1 ra92
set rq2 ra92
set rq3 ra92
att rq0 d0.dsk
att rq1 user1.dsk

set rqb enable
set rqb0 cdrom
set rqb1 cdrom
set rqb2 cdrom
set rqb3 cdrom

set hk disable
set ts disable
set tu disable
set rl disable
set rp disable
set ry disable

set tq enable
att tq0 mua0.tape

set vh enable,lines=16
att vh 8601

set dz enable,lines=8
att dz 8602

;set dmc enable,lines=2
;set dmc0 peer=127.0.0.1:33962
;att dmc0 33961
;set dmc1 peer=127.0.0.1:33964
;att dmc1 33963

set xu enable
set xu mac=AA-00-04-00-0A-04
att xu tap:tap10
```
when I log-in via the VH MUX and generate any multi-line output (typing a text file, directory listing, the welcome and last login details message), large chunks of the output are dropped. When I set the terminal speed down from 9600 to 1200, I see the same sort of thing except that the time between a drop happening and a resumption increases, as though the MUX is processing the missing characters at the same rate as the displayed ones.

Version of SIMH running is still the same: 
```
VAX 8600 simulator V4.0-0 Current        git commit id: 221d72f0
sim> show version
VAX 8600 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 6.3.0 20170516
        Simulator Compiled as C arch: x64 (Release Build) on Jun  4 2018 at 19:00:42
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux debian1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
        git commit id: 221d72f0
        git commit time: 2018-06-01T07:10:57+02:00
sim> exit
Goodbye
```

**Comment by markpizz** [comment]
Keith,

Thanks for adding your name to your profile.

The issue template clearly spells out that it is desirous to literally include the version and configuration output directly in the issue text.  Attaching things in separate files requires a 2 or 3 step process to access information that would otherwise be visible at a glance.  Someone (me or someone else) looking at one particular issue will most often need to glance through this information to help get back to a reasonable context while reading through the issue's content since they often will be working on any number of other issues or other things and sometimes some of these interactions happen with long delays between these interactions.

**Comment by markpizz** [comment]
Back to the subject of this issue...

1) Will you include the output of SHOW TERMINAL here in the issue text.
2) Will you please create a test file which you use consistently with these tests (doing a TYPE filename) and attach it to this issue.
3) Please include specific details about the results you see as you change variables in the test (9600 to 1200, for example), and the actual output you see one way or the other.

**Comment by markpizz** [comment]
I'm not sure how @sqkeith 's message got deleted, but here it is:

Output of SHOW TERM TXA0: from a logged in session on OPA0:
```$ show term txa0:
Terminal: _TXA0: Device_Type: VT102 Owner: _TXA0:
Username: SYSTEM
Input: 9600 LFfill: 0 Width: 80 Parity: None
Output: 9600 CRfill: 0 Page: 24
Terminal Characteristics:
Interactive Echo Type_ahead No Escape
No Hostsync TTsync Lowercase Tab
Wrap Scope No Remote No Eightbit
Broadcast No Readsync No Form Fulldup
No Modem No Local_echo Autobaud No Hangup
No Brdcstmbx No DMA No Altypeahd Set_speed
No Commsync Line Editing Overstrike editing No Fallback
No Dialup No Secure server No Disconnect No Pasthru
No Syspassword No SIXEL Graphics No Soft Characters Printer port
Numeric Keypad ANSI_CRT No Regis No Block_mode
Advanced_video Edit_mode DEC_CRT No DEC_CRT2
No DEC_CRT3 No DEC_CRT4 No DEC_CRT5 No Ansi_Color
VMS Style Input
```

**Comment by sqkeith** [comment]
I deleted it. I was trying to preserve the spacing - the preview mode is not great. Just re-running with idle=vms switched off.

**Comment by markpizz** [comment]
FYI, Google GitHub Flavored Markdown (aka GFM) for syntax while composing issue content.  Literal/code blocks are delimited (started and ended) with triple backticks (`) on separate lines.

**Comment by sqkeith** [comment]
[term.txt](https://github.com/simh/simh/files/2078270/term.txt) - the file used in a TYPE command.

When logged in via TXA0:, issuing the TYPE command results are variable:

```
$ type term.txt
Terminal: _TXA0:      Device_Type: VT102         Owner: SYSTEM

   Input:    9600     LFfill:  0      Width:  80      Parity: None
   Output:   9600     CRfill:  0      Page:   24

Terminal Characteristics:
   Interactive        Echo               Type_ahead         No Escape
   No Hostsync        TTsync
```

and again

```
$ type term.txt
Terminal: _TXA0:      Device_Type: VT102         Owner: SYSTEM

   Input:    9600     LFfill:  0      Width:  80      Parity: None
   Output:   9600     CRfill:  0      Page:   24

Terminal Characteristics:
   Interactive        Echo               Type_ahead         No Escape
   No Hostsync        TTsync             Lowercase          No Tab
   Wrap               Scope              No Remote          No Eightbit
   Broadcast          No Readsync        N
```

Also, the output rate, despite 9600 baud being set without a multiplier, is at console speed, with one or two very very short pauses midway through the output. By this I mean, there may be pause after the 'a' of 'Page:' and another mid 'Lowercase'

When I set the terminal speed down to 1200, I get the same variable output, again at console speed but the pauses mid-output are noticeably longer.

**Comment by sqkeith** [comment]
I worked out why preview wasn't showing me the results of mark-up. Edge. I've switched back to Chrome :)

**Comment by markpizz** [comment]
I can reproduce this problem, thanks for the info.

While I'm looking into this, please followup on the DZ speed issue #587

**Comment by EJMarr** [comment]
In testing a fix for #578, I ran into difficulties in using VH over telnet.

Firstly, I find that echoing is consistently one character late. With concentration, and limited typing errors, one can continue.

Then, with operations involving quantities of output, it either seems to work, with the exception that the last output chunk does not appear until the next character is typed; or output text is dropped and the outputting program can hang, requiring some input to make it resume.

A debug file for a test is attached below. It demonstrates both the delayed echo and the loss of output. The code base used includes 91bd90c3 and d20ef039, cloned as source, then built in Visual Studio 2015 with two minor changes to the debug output, one to show the generation of clock ticks, and one to suppress some excessive output related to idling.

The test is to fetch memory data from a remote system over Ethernet (in this case implemented as a separate simh instance on the same PC) and dump it to screen. The memory data shown is fetched in packets of 16 bytes, and each is output (with its address) before the next is requested.

The screen should look like this

```
>cip
CIP-LOGIN>2 EJM
CIP>MON.1
MON>OPE 0+100
0000000000  000240 000416 005774 000340 006014 000341 006014 000342
0000000020  006616 000343 006350 000344 006434 000345 006034 000346
0000000040  000167 010002 000000 000000 000000 000000 000000 000000
0000000060  003766 000340 003772 000340 003776 000340 004002 000340
0000000100  004006 000340 004012 000340 004016 000340 006426 000340
0000000120  004026 000340 004032 000340 004036 000340 004042 000340
0000000140  004046 000340 004052 000340 004056 000340 004062 000340
0000000160  004066 000340 004072 000340 004076 000340 004102 000340
0000000200  004106 000340 004112 000340 004116 000340 004122 000340
0000000220  004126 000340 004132 000340 004136 000340 004142 000340
0000000240  000002 000000 006050 000340 007544 000340 004162 000340
0000000260  004166 000340 004172 000340 004176 000340 004202 000340
0000000300  004206 000340 004212 000340
0000000310  004216>
```
but what came out (with echoes delayed) is

```
>cip
CIP-LOGIN>2 EJM
CIP>MON.1
MON>OPE 0+100
0000000000  000240 000416 005774 000340 006014 000341 006014 000342
0000000020  006616 000343 006350 000344 006434 000345 006034 000346 
0000000040  000167 010002 000000 000000 000000 000000 000000 000000
0000000060  003766 000340 003772 000340 003776 000340 004002 000340
0000000100  004006 000340 004012 000340 004016 000340 006426 000340
0000000120  004026 000340 004032 000340 00
0000000140  004046 000340 004052 000340 004056 000340 004062 000340
0000000160  004066 000340 004072 000340 004076 000340 004102 000340
0000000200  004106 000340 004112 000340 004116 000340 004122 000340
0000000220  004126 000340 004132 000340 004136
```

Output froze before the last 4 characters of the line at address 20 until Enter was pressed at 16:47:39.331 1129579104884

It froze again one the line for address 120 (which was also truncated) but resumed after a character was typed. I terminated the test following a freeze at the line for address 220.

[vhdebug1.txt](https://github.com/simh/simh/files/2129772/vhdebug1.txt)

**Comment by markpizz** [comment]
There have been several problems in my evolving implementation of VH functionality.

I committed the prior set of changes after only testing with VMS.   VMS's  VH driver only does DMA if the terminal port has been explicitly set to DMA mode with: SET TERM/DMA TXcn:
Even with DMA mode set, it only actually does DMA if the output buffer being sent exceeds some internal threshold in size.  Character input on VMS (and its echo) is all done with Programmed I/O.  On RSX, the driver always does DMA for all I/O (including character echo), which is why you saw the one behind behavior.

The latest changes should behave correctly both for Programmed I/O and for DMA I/O.  

There is one problem I'm still tracking down:  Output rates occur at the configured specified port speeds (with speed factor applied) for all programmed I/O cases, but for line length I/O sizes (using DMA) output speed is slower than expected.

Apart from this, the VMS device driver is not well behaved when performing DMA I/O at relatively slow speeds (600bps and slower).  This is due to the fact that the hard coded I/O timeout in the device driver seems to be set to a value of 2, where 2 is two seconds.  VMS has a once per second scan of the I/O database that implements timeouts for I/O operations.  At 300bps (30 cps) a 70 character output line will essentially always end up having 2 seconds elapse before the whole transfer is complete.  Since the VMS default terminal attributes don't have DMA enabled, and the use of devices connected at these relatively slow speeds was quite rare, it is reasonable that this combination either was never tested, or if it was, there was a completely sane workaround (don't enable DMA on slow lines), so it shipped that way.

**Comment by EJMarr** [comment]
Here is some debug data that gives information that may lead you towards an answer.

It includes int-clock idling and calibration, clock interrupts themselves, and the Ethernet packets fetching the data.

What is happening is that the calibration is very inaccurate for this I/O intensive activity, with clock tick occurring up to 115ms apart (in a small search - I have not looked for the overall maximum), and if the clock ticks are that far apart, perhaps also is the timing for the terminal I/O.

The clock ticks are happening at the correct interval as timed by instructions.

[JUN24VHDBG2.TXT](https://github.com/simh/simh/files/2131230/JUN24VHDBG2.TXT)

**Comment by markpizz** [comment]
Several questions:

1) How are you picking up the changed code from the GitHub master branch and then placing it in your working directory?  I ask since your runtime environment does not have a proper git commit I'd defined and I was under the impression that I'd covered all the ways people could end up missing it.
2) is the timing better or no different with idling disabled?
3) has the system been running long enough for calibration to have stabilized before you start this load?
4) you can use the remote console to query timing status SHOW CLOCK during execution.

**Comment by EJMarr** [comment]
Re your questions:

1.	By brute force and ignorance
        a. from Visual Studio clone a local copy of the whole thing (having deleted the previous version I had)
        b. re- apply the tweaks to debugging that I have stored in a local text file, necessary because one debug statement gives so much output that the system does not seem to do anything else.
        c. Build the PDP11 emulator – which fails the first time as it says that the source has been modified outside the VS environment and it gives me a button to update the VS environment. 
        d. after that it just builds, but with no commit ID, as you’ve noticed. 
2.	Latest test without IDLE:
[jun25dbg1.txt](https://github.com/simh/simh/files/2135909/jun25dbg1.txt)
•	Shows clock ticks at 19-22ms just before it heads into the memory dump
•	Then ticks at (s.ms) 34.214 as the fetch/display begins, followed by 34.344, 34.471, 34.598, 34.726, 34.856, … 37.246 (where there is a calibration), 37.293, 37.338, 37.383, 37.430, 37.476, continuing at 45ms intervals until another calibration at 39.481, 39.494, 39.508, ending with 39.911 where the system starts idling, and gives clock ticks at 1 to 2ms intervals until 39.988, then at 6ms intervals  until 40.301, then at 9 – 10ms periods until  41.792, then at 16 – 17 ms intervals until 42.661, when it stabilises at ~20ms.
•	The slowdown and speed-up is visible from RMD
•	Processor loads from Task Manager show:

Activity|System A (RSX + terminal)|System B (system dumped)|Reflections emulation frame|Reflections terminal|CPU rate
-------------|------------------|------------------|--------------|---------------|------------------
Systems quiet, A set to NOIDLE|Circa 50%, but can be a little over|0% to 0.5%, with occasional periods rising to 7%|0%|0%|3.2GHz
A set to NOIDLE, active dumping|47.8%|2.6%	|2.9%|18% to 21%|	3.2GHz
Systems quiet, A set to IDLE (after stabilisation)|~3%|0% to 0.5%|0.3%|0%|1.2GHz
A set to NOIDLE, active dumping|50%|3%|3.2%|17% to 20%|3.2GHz

3.	The example previously given shows the transition from being not stable to being stable
The log starts with Ethernet packets sent from system B while system A (the debug log’s) was stopped setting up the debug session.
It explains why it is not stable when it tries to idle (or at least the first reason it comes to), but it is running at circa 20ms tick timing.

```
if (!sim_idle_enab) reject_cause = 1;     /* idling disabled */
else if ((sim_clock_queue == QUEUE_LIST_END) && (!sim_asynch_timer)) reject_cause = 2;           /* or clock queue empty and not asynch */
else if ((sim_clock_queue != QUEUE_LIST_END) && ((sim_clock_queue->flags & UNIT_IDLE) == 0)) reject_cause = 3;           /* or clock queue not empty  and event not idle-able*/
else if (rtc_elapsed[tmr] < sim_idle_stable) reject_cause = 4;  /* or timer not stable? */
else reject_cause = 0;
```
	After 3 seconds I start typing and mistyping; after 20 seconds (DBG(22:10:00.462 382511383805)> INT-CLOCK IDLE: Can't idle 0: INT-CLOCK0 - elapsed: 20.000) the system is stable and can idle (Note the text ‘Can’t idle 0’ is the exit from Can’t idle).

	At 22:10:04.102 382762832316, I have completed typing and the data fetches start. Prior to this the clock ticks are a little short, as if it is trying to catch up.

	Clock ticks slow down during the relatively small fetch (3000 words), and speed up afterwards at 22:10:09.836. During the data fetch are only about 15 actual sleep periods mostly of 1ms. 

	Testing this later with an RMD display showing the time, the slowdown/speedup was not obvious with SET CPU IDLE, but the log from 24th June shows it happening. I am not convinced that it always behaved the same.

4.	I can’t get it to work reasonably for me. I do get “Connected to the PDP-11 simulator CON-TELNET device “, but RSX just takes over, perhaps because after setting up a remote console, a network status reporter puts out a message on the RSX console before I can do anything.

Looking at timings, I am at a loss to explain the timings from the following extract from 24th June.

```
DBG(22:10:06.514 382787611398)> VH RREG: vh_rd(vh=0, PA=0x003FE140 [CSR   ], access=0, data=0x4040) TX_ACTION0 TXIE1 DIAG_FAIL0 TX_DMA_ERR0 TX_LINE=0x0 RX_DATA_AVAIL0 RXIE1 MASTER_RESET0 SKIP0 IND_ADDR=0x0  
DBG(22:10:06.518 382787630393)> XQ PACKET: xq-write  dst: 6D:DB:6D:5B:02:00  src: 6D:DB:6D:5B:01:00  proto: 0x0014  len: 60  crc: 1B2A8BA2 
DBG(22:10:06.519 382787634573)> XQ PACKET: xq-recvd  dst: 6D:DB:6D:5B:01:00  src: 6D:DB:6D:5B:02:00  proto: 0x001C  len: 60  crc: 5B00E709 
DBG(22:10:06.525 382787669428)> VH WREG: vh_wr(vh=0, PA=0x003FE140 [CSR   ], access=2, data=0x4040) TX_ACTION0 TXIE1 DIAG_FAIL0 TX_DMA_ERR0 TX_LINE=0x0 RX_DATA_AVAIL0 RXIE1 MASTER_RESET0 SKIP0 IND_ADDR=0x0
```
Over 11 msecs, some 58000 instructions are executed, but calibrations show that an idle machine is capable of executing 1.3m instructions in a clock tick.

If this simh system is idling without sleeping, it should count instruction. If idling with sleeping, it should log in the debug file the time spent, and the CPU load would be lower. 

So what is it doing, I ask myself?

From the time taken for System B to respond (1ms), it seems unlikely that the time spent is in the DEQNA support code in System A; it ought to be similar. Is the telnet transfer synchronous with somewhere an internal loop waiting for a reply, or could it be the debug output?

**Comment by markpizz** [comment]
There seems to be a number of things going on here.

1) The latest code should have at least one fewer steps when you pick it up before you get a working pdp11 binary to test.  It will require updated windows-build components which it will point out to you if you haven't updated them prior to building.  I added debug to the PDP11 CLK device so you don't have to manually apply local patches.  Also, your suggestion to limit the IDLE debug output had been applied earlier.  Depending on the Visual Studio environment you've got and whether it contains native git binaries, you may be asked to install git for windows so that the correct commit id info is available at build time.
2) The dramatically different clock tick times you're observing seem to be reasonable given the dramatically different extra work that is happening in the Ethernet layer.  Clock calibration only occurs once per second and therefore the swings to correct the 'average' over time, and catching up for when it fell behind due to the extra work.  Maybe you should try and limit the dramatically different extra work that is happening in the Ethernet layer.  I'm thinking that maybe you could leverage the XQ THROTTLE capabilities to influence this:
```
THROTTLE
    The faster network operation of a simulated DELQA-T/DELQA/DEQNA device
    might be too fast to interact with real PDP11 or VAX systems running on
    the same LAN.
    Traffic from the simulated device can easily push the real hardware
    harder than it ever would have seen historically.  The net result can
    be excessive packet loss due to various over-run conditions.  To support
    interoperation of simulated systems with legacy hardware, the simulated
    system can explictly be configured to throttle back the traffic it puts
    on the wire.

    Throttling is configured with the SET XQ THROTTLE commands:

        sim> SET XQ THROTTLE=DISABLE
        sim> SET XQ THROTTLE=ON
        sim> SET XQ THROTTLE=TIME=n;BURST=p;DELAY=t

    TIME specifies the number of milliseconds between successive packet
    transmissions which will trigger throttling.
    BURST specifies the number of successive packets which each are less than
    the TIME gap that will cause a delay in sending subsequent packets.
    DELAY specifies the number of milliseconds which a throttled packet will
    be delayed prior to its transmission.
```

**Comment by EJMarr** [comment]
re: Notes above

Commit ID now works for me.

1. ... 'Also, your suggestion to limit the IDLE debug output had been applied earlier.'

Not fully - see extract from an 89MB debug file in 15 seconds when a system is started with 

```
SET INT-CLOCK DEBUG=CALIB;IDLE
set xq debug=packet
SET DEBUG -N -T jul8dbgn2.txt
BOO RQ0
```

[jul8dbgn2.txt](https://github.com/simh/simh/files/2173514/jul8dbgn2.txt)

2. I don't think it is the Ethernet layer; as I see it, more likely it is the VH to Telnet layer. The Ethernet traffic between my two simh nodes is symmetrical in packet numbers, and not far off in packet length. The node not doing terminal I/O runs at 7% CPU, putting an upper limit on the loading due to Ethernet packets while the node doing terminal I/O maxes out. I'll try to track it down further. I see you have just done some updates in this area. I'll include those and my idle debug patch and see where it takes me.

**Comment by markpizz** [comment]
You can minimize the "Can't idle: not stable" messages with:
```
sim> SET CPU IDLE=2
```
I think the Ethernet throttling may still be relevant since the change in overhead is significant and the packet delivery will be much faster than on the original system.  Without active throttling, many packets can get queued in receive buffers and the system's processing of those may keep kernel level activities overwhelming normal stuff.  The extra Ethernet layer work will certainly interfere with instruction execution and affect the clock calibration activities.

**Comment by EJMarr** [comment]
"You can minimize the "Can't idle: not stable" messages with:"

sim> SET CPU IDLE=2
I just tried it on commit id d593cdb6, and got a continuous stream of the above message.

Edmund Marr
Mobile + 44 (0) 7712 680511

On 8 Jul 2018, at 11:40, Mark Pizzolato <notifications@github.com> wrote:

You can minimize the "Can't idle: not stable" messages with:

sim> SET CPU IDLE=2

**Comment by markpizz** [comment]
When I said:
> You can minimize the "Can't idle: not stable" messages with...

I meant that instead of producing those messages for 20 seconds, they would only be produced for 2 seconds which would be the 'minimal' period with the current code.

If you were printing the debug log on paper, getting the output down to a couple of lines would be very valuable.  Since no one prints debug log data on paper and since modern editors (since the 1990's) can easily handle files that are 100's of MB in size, that should be good enough for where we need to go.

**Comment by EJMarr** [comment]
Yes, but the system spends so much time producing debug output that it hardly runs.

**Comment by markpizz** [comment]
That is true for the first 2 seconds and it settles down after that.  You certainly don't have to start your interaction with the other system that quickly...

**Comment by EJMarr** [comment]
Inspecting the debug output, it is not just the 'Can't idle: not stable', but also (for me) TT0, RQ and VH activity that produce vast quantities of output from the same debug statement, and these may be continuously active, not just for the first two seconds.

e.g.

```
DBG(21:42:02.656 32251299)> INT-CLOCK IDLE: Can't idle: RQ-QUESVC - elapsed: 3.033
```

Calibration results can show 'result' in the 10,000 to 20,000 range whereas without this output, numbers of the order 2,000,000 are common, suggesting that the debug output takes 98 to 99% of the available time.

Trying to get a handle on timing with this output present in this form is tricky, to say the least.

**Comment by jguillaumes** [comment]
Hello,
After compiling the last repo version I'm experiencing weird problems with the VH device, both on vax (vax780) and pdp11. I'm guessing it's the same problem discussed here. Basically, the output comes out in "chunks", with dropped characters, and the system is basically unusable.

Output of show version:

```
sim> show version
VAX 11/780 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)
        Simulator Compiled as C arch: x64 (Release Build) on Jul 24 2018 at 23:57:20
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.42 2018-03-20) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin macjordi.jguillaumes.dyndns.org 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
        git commit id: 52e8c7f6
        git commit time: 2018-07-21T02:22:26-07:00
```

I've tried to bisect the problem without success (my fault, probably). 

Oh, I'm observing the same behaviout both under MacOS and Linux.

**Comment by markpizz** [comment]
Opps.  That was an earlier version of serialspeedtest.ini.  This is what you should use:
[SerialSpeedTest.ini.txt](https://github.com/simh/simh/files/2226424/SerialSpeedTest.ini.txt)

**Comment by jguillaumes** [comment]
I've finished my bisecting. This is the result:

```
 git bisect bad
611679a5cd787dc105fb605e2a0450fd57ab2971 is the first bad commit
commit 611679a5cd787dc105fb605e2a0450fd57ab2971
Author: Mark Pizzolato <mark@infocomm.com>
Date:   Tue Feb 13 01:38:33 2018 -0800

    TMXR: Properly apply output rate limit timing to all lines on a mux
    
    Compute proper scheduling delays for all mux polling activities.

:100644 100644 5c660ba58b11f4bb3729ae623a5e90032942ddc3 46798bda1426e779a10aa7b168f0b52b6cb85183 M	sim_tmxr.c
:100644 100644 385fd34df94e29df99f2c2584d3d7094a76c15d1 e7597f195e3080e6f78c80b3452150317e32d9bf M	sim_tmxr.h
```
I'm guessing the problem I experience is related or the same you are discussing in this issue. If you think it is not I'll be happy to open a new issue.

The symptom is loss of characters/blocking when connected to the system using a VH device. Ulterior commits make things worse to the point it is not even posible to log in (I don't even get a login prompt).

The environment I've been using to do the bisect is:

- VMS 4.7
- vax780 simulator
- Configuration file:
```
$ cat vax780.ini
set cpu conhalt	
set cpu idle=vms
attach todr todr_clock.dat

set rq enable
set rq0 ra81
att rq0 RA81.000

set vh enable 
set vh lines=16
att vh 32961

set ts enable

set hk disable
set tq disable
set tu disable
```

You can download a system image here: https://drive.google.com/open?id=0B2q64Hq0IZ1WWm41NW40ZVROMG8

The password for the SYSTEM account is MANAGER. Please update the vax780.ini file to the one I've just posted.

**Comment by markpizz** [comment]
Jordy,

Bisecting the dramatic range of changes that were made to the VH device source code AND the TMXR library really doesn't help for this case.  Additionally, the details of your problem are not what issue #588 was about since, as I mentioned the problem has now been fixed.  

Meanwhile, using the failure example case you've provided absolutely demonstrates a problem with the VH device.  As it turns out, the problem you are having is a problem with the DHU mode of the VH device on UNIBUS systems.  Please confirm my observation (Unibus vs Qbus), and if you think it is true, move your problem description to a new issue about the Unibus mode of the VH simulation.  No additional Bisecting needed.

Thanks.

- Mark

**Comment by markpizz** [comment]
@sqkeith will you please confirm that the problem you were originally seeing is now fixed, and if so, please close this issue.

Thanks.

Mark

**Comment by sqkeith** [comment]
Confirming (and closing issue) that I'm not seeing any of the VH issues I reported a while back.
