### ISSUE TITLE
Commit 5a18d314 4/11/2018 (and all following) breaks PDP11 MSCP disk emulation under XXDPv25 O/S

### ISSUE THREAD

**Issue by AK6DN** [simh/simh#592]
Commit 8bec55b on 4/10/2018 (and earlier) running MSCP disk emulation on a PDP-11 under the XXDPv25 operating system (a very simple operating system by DEC for running diagnostic tests) worked fine, as shown in the below 'passing' log file.

Starting with commit 5a18d31 on 4/11/2018, and all following up to most recent on 6/23/2018, MSCP emulation under XXDPv25 operating system is broken. As the failing log shows, the disk image will boot, but then the controller emulation malfunctions, and further accesses to the image (DIR commands) fail.

Control file:
[foo.ini.txt](https://github.com/simh/simh/files/2130364/foo.ini.txt)

Failing log file:
[fail.log](https://github.com/simh/simh/files/2130362/fail.log)

Passing log file:
[pass.log](https://github.com/simh/simh/files/2130363/pass.log)

MSCP disk image file:
[mscp.zip](https://github.com/simh/simh/files/2130370/mscp.zip)

**Comment by markpizz** [comment]
Thanks for this test.

This problem clearly is related to the change you mentioned.

What is going on here is that the disk is now being autosized when it previously wasn't.

You can work around this problem by adding 
```
set rq0 noautosize
```
before you attach the mscp.dsk image to rq0.

This is yet another test case of the other problems that were introduced by that change.  I will fix.

Meanwhile, part of the fix relates to logic which probes into the disk being attached looking for know file system structures which can be interpreted to determine how big the disk structures expect the disk to be.  What is the file system structure of this mscp.dsk?  It looks like it might be something completely new or possibly RT11.  If someone has info about how to walk the contents of an RT11 disk to see what it expects the size of the volume to be, that would be generally helpful.

Thanks.

- Mark

**Comment by AK6DN** [comment]
I reran the test on the failing commit (5a18d31) and on the most recent (4f61cd3) it adding the 'set rq0 noautosize' makes no difference. The failure symptom is the same.

It happens the filesystem on the disk is that of XXDP, which is a derivative of the DOS-11 filesystem. There are lots of documents here:  http://www.bitsavers.org/pdf/dec/pdp11/xxdp/   that pertain. This one is the most relevant:  AC-S866A-M0_CHQFSA0_XXDP+_File_Struct_Doc_Apr81.pdf

Unfortunately with this filesystem it is not easy to determine the size of the filesystem image without walking thru a number of the disk filesystem structures. It is certainly true however that the filesystem will be 32MB at maximum, as it uses fixed 512B blocks and a 16bit block count.

That being said, I find it baffling why SIMH would care, or need to know, what the filesystem is. In many cases (like a data disk) there may be no filesystem at all. It seems to me that needing/trying to figure out the filesystem on a disk is really none of SIMH's business at all. It should NOT be going there. Just my 2c.

**Comment by markpizz** [comment]
Oops. I misread which commit introduced the problem.  The problem you're reporting is new and unrelated to anything that's been mentioned elsewhere and completely unrelated to autosizing,

I forgot to thank you profusely for isolating this problem to a particular commit.

The problem commit was: PDP11, VAX: Add settable unit numbers for RQ drives.

The MSCP Get Unit Status implementation that worked with the VAX Console ROM didn't meet XXDP's expectations.  I've changed the implementation to meet the expectations of both.

Meanwhile, the file system detection strategy that exists is there to address the following concept:  

Prior to the 4.x simh code all simh disks started out with zero size and only 'some' disk container files would actually be the correct size for the disk being emulated.  'some' would be the cases where there was DEC-144 bad block information written to the last track of the disk.  When simh newly created a disk on a controller that had OS support for this last track bad block info, the user was prompted to populate the last track (with a default of NO).  Therefore any such disk would end up only having a size representing the furthest into the drive that some file system or user data had been written.  No harm with this approach as long as every time that disk image was used, the disk type (which has a specific maximum size) was precisely the same as it was when the disk was originally written.  The current simh code trys to be more accommodating when users attach a disk and several disk controllers which previously didn't attempt to autosize disks at attach time now do so.  Any disk image created by the new code will always be precisely the correct size for the disk type that the unit had when the attach that created the disk image without regard to the creation of any bad block information in the last track.  The problem arises when someone tries to attach a disk which was created with a prior simh version that hadn't been written in its entirety.  There is logic to attempt to locate a known file system type on the disk and the furthest extent in the disk that the file system would expect to write.  If found, this information is used while autosizing disks so that disks which haven't ever been written to the full container size can be properly sized.

The disk image you provided here has 65535 512 byte sectors and as such is distinctly smaller than the RD54 disk you're attaching it to.  Since you've said that the maximum size of an XXDP disk is 32MB, you're already at that limit and autosizing won't cause anything unexpected.

**Comment by AK6DN** [comment]
I updated to the latest commit 8c0439f on 6/24/2018 and reran my XXDP MSCP test; it is now passing as before in commit 8bec55b and earlier. So I consider the problem resolved at this point.

It did take a while to narrow it down to the commit that introduced the issue. I hadn't updated my simh since Mar 2018, and when the latest Jun2018 then failed, I basically resorted to doing a binary search on the commits between Mar and Jun to narrow down the pass/fail line to the specific commit.

Thanks for the quick fix, and the explanation above re: the updated disk sizing algorithm.

Don

**Comment by markpizz** [comment]
> It did take a while to narrow it down to the commit that introduced the issue. I hadn't updated my simh since Mar 2018, and when the latest Jun2018 then failed, I basically resorted to doing a binary search on the commits between Mar and Jun to narrow down the pass/fail line to the specific commit.

Since you've been that industrious to walk around the range of commit history like that, I hope you were using a local git client to do it.  

If so, you've essentially reinvented a feature already built into git.  Check out "git bisect".  If you use "git bisect" next time, it will probably make the bookkeeping while doing that less tedious.

If not, you may want to explore using git to pickup the changes to the repo over time...

**Comment by AK6DN** [comment]
Yes, I am using a local git client on my Windows 7 box under CYGWIN. I just hadn't updated my SIMH install for a couple of months, until I decided to do an update last night and found the issue.

When I do a 'man git bisect' I see: "Use binary search to find the commit that introduced a bug"  which is exactly what I did, so yes I am going to figure out how to use this git feature for the future ...

Thanks,
Don
