### ISSUE TITLE
SHOW DEVICES includes disabled devices

### ISSUE THREAD

**Issue by mike632t** [simh/simh#613]
A minor issue but the Simh users guide (para 3.11) says that `show devices` shouldn't list disabled devices which is true for the VAX simulator but the both the PDP-8 and PDP-11 simulators behave differently (not tested any others yet)...  
```
$ ./pdp11 

PDP-11 simulator V4.0-0 Current        git commit id: f5488239
sim> sho dev
PDP-11 simulator configuration

CPU	11/73, NOCIS, autoconfiguration enabled, idle disabled
SYSTEM
RHA	address=17776700-17776753, vector=254, BR5
RHB	disabled
RHC	disabled
CLK	60Hz, address=17777546-17777547, vector=100, BR6
PCLK	disabled
PTR	address=17777550-17777553, vector=70, BR4
PTP	address=17777554-17777557, vector=74, BR4
TTI	address=17777560-17777563, vector=60, BR4
TTO	address=17777564-17777567, vector=64, BR4
TDC	disabled
CR	disabled
LPT	address=17777514-17777517, vector=200, BR4
DLI	disabled
DLO	disabled
DCI	disabled
DCO	disabled
DZ	address=17760100-17760137*, vector=300-334*, BR5, lines=16
VH	disabled
RC	disabled
RF	disabled
RK	address=17777400-17777417, vector=220, BR5, 8 units
RL	RLV12, address=17774400-17774411, vector=160, BR5, 4 units
HK	address=17777440-17777477, vector=210, BR5, 8 units
RX	address=17777170-17777173, vector=264, BR5, 2 units
RY	disabled
RP	Massbus adapter 0 (RHA), 8 units
RS	disabled
RQ	address=17772150-17772153, no vector, BR5, RQDX3, 4 units
RQB	disabled
RQC	disabled
RQD	disabled
TC	disabled
TM	address=17772520-17772533, vector=224, BR5, 8 units
TS	disabled
TQ	TK50 (94MB), address=17774500-17774503, no vector, BR5, 4 units
TU	disabled
TA	disabled
XQ	address=17774440-17774457, no vector, BR5, MAC=08:00:2B:85:60:16
	type=DELQA-T, mode=DELQA, polling=disabled, sanity=OFF
	throttle=disabled, DEQNALock=OFF, leds=(ON,ON,ON)
XQB	disabled
XU	disabled
XUB	disabled
KG	disabled
DMC	disabled
DUP	disabled
DPV	disabled
KDP	disabled
KE	disabled
sim> 
```
```
$ ./pdp8 

PDP-8 simulator V4.0-0 Current        git commit id: f5488239
sim> sho dev
PDP-8 simulator configuration

CPU	idle disabled
TSC	disabled
FPP	disabled
CLK	60Hz, devno=13
PTR	devno=01
PTP	devno=02
TTI	devno=03
TTO	devno=04
TTIX	lines=4, devno=40,42,44,46
TTOX	devno=41,43,45,47, 4 units
LPT	devno=66
RK	devno=74, 4 units
RL	disabled
RX	RX8E, devno=75, 2 units
DF	devno=60-62
RF	disabled
DT	devno=76-77, 8 units
TD	disabled
MT	devno=70-72, 8 units
CT	disabled
sim>
```

I usually display the output of `show devices` as part of my configuration script  so I can check I've mounted the right disks and see which port I'm using for the DZ etc, but with all the disabled devices being shown it is rather a long list and the information I want may have scrolled off the top of the screen.

I've discovered that I can work around this problem using `show rq` or `show dz`, but only for devices I explicitly include.

Thanks 

Mike T.

**Comment by markpizz** [comment]
Mike,

SHOW DEVICES lists disabled devices on all simulators (VAX included).  The PDP11 simulator has the largest number of devices, so scrolling off the top of the screen is therefore more likely, and even more likely when many/most devices are actually enabled since the output of an enabled device is more than
the one line of output which is produced for each disabled device.

I'm not sure what simh users guide you're looking at, paragraph 3.11 in the most up to date documentation doesn't mention disabled devices.  This documentation is available in the source repository at doc/simh_doc.doc.  Ahh.. I see the mention of disabled in section 3.13 of the latest user's guide.  This line says: "When a unit is disabled, it will not be displayed by SHOW DEVICE."  A device which is disabled doesn't list anything about any of its units in the output of SHOW DEVICE.  If a device is enabled, then device units which are disabled are not listed in the output of SHOW <devname>.  For example:
```
sim> SHOW RQ
RQ      address=20001468-2000146B, no vector, BR4, RQDX3, 4 units
  RQ0   159MB, not attached, write enabled
        RD54, UNIT=0, autosize
        AUTO format
  RQ1   159MB, not attached, write enabled
        RD54, UNIT=1, autosize
        AUTO format
  RQ2   159MB, not attached, write enabled
        RD54, UNIT=2, autosize
        AUTO format
  RQ3   409KB, not attached, write enabled
        RX50, UNIT=3, autosize
        AUTO format
sim> SET RQ2 disable
sim> SHOW RQ
RQ      address=20001468-2000146B, no vector, BR4, RQDX3, 4 units
  RQ0   159MB, not attached, write enabled
        RD54, UNIT=0, autosize
        AUTO format
  RQ1   159MB, not attached, write enabled
        RD54, UNIT=1, autosize
        AUTO format
  RQ3   409KB, not attached, write enabled
        RX50, UNIT=3, autosize
        AUTO format
sim>
```
This is merely how things have always worked.  If you look at the output of your configuration script WITHOUT any SHOW DEVICE command, it will be quite clear which device and units have been attached to what things.  The output from the SHOW DEVICE command will more than likely cause this information to have scrolled off the screen before you get a chance to read it.

**Comment by mike632t** [comment]
The version I have was down downloaded and converted to PDF at some point in the past and is titled SimH User Guide v3.10-0 23 May 18 and is Copyright (c) 1993-2017, Robert M Supnik - for some reason I can't up load a copy.   
Unfortunately I can't read .doc files directly so I have not been able to compare it to the current version on github.  However, are the document version numbers tied to the the SimH major version numbers?

Mike T.

**Comment by mike632t** [comment]
After a bit more research it appears that SimH version 3 is still being updated in addition to this version on github (which was a bit confusing until I realised what was going on).  In both cases in both the PDP and VAX simulations `show devices` displays the disabled devices, so I assume the correct thing to do would be to propose a correction to User Guide?

**Comment by markpizz** [comment]
The user guide is correct.  

When a unit (not device) is disabled, the unit configuration settings are not displayed (see my example).

**Comment by markpizz** [comment]
By the way, a portable way to read a .doc (MSWord) file is to stick it up on your Google Drive and use a browser to view the file at https://drive.google.com.

**Comment by mike632t** [comment]
Going through your example you have used `SHOW <devicename>`  which makes sense now I think I understand what is going on.  

Thanks you for the tip about using Google Drive - very useful for a Linux user!
