### ISSUE TITLE
PDP8 on GNU/Linux (aarch64): 100% Cpu usage on idle

### ISSUE THREAD

**Issue by vanfanel** [simh/simh#629]
Hi there,

I am new to PDP8 simulation, and I am enjoying the PDP8 simulator that's part of simh. However, I am getting a 100% CPU usage on the core the simulation is running on, even on idle: as soon as PDP8 is executed (no Xorg involved, it's a tty-only system) it uses 100% CPU.
What's going on?

Thanks

**Comment by vanfanel** [comment]
Sorry for not providing all that info. It seemed to me that it would be a somehow intentional behaviour so there could be some parameter to set CPU usage or something like that.

1. "sim> SHOW VERSION" says 
```

sim> SHOW VERSION
PDP-8 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 6.3.0 20170516
        Simulator Compiled as C (Release Build) on Oct  7 2018 at 19:42:42
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux raspberrypi 4.14.72-v8+ #6 SMP PREEMPT Wed Oct 3 18:34:09 CEST 2018 aarch64 GNU/Linux
        git commit id: c60c151b
        git commit time: 2018-10-05T08:11:00-0700

```
2 - The building process for the PDP8 simulator (the one using 100% CPU) was like this:

```
pi@raspberrypi:~/src/simh$ make pdp8
lib paths are: /lib/ /lib/aarch64-linux-gnu/ /usr/lib/ /usr/lib/aarch64-linux-gnu/ /usr/local/lib/
include paths are:  /usr/lib/gcc/aarch64-linux-gnu/6/include /usr/local/include /usr/lib/gcc/aarch64-linux-gnu/6/include-fixed /usr/include/aarch64-linux-gnu /usr/include
using libm: /usr/lib/aarch64-linux-gnu/libm.so
using librt: /usr/lib/aarch64-linux-gnu/librt.so
using libpthread: /usr/lib/aarch64-linux-gnu/libpthread.so /usr/include/pthread.h
using regex: /usr/include/regex.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/aarch64-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/aarch64-linux-gnu/libpng.so /usr/include/png.h
using mman: /usr/include/aarch64-linux-gnu/sys/mman.h
***
*** pdp8 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 6.3.0.
*** - Per simulator tests will be run.
***
*** git commit id is c60c151b4e7573d745369162efb259ceaa30e7a0.
*** git commit time is 2018-10-05T08:11:00-0700.
***
mkdir -p BIN
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=c60c151b4e7573d745369162efb259ceaa30e7a0 -DSIM_GIT_COMMIT_TIME=2018-10-05T08:11:00-0700  -DSIM_COMPILER="GCC Version: 6.3.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_REGEX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP8/pdp8_cpu.c PDP8/pdp8_clk.c PDP8/pdp8_df.c PDP8/pdp8_dt.c PDP8/pdp8_lp.c PDP8/pdp8_mt.c PDP8/pdp8_pt.c PDP8/pdp8_rf.c PDP8/pdp8_rk.c PDP8/pdp8_rx.c PDP8/pdp8_sys.c PDP8/pdp8_tt.c PDP8/pdp8_ttx.c PDP8/pdp8_rl.c PDP8/pdp8_tsc.c PDP8/pdp8_td.c PDP8/pdp8_ct.c PDP8/pdp8_fpp.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -I PDP8 -o BIN/pdp8 -lm -lrt -lpthread -ldl -lpng  

```

3- The simulator .ini file used. 

```
attach rk0 advent.rk05
boot rk0
exit
```

The advent.rk05 file can be found here:
http://www.rickmurphy.net/advent/advent.rk05
Note that 100% usage happens only when "boot rk0" is present (in other words, when actual simulation starts).

I think that's all you requested. Hope it helps!

**Comment by jguillaumes** [comment]
Please add
``` 
set cpu idle
```
to the ini file and check it again. Please take into account the simulator needs a little bit of time to detect the guest system is in an idle loop so the CPU usage will keep itself high for a while.

```
top - 16:18:31 up 33 min,  1 user,  load average: 0,43, 0,54, 0,93
Tasks: 136 total,   1 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5,8 us,  3,4 sy,  0,0 ni, 90,7 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem :  3065880 total,   813092 free,   429572 used,  1823216 buff/cache
KiB Swap:  3145724 total,  3145672 free,       52 used.  2427764 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                          
 22199 jguilla+  20   0  643080  36752  27568 S  4,3  1,2   0:03.71 mate-terminal                                    
 21999 root      20   0  427884  76708  35308 S  3,7  2,5   0:04.35 Xorg                                             
 23341 jguilla+  20   0   17096   3224   2604 S  1,0  0,1   0:20.77 pdp8                                             
 22133 jguilla+  20   0  492200  26764  20560 S  0,7  0,9   0:00.21 wnck-applet                                      
   256 root      20   0  134212  10856   9468 S  0,3  0,4   0:01.50 vmtoolsd                                         
 17712 root      20   0  563220  83668  39032 S  0,3  2,7   0:03.09 dockerd                                          
```

**Comment by vanfanel** [comment]
@jguillaumes : Thanks. I had already tried that. It's true that CPU usage drops after a while, but for example, when running Adventure, CPU usage seems to be always 100%. 
I have read that simh uses all idle CPU, so if my host system does not have any services consuming significant CPU time, then it may be taking all CPU for itself. Am I right?
I have tried several "set cpu idle" variations too, but no luck. When I run a program on the pdp8, CPU usage is always 100%.

**Comment by markpizz** [comment]
Not being a PDP8 user, I have no idea how to get from the ADVENT.FT to a running program on that system.  If you showed how you got there, I could look under the covers and describe why what you're seeing behaves that way.

Without having actually going that far, it is useful to explain/understand generically how idling works in simh simulators.  Idling depends on having the simulator, be able to detect when the simulated system is in a useful instruction execution state vs when it is merely waiting for user input.  Some systems (CPU architectures) have a WAIT instruction which makes idling quite easy since an instruction like this lets the CPU wait until an interrupt occurs.  Most systems don't have such an instruction, or even with those that do, the software running on the system may not actually use such an instruction.   These other systems usually have some sort of 'idle loop' that is executed while waiting for some sort of input to the system.  The simulator for these systems can explicitly look for the one (or many) instruction patterns that indicate that the system is idling, and it can then invoke the simh framework API (sim_idle()) to let the simulator give up the host system CPU when this is happening.  As I mentioned, there may be more than one different execution pattern that indicate the system is merely waiting for input.  The PDP8 simulator currently has a single idle detection pattern that is recognized.  This is readily detected when the example you provided is sitting at the '.' prompt.  From your description, it would seem that what ever facility is used in the ADVENT program to read from the console executes a different pattern than the one the OS uses while at the '.' prompt.  The CPU instruction history facility can be used to observe the simulator's state while in other places where it is actually idling, and knowing these other idle patterns, the simulator could be enhanced to also idle at these times.

If you:
```
    sim> SET CPU HISTORY=200
    sim> GO
    #start your program running and let it run
    # to the point where it is waiting for input
    ^E
    sim> SHOW HISTORY
```
and this 'idle' instruction pattern will be revealed.  Knowing that, the code in pdp8_cpu.c could be enhanced to also detect this particular pattern.  Different programs (possibly written in different languages: BASIC, FORTRAN, etc). may have different patterns that could be part of the runtime support provided by those languages.

**Comment by tangentsoft** [comment]
> Not being a PDP8 user, I have no idea how to get from the ADVENT.FT to a running program

The disk image has runnable binaries on it already. The safest way to run it is:

    .R FRTS
    *ADVENT<ESC>

where `.` and `*` are prompt characters and `<ESC>` is a literal Escape keypress. You don't need to press `Enter`, but it will work if you do.

On pressing `<ESC>`, FRTS will output a `$` character, then Adventure will start.

Another way to start it is with `EXE ADVENT.LD` at the OS/8 `.` prompt, but if you forget the `.LD` part, you'll [wreck your binary and have to recover](https://tangentsoft.com/pidp8i/wiki?name=Adventure).

When idle, OS/8 Adventure appears to be using this pattern to create a delay loop:

    ISZ 36        / increment zero-page location 36 unless zero, else skip next
    JMP .-1       / go to previous instruction

The amount of delay is therefore proportional to the initial value stored in location 36 and the IPS rate of the processor. I'm not sure the simulator should go into idle mode when that happens: it's trying to burn time, on purpose.

Incidentally, if for some reason you had to recompile Adventure, you'd say `EXE COMPIL` to run [the compilation batch file](http://www.rickmurphy.net/advent/COMPIL.BI) that ships on this same disk, then `EXE LOAD` to link the modules to create the `ADVENT.LD` binary.

**Comment by markpizz** [comment]
> When idle, OS/8 Adventure appears to be using this pattern to create a delay loop:
> 
>     ISZ 36        / increment zero-page location 36 unless zero, else skip next
>     JMP .-1       / go to previous instruction
> 
> The amount of delay is therefore proportional to the initial value stored in location 36 and the IPS rate of the processor. I'm not sure the simulator should go into idle mode when that happens: it's trying to burn time, on purpose.

Given this generic idling based on this pattern really isn't a great idea.  Therefore , if a user (@vanfanel) wants to avoid 100% host system CPU saturation, throttling would be the way to go.  For example:
```
   sim> SET THROTTLE 300K
```

**Comment by markpizz** [comment]
Lacking further comments on this, it seems that the problem that was originally reported has been satisfactorily addressed.
