### ISSUE TITLE
Needed feature.

### ISSUE THREAD

**Issue by Zibri** [simh/simh#651]
Since SIMH is able to read and write ODS2 Files 11 images,
there is a feture which is really missing:
being able to share a directory and let it be seen as an HDD to SIMH guests.

Alternatively, a utility to create a Files11 image from a direcory (or like tar utility from any file) would be greatly apreciated because when emulating very old machines with very old OS (let's say VAX/VMS 5 or 4) you have almost no way to transfer files efficiently to the guest.

**Comment by markpizz** [comment]
Feel free to undertake the project you described.

Alternatively, you could connect the simulated system you mentioned with a tcp/ip network stack and you could then get files in and out of the simulated system somewhat easily.

If you are dead set on direction media exchange, you might be able to find (or write) a simh format tape image which could be written that contained the files you are interested in accessing.

**Comment by Zibri** [comment]
well at the moment the "raw" method to pass data is this:
create a test file on linux like:
for b in {0..255};do for a in {0..255};do printf "\x$(printf %x $a)";done;done >64k.bin

Then in SIMH I do:

sim> set rq3 cdrom
sim> attach rq3 -f raw 64k.bin
sim> cont

Then on VAX/VMS 5.5 I do:

$ mount/foreign dua3:
%MOUNT-I-MOUNTED,              mounted on _DUA3:
$ copy dua3: 64k.bin

and the binary file matches the original. (ON VMS some more modifications are needed)

I know of mksimtape utility, but if I do the same test, some bytes are added at the start.

**Comment by markpizz** [comment]
The mksimtape utility does add the simh tape record structure to the resulting output file. But it doesn't add any data at the beginning of the resulting file on the tape image.  It will pad the last block of the file with 0 bytes.  Tape blocks default to 10240 bytes, but can be changed to a user desired value by appending :blocksize to the filename.  Since the resulting output of mksimtape is a simh tape image you've got to read the file within a simulator from a tape device:
```
    $ mount/foreign mua0:/blocksize=10240
    %MOUNT-I-MOUNTED, mounted on _MUA0:
    $ copy mua0: filename.bin
```

It would seem reasonable to add an option to the mksimtape.c utility that simply wrote a shorter tape block for the last tape block of the file.  You would then not need to remove any extra trailing 0 bytes.

**Comment by Zibri** [comment]
It would be nice a utility "mksimdisk" to create files11 disk structure.

**Comment by markpizz** [comment]
> It would be nice a utility "mksimdisk" to create files11 disk structure.

Every DEC operating system which can use a disk with a files11 disk structure comes with a utility that can create a files11 disk structure.  That utility is either directly called or embedded under the operating system's INIT command.  All of these operating systems can be run under one of the available simh simulators and can then be used to put a files11 disk structure on a simh disk container file with is attached to any of the many different disk types that are emulated.  

What problem would an external utility that could create a files11 disk structure solve that isn't already readily solved by the existing "utilities"?

**Comment by Zibri** [comment]
The same that is accomplished by mksimtape:The ability to create from
scratch an emulator disk file with files from other sources from the
host system.

**Comment by markpizz** [comment]
Once again, feel free to write such a utility yourself.

Alternatively, you could use a simulator with a network device to transfer files from your host system into the simulated system and on to a simulated disk.  You might do this directly into the target system you ultimately desire to move the files to, OR you could easily have a 'transfer' system with the most modern VMS version (V7.3) and a TCP/IP package (UCX or MultiNet) and once you've got the files you want on a target simulated disk, you can move that simulated disk to the target simulated system.

**Comment by Zibri** [comment]
Yes I know.. but when I had this problem, the emulator guest OS (VMS 5.5) didn't have networking and it's way easier and faster to create a disk on the host system and then add it to the emulator than anything else. This ora using (like in any other emulator or vm) the possibility to make a host directory 
 on the host appear as a disk to the guest.

**Comment by markpizz** [comment]
Given how easy and fast you think it is to create a simulated disk on the host OR to share a host directory as a disk in the guest system, feel free to undertake either or both as projects.   You will, at least, learn many things along the way.

When you're done we'll be glad to incorporate the results into the simh codebase. 

You might want to start by making the previously suggested small modification to mksimtape.c so that it doesn't pad the last block of a file with 0's.

**Comment by markpizz** [comment]
This issue is being closed now.

When you're done creating the functionality you describe, please create another issue (or pull request) to actually get that functionality into the codebase.
