### ISSUE TITLE
Can SCSI pass through device (/dev/sg2) be attached on linux host? 

### ISSUE THREAD

**Issue by dongce** [simh/simh#658]
- #### Context

Dear SIMH developers. 

I am trying to use SCSI tape reader on SIMH Vax simulator. 

    SCSI Tape Reader :  Archive VIPER 2150S
    SIMH Host :  Linux (Fedora 29)
    SIMH Guest :  OpenVMS 6.2 
    SIMH Vax version : 4.0-Beta 
    Tape read/write program :  Custom program which use SCSI directly on OpenVMS. 

I have tried followings. But it does not works. 

    simh> attach rqc3 -f raw  /dev/sg2 
    and
    simh> attach rqc3 -f /dev/st0
     
 SCSI pass through is implemented on SIMH Simulator ? 
 If it does not, is there any plan to implement  SCSI pass thourgh? 
 Or whould you tell me staring point to implment SCSI pass through feature ? 

Thank you for reading this. 

- #### how you built the simulator or that you're using prebuilt binaries

 I build it myself.

**Comment by markpizz** [comment]
SCSI pass through would, in theory, be somewhat possible IF AND ONLY IF there were any existing simulators which actually implemented simulated SCSI devices.  Since there are no such simulators and no simulated SCSI interfaces, the idea is a non-starter.

There are explicit ways for some simulated disk devices to directly access physical disk devices existing in the PDP11 and VAX simulators for the MSCP devices.  In theory, it might be possible to extend the simulated tape functionality to access some subset of physical tape devices, but that would be a significant development project.

Your suggestion about SCSI pass through is a solution to a problem which you haven't actually stated.  Are you trying to import data from one (or more) tapes?
Are you trying to export data to another system?
Are you trying to model legacy tape backup paradigm?

Answer these questions and we can suggest reasonable solutions.

**Comment by dongce** [comment]
I am trying to export data to another system.

That system have tape reader only. 
It does not have network and cdrom. 

Tape is made by custom program (tpf).
Tpf support only scsi tape read/writer.  
So scsi emulation device or pass through is needed.
 
Thank you.

**Comment by markpizz** [comment]
If you're suggesting that this tpf program runs on VMS (under a VAX simulator) that would be hard to understand given that there are no SCSI tape devices on any simh simulator.  Therefore you aren't actually exporting data from a simh simulator.  If you're exporting data from some existing non simh system to a tape, it is hard to imagine that any VAX system that had an attached SCSI tape, actually operated the tape with other than normal tape operations rather than explicit SCSI commands.  What type of tape driver was being written to?  How is the tpf program invoked and how is the drive you are writing to specified?

**Comment by markpizz** [comment]
How/where did you get the device name MSA500?

You are exporting data here for what purpose?  Where/how are you expecting to use the exported data?

**Comment by dongce** [comment]
Actually i am prepairing to migrate from Charon-VAX to SIMH.  
Charon-VAX hard lock key are going to broken. 
MSA500 come from charon-vax. 

Exported data is install program for other system. 
About one hundread file in QIC 150 tape. 

If you do not have any idea of tape format, please close this thread. 

Thank you.

**Comment by markpizz** [comment]
QIC 150 tapes were not real candidates to be ANSI labeled tapes.  QIC tapes tended to have fixed record sizes, not the variable record size that a traditional labeled tape would have.

To migrate the from Charon, to a simh VAX, I suspect it might be much easier to merely move the disk container files, or shutdown the Charon system and then copy the disk container files elsewhere and attach them to a simh simulator and merely boot the system.  The device names may have changed, but most things should be workable pretty easily.

**Comment by markpizz** [comment]
Lacking any further comments on this issue, it is being closed now.

Further comments can reopen this issue or create a new one.
