### ISSUE TITLE
PDP11: possible issue in ASHC emulation

### ISSUE THREAD

**Issue by shattered** [simh/simh#673]
https://www.computer.org/csdl/mags/co/1978/05/01646958.pdf "Using Emulation to Verify Formal Architechture Descriptions" (May 1978) points out that

>  An example of this is the ASHC (arithmetic shift combined) instruction. The processor manual states that the V condition code bit is set if the sign bit changes during the shift. The writer of the ISP
description interpreted this to mean that the V bit should be set if the sign of the final result is dif-
 ferent from the sign of the initial value. Actually,  the V bit should be set if the sign bit changes at
 any time during the shift operation (to indicate overflow).

**Comment by archivisth** [comment]
The simulator is correct. It uses a more efficient technique than the original one-bit-at-a-time algorithm in the J11 microcode, but the end result is the same.

The simulator compares all the bits shifted out and lost with the final sign. If they are not the same, then the sign changed sometime during the shift, and V is set. Otherwise, it is cleared. In more detail,

final sign = 0: if lost bits = all 0s, then V=0; otherwise, V=1.
final sign = 1: if lost bits = all 1s, then V=0; otherwise, V=1.

The ISP description is irrelevant. The simulator was written from the J11 microcode.
