### ISSUE TITLE
Shut down simulator from the outside with a signal

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#681]
The PiDP-8/I project runs the PDP8 simulator in the background and needs a way to shut it down cleanly. We've tried sending it signals, but SIGINT, SIGTERM, and SIGHUP all cause a call to `int_handler`, which basically does the same thing Ctrl-E does while the simulator runs. That leaves the simulator stuck at a `sim>` prompt in the background, which isn't much use to us.

That leaves us with a few ideas as workarounds:

1. Send `SIGKILL` instead, which isn't nice, but it is effective. The problem with this option is that unflushed data could be lost on opened devices.

2. This request, where I try to convince you to bind `SIGTERM` to a handler that just calls `exit_cmd()`, which should shut the simulator down gracefully. That would leave `SIGINT` and `SIGHUP` with the current behavior, so there's still a way to cause that from the outside.

A non-solution is the remote console feature, which doesn't allow an `EXIT` command. Master mode is no solution because we don't want the simulator console redirected to telnet: it needs to go out to the controlling process's terminal in the normal use case. Even if master mode would work, we'd want this bound to localhost only, which doesn't appear to be a current option.

Obviously we could patch `scp.c` to do #2 ourselves, but since we can't see a good reason to keep this new feature to ourselves, we're asking for you to do this upstream from us so others can benefit. Surely there must be other users of SIMH that could use this feature as well, the PiDP-11 project if nothing else.

Thanks!

**Comment by larsbrinkhoff** [comment]
Some time ago, I suggested the possibility of having an external signal raise a power fail interrupt:

http://mailman.trailing-edge.com/pipermail/simh/2018-September/018330.html

@markpizz replied:
> Currently SIGINT and SIGTERM both will bring a simulator to the sim> prompt (or the next input when running in the context of a simh command file).  Code in that command file can readily manipulate details of the simulator state.  These manipulations might set the simulator internal variables to trigger a Power fail interrupt when simulation execution continues

**Comment by markpizz** [comment]
The solution is already present.  Before the BOOT command in your simulator, you should have the following commands:
```
   sim> SET ON
   sim> ON SIGINT EXIT
   sim> BOOT
```

**Comment by markpizz** [comment]
The 3b2 simulator just recently implemented device specific code in that the simulated OS interprets as an OS power off/shutdown signal.  It leverages this functionality and is triggered by a SIGINT.

See: #680

**Comment by tangentsoft** [comment]
>    sim> ON SIGINT EXIT

It only works if I manually type those commands in at the SCP prompt, not when I put them into a boot script. If I put the commands into a boot script, sending `SIGINT` from the outside drops me back to the `sim>` prompt, it doesn't exit. This is with the SIMH code as of a few days ago — 2f0db744 — and with all PiDP-8/I extensions disabled.

At the resulting `sim>` prompt, if I ask it to tell me `show on`, it claims "On Processing for input commands is disabled."  If I then manually type your commands at that prompt and send `SIGINT` again, it does exit, but only after an Enter keypress.

Examination of all of this code shows that this feature is about input commands to SCP and the script processor. I want this to happen while the simulator is running.

The relevant help text confirms that this feature is unsuitable to my purpose:

> A special ON trap is available to describe action(s) to be taken
> when CONTROL_C (aka SIGINT) occurs during the execution of
> simh commands and/or command procedures.

The fact that this is all tied up with Control-C handling, and that that has to be handled specially while the simulator runs is also part of this: it's no good reassigning Control-C handling to the simulator just to make this work.

I'm back to asking for this to be handled on `SIGTERM`, which is a more appropriate signal anyway and doesn't mess up the existing SIGINT handling features.

**Comment by markpizz** [comment]
OK, I forgot about the Control-C handling.

Meanwhile, why doesn't:
```
BOOT ddd
EXIT
```
work?

**Comment by rcornwell** [comment]
How about having SIGTERM call a simulator defined routine that could generate the correct flags for a power failure. Then add in "on sigterm save fail.sav" to save the state. The on state would be triggered on the simulator leaving sim_instr with the correct error code. If the routine was not defined the behavior could be to just return the error code from the next call to sim_process_event. This would allow the simulator to cleanly shutdown when the host system rebooted. Then with mods to the .ini file the system could be automatically restored from the save state if the file existed.

**Comment by markpizz** [comment]
What you described is already doable with a slightly complicated script.

The user of a simulator that they've configured explicitly to running in the background won't ever be directly interacting with the process that is running (i.e. via Control-E).  Therefore, in that case, any return to sim> prompt must have occurred due to either a fatal error (not likely with a stable configuration), or the receipt of a signal (SIGINT, SIGTERM or SIGHUP) which all are caught and produce the same behavior as Control-E (on some systems the Control-E (WRU) is actually setup as the SIGINT character).  In any case, a return from the BOOT command (or whatever command started execution) will indicate that this should happen.  You can get specific and distinguish between the fatal error case with configuration that looks like this:
```
    SET ON
    ON STOP GOTO save_stuff
    ON ERROR GOTO fatal_error
    IF NOT EXIST simstate.saved GOTO cold_boot
:warm_boot
    RESTORE simstate.saved
    DELETE simstate.saved
    CONTINUE
    # This EXIT should never be executed since all error reasons do something else
    EXIT
:cold_boot
    BOOT ddd
    # This EXIT should never be executed since all error reasons do something else
    EXIT
:save_stuff
    SAVE simstate.saved
    EXIT
:fatal_error
    ECHO Other Error Happened: %STATUS% - %TSTATUS%
    EXIT
```
The idea of actually running a complete shutdown of the simulator is somewhat less reliable since, most of the older systems I worked with that actually had a natural shutdown procedure took an indeterminate amount of time to achieve the shutdown which almost always would be too long for the host system's shutdown to wait.  The above logic to save state will essentially always happen quickly enough to operate within normal timing of the host system's shutdown.

I've had something similar to the above logic running a VAX simulator for about 14 years.

**Comment by rcornwell** [comment]
SIGTERM is not the same as SIGINT. Perhaps the simpler option is to add in a new SCPE_... (ie SCPE_PWR or SCPE_TERM). When SIGTERM is delivered sim_instr via sim_process_event which can catch it if the hardware supported it. Once SIGTERM is detected it should NOT be caught again. Windows also has similar flag to SIGTERM when windows is shutting down is sent. Typical Unix shutdown sequence is to send two SIGTERMs (about 15 seconds apart) to a process followed by SIGKILL.

The only simulator that I have that supports power fail is the PDP10. Under ITS it would probably BUGHALT, on TOPS10, it saves the machine state and goes into a 200ms loop to wait for power to die. On machines that handled power fail, an interrupt could be generated and then return SCPE_TERM when the machine halted, or when it detected the IDLE out. When SCP detects an exit from sim_instr with SCPE_TERM it can handle any ON conditions, then exit. This could also be used by machines that support a power off function which would return SCPE_TERM to simulate a power off (3B2, some VAX).

**Comment by tangentsoft** [comment]
> Meanwhile, why doesn't:
> 
> ```
> BOOT ddd
> EXIT
> ```
> work?

Um...you tell me? :)

Let's get concrete. Here's the SIMH boot script I'm trying to use:

<pre>
reset
set cpu 32k
set cpu noidle
set df disabled
set nothrottle
deposit int-throttle THROT_DELAY 3

set tti 7b

set ON
on SIGINT EXIT

att rk0 v3d.rk05
boot rk0
exit
</pre>

The referenced `v3d.rk05` image isn't special. You can use [one of these](https://tangentsoft.com/pidp8i/#os8) if you don't have anything else handy.

With the latest tip-of-master (cdfb7c08) saying `BIN/pdp8 run.script`, then opening another terminal and saying `pkill -INT pdp8` drops the simulator to the `sim>` prompt as I've been saying. The rest of the symptoms remain as documented above: no "on" handlers registered, no effect of second SIGINT, a manual registration of SIGINT handler works but requires manual Enter to actually kill the simulator.

As @rcornwell says, `SIGINT` and `SIGTERM` are very different things. Why are you resisting the idea that they have different handlers in SIMH?

Also, all of the comments about graceful shutdown of complicated OSes doesn't apply in this case. The PDP-8 was a core memory machine, so most OSes were shut down by just stopping the CPU then cutting power. All I want is for any cached blocks to hit the disk before the simulator stops, thus ruling out `SIGKILL`.

**Comment by rcornwell** [comment]
On Unix/Linux. SIGHUP is signaled when the console connection gets disconnected. It means hang up. When used with daemons it typically means reload yourself. Sighup can be blocked with "stty nohup". Not sure what SIGHUP should be configured as in SCP. SIGINT is sent my ^C (or in SimH case WRU). It indicates interrupt. SIGTERM is sent to cause a process to shutdown. It is the soft version of SIGKILL.

My guess is that SIGHUP should just stop the sim and exit. SIGTERM should send SCPE_TERM or SCPE_PWR to be returned from sim_instr. SIGINT can continue to behave as it does. Since most sims don't do much with what sim_process() return of SIG_TERM or SIG_PWR will just return to the command prompt.

**Comment by tangentsoft** [comment]
Also, `SIGTERM` is the default signal: if you say "pkill pdp8", you want a process called "pdp8" to die, not prompt for a command. :)

**Comment by larsbrinkhoff** [comment]
My intended use case is to have some kind of automated script telling the guest operating system (i.e. ITS in my case) to shut down.  It could be done with an expect script logging in and running the shutdown command.  But it seems somewhat fragile, so my idea was to subvert the PDP-10 power fail condition for this.  For now, ITS will just do a BUG HALT which goes into exec DDT, the monitor debugger.  I'd like to add an option to instead start the shutdown sequence.

**Comment by markpizz** [comment]
> Also, all of the comments about graceful shutdown of complicated OSes doesn't apply in this case. The PDP-8 was a small core memory machine without an MMU, memory protection, or any of the other features that encourage a Unix-like "shutdown" mechanism. Typical PDP-8 OSes were shut down by just stopping the CPU then cutting power. All I want is for any cached blocks to hit the disk before the simulator stops, thus ruling out SIGKILL.

See below about isatty(0) and/or having an EXIT command after the BOOT command.  Additionally, since it was a system with core memory, would turning it back on let it continue execution where it left off?  If so, then the earlier suggestion about how to save state might be useful.  Either of these would allow SIGTERM to get the chance to achieve a clean exit.

> Also, SIGTERM is the default signal with kill(1), pkill(1), etc.: if you say "pkill pdp8", you want a process called "pdp8" to die, not prompt for a command. :)

If you really want to rip out the things from below, just send a SIGKILL.

If you want buffers flushed and a clean close, put an EXIT command immediately following your BOOT command, OR don't run the simulator in a process which will answer "yes" to the isatty(0) call.  That would be the only time a simulator that was started by running a command procedure would end up presenting a "sim>" prompt instead of exiting.

> My intended use case is to have some kind of automated script telling the guest operating system (i.e. ITS in my case) to shut down. It could be done with an expect script logging in and running the shutdown command. But it seems somewhat fragile, so my idea was to subvert the PDP-10 power fail condition for this. For now, ITS will just do a BUG HALT which goes into exec DDT, the monitor debugger. I'd like to add an option to instead start the shutdown sequence.

Any such script logic to handle, initiate and manage shutdown would naturally be present immediately following the BOOT command and could do anything from SENDing input commands to depositing values in appropriate registers that will trigger OS power fail mechanisms, etc...

Earlier @tangentsoft had said:
> Um...you tell me? :)
> 
> Let's get concrete. Here's the SIMH boot script I'm trying to use:
```
reset
set cpu 32k
set cpu noidle
set df disabled
set nothrottle
deposit int-throttle THROT_DELAY 3

set tti 7b

set ON
on SIGINT EXIT

att rk0 v3d.rk05
boot rk0
exit
```
Well, it was my error forgetting that SIGINT is for SIGINT delivered for scripts and not during simulator execution, so the "on SIGINT EXIT" trap would never be relevant.

Meanwhile, the "set ON" enabled generic traps for any command that returns with a non-zero status.  The generic trap for all trap values is "ON value RETURN", so when execution stopped and sim_instr() return SCPE_STOP, the STOP trap was taken and the do command procedure was exited without executing any more commands, and since you were running the simulator from a terminal session (rather than in the background), stdin was a tty so you got a prompt.  If you had "ON STOP EXIT" OR "ON ERROR EXIT" OR if you left out the "set ON" and the "ON SIGINT EXIT", then the "exit" following boot command would have been executed and your desires would have been met.

**Comment by tangentsoft** [comment]
> since it was a system with core memory, would turning it back on let it continue execution where it left off?

Not automatically, because the registers won't be preserved:

* The initial state for PC is 0000 and the CPU doesn't run until you hit START in the base PDP-8 hardware configuration
* PC could be reloaded by hand before the user pressed START with SR and the LOAD ADDRESS key, but how does the user know what PC was before the power failed?
* The key registers (AC, L, IF, DF, and MQ) are also lost, and if those aren't restored, restarting at PC will probably do the wrong thing anyway.

These were problems in the late 1960s, too, so there were add-on boards for PDP-8s (e.g. KP8-I for the PDP-8/I) that would somehow arrange to preserve such registers through a power cycle or would reload them with safe defaults on power-up.

Your SAVE and RESTORE scheme kinda sorta emulates this, and I think I will try to make use of it independently of this SIGTERM matter. It's been on my wishlist to have a core saving feature, at the least.

Strictly speaking, though, this scheme isn't historically accurate. The KP8-I — to take just one of several add-on boards produced for the PDP-8 series through the years — worked by detecting failing power, calling a previously registered interrupt handler to save the key registers to core, then call HLT. (This particular option board was only rated to buy the user 1ms to work in, enough time to run a few hundred instructions at most.) Then on startup, it would automatically re-START the CPU, executing whatever happened to be at address 00000, which would presumably also be user-written code to reload those registers, restoring the system to its pre-power-fail state.

I point this out not out of pedantry but because neither OS/8 nor TSS-8 — the two most popular OSes for the PDP-8 — required the KP8-I or compatible, so they didn't register such an interrupt handler or set up the power-on restore code at location 00000. Doing the SAVE and RESTORE trick with them is, strictly speaking, historically inaccurate.

This also wasn't the only scheme for handling power failure on PDP-8s, so even if we say that the PiDP-8/I emulates a PDP-8 with a power fail option installed, we're picking only one of several to emulate. Another common scheme was a card with a small number of hard-coded instructions (8-16 was common) that it would execute to restart the user application, losing the prior unsaved work but getting the machine back into operation without human intervention. Think if this mode as a very primitive AUTOEXEC.BAT. :)

> Either of these would allow SIGTERM to get the chance to achieve a clean exit.

I'll try them later, thanks. I'll close this issue if one of them ends up working for me.

I still think the default behavior of SIGTERM in SIMH is incorrect. It's fine for SIGINT to do what it does now, but SIGTERM should *always* cause the program to exit, without configuration, and irrespective of what `isatty(0)` returns. SIGKILL is a last resort, and should ideally never be needed.

> since you were running the simulator from a terminal session (rather than in the background), stdin was a tty so you got a prompt

That's actually true of our "background" operation as well, since we run the simulator under GNU screen so that the user can reattach to the simulator console at will: we start the simulator on boot, then later the user SSH's into the system and runs a command that reattaches them to the waiting `screen` session.

Because `screen` presents a `pty` to programs running under it, `isatty(0)` will always return true, even though the simulator is in the background, from the user's perspective. That makes my two-terminal test above a good model of the actual running configuration.

> ON STOP EXIT

That causes Ctrl-E to exit the simulator as well.

> ON ERROR EXIT

That causes `Invalid argument: ERROR`.

**Comment by rcornwell** [comment]
I would still like to see SIGTERM delivered to sim_instr as a reason return from sim_process_event. Since most simulators just exit on a unknown event, this should not break any existing sims. And would allow those machines that supported power fail function to handle it as they see fit. Also if this same error code was returned by sim_instr it would cause simh to exit (after doing any "on" processing). So that machines (like 3b2) which had the ability to power down to simulate this behavior.

**Comment by tangentsoft** [comment]
I have a partial solution based on the above `ON ERROR` script plus something like `pkill -INT pdp8 ; sleep 2 ; pkill -KILL pdp8`. The sleep gives the savestate step time to work.

For what it's worth, here's what the script looks like now:

<pre>
    SET ENV statefile=%HOME%/.pidp8i-@SHORTNAME@.state

    SET ON
    ON STOP SAVE %statefile%

    IF NOT EXIST %statefile% GOTO boot

:restore
    RESTORE %statefile%
    DELETE  %statefile%
    CONTINUE
    GOTO end

:boot
</pre>

1. The `statefile` has to be variable because there's more than one bootscript in the PiDP-8/I environment; we can't have them overwriting each others' state.

2. We don't want to EXIT on STOP. If the user hits Ctrl-E, just let them do their SCP-ish things. But if SIMH gets proper SIGTERM handling, this STOP handler should still be called! (Or it should give us ON TERM or similar so we can do the same thing in that case.)

3. I can't see that the ON ERROR handler helps, even with the recent change to make it not give an error. It actually caused me a bit of hassle because there's a way to make the ON ERROR handler trigger with STATUS == 00000000, "No error". But since it doesn't help, I stopped chasing it and ripped it out.

4. The jump to `:boot` is because this script is included bodily within each bootscript that needs it, just before the "att dddd ;  boot" bit.

5. The :end label is manually added to the outer script as the last line so that Ctrl-E CONT doesn't fall through to the `:boot` case.

I'm leaving this issue open because I still want proper SIGTERM handling in SIMH. If it's not going to happen, you can close it, Mark, and I'll just patch our simulator to do what I want.

**Comment by markpizz** [comment]
> The statefile has to be variable because there's more than one bootscript in the PiDP-8/I environment; we can't have them overwriting each others' state.

You can generate the state file's name from the filename of the bootscript that is running:
```
set env STATEFILE="%~pn0.state"
echo STATEFILE=%STATEFILE%
```
> We don't want to EXIT on STOP. If the user hits Ctrl-E, just let them do their SCP-ish things. But if SIMH gets proper SIGTERM handling, this STOP handler should still be called! (Or it should give us ON TERM or similar so we can do the same thing in that case.)

With the most recent code change, if a SIGTERM has occurred, any attempt to read from stdin will exit cleanly.  There is also an ON SIGTERM option which is available in either direct command input (from stdin) or within scripts.  The initial occurrence of SIGTERM will cause instruction execution to stop and possibly trigger a SIGTERM ON action sequence.  Instruction execution can be restarted (after any amount of scripted probes into the simulator state via DEPOSIT or SET commands).  If subsequent execution exits with a SCPE_STOP status the STOP will be translated to SIGTERM again.  A simulator shutting down would/should ultimately return from sim_instr() with a simulator specific exit status.

> I can't see that the ON ERROR handler helps, even with the recent change to make it not give an error. It actually caused me a bit of hassle because there's a way to make the ON ERROR handler trigger with STATUS == 00000000, "No error". But since it doesn't help, I stopped chasing it and ripped it out.

SCPE_OK (aka 0) is NOT an error.  Anything else is.  If you want to test for a particular status, then avoid using ON traps.  Meanwhile, simulator instruction execution won't ever return with a 0 status, so that probably won't be useful for this problem.  To test for a particular status:
```
# disable ON trapping
SET NOON
# run some command
some command
# test status;
IF (STATUS == 0) echo some command returned status 0
```

**Comment by rcornwell** [comment]
Does the simulator know when SIGTERM has been received or is it just a standard stop code?

**Comment by markpizz** [comment]
I'm trying to keep the very separate line between the details of activities on the host and platform specific details vs things which are in the guts of simulators.  If a simulator developer wants to provide some interface to their simulator which informs the simulator of the SIGTERM condition, then it is up to the simulator to solve that in what ever ways are appropriate and necessary within that simulator.  The scripting  language has several ways to react to the SIGTERM and take any appropriate action and convey that info into the into simulator.

**Comment by rcornwell** [comment]
How would I as a simulator developer know that a SIGTERM was received so that I could convert this into a power fail interrupt on my simulator?

**Comment by markpizz** [comment]
The script that is used to run the background process in which the simulator is running would start the simulator something like this:
```
SET ON
ON SIGTERM SET CPU SIGTERM_RECEIVED; CONTINUE
BOOT dev
```

The CPU device's MTAB routine that implements the SET SIGTERM_RECEIVED will change whatever in the CPU state that is needed to for that particular simulator so that a powerfail interrupt will be delivered when instruction execution resumes by the CONTINUE command.   The CPU's code is responsible to detect the completion of whatever the simulated OS is doing on a powerfail and  then to stop executing instructions and exit sim_instr() with a CPU specific STOP code (mentioned in CPU specific sim_stop_messages)  The running script should exit SCP when sim_instr() returns with this STOP code.

**Comment by rcornwell** [comment]
Sounds like much more work, then just returning SIGTERM from sim_process_event. This also means that you have to have checks that will handle how to save the state and shut som down after CPU has done it's thing.

**Comment by markpizz** [comment]
> Sounds like much more work, then just returning SIGTERM from sim_process_event. 

The SET ON and ON SIGTERM commands are hardly more work, just a different and more controllable and testable path to getting there.

> This also means that you have to have checks that will handle how to save the state and shut som down after CPU has done it's thing.

Depending on what you're system is doing, most common scenario is to just exit, but of course a simulator script can do anything it wants.  The state saving (via SCP commands) if that is what needs to be done, is no different either way.

**Comment by rcornwell** [comment]
Can you give an example of how I might use "set cpu power" to set the power fail flag, then when the CPU goes into an idle loop it would exit the sim_instr. How would I then save the state and exit. And how would I restart this again?

**Comment by markpizz** [comment]
How would you have done the same thing if sim_process_event() returned some status you happened to be looking for?

Not knowing anything about the particular details of how the system you are simulating works I can't spell out those details.  Something in sim_instr() knows that SET CPU POWER has been invoked, and it also knows what an CPU/simulatedOS specific idle loop is, when these conditions are both true, then sim_instr() exits with a simulator specific STOP code.  Your I7000 simulators have a number of different stop codes (and related messages) so just do that if the invoking script needs to know that this state has been reached.  Given the return status, the script can do what it wants...

As far as how to entangle the details of saving state with the simulated OS knowing that this happened, I never suggested that this would be useful to simulate.  

Auto Saving and Restoring state is an interaction between the simulator (its framework) and the host system.  My initial suggestions were completely about this and had absolutely nothing to do with anything about letting the simulated OS know anything had happened.  What I described can reasonably be done in response to a SIGTERM (without SIGTERM behaviors being extended), while I was concerned about the arbitrarily variable time a simulated OS might take to complete its activities and how those might not be quick enough to occur during a host system shutdown.  My model lets the simulator precisely be unaware that the host system rebooted and to automatically continue with whatever it happened to be doing when the host restarts.  The model I described is absolutely implemented in all the modern HyperVisors that manage virtual machines.  I haven't seen anything in modern HyperVisors that attempts to pass the host system shutting down fact into any running virtual machines.

**Comment by tangentsoft** [comment]
I do think this new ON SIGTERM mechanism will work for us. Thanks, @markpizz!
