### ISSUE TITLE
PDP10: Commit 45d8c90 introduces regression ... maybe?

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#713]
Commit 45d8c908ba1f153522d9575e373599f1ff19bae8 breaks the ITS build script.  The previous commit works.

The reason I say "maybe" in the title is that this only happens when run from the expect script.  It doesn't happen when typing the same input manually, or when a one-second delay is added to the script.

When run `expect -f expect.tcl`, I get this:

```
PDP-10 simulator V4.0-0 Current        git commit id: +45d8c90
ITS MTBOOT.176
MARK$G'
Format pack on unit #0
Drive 0 offline

Disk 0 (unit 0) is losing.
RH-11 disk ctl status:  I = 0; Current drive is #0, which is virtual unit #0
Disk Attention Summary: 0000000000000001
Drive Status = (140400)DIFF LT 64  DRIVE-PRESENT  ERR  ATTENTION
Ctrl & Status 1 = (104222)READY  DRIVE-AVAILABLE  SPECIAL-CONDITION
Ctrl & Status 2 = (300)SILO-INPUT-READY  SILO-OUTPUT-READY
Offset = (0)
Error 1 = (40001)  ILL-FUNC  UNSAFE
Error 2 = (0)
Error 3 = (0)
Word Count = 0., Unibus Address = 0
Desired Cyl = 0., Current Cyl = 0.
Desired Addr = 0  (Track 0.  Sector 0.)
Do you want to see all the UNIBUS registers  (Y or N)
```

Expected output is:

```
PDP-10 simulator V4.0-0 Current        git commit id: +6a131ec
ITS MTBOOT.176
MARK$G'
Format pack on unit #0
Are you sure you want to format pack on drive # 0 (Y or N)
```

**Comment by larsbrinkhoff** [comment]
The attachment got lost.  Here it is.

[files.zip](https://github.com/simh/simh/files/3328990/files.zip)

**Comment by larsbrinkhoff** [comment]
The other KS10 emulator, KLH10, doesn't need any delay.

**Comment by markpizz** [comment]
I can't really speak to the subtle timing details that may be observed with an expect script that isn't built into simh.  In circumstances like that, you can't be sure about data delivery into the simulator and if/when input buffers might be overrun.  The internal simh EXPECT and SEND commands run lock step with instruction execution and therefore generally can be counted on to behave completely consistently on all platforms.

The changes in  45d8c90 were introduced due to the fact that at least one operating system that ran on that hardware, changed the clock tick interval value on almost every clock tick.  This means that the clock calibration has a moving target for how big clock ticks actually are and therefore can't end up calibrating a proper clock tick instruction interval.  The interval timer, when used in this way, is not a candidate to be used for clock calibration.  Fortunately, the SCP timing services will run an internal hidden calibrated clock that can be used for proper wall clock delays (that the interval timer and other devices might need).  One unfortunate consequence of removing this device from being a calibrated timer is the fact that when it was a calibrated timer, the calibrated interval value (or an integral multiple of it) is used as the input character polling interval for MUX device (including the console/front-end).  In a well behaved simulator these input polling activities are synchronized to with clock ticks so that the simulator minimizes useless spinning while idling.  Under some conditions, the changes in 45d8c90 might set the tmxr polling rate unexpectedly.  A new commit to make this more consistent has been applied.  If this doesn't change anything, then adjust your external expect script so that it has timing which works well enough.

**Comment by larsbrinkhoff** [comment]
I think we can close this.  A one second delay was added to the build script and we haven't seen any problems since.
