### ISSUE TITLE
GCC 8.1.0, VAX MNEGL and negative 0 (0x80000000)

### ISSUE THREAD

**Issue by bscottm** [simh/simh#732]
I use `scoop.sh` as my local Windows external program package manager. The current GCC that `scoop` installs is 8.1.0. I can rebuild the VAX750 emulator from code just fine using the code on the latest `master` branch, but EVKAA fails with unexpected condition codes on the value `0x80000000` (negative 0), because the "N" flag isn't set:

````
sim-master master *$% = $ BIN\vax750 vax\tests\vax-diag_test.ini -v

VAX 11/750 simulator V4.0-0 Current        git commit id: 2f707ffc
Running Hardware Core Test (EVKAA)

                VAX DIAGNOSTIC SOFTWARE
                        PROPERTY OF
              DIGITAL EQUIPMENT CORPORATION

            ***CONFIDENTIAL AND PROPRIETARY***


Use Authorized Only Pursuant to a Valid Right-to-Use License


EVKAA V8.0 Hardcore Instruction Test

??? ERROR - Test # 09, Subtest # 61, MNEGL failed
Condition Code bits wrong
Expected - 0000000B
Received - 00000003
*** FAILED - VAX 11/750 Hardware Core Instruction test EVKAA
````

If I put in a `priintf`:

````
sim-master master *$% = $ BIN\vax750 vax\tests\vax-diag_test.ini -v

VAX 11/750 simulator V4.0-0 Current        git commit id: 2f707ffc
Running Hardware Core Test (EVKAA)

                VAX DIAGNOSTIC SOFTWARE
                        PROPERTY OF
              DIGITAL EQUIPMENT CORPORATION

            ***CONFIDENTIAL AND PROPRIETARY***


Use Authorized Only Pursuant to a Valid Right-to-Use License


EVKAA V8.0 Hardcore Instruction Test
MNEGL before: r 55555556 op0 aaaaaaaa cc 0000000e
MNEGL after:  r 55555556 op0 aaaaaaaa cc 00000001
MNEGL before: r 00000000 op0 00000000 cc 00000009
MNEGL after:  r 00000000 op0 00000000 cc 00000004
MNEGL before: r 00000001 op0 ffffffff cc 00000008
MNEGL after:  r 00000001 op0 ffffffff cc 00000001
MNEGL before: r edcba988 op0 12345678 cc 00000008
MNEGL after:  r edcba988 op0 12345678 cc 00000009
MNEGL before: r ffffffff op0 00000001 cc 0000000f
MNEGL after:  r ffffffff op0 00000001 cc 00000009
MNEGL before: r 80000000 op0 80000000 cc 0000000e
MNEGL after:  r 80000000 op0 80000000 cc 00000003

??? ERROR - Test # 09, Subtest # 61, MNEGL failed
Condition Code bits wrong
Expected - 0000000B
Received - 00000003
*** FAILED - VAX 11/750 Hardware Core Instruction test EVKAA
`````

I suspect that it's the various condition code macros that are the likely problem (actually, I know it's the problem because everything that goes into those macros should be promoted to `uint32`); `int32` for `cc` is also a bit sketchy, as is the type for `r` and other values.

Before I propose a solution, I did want to understand the possible range of acceptable solutions. `do-while(0)`encapsulation in the macros is one potential fix, as are `static SIM_INLINE` functions.

(Note: VC 2019 does just fine. All tests pass. This problem impacts MingW64 users.)

**Comment by markpizz** [comment]
This problem was fundamentally related to the basic idea that the VAX simulator was written assuming particular overflow of signed integer operations in C.  The C language specifies that these operations (overflow with signed integers) are undefined.  The current "expected" behavior has been consistent with GCC for a long time, and the makefile has specifically been telling gcc and clang that the original "expected" overflow behavior is desired by invoking the compiler with -fno-strict-overflow.

We've had this problem previously and it was "solved" by influencing the compiler's behavior.  

Historically, this has been a "wack-a-mole" problem.  Trying to explore the fix you were looking at was another example of this "wack-a-mole" solution.  The real solution is a rewrite of the VAX CPU simulator which explicitly uses only unsigned integer values throughout and thus all behaviors are naturally defined by the C language.  A extensive effort was made to rework the VAX CPU to be implemented entirely with unsigned integers.  This effort was completed well enough so that VMS booted.  However, due to the massive number of changes throughout the simulator, low confidence that a completely functional operations that are completely data sensitive.  These changes were not adopted waiting for the original tools that DEC used to validate new VAX models were actually correct implementations of the VAX architecture.  This tool was know as AXE,  An earlier version of the VAX780 simulator to validate the implementation and to correct some error cases.

Meanwhile, this original problem report was particularly specific to gcc  8.1.0.   It seems that this version of gcc had a bug that didn't completely implement the -fno-strict-overflow compiler option.  Newer version of gcc no longer seem to exhibit this problem, so I suspect that someone else noticed the bug in a different context and inspired a fix to the compiler.  

Additionally, MingW64  is not a supported toolchain to build the simh simulators.  The original support for MinGW32 was provided in the early simh days since at the time this was the only choice for folks to have a free compiler to build on Windows.  Microsoft has long provided free versions of Visual Studio for approximately the last 14 years. so if you're not happy with the results produced by your random choice of build tool chain, please use one that actually works, or encourage that tool chain to upgrade its compiler technology to the latest version.

**Comment by bscottm** [comment]
@markpizz: The same issue crops up with the 32-bit MinGW compilers for 8.1, 9.1 and 9.2 with "-O3" optimization (but all VAX tests pass using a Debug configuration.) I'll try "-fno-strict-overflow" to see if that solves the issue.

Personally, I'm agnostic about compiler flavor. I'm in the process of ensuring that the widest swath of "reasonable" compilers work using a CMake-based build system with the fewest number of cppcheck, compiler warnings and as much 64-bit hygiene as possible. (BTW: It wasn't just MinGW, Linux "-m32" also failed on Ubuntu 18.)

[As a side note: the CMake-based build system is a superbuild that will download and compile dependency libraries if they aren't installed, eliminating the `windows-build` hack. And Windows developers get a VS solution file as a byproduct. But I digress...]

**Comment by markpizz** [comment]
> The same issue crops up with the 32-bit MinGW compilers for 8.1, 9.1 and 9.2 with "-O3" optimization (but all VAX tests pass using a Debug configuration.) I'll try "-fno-strict-overflow" to see if that solves the issue.

The makefile explicitly uses -O2 optimization and it explicitly uses -fno-strict-overflow when available with gcc and clang.  If you've got later examples of problematic compiler cases that fail, I suggest that you create a minimal C program test case (not involving simh components) that can be passed over to the compiler developers along with an appropriate bug report.
