### ISSUE TITLE
HP2100 tape issue

### ISSUE THREAD

**Issue by MarcoVerpelli** [simh/simh#756]
I use prebuild HP2100.exe with RTE-IVB on a PC with Win7 32 bit.
I encountered a problem with the tapes, To reproduce the issue:

1) create a new tape - attach msc c:\users\marco\desktop\test
2) use FC to copy some files to the newly created tape
3) detach msc
4) stop & close everything

The next time I run the emulator (simulator!)  and mount the same tape
I get:
V4.0-0 Current git commit id:4b82a90c - OK
                             e56b5f05 - OK, only a little more verbose
                             98f6aae3 -> 52a31597 - OK with the message: Unexpected tape file position between forward and reverse record read: (304, 57600
                             c5a04861 - KO Unexpected tape file position between forward and reverse record read: (306, 57600
                                           Tape Image 'c:\users\marco\desktop\test' scanned as SIMH format.
                                           After processing 240 bytes of tape data (9 records, 1 tapemarks)
                                           Read Tape Record Returned Unexpected Status: error in record
                                           37162 bytes of unexamined data remain in the tape image file
                                           An unreasonable number of record sizes(7) vs tape marks (1) have been found
                                           The tape format (SIMH) might not be correct for the 'c:\users\marco\desktop\test' tape image

At this point it is no longer possible to read the tape with FC

It is the first time that I report a possible bug, so please excuse me if maybe I didn't put all the necessary information. Just ask if you need to know more.

Thanks

Marco

**Comment by markpizz** [comment]
Hi Marco,

Please zip that tape image file and attach the zip file here.  After I take a look I'll let you know what to do next.

Thanks.

- Mark

**Comment by MarcoVerpelli** [comment]
[test.zip](https://github.com/simh/simh/files/3727558/test.zip)
Tape made with
HP 2100 simulator V4.0-0 Current git commit id: 4b82a90c

Thanks

Marco

**Comment by markpizz** [comment]
Hi Marco,

The changes between the version that you describe as OK and the latest were specifically designed to report potential tape image structure errors at attach time (when you are sitting at the sim> prompt) rather than in the middle of operational tape usage.  Tape structure errors do not correspond to hardware errors that would normally happen with physical tapes, but are problems in the tape image data itself.  At least one of the potential tape formats actually allow for tape structure information that can describe real tape errors.  Since you created the tape image with a simulator, there should be no errors in the tape image structure.  Tools which convert physical tapes to tape images may encounter errors while reading the physical tape, and can thus possibly reflect any such errors in the tape image that was created without violating the structure of the tape that was created.

In any case, the problem you're encountering isn't actually a tape format error, just an error in the detection logic around the tape structure validation test.

The idea behind the tape structure validation test was to explicitly notify you of potentially suspicious  or erroneous tape, but it also specifically should not have disallowed you from accessing tape data that you might have found valuable.  The messages displayed should not deny access to data.

If you ignore the message displayed at attach time, are you really unable to get to the Fortran program that is on the tape? 

If you can get to the data normally, then the problem you're reporting is actually about the tape structure analysis instead of the access to data.  Assuming that analysis is the problem, the tape image you've provided has some unusual characteristics which weren't present in any of the tapes used for testing previously.  Specifically, whatever software that wrote this tape data uses tape gaps, while previous test data never did.  Let me know if you can get to the data and then I'll fix the analysis logic to tolerate tape gaps.

Thanks.

- Mark

**Comment by markpizz** [comment]
Thanks for that feedback.  As it turns out, the validation logic marks the end of data on the tape image as the point it recognizes as invalid, and thus you no can't read beyond that.

I've added Gap data to the tape library testing logic and am working on the appropriate way to tolerate the existence of Gaps during the tape image validation process.

**Comment by MarcoVerpelli** [comment]
Thank you for your time.
At least in my case there is no hurry, it is just nostalgia for school days!

Marco

**Comment by markpizz** [comment]
Marco,

Give the latest a try and close this issue if things work correctly for you.

- Mark

**Comment by MarcoVerpelli** [comment]
I have compiled the program using minGW-W64.
It worked perfectly!
I think that in the next few days I will find the official version in the simh/Win32-Development-Binaries repository
Thanks again

Marco
