### ISSUE TITLE
Bad warnings on Cygwin

### ISSUE THREAD

**Issue by al20878** [simh/simh#760]
Hello,

I'm building the PDP11 binary on Cygwin from the current git version (updated just now).

I'm getting some warnings (below) that suggest code problems.  Note that size_t is a 64-bit quantity, yet the values returned via the pointer parameter are socken_t which are basically int's (32-bit), so only the lower 32-bits of the return will be updated by the calls (with garbage, or whatever, is left in the upper 32-bit words).

```
sim_sock.c: In function ‘sim_accept_conn_ex’:
sim_sock.c:1064:60: warning: passing argument 3 of ‘accept’ from incompatible pointer type [-Wincompatible-pointer-types]
 newsock = accept (master, (struct sockaddr *) &clientname, &size);
                                                            ^
In file included from sim_sock.h:59:0,
                 from sim_sock.c:49:
/usr/include/sys/socket.h:21:7: note: expected ‘socklen_t * {aka int *}’ but argument is of type ‘size_t * {aka long unsigned int *}’
   int accept (int, struct sockaddr *__peer, socklen_t *);
       ^~~~~~
sim_sock.c: In function ‘sim_check_conn’:
sim_sock.c:1136:63: warning: passing argument 3 of ‘getpeername’ from incompatible pointer type [-Wincompatible-pointer-types]
     if (0 == getpeername (sock, (struct sockaddr *)&peername, &peernamesize))
                                                               ^
In file included from sim_sock.h:59:0,
                 from sim_sock.c:49:
/usr/include/sys/socket.h:25:7: note: expected ‘socklen_t * {aka int *}’ but argument is of type ‘size_t * {aka long unsigned int *}’
   int getpeername (int, struct sockaddr *__peer, socklen_t *);
       ^~~~~~~~~~~
sim_sock.c: In function ‘sim_getnames_sock’:
sim_sock.c:1203:56: warning: passing argument 3 of ‘getsockname’ from incompatible pointer type [-Wincompatible-pointer-types]
 (void)getsockname (sock, (struct sockaddr *)&sockname, &socknamesize);
                                                        ^
In file included from sim_sock.h:59:0,
                 from sim_sock.c:49:
/usr/include/sys/socket.h:26:7: note: expected ‘socklen_t * {aka int *}’ but argument is of type ‘size_t * {aka long unsigned int *}’
   int getsockname (int, struct sockaddr *__addr, socklen_t *);
       ^~~~~~~~~~~
sim_sock.c:1204:56: warning: passing argument 3 of ‘getpeername’ from incompatible pointer type [-Wincompatible-pointer-types]
 (void)getpeername (sock, (struct sockaddr *)&peername, &peernamesize);
                                                        ^
In file included from sim_sock.h:59:0,
                 from sim_sock.c:49:
/usr/include/sys/socket.h:25:7: note: expected ‘socklen_t * {aka int *}’ but argument is of type ‘size_t * {aka long unsigned int *}’
   int getpeername (int, struct sockaddr *__peer, socklen_t *);
       ^~~~~~~~~~~

$ gcc --version
gcc (GCC) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by markpizz** [comment]
simh support on Windows is 100% available when building with Microsoft Visual Studio (the paid or free versions), it most simulators "sort of work" when building with the x86 (32bit) version of MinGW and they might work when building with MinGW64.  Some things historically sort of work when building x86 simulators with cygwin.

From time to time, one line changes to the makefile or some other file have been accepted for cygwin, but we're really not interested in attempting to support every possible combination of build tools, when there is 100% support using other free choices.

The build components are maintained with direct support for Visual Studio 2008 Express which can be freely downloaded from:  http://download.microsoft.com/download/E/8/E/E8EEB394-7F42-4963-A2D8-29559B738298/VS2008ExpressWithSP1ENUX1504728.iso

**Comment by al20878** [comment]
I didn't know it wasn't supported... It compiled just fine (on 64 bit Cygwin) but these few warnings, which are very easy to take care of by the very same big #ifdef's that are already there is the code for other Unixes for "socklen_t"-- I've taken a look.  Is there a reason that Cygwin is not (officially) supported?  It's a much less cumbersome environment than MSVC.

**Comment by markpizz** [comment]
As you say, it compiled just fine, but then you observed the other issues (#761), and this is just the beginning of the iceberg.

The reason Cygwin isn't supported is due to the ridiculously complex tool chain matrix including any and/or all dependent packages.  The goal of the simulator environment is to get running simulators.  The best and fully supported running simulators on any platform are produced by native OS facilities on each respective platform.  Cygwin, being a Posix/Linux shim on top of Windows can, at best, weakly support the needs of the simh simulator framework.

If you're really interested in running simulators, then all you need is working binaries, which on Windows are directly available, or easily available with the supported tools if you happen to be a Windows user who is predisposed to building things yourself.  If, on the other hand, like a small number of folks, you are interested in writing a simulator (or several) or merely extending one of the existing simulators, then you're welcome to develop using the native tool chain on your most comfortable host platform.  For most folks that seems to be Linux or OS/X and for others it is Windows.

Please try either the pre-compiled binaries, or installing VS2008 (potentially in a VM if you don't want to "pollute" your primary platform).  Beyond installing VS2008, things work best if you also install git for windows (https://git-scm.com/download/win).  Clone the https://github.com/simh/simh repo and use MSVC to open the simh.sln file in the "Visual Studio Projects" folder.  Right click on a simulator you want to build and select Build.  If you don't want to do that through the GUI, I'll give you a way to do build a simulator through a command line interface.

If you want to submit a 1 or 2 line change to some simulator piece so that you get clean compiles with Cygwin, I'll accept that, but you are on your own dealing with any and all failures and warts that you observe while running a Cygwin built simulator.

**Comment by al20878** [comment]
To be honest, I haven't (yet) built anything but the PDP11 binary but even then I am only interested in and going to use the PDP11.  That said, the binary worked just fine (so far) except for the nuisances noted in #761.  There was no graphics or networking involved; but with this in mind, simh is merely a byte-code processor written in standard C / POSIX, so it should be fine on Cygwin (theoretically).

I know how to use MSVC but that's not my favorite IDE to say the least.  Also I'm using some of my own tools that are better suited for UNIX-like environment like Cygwin (I do not have Linux installed on the PC -- only as a guest OS but it makes the interaction too cumbersome, again).

I'll see if I can post a patch for those warnings Cygwin's gcc was issuing for me.

Thanks,
Tony

**Comment by agn453** [comment]
I've been one of the people who have contributed various patches for SIMH support under Cygwin for more than a decade.  I'm using only the "legacy" 32-bit version under Windows 10 1903 (64-bit) and have not experienced these issues while using PDP11, various VAX models and AltairZ80.

I tried the 64-bit Cygwin implementation a few years back and had similar issues that I put down to "teething" issues with porting things.

Why not give the 32-bit version a go?

Tony

**Comment by al20878** [comment]
```
From 8d7a57820116fa8c57319cb86da6246b429cecee Mon Sep 17 00:00:00 2001
From: Tony Lawrence <al20878@gmail.com>
Date: Tue, 29 Oct 2019 23:28:09 -0400
Subject: [PATCH] Cygwin to use socken_t

---
 sim_sock.c | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/sim_sock.c b/sim_sock.c
index 858a74b6..712f9ca0 100644
--- a/sim_sock.c
+++ b/sim_sock.c
@@ -1045,7 +1045,7 @@ int keepalive = 1;
     defined (__APPLE__) || defined (__OpenBSD__) || \
     defined(__NetBSD__) || defined(__FreeBSD__) || \
     (defined(__hpux) && defined(_XOPEN_SOURCE_EXTENDED)) || \
-    defined (__HAIKU__)
+    defined (__HAIKU__) || defined(__CYGWIN__)
 socklen_t size;
 #elif defined (_WIN32) || defined (__EMX__) || \
      (defined (__ALPHA) && defined (__unix__)) || \
@@ -1111,7 +1111,7 @@ struct sockaddr_storage peername;
     defined (__APPLE__) || defined (__OpenBSD__) || \
     defined(__NetBSD__) || defined(__FreeBSD__) || \
     (defined(__hpux) && defined(_XOPEN_SOURCE_EXTENDED)) || \
-    defined (__HAIKU__)
+    defined (__HAIKU__) || defined(__CYGWIN__)
 socklen_t peernamesize = (socklen_t)sizeof(peername);
 #elif defined (_WIN32) || defined (__EMX__) || \
      (defined (__ALPHA) && defined (__unix__)) || \
@@ -1181,7 +1181,7 @@ struct sockaddr_storage sockname, peername;
     defined (__APPLE__) || defined (__OpenBSD__) || \
     defined(__NetBSD__) || defined(__FreeBSD__) || \
     (defined(__hpux) && defined(_XOPEN_SOURCE_EXTENDED)) || \
-    defined (__HAIKU__)
+    defined (__HAIKU__) || defined(__CYGWIN__)
 socklen_t socknamesize = (socklen_t)sizeof(sockname);
 socklen_t peernamesize = (socklen_t)sizeof(peername);
 #elif defined (_WIN32) || defined (__EMX__) || \
--
2.17.0
```

**Comment by markpizz** [comment]
An open question to both Cygwin lovers who happen to be named Tony :-) :

Have either of you tried installing and running WSL (Windows Subsystem for Linux)?  

In some sense, it is a shim like Cygwin, BUT it is a much more precise Linux environment running on Windows.  Essentially all simh functionality should work if you setup and run an XWindow server on your Windows environment.  Binaries compiled under WSL or on a native Ubuntu system will run unchanged on either environment.

**Comment by AK6DN** [comment]
WSL is for Windows 10 only. Does not work on earlier versions of Windows.
When I need Windows 10 I run it in a VM on my Windows7 box.
I have been using Cygwin 32b on WinXP-32b/Win7-64b basically forever.
I have only ever used SIMH (since pre-github days) compiled on Cygwin.

**Comment by al20878** [comment]
I'm behind the curve with my Windows-7...  Duh :-)

BTW, I ran RSX11M+ in simh patched with the socklen_t patch I posted above, and it worked just fine!
All other simulators seemed to compile cleanly (no warnings), and all the VAX tests there are, passed.

**Comment by agn453** [comment]
I've tried WSL1 with SIMH and run into difficulties with winpcap support and SDL2 display features.  My use of Cygwin is "boat anchor syndrome" - it was the nicer of the two choices at the time (MinGW being the other) in that it ran X11 and had a decent ANSI console in the form of xterm - back when I started using it on Windows NT4 and 2000.  I've stuck to it.

I can be persuaded to change - indeed I'm hoping the new WSL2 that will be out next week sometime with the latest Windows-10 refresh will be suitable.   Most of the time I run SIMH under macOS or Raspbian - but it's nice to be able to run it up on a Windows machine if needed.

If SIMH support of Cygwin is to vanish... then so should Windows XP and MinGW support! (...pauses for the howling cries....).  I already see that OpenVMS VAX support has crept away  (with 64 bit stuff making inroads).

**Comment by larsbrinkhoff** [comment]
I'm also a Cygwin "lover", in the sense that I often install it to have a set of familiar tools on Windows.  I did try WSL briefly when it was first released, but at that time it was not a viable option for me.

@al20878, keep in mind that each additional target may come with a significant maintenance cost.

**Comment by al20878** [comment]
> that each additional target may come with a significant maintenance cost

Well, Cygwin is supposed (and they actually put a lot of effort) to follow Linux very closely, so as long as the code is POSIX / C, it should not be a lot of "cost" involved.  Third-party library stuff, though, is another matter (I haven't checked any of those TBH, because I don't need them this far).

**Comment by markpizz** [comment]
@AK6DN said:
> WSL is for Windows 10 only. Does not work on earlier versions of Windows.
> When I need Windows 10 I run it in a VM on my Windows7 box.

Windows 7 is going out of support in just a few months.  After that you'll be like the few folks still running XP. :-)

> I have been using Cygwin 32b on WinXP-32b/Win7-64b basically forever.
> I have only ever used SIMH (since pre-github days) compiled on Cygwin.

In the pre-github days that was fine.  Meanwhile, since that time many functional features have been added to the simh framework.  You may not care about some or all of these, but they add to the support complexity.  I'm glad if Cygwin happens to work for what you want out of simh, but if it doesn't then you're welcome to expore other choices.


@al20878 said:
> I'm behind the curve with my Windows-7... Duh :-)
> 
> BTW, I ran RSX11M+ in simh patched with the socklen_t patch I posted above, and it worked just fine!

Except for #761, right?

> All other simulators seemed to compile cleanly (no warnings), and all the VAX tests there are, passed.

The VAX tests are explcitly there to confirm that the compiler hasn't optimized some aspect of the simulator and thus caused it to produce garbage results with some instructions and data combinations.  No effort, in these tests, is made to assure anything about how or if host system library dependencies are handled correctly.

@agn453 said:
> I've tried WSL1 with SIMH and run into difficulties with winpcap support and SDL2 display features. My use of Cygwin is "boat anchor syndrome" - it was the nicer of the two choices at the time (MinGW being the other) in that it ran X11 and had a decent ANSI console in the form of xterm - back when I started using it on Windows NT4 and 2000. I've stuck to it.

The ability to build under MinGW and Cygwin in the early days was completely reasonable given the pricy other choice for a native Windows build environment.  The things you could with simh under NT4 and 2000 "should" still be doable today if you build with Cygwin.  

I don't expect there will be support for libpcap (or any form of pcap) in WSL any time soon.  Meanwhile, SDL2 should work fine given you run an X server on the host Windows system.

Winpcap is long deprecated and the modern replacement is npcap (https://github.com/nmap/npcap).  Supported Windows compiled binaries will run with either.  I've no idea if or how any of that might work under Cygwin.

> I can be persuaded to change - indeed I'm hoping the new WSL2 that will be out next week sometime with the latest Windows-10 refresh will be suitable. Most of the time I run SIMH under macOS or Raspbian - but it's nice to be able to run it up on a Windows machine if needed.

When you need to run on Windows, you could readily use a pre-compiled binary and if any issues are observed/reported I'll jump on fixing them.

> If SIMH support of Cygwin is to vanish... then so should Windows XP and MinGW support! (...pauses for the howling cries....). 

No extra effort to build on Windows XP is provided.  I'm pretty sure that some folks actually run pre-compiled binaries there, but I can't really name them.

> I already see that OpenVMS VAX support has crept away (with 64 bit stuff making inroads).

OpenVMS VAX host support is still as supported as it always has been.  The big problem with that host platform is that many current simulator developers have reasonably used 64bit values for all sorts of data throughout their simulators.  The most recent VAX C compiler doesn't have support for 64bit data elements, and as such simply can't compile simulators that have a dependency on 64bit data values.  Given the lack of large numbers of still running VAX host systems, the demand for these newer simulators running on VAX host systems is lower than low.  :-)

@al20878 wrote:
> > that each additional target may come with a significant maintenance cost
>
> Well, Cygwin is supposed (and they actually put a lot of effort) to follow Linux very closely, so as long as the code is POSIX / C, it should not be a lot of "cost" involved. Third-party library stuff, though, is another matter (I haven't checked any of those TBH, because I don't need them this far).

The "cost" of yet another implementation which has its own set of dependencies on a host platform which:
 1) has binary distribution, and 
 2) has a solidly supported implementation

is not justified.

Folks who just want to build their own unmodified simulators and insist on using Cygwin tools and libraries are on their own dealing with the "very closely Linux" issues which may arise.  If everything they want out of the simulator works, they're welcome to go down that path.

If an active simulator developer somehow couldn't work on a solidly supported platform, but somehow was only left with Cygwin, we might consider a degree of support.  No folks like this have stopped by.

**Comment by AK6DN** [comment]
@markpizz said:
>
> @AK6DN said:
> 
> > WSL is for Windows 10 only. Does not work on earlier versions of Windows.
> > When I need Windows 10 I run it in a VM on my Windows7 box.
> 
> Windows 7 is going out of support in just a few months. After that you'll be like the few folks still running XP. :-)
> 
> > I have been using Cygwin 32b on WinXP-32b/Win7-64b basically forever.
> > I have only ever used SIMH (since pre-github days) compiled on Cygwin.
> 
> In the pre-github days that was fine. Meanwhile, since that time many functional features have been added to the simh framework. You may not care about some or all of these, but they add to the support complexity. I'm glad if Cygwin happens to work for what you want out of simh, but if it doesn't then you're welcome to expore other choices.
> 
All true enough.
My base system is Win7 64b with lots of legacy specialty apps. Most don't run on Win10.
So I run Win10 in VirtualBox when I really need Win10, or browse the internet using FireFox.
I still run real WinXP lab systems for old programs/hardware that won't run on newer Windows.
Like Adaptec PCI SCSI cards to image real SCSI disks from SIMH disk images.
To me Win10 in VirtualBox is just like PDP-11 RSTS or 2.11BSD or VAX/VMS in SIMH.
I have also installed Cygwin 32b into my Win10 image, so it works there too.
If I really need to move beyond Cygwin, probably will go to linux in a VirtualBox.
As to 'out of support' from Microsoft well ...

**Comment by al20878** [comment]
Thanks.  PDP11 builds and runs okay (sans #761)
