### ISSUE TITLE
sim_sock.c:282 -- questionable code (duplicate condition)

### ISSUE THREAD

**Issue by bscottm** [simh/simh#767]
Found the following questionable code in `sim_sock.c` at line 282 and was wondering about its intent:

````
if (hostname) {
    if ((0xffffffff != (ipaddr.s_addr = inet_addr(hostname))) || 
        (0 == strcmp("255.255.255.255", hostname))) {
        fixed[0] = &ipaddr;
        fixed[1] = NULL;
        }
    else {
        if ((0xffffffff != (ipaddr.s_addr = inet_addr(hostname))) || 
            (0 == strcmp("255.255.255.255", hostname))) {
            fixed[0] = &ipaddr;
            fixed[1] = NULL;
            if ((hints->ai_flags & AI_CANONNAME) && !(hints->ai_flags & AI_NUMERICHOST)) {
                he = gethostbyaddr((char *)&ipaddr, 4, AF_INET);
                if (NULL != he)
                    cname = he->h_name;
                else
                    cname = hostname;
                }
            ips = fixed;
            }
        else {
          /* ... */
        }
````

Seems as if the first test for a broadcast address could be dropped.

**Comment by markpizz** [comment]
Actually, given the identical conditions, the second test and it's actions (which are more complicated than the first test, and the else code path) won't ever be called.

This is some legacy code to support consistent higher level calls on platforms that might not have the getaddrinfo APIs.  There is a bug here, but maybe some or all of the logic following the second test is relevant, but host systems needing this are hard to find today.  I had to craft a special case to test this and the default code path using just the first test is definitely wrong and produces bogus results which leads to a later segfault in the caller.

As it turns out, your suggestion of merely removing the first test provides correct results and works, but the rest of the logic has now been tested.  Testing this uncovered a problem in the most common calling code which has also been fixed.

**Comment by bscottm** [comment]
@markpizz: Is there a test harness for this committed (so that it doesn't happen again)?

**Comment by markpizz** [comment]
Not really.  This is Windows specific code which is really only relevant on XP and some Vista versions (those that don't have the getaddrinfo APIs).  

To test, I temporarily changed the socket init code to unconditionally dispatch to the internal implementation logic.  The socket initialization logic is a deep part of the simh framework and is initialized much earlier than the testing logic that exists to possibly exercise the various framework library routines used directly by simulator developers.  The sim_sock routines are not intended for direct use in simulator code, but only for use by the the other library code.

When testing with the modified socket init code, I exercised the code path through the getaddrinfo logic with:
```
       sim> SET TELNET host-system-ip-addr:portnum
and 
       sim> SET TELNET host-system-name:portnum
```

These comments should suffice if manual testing is required in the future.
