### ISSUE TITLE
sim_disk.c:1396 - (t_offset) 0xFFFFFFFFu is multiplication by -1

### ISSUE THREAD

**Issue by bscottm** [simh/simh#768]
The code at sim_disk.c, at or about line 1396:

```c
t_offset temp_capac = 512 * (t_offset)0xFFFFFFFFu;  /* Make sure we can access the largest sector */
```

`cppcheck` flags `temp_capac` because `t_offset` on many platforms is a signed 32-bit integer:

```
Assignment 'temp_capac=512*(int32_t)4294967295U', assigned value is -512
```

What was the original intention? `512 << 24`? (There are other occurrences of the same constant in sim_disk.c, calculating the same capacity value. Once this is figured out, the others are easy to update.)

**Comment by markpizz** [comment]
I'm not too sure that case really matters, since I think the maximum RT11 disk size is not really big enough to come close to overflowing here, but as you point out the overflow that happens if t_offset is 32bits shouldn't be there.  Maybe the solution is just to check the current disk size and just return -1 (not recognized) if the disk is too large.  I'm assigning John Forecast to this issue since he implemented the RT11 disk recognition support.

**Comment by JohnForecast** [comment]
This was a cut and paste from one of the earlier disk recognition routines. As bscottm points out the same logic is used for the ods1, ods2 and ultrix disk recognition routines as well as rt11. The intention appears to be to allow a read past the EOF to return a zeroed buffer rather than generating an error. Since t_offset is a locally defined type in sim_fio.h, maybe we should define a maximum value along with the typedef. However, this does bring up a more basic problem for disk I/O in SIMH - what do we do for large files if t_offset is 32bits (even rt11 allows a max disk size of 8GB which will not fit) and how capac_factor is handled in such systems.

**Comment by markpizz** [comment]
Hmmmm...  I hadn't read the bottom of Scott's report about this being a repetitive problem.  Sorry.

In any case, SIMH disk container files are limited to 2GB on host systems with 32bit t_offset.  That is a limitation of the C runtime library on those host platforms.  "Those" host platforms are very hard to find.  The one case I can think of is a host running under VAX VMS.  The VMS C compiler on this platform doesn't have support for 64bit integers, so we're stuck with that.  Since there is a rapidly diminishing number of physical machines running VMS and none of them are have all sorts of extra spare CPU cycles to which their users are dying to have run simh simulators under, I don't think anyone will worry too much about this limitation.

Meanwhile, back to the overflow problem in these cases, I've restructured the logic in each of the file system recognizer routines to avoid the overflow in when t_offset is 32bits.

The file system recognizer routines are internal to logic flow of the sim_disk_attach.  In general the size detecting logic exists primarily to support RQ disks initially and subsequently RZ disks (SCSI) both of which can come in arbitrary sizes.  These devices are the only cases where a disk could be > 2GB, and thus affected by the size limitation of a 32bit t_offset.  As it turns out (by design actually), these devices use the uptr->capac value as a number of 512 byte sectors rather than a file offset (they have the DEV_SECTORS flag bit set in their DEVICE structure).  A consequence of this is that simh disk container files are limited to a max size of just under 2TB which happens to be the maximum size of a VHD format file anyway.

Somewhat independent of the 32bit t_offset question is:  A while back I converted several other disk devices types (RL, RP, HK) to use sim_disk for I/O.  I don't recall if auto sizing of RT11 format disks were ever tested on these disk types.

**Comment by JohnForecast** [comment]
Looks like sim_disk support for RL, RP and HK devices was added before I wrote the rt11 auto sizing code, but the changes to handle the different types of each device was added afterwards. The RL and HK devices (both types of each) should be OK since they are smaller than the maximum rt-11 partition size (32 MB) so there can only be a single partition. I'll have to check what RP devices rt-11 supported and check out the auto sizing code.

**Comment by bscottm** [comment]
If you two think the problem is addressed, I'll close the issue. If there are unit tests that can be run (or proposed), I'd like to add them to my fork to ensure that I haven't hosed anything.

(@markpizz, @JohnForecast: Unfortunately, I've diverged from `simh/master` because I did relatively stupid things such as fixed `-Wall` warnings, reformatted the source code with `clang-format`, added a suite of `cppcheck`-based utility targets, fixed up `printf` issues with `size_t` and other types (`t_value` comes to mine, and such. I'm sure some of my work could be merged back, but only after properly reformatting the end-of-statement comments.)

**Comment by markpizz** [comment]
I'm waiting on @JohnForecast feedback about RP disks.  Otherwise I believe this can be closed since the current logic will do file system scans out to 2TB on hosts with 64bit t_offset (everywhere except VAX/VMS hosts) for RQ disks, and 4GB for RZ and RP disks.  A larger scan for RZ disks is a different problem since since they currently don't maintain the capacity in sectors in the uptr->capac field, but as a direct representation of a t_offset value.

Meanwhile, since as you say, you mangled things in your fork, I'm glad you're coming here with details of real problems on a case by case basis.  Please keep them coming.

**Comment by bscottm** [comment]
@markpizz: Could potentially typedef `t_offset` as `fpos64_t' for platforms that support it. I looked into `offset_t` and `offset64_t`, but those are semi-standard. Can dig a bit further.

**Comment by bscottm** [comment]
> Meanwhile, since as you say, you mangled things in your fork, I'm glad you're coming here with details of real problems on a case by case basis. Please keep them coming.

"Mangled" is a bit strong. "Diverged", yes. Hard to merge, very much so. But once I figure out the whole strict overflow issue or just get past the `cppcheck` issues, I can figure out a merge strategy (which'll mean conflicts when I pull them back into my repo, but that's just the way it'll go.)

BTW: Is there a mailing/discussion list where this could be better discussed?

**Comment by JohnForecast** [comment]
I re-checked the RL and HK devices and they work fine. The RP driver in RT-11 is for an RP11-C controller which is not supported by SIMH. The only reference I've found for SIMH RP style device support is a DECUS submission for an RT-11 disk driver but I've not been able to track down the source kit. I think this issue can be closed.
