### ISSUE TITLE
sim_disk.c: CreateVirtualDisk name clash with Windows

### ISSUE THREAD

**Issue by bscottm** [simh/simh#785]
Unfortunate name clash on MinGW-W64/MSYS2 build (proposed rename in #787):

```
[  1%] Building C object CMakeFiles/simhi64.dir/sim_disk.c.obj
C:\projects\simh-cmake\sim_disk.c:4157:1: error: conflicting types for 'CreateVirtualDisk'
 4157 | CreateVirtualDisk(const char *szVHDPath,
      | ^~~~~~~~~~~~~~~~~
In file included from C:/msys64/mingw32/i686-w64-mingw32/include/windows.h:78,
                 from C:/msys64/mingw32/i686-w64-mingw32/include/winsock2.h:23,
                 from C:\projects\simh-cmake\sim_defs.h:137,
                 from C:\projects\simh-cmake\sim_disk.c:78:
C:/msys64/mingw32/i686-w64-mingw32/include/virtdisk.h:537:26: note: previous declaration of 'CreateVirtualDisk' was here
  537 | VIRTDISKAPI DWORD WINAPI CreateVirtualDisk(PVIRTUAL_STORAGE_TYPE VirtualStorageType, PCWSTR Path, VIRTUAL_DISK_ACCESS_MASK VirtualDiskAccessMask, PSECURITY_DESCRIPTOR SecurityDescriptor, CREATE_VIRTUAL_DISK_FLAG Flags, ULONG ProviderSpecificFlags, PCREATE_VIRTUAL_DISK_PARAMETERS Parameters, LPOVERLAPPED Overlapped, PHANDLE Handle);
      |                          ^~~~~~~~~~~~~~~~~
```

**Comment by markpizz** [comment]
This change will not be accepted to work around a bug in the include files of a new compiler environment (MinGW64) which there is absolutely no reason to jump through hoops to add support for.  

The original code compiles today just fine with MinGW32 (iinstalled just to test this) and has always done so ever since windows added the CreateVirtualDisk API more than 10 years ago with the release of Windows 7.

We are definitely not interested in adding support for another tool chain that only adds instability.

MinGW32 support goes back to the earliest days of simh on Windows (almost 20 years ago).  In those days, MinGW32 was the only free compiler environment available.  Microsoft's compilers all cost significant money.  Microsoft has provided free compilers since VS2005 with built in IDEs, so the need to support MinGW32 has only existed since it's been there for legacy reasons and it has continued to work without problems.

SInce you found this problem, you may want to propose a fix upstream to the MinGW64 folks.  On all of the Microsoft SDKs, including windows,h DOES NOT cause virtdisk.h to be included, hence there is no conflict.

**Comment by bscottm** [comment]
Respectfully, I would ask you to pause and reconsider. 

Firstly, using a function name that is part of a system API is considered poor form. There is no harm in renaming the function. 

Secondly, MinGW-W64, which includes continued support and update for MinGW32, is what users are more likely to install than the original MinGW. 32-bit environments are starting to become deprecated, which will make simh harder to support in the future.

**Comment by markpizz** [comment]
Get the upstream to fix their bug and we might look at adding MinW64 again.

We are absolutely NOT trying to get every tool chain in the Universe to work with simh.  The complexity matrix isn't worth it.  This case is just one of the potential examples.

**Comment by bscottm** [comment]
With all due respect, I think you're being shortsighted. Supporting a wide variety of (dare I say, diverse?) build platforms is to ensure better interoperability and forward progress as the software ecosystem evolves. MinGW is pretty much a dead end; MinGW-W64, MSYS2 are the current choice for GNU C on Windows (or Cygwin.) 

Notably, the current set of developers for whom the work I'm doing is targeted can't use MinGW due to a variety of cyber concerns, founded or otherwise. MinGW-W64 is on the approved software list, MinGW is not. Secondary motivation for a CMake-based build has to do with simh as an alternate source Vax simulators and the particularly Byzantine build system that is currently simh on Windows makes getting buy-in substantially harder.

On the other hand, if you are completely set on rejecting the pull (seriously, digging in your heels over a simple name change), then clearly my efforts are rather pointless.

**Comment by rcornwell** [comment]
One of the problems with simH is that any change to SCP effects all simulators. Some of them are currently well maintained, others the creators are no longer around. Testing simulators is not easy. It can take me several days to run a complete test suite on my simulators. Also changing SCP level can break simulators in strange ways.

I do agree with Mark that this change should go into the MinGW-W64 system rather then into simH. Looking with VS2008 I do not see CreateVirtualDisk() in any of the included header files. So this appears to be a MinGW-W64 issue rather then a simH issue.

**Comment by markpizz** [comment]
My sights are to have a sanely working build environment on Windows and other platforms.  Microsoft has made free compiler technology (compatible with their paid products) for on the order of 15 years.  The only reason MinGW32 is still supported is that it still works.  As soon as it stops working (not likely) no extra effort will be made to support it.

I'm specifically saying that we're not interested in yet another built tool chain, especially one which has implementation bugs that break the current build.  Like I said, fix the broken upstream MinGW64 first and maybe...

You have been the only one who's ever come along trying to us MinGW64.  

@rcornwell wrote:
> Looking with VS2008 I do not see CreateVirtualDisk() in any of the included header files. So this appears to be a MinGW-W64 issue rather then a simH issue.

Checking from VS2008 isn't complete since VS2008 predates the release of Windows 7 which added this API to Windows.  The new API in Windows is ONLY available if an application explicitly includes virtdisk.h.  It is NOT automatically included when windows.h is included.  The include files packaged with MinGW64 are broken in that they include virtdisk.h somewhere inside of windows.h

**Comment by rcornwell** [comment]
@markpizz I agree MinGW64 is the broken one. I check VS2019 and there is no conflicts, CreateVirtualDisk is only defined in sim_disk.c.

Including windows.h should not include virtdisk.h, that is bringing in too much stuff.

**Comment by bscottm** [comment]
@markpizz, @rcornwell: MinGW-W64 is a lot larger, user base and projectwise, than simh. What's the chance that MinGW-W64 will spin out a release just to fix this one problem that's easily fixed through other means? Low. Very low.

This may have been fixed in a more recent release, but now you're asking AppVeyor to update their virtual machine images. Probability asymptotically close to zero.

**Comment by rcornwell** [comment]
@bscottm Since it is broke it should be fixed! windows.h should not include <virtdisk.h> period! It does not on VS2008 and VS2019. I also believe that this would pull in more libraries, which the developer might not want.

**Comment by bscottm** [comment]
@rcornwell: It may well be that MinGW-W64 may have fixed this, but that doesn't change the AppVeyor VM images, wherein the software is installed. Pulling in more libraries is a red herring, if you know how linkers actually work (which I'm assuming you do as one of the several FOGs on this list) -- it'll slow down the linking process, but doesn't blow up the size of the executable if none of the symbols are referenced.

Nonetheless, this is relatively pointless if it'll impact the unsuspecting and cannot be worked around. Frankly, standing on principle is admirable but has to be moderated by externalities. Since this can't be resolved, there's really little benefit to investing much more in contributing.

**Comment by markpizz** [comment]
When @rcornwell said:
>@bscottm Since it is broke it should be fixed! windows.h should not include <virtdisk.h> period! It does not on VS2008 and VS2019. I also believe that this would pull in more libraries, which the developer might not want.

I don't believe that he was concerned about actual libraries, but merely the fact that since virtdisk.h is inappropriately being  included, who knows what other include files are also being inappropriately included.  That may cause similar problems to the CreateVirtualDisk one for other folks.  These inappropriate include files may contain explicit  #pragma comment(lib, "library-name.lib") lines that would have exactly the undesired effect you describe, which I agree is inconsequential.

Meanwhile, I didn't realize that the use of cmake required using every tool chain in the Universe.  If I knew that when you started, I would have told you not to bother.  I absolutely NEVER wanted simh support for building with MinGW64.  

You had earlier found compile issues with the fact that some recent version of GCC that MinGW64 is packaged with no longer correctly honored the specific compiler feature -fno-strict-overflow.  You came up with a specific change that allowed the VAX diagnostic to pass, but since the VAX diagnostic is absolutely not an exhaustive test of VAX instruction functionality, your specific change merely occluded the compiler bug for this particular case, but didn't cover any of the potentially many other places that this compiler bug would affect simulator instruction execution.  These cases are two examples of why changing code to accommodate tool chain bugs isn't a good idea.  

The goal of the simh project is to have simulators which function as correctly as possible, not to support building with every tool chain in the Universe.

**Comment by rcornwell** [comment]
@bscottm I am not sure what you are using, however I agree with Mark on not putting a fix in to something external which is not broken, when the external thing is broken.

As to me, I have several sims in the simH tree (B5500, I7000's, KA10/KI10), soon to be adding a KL10 and possibly a IBM360. Mark (and Bob) are very protective since changes to SCP require careful surgery.

**Comment by bscottm** [comment]
@rcornwell: You're telling me that all of this sturm und drang is necessary about renaming two static functions? No, this is merely a case of cutting off one' nose to spite one's face. If there are such sensitivities about breaking SCP, there's a solution to that: unit tests.

@markpizz: There's a _REALLY_ big chasm between _requiring_ and _enabling_. Asserting that CMake requires every toolchain in the universe is speculative, at the most charitable. CMake generates environments for a variety of toolchains -- I matrixed a variety of build platforms in AppVeyor because some, like MSYS/MinGW-W64, are more likely for newer developers and the "I only build from source" crowd (and yes, I'm in that crowd.) Demonstrating that they can work improves on simh's "-ilities", such as maintainability and could cut down on FAQs -- "`simh` doesn't compile with MSYS2!!" can be answered with "Well, actually it does. What's wrong with your environment?"

And that's one of the principal reasons for expending effort on CMake: improving the "-ilities". with maintainability and decreasing fragility being the foremost. Ever compile with `-Wformat`? You'd be surprised at the format string issues that `simh` has. Was going to submit that as a separate branch patch, but the utility of that seems to be pretty close to zero. 

MinGW-W64 may have screwed one of their distributions with `virtdisk.h` included in `windows.h`, but at least the Vax simulators function properly, with the exception of `vax8600` on the MSYS2 `Debug` build. Just check the build results -- each one of those builds invokes `ctest`, which executes the Vax diagnostics. You can stand on principle, but eventually it starts to sound like the RFOGs on comp.arch arguing about pre-Intel glory days and nattering on about the Mill and the Belt.

I am not interested in fighting a losing battle, namely, getting AppVeyor to change their VS 2019 image or MinGW-W64 to change their distribution. At best, I can report it and hope that change happens. In the words of my Navy's "Green Team" brethren and sestren, "Assess, Adapt and Overcome."

**Comment by rcornwell** [comment]
@bscottm That is up to Mark to make the changes to SCP. My point was that the windows.h should not include this file. Whether Mark should rename the static function is up to Mark to make. Unit tests are a great idea, however this would probably not solve things. I can give some examples from my simulators:

B5500: there is zero diagnostics, the only test case that is available is the actual operating systems.

I7090: only diags are for 709, However IBSYS will not run on I709.

PDP10: It can pass diags but not run OS, It can run OS and not pass diags.

So unit testing is not a simple task.

In terms of fragile, Mark introduced some changes to timing which messed up some stuff in my PDP10 simulators that took a bit to fix.

The point is to make sure that all simulators function, not just the VAX.

**Comment by markpizz** [comment]
> asserting that CMake requires every toolchain in the universe is speculative, at the most charitable. 

I never made such an assertion.  I asked if that was the fact.  You are the cmake domain expert here.  If MinGW64 isn't required by cmake then cmake builds for simh is still a choice without MinGW64.

> MSYS/MinGW-W64, are more likely for newer developers and the "I only build from source" crowd (and yes, I'm in that crowd.) 

The "I only build from source" crowd is probably 90% Linux and OS/X folks.  Of the remaining 10%, 99% of them have no problem with a Visual Studio build.  You're the first who come from the preference for MinGW64.  

> MinGW-W64 may have screwed one of their distributions with virtdisk.h included in windows.h, but at least the Vax simulators function properly, with the exception of vax8600 on the MSYS2 Debug build.

Testing is at the root of the support for more tool chain platforms.  We don't have rigorous enough testing to declare that arbitrary tools chains will work.  The diagnostic testing that the VAX simulators perform are absolutely minimal.  Sure, they are much greater than none, but they are not sufficient to approve a new compiler.  The results from changing compilers is not unlike what DEC's original design teams did when they designed a new VAX model at a pace which might have been measured in a good number of months or years.  DEC had a tool which they ran on each new model to assure that a new VAX is a VAX.  This tool was known as AXE.  If you can get that tool or access to someone who can run it for us, we'l be glad to use it to verify evolving compiler technology.  Lacking this level of robust testing, new compilers will, at best be iffy.  Any sniff of a problem and we're not interested. 

> I am not interested in fighting a losing battle, namely, getting AppVeyor to change their VS 2019 image or MinGW-W64 to change their distribution. At best, I can report it and hope that change happens. 

Well, that is part of the job here.  In the 18+ years I've been working on this stuff, I had to wither work with upstream folks to fix problems or just report problems along with minimal test cases which reproduced the problem.  These issues have included at least:
1) bogus warnings issued by GCC when optimizing (eventually fixed as a result of my report)
2) enhancements to libpcap
3) fundamental bugs to libSDL, fixes which I supplied were eventually merged into the next release.
4) problems with PCRE on some platforms

A part of dealing with problems like this involved finding ways to accommodate them until the fixes were globally available. Sometimes this involved code changes, sometimes local patches, sometimes avoiding the failing component.

Given that MinGW64 has produced more than one visible failure and there are other completely solid choices on Windows, The correct strategy for this case is avoidance.

Do submit good bug reports up stream.  Don't fight a loosing battle with AppVeyor, just avoid MinGW64 for now.

Most contributors work on new simulators or new functionality in one or more existing simulators.  The list of folks who actually do these things is particularly small. You're coming along and attempting to contribute a solution to an already solved problem (that happens to not have been solved the way you would), while at the same time adding dependencies on additional build components.  So far, your directions have not yielded working results on any platform I tested on.  We're not close yet, and there is no skin off my nose to completely drop the idea.  I've got other useful things to spend my time on.

> Ever compile with -Wformat? You'd be surprised at the format string issues that simh has. Was going to submit that as a separate branch patch, but the utility of that seems to be pretty close to zero.

I don't see current problems.  Rather than submitting a patch, send send along the compiler warnings you're seeing.

> it starts to sound like the RFOGs on comp.arch arguing about pre-Intel glory days and nattering on about the Mill and the Belt.

Well, this project is all about simulating systems that existed in the "pre-Intel glory days".  What are "RFOGs" ?

**Comment by bscottm** [comment]
I've never encountered an open source project that is as adversarial as this. Best of luck, and as they say in DC, "Have a nice day."
