### ISSUE TITLE
simh simulators and cpulimit don't like each other

### ISSUE THREAD

**Issue by asbestomolesto** [simh/simh#793]
Hi there, 

I'm trying to limit the CPU usage of a vax emulator using cpulimit, but every time I start cpulimit, vax stops as if I had pressed CTRL-Z. 

here's the problem:

`
root@corazzini:/storage/vax# cpulimit -e vax -l 25 -b
root@corazzini:/storage/vax# Process 1988 detected

root@corazzini:/storage/vax/snorry# vax

VAX simulator V3.8-1
NVR: buffering file in memory
Eth: opened eth4

KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..
[1]+  Stopped                 vax
root@corazzini:/storage/vax/snorry#
`

About my system:
`
root@corazzini:/home/asbesto# uname -a
Linux corazzini 3.16.0-4-586 #1 Debian 3.16.36-1+deb8u2 (2016-10-19) i586 GNU/Linux
root@corazzini:/home/asbesto#

root@corazzini:/home/asbesto# vax

VAX simulator V3.8-1
sim>
sim> show version
VAX simulator V3.8-1 [64b data, 64b addresses, Ethernet support]
sim>
`

my vax.ini: 

`
load -r ./ka655.bin
attach nvr ./nvram.bin

set cpu 64m
set cpu idle
set rq0 ra92
attach rq0 ./snorry.img

; disable unused stuff
; rl01/02
set rl disable
; magtape
set ts disable
; floppy lo abilito
set ry disable

; deqna is faster!
SET XQ TYPE=DEQNA
set xq mac=08-00-2B-00-CA-CA
attach xq eth1

; create a tape device, you never know
set tq enable
set tq tk70
att tq0 mua0.tape

set cpu conhalt
dep bdr 0
boot cpu
exit
`

Any idea? :(

**Comment by markpizz** [comment]
Hi there.

We're glad you've come along to use simh, but the version you're running is a somewhat old (12 years).

My first suggestion is to run the latest, which can be achieved on your system with the following commands:
```
## start by removing the old stuff
# apt remove simh
## pickup the required tools and libraries to self build
# apt install git gcc make libpcap-dev libsdl2-dev
# git pull https://github.com/simh/simh
# cd simh
# make vax
```
This will produce a simulator in simh/BIN/vax that is the latest.

You should remove this line from your configuration:
```
load -r ./ka655.bin
```
You should add this line to your configuration:
```
set cpu idle
```
Then you should be able to run the vax simulator WITHOUT trying to control the cpu usage externally with the cpulimit command.

**Comment by markpizz** [comment]
Looking beyond the fact that you were running the ancient version of simh, the behavior you are seeing (CTRL-Z causing the process to stop), is expected behavior of most programs when running under a linux shell.  

See:  https://unix.stackexchange.com/questions/116959/there-are-stopped-jobs-on-bash-exit

It is odd that CTRL-Z you typed wasn't merely a character that should have been passed into the running simulator.  That may have something to do with the ancient simh version or you running or due to the fact that you were running with cpulimit.

Typing CTRL-Z while the vax boot rom was running its initial diagnostics shouldn't have done anything, so why were you typing that then?

If you were intending to get back to the sim> prompt, the character that should have gotten you there would normally be CTRL-E (unless you changed the WRU character in your configuration which you didn't).  Had you typed CTRL-E, you would have then been surprised to see that the simulator merely exited which probably wasn't what you actually wanted.  The simulator would have exited due to the fact that the last line of your configuration file was the "exit" command which would have been processed before the simulator had a chance to prompt you for a new command.

**Comment by asbestomolesto** [comment]
Ehm, the problem is that I NEVER typed Ctrl-Z. It just pops out when, on another shell, I launch cpulimit. This is the problem.

**Comment by markpizz** [comment]
I'm glad to hear that you didn't actually type CTRL-Z, and also to know that you were running cpulimit from a different window.

therefore, cpulimit must be sending a SIGSTOP signal to the vax process.

**The solution is: DON'T USE cpulimit to control the cpu used by the vax process.**

The simulator has it's own internal way of managing cpu consumption on the host system.

Like I suggested, you can use "SET CPU IDLE" to get the simulator to sleep when it has nothing useful to do, OR if you really want the simulator to consume 25% of the host system's CPU cycles even when it has nothing to do, you can use "SET THROTTLE 25%" to get it to always consume 25% of the host's CPU cycles even when it otherwise could be sleeping.  You can choose one or the other.  Most folks prefer the sleep when idle approach.

**Comment by asbestomolesto** [comment]
As you can see from my config file, I' still using SET CPU IDLE, but this seem not working. CPU peaks at 100% especially while the vax is booting up :(

**Comment by markpizz** [comment]
> As you can see from my config file, I' still using SET CPU IDLE, but this seem not working. CPU peaks at 100% especially while the vax is booting up :(

I didn't notice your use of SET CPU IDLE.  My first suggestion of running a 12 year newer simulator version was driven by the fact that numerous internal details in the simulator framework process idling and other timing activities better than they did 12 years ago.  Additionally, more instruction patterns are available for idle detection in the newer system.

> What's weird is that I still use cpulimit with a PDP-11 simh emulator and I have no problem at all, it works flawlessy.

You haven't mentioned what OS you're running  on the VAX simulator, which will influence what patterns are used to detect the idle condition.

The PDP-11 has an instruction which explicitly declares the idle condition, the VAX meanwhile doesn't have any such instruction and therefore particular patterns of instruction execution are needed to detect idling and these patterns are different when different operating systems are running.

Independent of all of this, there is internal logic in the simulator framework which is used to manage idling, throttling and manage wall clock based clock ticks.  Using an external program (cpulimit) to try and manage cpu usage of a simulator interferes with the simulator's internal timing management activities and pretty much guarantees that it won't keep anything close to correct time.

PLEASE try the 5 commands mentioned above to run the latest simulators.  Change the last line "make vax" to "make vax pdp11" so that you can end up with both of the simulators you are using.

The VAX has a significantly longer set of things which are truly busy activities before things settle down to doing nothing when the system boots.  Hopefully you actually use the system for other things after it boots, so the time spent booting won't be your fundamental concern.  If you are really worried about the boot CPU time you can use throttling, but then you'll always waste CPU cycles even after booting has completed and the system really is idle.

**Comment by asbestomolesto** [comment]
Roger, wilco

**Comment by asbestomolesto** [comment]
We just compiled and tried the last simh release - seem amazing! But the problem persist. 

:( 

It seem that cpulimit send some sort of signal, as stated in his help page:

```
      -s, --signal=SIG   Send this signal to the watched process when cpulimit exits.
                         Signal should be specificed as a number or
                         SIGTERM, SIGCONT, SIGSTOP, etc. SIGCONT is the default.
```
anyway I'm trying SET CPU IDLE=VMS :)

**Comment by markpizz** [comment]
Like I've said repeatedly, you shouldn't be using cpulimit to manage CPU cycles used by the VAX (and PDP11) simulators.

"SET CPU IDLE" should work well for all practical purposes, if not, then "SET THROTTLE 25%" will work and when you use either of these approaches, the Operating System running within the simulator will keep good time, where it would never do that if you tried to use cpulimit to control the simulator's CPU usage.

**Comment by asbestomolesto** [comment]
Thank you for the title correction :) 
Ok I will say that this closes the issue. Thank you all for the patience!
