### ISSUE TITLE
simh fails to build with gcc-10 or CFLAGS+=-fno-common

### ISSUE THREAD

**Issue by trofi** [simh/simh#794]
gcc-10 will change the default from -fcommon to fno-common: https://gcc.gnu.org/PR85678. Due to this change `simh` release and master branch fails to build as: `multiple definition of 'sim_vm_init'`.

The error also happens if `-fno-common` option passed to gcc explicitly. This is an upstream variant of https://bugs.gentoo.org/706866 downstream report.

As I understand `sim_vm_init` is defined multiple times on purpose: as a `NULL` pointer and a few overrides in individual emulators also as weak symbols. `-fno-common` does not allow such setup probably because it can't chose from multiple weak symbols. Perhaps it would help to mark more definitions of `sim_vm_init` as `WEAK`?

Larger part of build log:
```
$ LANG=C make
lib paths are: /lib/ /lib64/ /usr/lib/ /usr/lib/OpenCL/vendors/beignet/ /usr/lib/gcc-lib/x86_64-pc-linux-gnu/3.3.6/ /usr/lib/gcc-lib/x86_64-pc-linux-gnu/3.3.6/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/10.0.1/ /usr/lib/gcc/x86_64-pc-linux-gnu/10.0.1/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/3.4.6/ /usr/lib/gcc/x86_64-pc-linux-gnu/3.4.6/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.0.4/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.0.4/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.1.2/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.1.2/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.2.4/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.2.4/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.3.6/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.3.6/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.4.7/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.4.7/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.4/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.4/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.4/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.4/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/5.5.0/ /usr/lib/gcc/x86_64-pc-linux-gnu/5.5.0/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/6.5.0/ /usr/lib/gcc/x86_64-pc-linux-gnu/6.5.0/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/7.4.0/ /usr/lib/gcc/x86_64-pc-linux-gnu/7.4.0/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/7.5.0/ /usr/lib/gcc/x86_64-pc-linux-gnu/7.5.0/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/ /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/32/ /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/ /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/32/ /usr/lib/llvm/7/lib/ /usr/lib/llvm/7/lib64/ /usr/lib/llvm/8/lib/ /usr/lib/llvm/8/lib64/ /usr/lib/llvm/9/lib/ /usr/lib/llvm/9/lib64/ /usr/lib/sidplay/builders/ /usr/lib64/ /usr/lib64/OpenCL/vendors/beignet/ /usr/lib64/sidplay/builders/
include paths are:  /usr/lib/gcc/x86_64-pc-linux-gnu/10.0.1/include /usr/lib/gcc/x86_64-pc-linux-gnu/10.0.1/include-fixed /usr/include
using libm: /usr/lib/libm.so
using librt: /usr/lib/librt.so
using libpthread: /usr/lib/libpthread.so /usr/include/pthread.h
using libpcre: /usr/lib/libpcre.so /usr/include/pcre.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/libpng.so /usr/include/png.h
using zlib: /usr/lib/libz.so /usr/include/zlib.h
using mman: /usr/include/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
*** Info ***
*** Info *** all  Simulators are being built with
*** Info *** minimal libpcap networking support
*** Info ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should read 0readme_ethernet.txt and follow the instructions
*** Info *** regarding the needed libvdeplug components for your Linux
*** Info *** platform
*** Info ***
***
*** all  Simulators being built with:
*** - compiler optimizations and no debugging support. GCC Version: 10.0.1.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
*** - Per simulator tests will be run.
***
*** git commit id is 2e9fd354a40ec5e01037c97d5642040397d14286.
*** git commit time is 2020-01-26T19:53:45-0800.
***
font paths are: /usr/share/fonts/ /usr/lib/jvm/
font names are: DejaVuSans.ttf LucidaSansRegular.ttf FreeSans.ttf AppleGothic.ttf tahoma.ttf
using libSDL_ttf: /usr/lib/libSDL_ttf.so /usr/include/SDL/SDL_ttf.h
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=2e9fd354a40ec5e01037c97d5642040397d14286 -DSIM_GIT_COMMIT_TIME=2020-01-26T19:53:45-0800  -DSIM_COMPILER="GCC Version: 10.0.1" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./VAX/vax_cpu.c ./VAX/vax_cpu1.c ./VAX/vax_fpa.c ./VAX/vax_io.c ./VAX/vax_cis.c ./VAX/vax_octa.c  ./VAX/vax_cmode.c ./VAX/vax_mmu.c ./VAX/vax_stddev.c ./VAX/vax_sysdev.c ./VAX/vax_sys.c  ./VAX/vax_syscm.c ./VAX/vax_syslist.c ./VAX/vax_vc.c ./VAX/vax_lk.c ./VAX/vax_vs.c ./VAX/vax_2681.c ./PDP11/pdp11_rl.c ./PDP11/pdp11_rq.c ./PDP11/pdp11_ts.c ./PDP11/pdp11_dz.c ./PDP11/pdp11_lp.c ./PDP11/pdp11_tq.c ./PDP11/pdp11_xq.c ./PDP11/pdp11_vh.c ./PDP11/pdp11_cr.c ./PDP11/pdp11_td.c ./PDP11/pdp11_io_lib.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I ./VAX -I ./PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/bin/sdl2-config --cflags` `/usr/bin/sdl2-config --libs` -o BIN/vax -lm -lrt -lpthread -lpcre -ldl -lpng -lz
/usr/lib/gcc/x86_64-pc-linux-gnu/10.0.1/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccIhuO4w.o:(.bss+0x430): multiple definition of `sim_vm_init'; /tmp/ccn7L1lu.o:(.data.rel.local+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:2223: BIN/vax] Error 1
```

**Comment by markpizz** [comment]
Most of the features that are discussed around WEAK seem to leverage the concept to replace existing functions in some library that the routine links with.  Simh's expected behavior is to provide a way for a variable defined as WEAK to optionally specifically assign a value in a different module.  If that variable is not defined elsewhere, then it will default to 0 implicitly by the linker which the simh framework can then see.  

This is only used to convey a simulator specific initialization routine.  As it turns out, the need for such a simulator specific initialization routine is completely unnecessary.  It is unnecessary since there already is a code path that the simh framework will always call before it processes the invoking command parameters and/or asks for any input.  This always available call is the CPU device specific reset routine.  This fact is documented in the guide to writing a simulator.

I've dug through things to gain an understanding the WEAK concept.  As it turns out, normally simh is compiling as C and not C++.  As a result WEAK has been defined to be the null string under those conditions.  This is equivalent to the Fortran concept of a common block, which is why gcc has an argument (-fno-common or its inverse -fcommon).  Historically, most C environments result in the "common" behavior which simh desires.  

For now, I've added an explicit -fcommon to the GCC compile line used by the makefile.

Next, I'll redefine WEAK as "__attribute__((common))" (when __GNUC__ is defined) to explicitly address the problem you've opened this issue about and then remove the -fcommon from the makefile.

Not all of the current simulators use WEAK in the declaration that initializes a simulator specific initialization routine.  This historically hasn't mattered since WEAK was a blank string for C code, but does going forward when GCC's default is -fno-common.  I will either fix these or completely remove the use of sim_vm_init in the simulator.  The choice will depend on the complexity of impact to the code for the specific simulator.

Avoiding the use of sim_vm_init is preferred since the available storage class modifiers are not 100% equivalent on all possible compile environments.  Specifically, when compiling as C++ under Windows, the closest storage attribute to "common" or "weak" is "selectany".  "selectany" results in the linker randomly choosing one of the 0 value implicitly defined in the simh framework, or the one defined in the simulator specific code.  Random results aren't a good goal. :-(

**Comment by markpizz** [comment]
@trofi Does the latest code in the master branch work for you?

**Comment by trofi** [comment]
Yes, the master branch works. Thank you!

**Comment by markpizz** [comment]
Thanks for the feedback...  I don't have access to the failing situation, so I had to bug you.

Meanwhile, you had mentioned elsewhere about putting together a new simh package.  Can you elaborate what you're plans are and the timeline.

Thanks.
