### ISSUE TITLE
AltairZ80: s100_tarbell.c is not included in the source files for the Visual Studio build.

### ISSUE THREAD

**Issue by mgthompson** [simh/simh#804]
The new file s100_tarbell.c is not included in the Source Files for the Windows Visual Studio build.

I tried to build AltairZ80 with Visual Studio 2017 and the latest source files. It would not build and reported these errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _tarbell_dev	AltairZ80	C:\simh\trunk\Visual Studio Projects\altairz80_sys.obj	1	
Error	LNK1120	1 unresolved externals	AltairZ80	C:\simh\trunk\BIN\NT\Win32-Debug\AltairZ80.exe	1	

The symbol _tarbell_dev did not exist in any of the source files in the AltairZ80 project. I looked on github and found the new file s100_tarbell.c that defined the symbol s100_tarbell.c. I added an existing item, s100_tarbell.c, to the Source Files in the AltairZ80 project, and now AltairZ80 builds OK.

**Comment by markpizz** [comment]
You didn't start with a clean clone of the github.com/simh/simh repo.  Specifically, when you're using a newer Visual Studio version than 2008, you must do the equivalent of:
```
    $ # get rid of any locally changed files (simh.sln in particular)
    $ git reset --hard HEAD^
    $ # pickup the latest code from the github repository
    $ git pull https://github.com/simh/simh
```
The project conversion process that happens when you build with a different version of Visual Studio changes "Visual Studio Projects\simh.sln".  In order to pick up the latest information recorded in the projects in the repository, you have to perform that conversion process again.

**Comment by mgthompson** [comment]
Just deleting simh.sln, updating the files to the latest version in the repository, and redoing the conversion made it work OK. Sorry for the bother.
