### ISSUE TITLE
VAX: TCP connection issues with SIMH VAX on Docker

### ISSUE THREAD

**Issue by OrBin** [simh/simh#813]
## Summary
I'm running a simulated VAXServer 3900 using SIMH, with an OpenVMS operating system.
Incoming communication works when running "natively" on a linux server, but doesn't work when running inside a Docker container.

## Detailed problem description
I've managed to successfully configure networking in the OS **using TCPWARE** - when running "natively" on a linux server.
When running the same inside a Docker container, incoming communication (telnet, ftp) doesn't work (of course, I've re-configured TCPWARE).

To be more specific, I see packets coming in and identified as IP packets (when running `netcu debug /ip`), but it seems like they are not identified as TCP/UDP packets (when running `netcu debug /tcp`, nothing is shown).

Outgoing connections seem to work - I can connect to other servers using telnet.
When running `netcu debug /ip`, I see that the packets are identified with "pro=TCP".

I've tried to compare the packets (using Wireshark) for the working setup (natively on linux) and for the failing setup (in Docker), but they don't differ much.

I don't have TCPIP installed, I'm using TCPWARE V4.1-2 (Patch level V4.1-2A).

## Version Info
```
MicroVAX 3900 simulator V4.0-0 Current        git commit id: 34a133ce
MicroVAX 3900 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.8.5 20150623 (Red Hat 4.8.5-28)
        Simulator Compiled as C arch: x64 (Release Build) on Nov 11 2019 at 16:08:01
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.32 2012-11-30) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux my-server 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: 34a133ce
        git commit time: 2019-10-29T08:07:58-0700
```

## The simulator configuration file (snippet)
```
set xq mac=<eth1 mac address>
attach xq0 eth1
```

**Comment by markpizz** [comment]
There never was any response to this issue.  I'm not sure why.

In any case, I have no specific experience with Docker hosted systems, however on some VM platforms, trying to run a simh simulator with a VM as a host DOES require some special configuration on some VM hypervisors or other VM setups.  Specifically, the VM setup for the host configuration that will run a simh simulator usually needs to have it's network interface specifically configured to allow transmission and reception of arbitrary MAC addresses via the VM's LAN interface(s).  Some hypervisors default to only allow the hypervisor assigned/configured MAC address to be sent and received.

I'm closing this now since it is old and the answer I just gave would reasonably seem to be relevant to the reported problem.  Please reopen this as needed.
