### ISSUE TITLE
"dump" fails on PDP8

### ISSUE THREAD

**Issue by KedalionDaimon** [simh/simh#852]
"dump" does not seem to work in a PDP-8 emulator in any recent SimH version. Just start the pdp-8, load a tape, then try saying "dump some.file", and see that it creates some.file with 0 bytes.

**Comment by markpizz** [comment]
You are 100% correct.  

However, the DUMP command (and LOAD command) invoke a simulator specific routine called sim_load().  The simh framework calls this routine (passing a flag indicating when a LOAD or a DUMP should be done).  

That routine (in PDP8/pdp8_sys.c) has NEVER actually implemented DUMP functionality since the earliest version of the PDP-8 simulator.

If you need to save the current state of the simulator there is the SAVE command which will store everything about the current state in a file, you can exit the simulator and later you can start the simulator again and RESTORE the saved state from that file.

Otherwise, if you really feel the need for DUMP functionality, feel free to implement it and we'll consider your changes as an addition to the PDP-8 code base.

**Comment by KedalionDaimon** [comment]
Well, I am not in a position to patch this thing, so good luck. :) Thank you for your proposals, too. Still, I advise to then at least mention this peculiarity when running the command or something - "No dump command available, use instead..."

I needed the dump functionality in order to "get software" to other systems, and such which have no loader capability. So yeah, that was my "business case", and while your SAVE and RESTORE are great for simh, they are obviously not portable. However, meanwhile I think I found a workaround, and namely:

for a decimal dump:

ex -d @simdump.txt 0-7777

for an octal dump:

ex @simdump.txt 0-7777

Perhaps this workaround can be documented or even used as an alias? Just a friendly suggestion. Turns out your very nice emulator CAN, in fact, dump memory... :)
