### ISSUE TITLE
"-fno-common" is the default for GCC 10

### ISSUE THREAD

**Issue by bscottm** [simh/simh#862]
`-fno-common` is now the default in gcc 10. I manually added -fcommon to the makefile and the compile succeeds. That's going to be a problem for SIMH at some point down the road for code security/safety purists.

`hp2100` and `hp3000` are the __only__ simulators that rely on `sim_vm_release` and `sim_vm_release_message`, which does beg the overall utility of the two variables. Several options for a fix:

- Add `-fcommon` if `GCC_MAJOR_VERSION` >= 10. Fixes problem, but isn't future-proof if GCC decides to change behavior again.
- Redefine `sim_vm_release` and `sim_vm_release_message` as weak functions returning `const char * ` and then call the functions to get the release string and release message inside of `show_version`.

````
    WEAK const char *(*sim_vm_release)();
    WEAK const char *(sim_vm_release_message)();
````

- Rename `sim_vm_release` and `sim_vm_release_message` to `hp2100_vm_release`/`hp3000_vm_release` and `hp2100_vm_release_message`/`hp3000_vm_release_message`, respectively and assign to `sim_vm_release` and `sim_vm_release_message` inside of the simulators' `one_time_init` function.

The last two are relatively future-proof and a bit more kosher.

**Comment by markpizz** [comment]
The use of WEAK paradigm has been removed completely from simh (sim_vm_init no longer supported) due to the random results that can happen under windows builds.  As such, suggestion 3 has more or less been adopted and the 3 of 82 simulators that used sim_vm_init have been modified to perform the one time initialization activities in their respective cpu_reset() routines.

Thanks.
