### ISSUE TITLE
display: Rate limit video updates

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#876]
- #### Context

The display library frequently calls display_sync, which in turn calls ws_sync to redraw the entire display window.  Checking the new Imlac simulator, I measured 360 calls per second.  Apparently this works fine on a high end computer, but on a Raspberry Pi 3 it will get bogged down.

A quick hack to limit the rate to 60 updates per second makes the display update smoothly on the Pi.

@philbudne, is there some parameter in the display library that can be adjusted for this?  I don't fully understand the numbers assigned to half_life, refresh_rate, etc.

I will also try other simulators.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

Latest master + Imlac branch.

- #### how you built the simulator or that you're using prebuilt binaries

`make imlac` with SDL2 installed.

- #### the simulator configuration file (or commands) which were used when the problem occurred.

The "clock" program and configuration posted in a ZIP file here: #868.

The problem will not be evident on a "normal" PC, by which I guess anything later than 2015 or even earlier will do fine.  The Raspberry Pi 3 is a 4-way ARM at 1.2 GHz with DDR2 memory at 900 MHz.

**Comment by larsbrinkhoff** [comment]
The GT40 simulator updates around 50 times per second, which is very reasonable.

**Comment by larsbrinkhoff** [comment]
It seems the half_life parameter controls the update rate.

**Comment by philbudne** [comment]
Everything is a bit hazy, since I borrowed/hacked/tuned the code
17 years ago.

> It seems the half_life parameter controls the update rate.

Yes:

    refresh_rate = (1000000*LEVELS_PER_HALFLIFE)/half_life;

So you can try reducing LEVELS_PER_HALFLIFE from the default of 4.

The purpose of display.c is to simulate the decay of slow phosphors,
and is (much) more pain than it's worth for a display that NEVER shows
any noticible persistence or blur.

From a distance of nearly two decades, it seems reasonable to say the
simulated refresh rate should never be allowed to exceed 100, and that
something lower could well be sufficient, and that perhaps fixing the
simulated refresh rate would make sense (except if/when it doesn't).

But testing and experimentation is necessary to see whether the
results are reasonable and pleasing.  I remember going through a
number of iterations before deciding that it was "good enough", and
there are still many tunables from that process that can easily be
tweaked to get bad results.

**Comment by larsbrinkhoff** [comment]
Thank you.  Adjusting half_life seems to fix the excessive updates.

Imlacs would usually refresh the screen at 40 Hz, but would go slower if the display program grew excessively large such as a screenful of text.  The preferred CRT seems to have used P31 phosphor.

**Comment by philbudne** [comment]
For posterity:

The code tries to display a point for 5 half-lives (to 3% of original
brightness), and to display 20 different levels in that time.  This
done with the slow phosphor in the P7 (Type 30) tube in mind. And ends
up with a refresh rate of 32Hz.

http://research.mrl.ucsb.edu/~ngeorge/downloads/Phosphor%20books/Phosphor%20Handbook.pdf

says P31 is "Medium Short" persistence and has 10% decay time of
approx 40us. My math is that the half-life is 12us.

That seems to confirm my guess that the persistence is too short to
bother/try simulating decay.  There's no point in trying to display 20
different levels of decay for a spot that will vanish in under a ms
(three orders of magnitude faster than the phosphor the code was
written/tuned for).

MAYBE capping refresh_rate would do the right thing?

**Comment by larsbrinkhoff** [comment]
The Imlac would typically update the display 40 times per second (or less), so whatever phosphor the CRT had would have to accommodate that.  I have seen P31 cited, but I don't know any specifics beyond that.
