### ISSUE TITLE
SCP: System specific end-of-lines

### ISSUE THREAD

**Issue by gavineadie** [simh/simh#922]
Mark, would you accept a PR with this suggested change and all the resulting changes to the impacted `sim_` files?

    /* system-specific EOL char(s) */
    #if defined (__unix__) || defined (__APPLE__) || defined (__hpux) /* UNIX definitions */
    #define EOL "\n"
    #define EOL_LEN 1
    #else
    #define EOL "\r\n"
    #define EOL_LEN 2
    #endif

this work was done by a friend and I would attribute so.  He's at

https://github.com/ghfbsd/sims

where you will see other changes to `sim_` files functionality, but I've isolated the e-o-l NFC changes.

**Comment by markpizz** [comment]
You're proposing a solution without defining a problem.

Please spell out specifics about what problem this addresses and how things don't work correctly for some universe of users.

**Comment by gavineadie** [comment]
Fair criticism, @markpizz .. I did say "no functional changes."
Before we close this (accept or reject), let me debate any merits with the author.

**Comment by markpizz** [comment]
Feel free to have that discussion here...

**Comment by gavineadie** [comment]
It has been suggested that, "There’s no need for you to die in a ditch just to get that update accepted" .. regardless, I'll make a small effort.  Though my writing this, and you reading it, is likely to be wasting both of our times, I feel I need to do the pitch due diligence.

.. line-endings for some platforms don't include `\r` and this PR  makes simh adhere to that norm.

.. code behind the `sim_debug()` macro changes an ending `\n` to `\r\n` illustrating correct line endings do matter.  Though the PR doesn't address it, I'd argue, that code should insert the `\r` only when appropriate via the same compile-time conditional.

.. most terminal programs on those platforms don't emit the `\r` so their presence is typically benign, but relying on that side-effect seems a little unsanitary.

.. semi-frivolously, an ongoing frustration that a 50 year old teletype mechanism still influences today's programming (though its appearance in the emulation of teletype era computers is a pretty good excuse).

That's my case, I'll accept rejection without rancor.

**Comment by gavineadie** [comment]
Please accept my regrets for sim_ changes .. Richard raised the 'ground rules' that would have stopped us going down this path.  I'm closing this issue.

**Comment by markpizz** [comment]
Actually I think you're missing something in the concept.  The unix line ending convention's semantics haven't ever changed.  Text data stored in files had \n (LF) line endings for conceptual simplicity and possibly even to save space.  In any case, that data, when emitted to a terminal device actually translated the LF line ending to BOTH a CR and a LF for display.  That is still done today.  Extra CR characters in the output data stream have no negative visual effect since CRLF and CRCRLF leave the a screen (or hardcopy terminal with the same visual result).

> .. line-endings for some platforms don't include \r and this PR makes simh adhere to that norm.

Line endings stored in files, indeed are different on some platforms, however most, if not all of the cases that are being changed aren't related to data uniquely stored in files.

> .. code behind the sim_debug() macro changes an ending \n to \r\n illustrating correct line endings do matter. Though the PR doesn't address it, I'd argue, that code should insert the \r only when appropriate via the same compile-time conditional.

Joe average users never will be using or seeing any output produced by sim_debug since this is a facility useful for simulator developers who may be troubleshooting some aspect of simulator CPU or device behavior.

The debug process used by these folks "might" direct debug output to a file, or quite commonly will be directing that output to the console session of the simulator process (i.e. STDOUT or STDERR).  When the simulator is running (i.e. when useful debug output will be generated) traffic to the console session is completely in character mode and not in line oriented mode.  In this mode, emitting a bare LF will move the cursor down one line on the screen or a printed page, but WILL NOT return output to the beginning of the line., so the output you're expecting won't actually be realized.  This is true on ALL host platforms and is in no way host platform specific.

As you noticed, sim_debug expands \n to \r\n as debug output is emitted.  This was actually a relatively late addition to the sim_debug behavior.  Early use cases of sim_debug() had explicit \r\n in the output that was specified, while later cases didn't.  The logic in sim_debug only adds a \r prefixing a \n if one wasn't already there.  This, then doesn't require sim_debug users to worry about the detail, and to use the common simple \n for line endings.

So, this concept would be rejected since it actually breaks things (debug output to the console session) rather than solve a real problem.
