### ISSUE TITLE
PDP11 - TPC tape format not correctly read.

### ISSUE THREAD

**Issue by Ventresca68** [simh/simh#940]
Hello,

I'm trying to install fortran v5.3 from a tpc tape but the tape is not correctly recognized from the emulator with this error code:

sim> att ts0 tapes/f77_v5_3.tpc
TS: unit is read only
Forward Record Read returned: no error, Reverse read returned: tape mark
TS: Tape Image 'tapes/f77_v5_3.tpc' scanned as TPC format
After processing 109674 bytes of tape data (11 records, 80 tapemarks)
Read Tape Record Returned Unexpected Status: tape mark
561360 bytes of unexamined data remain in the tape image file

When I try to use it on RSX11-M-PLUS I get this:

$ @ <EOF>
$ all ms0:
$ mou/for ms0:
$ bru /rewind/directory ms0:
BRU -- *FATAL* -- Tape read error
I/O error code -10

$

The pdp11 simulator version is (x86-64):

PDP-11 simulator V4.0-0 Current        git commit id: 52fbdcd1
sim> show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 6.3.0 20170516
        Simulator Compiled as C arch: x64 (Release Build) on Oct 13 2020 at 15:26:06
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.5, PNG Version 1.6.28, zlib: 1.2.8
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap version 1.8.1
        OS: Linux balabam 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
        git commit id: 52fbdcd1
        git commit time: 2020-10-13T05:23:02-07:00
sim> 

The same tape file is correctly mounted and read on another version of pdp11 running on another system (x86):

sim> att ts0 tapes/f77_v5_3.tpc
TS: unit is read only

$ all ms0:
$ mou/for ms0:
$ bru/directory/rewind ms0:
VOL1.   INSTAL	F77V53	26-AUG-1988 10:06:21
VOL1.   CFGF77	F77V53	26-AUG-1988 10:06:37
VOL1.   F77REL	F77V53	26-AUG-1988 10:06:53
VOL1.   PDPF77	F77V53	26-AUG-1988 10:07:09
BRU - Completed

$

This pdp11 simulator version is:

PDP-11 simulator V4.0-0 Current        git commit id: 52e8c7f6
sim> show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 6.3.0 20170516
        Simulator Compiled as C arch: x86 (Release Build) on Jul 25 2018 at 09:02:27
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.5
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux emulatori1 4.9.0-13-686-pae #1 SMP Debian 4.9.228-1 (2020-07-05) i686 GNU/Linux
        git commit id: 52e8c7f6
        git commit time: 2018-07-21T02:22:26-07:00
sim> 

Can someone help me please? :)

Many thanks.

Fabio Bizzi.

**Comment by agn453** [comment]
When I've used TPC format tapes with SIMH PDP11, I've always added a "-f tpc" to the attach command to explicitly set the format.

For example, a TK50 tape set to read-only and TPC format on a TMSCP controller -

set tq enable
set tq TK50
attach tq0 -r -f tpc tapes/f77_v5_3.tpc

A suitably sysgen'ed RSX-11M-Plus system sees this as device MU0:

Tony

**Comment by markpizz** [comment]
Hi @Ventresca68,

Thanks for this thorough report.   

The one missing detail is the tape data that is encountering the error.  Having this, your problem should be easily reproducible,

Please zip up that file and drop it into this issue.

Thanks.

- Mark

**Comment by Ventresca68** [comment]
> Hi @Ventresca68,
> 
> Thanks for this thorough report.
> 
> The one missing detail is the tape data that is encountering the error. Having this, your problem should be easily reproducible,
> 
> Please zip up that file and drop it into this issue.
> 
> Thanks.
> 
> * Mark

Many
[f77_v5_3.zip](https://github.com/simh/simh/files/5377970/f77_v5_3.zip)
 thanks Mark! :)

**Comment by markpizz** [comment]
My first question is: Where did you get this f77_v5_3.zip file?  

I find a file on bitsavers with the same name containing a f77_v5_3.tpc file.  This other file has no problems, but even though the files have the same name and are of similar size, they are distinctly different tape images.

Back to where you got the tape image file?

The data on the tape image appears to be somewhat mangled.

You should be able to observe essentially the same mangling with either version of the simulator you tested with.

There is debug info available at attach time in both 52e8c7f and the latest code.  You can engage this via:
```
sim> SET DEBUG STDOUT
sim> SET TS0 DEBUG=TAPE
sim> attach TS0 -f tpc f77_v5_3.tpc
```

I will explore why you ultimately get different errors while reading this under the PDP11 the operating system, but this may merely be a "garbage-in" producing "garbage-out".

The logic and testing done at attach time exists so that mangled tape data will be reported from within the simulator logic rather than having strange or impossible errors passed down and up through simulated devices,

**Comment by Ventresca68** [comment]
@markpizz I looked at bitsavers site and the only f77_v5_3.zip file I found is for RSTS not for RSX11-M-PLUS. :)

**Comment by markpizz** [comment]
Like I said, the tape image contents were very different, so I wasn't intending to suggest you use the Bitsavers one.

The problem here is that the TPC tape format is very susceptible to possible bit rot in the container file.  That format uses a 16 bit value to indicate the tape record size followed immediately by the data for that record.  A 0 record size indicates a tape mark.  Each record's size is effectively pointed to by the prior record.  If, any record size gets corrupted, the rest of the record sizes won't be found and random data will be interpreted as record sizes all the way through to the end of the container file.  If a record size got corrupted, then surely some data also got corrupted.

I'm guessing that the newest code's tape verification logic interprets some number of multiple successive tape marks as a end of media and that's why you're seeing different behavior.  Any chance you could package (zip) the system disk image and the configuration file you're using along with instructions how to get as far as the "$ bru/directory/rewind ms0:" command you used.  I can then get a precise answer about this behavior.

**Comment by Ventresca68** [comment]
> Any chance you could package (zip) the system disk image and the configuration file you're using along with instructions how to get as far as the "$ bru/directory/rewind ms0:" command you used. I can then get a precise answer about this behavior.

Do you want the images/configs for both the systems (the one with the error and the one that works fine) or only the one that complains?

**Comment by markpizz** [comment]
I don't need the compiled simulators.  I readily regenerate arbitrary versions.  The commit-id identifies that.,

I need, hopefully, a single disk image, along with a minimal configuration file that has the OS on the disk which:
1) using the latest simulator code, generates a failure
 and 
2) using the earlier version, doesn't get the hardware error.

To get this, I'd start from the disk that demonstrates the failure and, move that disk to wherever you've got the older non failuring simulator and prove that that disk doesn't fail.

Thanks.

**Comment by Ventresca68** [comment]
The compressed files are about 26Mb each one, do you have a public ftp/ssh server where I can put them?
If you like I can put them on an http server and paste here the url.
Let me know.
Many thanks. :)

**Comment by Ventresca68** [comment]
Hello Mark, do you have an email addrees where I can write to you the url to pickup the images?
Ore there any way to share it only with you via github (I didn't find how)?
Thank you.

**Comment by markpizz** [comment]
Please send to mark@infocomm.com

Thanks.

**Comment by Ventresca68** [comment]
Mark found that the tape file on the failing system was really corrupted and I found that the tape file on the working PDP isn't corrupted so basically I have two version of the same file, one corrupted and the other not.

I apologize for my fault.

I close the issue.

**Comment by markpizz** [comment]
Please attach the non-failing tape image here.  I'm interested in the details of the actual corruption and others may be interested in seeing this tape image since it wasn't easily located.

**Comment by Ventresca68** [comment]
> Please attach the non-failing tape image here. I'm interested in the details of the actual corruption and others may be interested in seeing this tape image since it wasn't easily located.

No problem, thanks again! :)
[f77_v5_3.tpc.zip](https://github.com/simh/simh/files/5400693/f77_v5_3.tpc.zip)

**Comment by markpizz** [comment]
Careful review of the good vs bad files suggest to me that the bad one was produced by a non-binary mode (i.e. ASCII mode) ftp operation.

The first difference in the files has a removed 0x0D (aka CR character) which had been immediately followed by a 0x0A (aka LF character).
