### ISSUE TITLE
SDS typewriter output problems

### ISSUE THREAD

**Issue by kenrector** [simh/simh#943]
Hi Bob,
Per your suggestion I'm describing 2 problems and their fixes in the SDS typewriter simulator, sds_stddev.c.  Below are my suggested changes with line numbers corresponding to  SIMH version v4.0-19-01.

Problem 1:  Typewriter simulator ignores the  L/N bit(13) in the EOM and
always types a leader character.  This is a random character.

Problem:2  Typewriter simulator does not disconnect from the channel
following a TOP EOM.

I found these problems while running SDS applications, including the FORTRANII compiler.

Concerning problem 1, the leading garbage character. the 910 Theory of Operations, page 2.19 says:

'As with input, the SCR is cleared at the start of output by W9 W6 W5 W4. The first output character is, therefore, all zeros for the first clock signal, which is appropriate for a leader, or a gap in tape punching. For some forms of output, such as leaderless punching or typing, the first output character should be in the character buffer before the first clock signal. For this type of output, an EOM02XXX start instruction with a one-bit in C13 is used. This code bit is used to set W5 which then causes the first loading of the WAR to be followed directly by precession of the first output character into the SCR.'

I believe that what's happening is the sequence:
EOM
MIW                                           loads the WAR with the output word
process_event() calls tto_svc()   outputs a character from the driver buffer.  This is random what ever is in buffer

then,
process_chan() - chan_write()    moves the first character from the WAR to the driver buffer.
process_event calls tto_svc()      outputs a character from the driver buffer.
and so on....

I would fix this with a leader flag, similar to that in the ppo driver.  We shouldn't ever expect to have a leader
for tty output, but checking EOM  N/L looks nice here.

Problem 2, the missing disconnect after TOP is a more severe problem since it can interrupt output completely and cause the program to hang.  This problem depends on how the program is coded, but be aware I found this problem with real SDS programming library code.  Some other programs worked ok.

To fix this, I set the tto_eor flag in the IO_WREOR case and test it and test it in the tto_svc() function to disconnect the channel and clean up.

+194
  { FLDATA (LDR, tto_ldr, 0) },

+553
       tto_ldr = (inst & CHC_NLDR)? 1: 0;              /* leader? */
        tto_eor = 0;

+572
       tto_eor = 1;                                    /* need eor */
        sim_activate (&tto_unit, tto_unit.wait);        /* activate */

+598
 if (tto_ldr == 0) {
    if ((r = sim_putchar_s (asc)) != SCPE_OK) {             /* output; error? */
        sim_activate (uptr, uptr->wait);                    /* retry */
        return ((r == SCPE_STALL)? SCPE_OK: r);             /* !stall? report */
        }
    }
tto_ldr = 0;

+611
if (tto_eor) {
    tto_eor = 0;
    chan_disc (tto_dib.chan);                               /* disconnect */
    tto_unit.buf = 0;                                       /* clear state */
    xfr_req = xfr_req & ~XFR_TTO;                           /* clr xfr flag */
    sim_cancel (&tto_unit);
    }

SDS 940 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)
        Simulator Compiled as C arch: x64 (Debug Build) on Oct 20 2020 at 20:36:35
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.44 2020-02-12) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin kens-iMac-143.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        git commit id: 232804ca
        git commit time: 2020-10-07T17:37:30-0700

**Comment by archivisth** [comment]
Thanks, Ken. I'll take a look at both cause and suggested cure. It's nice to see the SDS simulator getting a workout.

**Comment by markpizz** [comment]
Hi Ken,

You started this discussion with specific mention of:
> I found these problems while running several SDS applications, including one of their tty test programs.

If you've got one or more diagnostic programs that run and potentially have identified problems that are fixed or just exercise the simulator, we'd be glad to add such tests to the V4 build environment.  Since you've already dug into this, you're a good candidate to add such testing.  I'll be glad to work with you to achieve this if you're interested.

Thanks.

- Mark

**Comment by kenrector** [comment]
Hi Mark,

What I have so far are some utilities to run on the Mac to extract files 
from the PAL tape, and some programs I've extracted that way.  My goal 
is to organize these into a kit, as others have done for other 
simulators.  I expect to get this done in a few Kenweeks, (months) and 
then proceed with my real plan which is to get the Digitek FortranII 
source and assemble it and get it running.

I hope you won't mind waiting.

Ken





Mark Pizzolato wrote on 10/21/20 11:08 AM:

**Comment by markpizz** [comment]
Hi Ken,

I'm just planting seeds that hopefully will sprout into useful results whenever you're ready.

- Mark

**Comment by archivisth** [comment]
1. TTY leader.

Does this same problem exist for other serial output devices, like the line printer and the card punch?

If it's just a TTY problem, then making the TTO code parallel the PTP code should fix the problem. Or make the logic always set no leader, regardless of how the bit is set; the first write is always suppressed.

2. TOP.

I this problem is more widespread than just the TTY. I never paid much attention to single-word IO, because the 940 manual more or less deprecates it. But I think at least PTP has the same problem.

Look at these two "utility routines":

t_stat dev_disc (uint32 ch, uint32 dev)
{
chan_uar[ch] = 0;                                       /* disconnect */
if (dev_dsp[dev][ch])
    return dev_dsp[dev][ch] (IO_DISC, dev, NULL);
return SCPE_OK;
}

t_stat dev_wreor (uint32 ch, uint32 dev)
{
if (dev_dsp[dev][ch])
    return dev_dsp[dev][ch] (IO_WREOR, dev, NULL);
chan_flag[ch] = chan_flag[ch] | CHF_EOR;                /* set eor */
return SCPE_OK;
}

Disconnect takes the default action first and then calls the device for specific cleanup. Write EOR, on the other hand, calls the device dispatch first and ONLY sets channel EOR if there is <no> dispatch routine at all, rather than if the dispatch routine did something special. That means CHF_EOR basically never gets set in this flow (every device has a dispatch, after all).

Some devices (like the drum and MUX) don't seem to use EOR at all, but MT, DSK, RAD, LPT, and MT all take device-specific action that ultimately sets CHF_EOR. PTR, PTP, TTI, and TTO do not. Because CHF_EOF doesn't get set, the channel write process doesn't do the disconnect for non-interlaced (DMA) transfers.

Not sure how to solve this. A couple of possibilities:

- Make IO_WREOR in PTP and TTO set CHF_EOF. The code is similar in all both cases:

    chan_set_flag ('dev'_dib.chan, CHF_EOF);

where 'dev' is the correct device data structure.

Question: do PTR and TTI need this as well?

- Create a new status return for IO_WREOR (only) that means 'I didn't do anything'. Fall through to the default action if that return occurs.

- Move the default action up and let other devices clear CHF_EOR if need be. Introduces more bugs, I think.

I'm inclined toward the first option.

**Comment by kenrector** [comment]
Bob,

I looked at the RAD, dsk, lp and mt simulators and they all do pretty much the same thing in their IO_WREOR case. 

Strangely, drum simulator doesn't have an IO_WREOR case defined?

The IO_WREOR case is entered as the result of a TOP EOM, either immediately, or when the buffer is ready.  
Then the CHF_EOR flag is set and the remaining data is written to the file.  
Only the lp sets a local flag so the next svc function call will set CHF_EOR and output it's data.

Change my fix to:

+611
if (tto_eor) {
    tto_eor = 0;
    chan_set_flag (tto_dib.chan, CHF_EOR);              /* set eor flg */
    }

I tried this and it seems ok.

It looks like the pto simulator needs this also.  But for tti, I don't know what Terminate Output would mean on an input device.


Ken

**Comment by archivisth** [comment]
I think that linking TOP to EOR processing shows I made a fundamental mistake in how the instruction is handled. The description doesn't say that end of record is generated. It says that when the last character has been delivered to the device, the device is disconnected. That implies the current processing of TOP is not correct.

1. In op_eomd, if TOP is issued to an output device and the device/channel is idle, disconnect immediately; don't do WREOR.
2. In chan_write, if the character count is 0 after a character is delivered, and there's a TOP pending, disconnect; don't do WREOR.

This will work fine for the PTP, because the character is put in the output file when the character is delivered. The disconnect cancels the delay before setting the next transfer request, but the last character is safely output. It will also work for the LPT, because disconnect forces any buffered characters to be output. It will even work for magtape. However, it won't work for the TTO, because the TTO delays output until the service routine. This causes the leader problem, and it will also cause the last character to be lost on TOP.

So I think the solution has two parts:

1. Make the TTO flows exactly parallel the PTP flows. That solves the leader problem AND the loss of last character on TOP.
2. Change TOP handling to call disconnect instead of EOR, as the manuals indicate.

This is the direction I will pursue.

**Comment by archivisth** [comment]
There's a bit more complexity because the TTY output can stall in sim_putchar_s. This means a retry mechanism is needed too. But the outline above appears to be directionally correct.

**Comment by markpizz** [comment]
1) While considering the sim_putchar_s retry problem, I notice that sim_putchar (without the _s) is used at character reception time for echo.  Should retry considerations be relevant here?

2) Similarly, after sim_putchar_s has succeeded, it seems that sim_putchar (again without the _s) is called to push out a LF after a CR has been successfully delivered.  It would seem that the logic that retries the initially stalled sim_putchar_s should also solve the retry for the related LF when needed.

**Comment by archivisth** [comment]
Actually, none of the half-duplex terminal input devices (1401, 1620, 
PDP1, etc) use sim_putchar_s for echo.

**Comment by kenrector** [comment]
I have tested changes supplied by Bob to sds_io.c and sds_stddev.c and they correct the problem I reported for this issue.  The changes do not have any negative effect in any of the other programs I use, Fortran, Symbol. etc.

None of these programs use RAD, disk or drum drivers and only the simplest MT io.
