### ISSUE TITLE
Link directly against libraries like libncurses, libreadline, libpcap, libuuid

### ISSUE THREAD

**Issue by eschaton** [simh/simh#964]
Using `dlopen()` and `dlsym()` to load and use libraries at runtime like libncurses, libreadline, libpcap, and libuuid doesn’t actually win SIMH anything, and in addition to adding a lot of complexity, it also opens SIMH up to some very subtle potential bugs.

As an example of the type of bug it can expose SIMH to, a library could preserve an existing API but rename it for “new” clients via macros, and SIMH would still wind up using the old API rather than the new one. (macOS has done this in the past with numerous POSIX APIs, mainly for things like 32/64-bit inode compatibility and conformance improvements that require preservation of existing behavior to not break existing software.)

Another very subtle problem this can expose SIMH to is that SIMH has to *exactly* match the prototypes of all of the APIs in these libraries, which can change from release to release of the libraries and in the face of compiler differences and so on, which SIMH won’t necessarily be able to react to. For example, a library like `libpcap` could adopt compiler-specific “hardening” attributes on its declarations, but since the calls are through function pointers with their own declarations, SIMH won’t get the advantage of these attributes even when using a compiler that supports them.

Switching to direct linkage will also reduce overall complexity in the codebase.

**Comment by markpizz** [comment]
The mechanisms you're concerned about aren't really problems with simh's use of various shared libraries.  They've been in use for the better part of a decade.  When funcctional API changes happen with libraries like this, new library versions with different API signatures are produced specifically to avoid problems with dependencies on prior interfaces.  Your concern appears to have arisen due to problems actually locating/using these various shared libraries on macOS 11.  You described theoretical problems, but didn't actually offer any solution to the problem you observed.  Meanwhile a handful of platform specific lines in the simh makefile now fixes the original problems that sent you down this path.

I'm closing this issue now since the underlying problem has been addressed.

**Comment by eschaton** [comment]
This should be reopened as the actual problem described in this issue has not been addressed.

I discussed real problems that have hit other projects in similar situations because of things like symbol renaming in macOS. People often assume that because it’s a UNIX, that macOS is “just like Linux” and that everything they do will work the same way. This is the 2000s equivalent of “all the world’s a VAX” and its predecessor, “all the world’s a PDP-11,” and is just as inaccurate.

Just because you have not run into these problems in practice does not mean they don’t, can’t, or won’t exist.

I offered a solution to the very real problem present in the way SIMH uses these libraries: Link the libraries normally. The approach used by SIMH provides little actual value and has a variety of downsides, some of which can be quite subtle and difficult to debug. Switching to a mainstream approach to use of shared libraries will help keep SIMH running far longer than trying to fight against any change.

**Comment by markpizz** [comment]
This is like running into a building and saying it is on fire.  In fact it is NOT on fire.  This is a clear case of "it ain't broke", so no effort on my part will be made to fix it.

Other than "you shouldn't do these things this way" you don't actually provide a solution (where you work through the details of the code to solve this for ALL platforms) which addresses all YOUR concerns.

Note: If any of those "theoretical reasons" ever actually becomes true at some time in the future, a solution to the particular problem that actually occurs will be addressed WHEN that actually happens.

Note that this project is all about simulators which simulate computers and run the simulated computer's instructions.  Essentially none of the uses of any API which is accessed via a dlopen() and dlsym() are critical to the primary purpose of any simulator.  If all of these cases didn't work at all, simulators would still be fully capable of performing all of their primary functions.

If you are so worried about these possible future problems without me providing your suggested fixes, no one is forcing you to use such risky software.

**Comment by eschaton** [comment]
This is more like visiting a house full of stacks of old newspapers and saying “you should do something about the fire hazard,” to which you retort “nothing is on fire right now, and even if they were nothing important would be damaged.”

Technical debt is a thing that exists in large projects. I’m pointing out one area of SIMH that has it in a surprising form. (Just like the surprising technical debt in the default build system, where instead of using the dependency graph features `make` offers, SIMH turns it into a procedural scripting system that conflates things like building common code, building simulator-specific code, and running tests for a simulator.)

All I’m doing is pointing out ways that SIMH can be improved, because I can’t currently do more than that. If I had the authorizations necessary to submit PRs instead of just filing bugs, I’d be doing that, believe me.

**Comment by rcornwell** [comment]
One important thing that many new developers to SimH do not understand is that minor changes to the SCP code can break simulators in weird and not obvious ways. So the ability to test as many simulators as possible is very important to developers.

Also while having the SCP code as a library is nice for people like me who develop several simulators. But most users of SimH only build 1 or 2 simulators. Which does not take much time. There are several changes I myself would like to see to SCP, some make it some don't. I would like to see it such that only the required modules need to be included, I personally do not like name space pollution.

Make is also probably the best for SimH since it is probably the most portable to any platform. Using things like cmake or other build systems require that these tools be installed before the system can be built.
