### ISSUE TITLE
PDP-10 compatibility with klh-10

### ISSUE THREAD

**Issue by Rhialto** [simh/simh#98]
I have a (by now modified) Panda distribution of Tops-20. It has instructions and a configuration file on how to run it on klh10.
It would be nice if the documentation could contain a section on what configuration commands are equivalent to those commands, or some other example of how to run Panda.
Thanks!

**Comment by larsbrinkhoff** [comment]
The original question remains: What conversion would be needed to use a KLH10 disk image with SIMH, or vice versa?  Of course, TOPS-20 v7 is out of the question, but obviously there are other operating systems that work with both emulators.

@R-Voorhorst Is the SIMH disk image format documented somewhere?

@Rhialto I see KLH10 supports several disk image formats.  What are they, exactly?

**Comment by R-Voorhorst** [comment]
L.S.

 

Klh10 knows the format simh for disks next to dbd9 in the format spec for disks.

 

 

Best regards

**Comment by markpizz** [comment]
FYI:  Someone (Cory if I recall correctly) once asked why a simh RP/RM disk image for a simh PDP11 wasn't the same size as the same disk type disk image for a PDP10.

I looked into this and discovered that the reason comes back to how the simulator stores data in memory.  The PDP10 simulator stores each 36 bit word of data in a 64 bit (long long) in host memory.  Disk DMA moves words of data between memory and disk, so it is natural to merely move the complete 64 bits directly without having to worry about any funky packing/unpacking between the 8bit addressable files we've got today.  The wasted space is of no real concern given modern storage capacities compared ot the maximum size of the devices being simulated.  BTW, the 64 bit data is stored in Little-Endian byte order and simh PDP10 disk images are interchangeable between Little-Endian and Big-Endian host systems.

Given that these disks were never used as interchange media between PDP10 and other systems, the difference in size in for the same simulated RP/RM devices isn't too important.

Given the above explanation, I just now dug through klh10/vdisk.c and it seems that dlw8 reflects the general concept that represents the simh disk format.  I didn't check to see if the geometry that the various disk types have are 100% consistent between the klh10 and simh environments.  I don't think the geometry should be a problem given that the OSes that run on this hardware generally have hard coded internal geometry information for each disk type.
