### ISSUE TITLE
Handle non-seekable files attached to SEQ units

### ISSUE THREAD

**Issue by leobru** [simh/simh#982]
In scp.c, around line 8738:
```
        if ((uptr->flags & (UNIT_ATT + UNIT_SEQ)) == (UNIT_ATT + UNIT_SEQ))
            if (sim_fseek (uptr->fileref, uptr->pos, SEEK_SET))
                return sim_messagef (SCPE_IERR, "Can't seek to %u in %s for %s\n", (unsigned)uptr->pos, uptr->filename, sim_uname (uptr));
```
When a file is attached with a -a flag, that file might not be seekable with SEEK_SET (e. g., I might want to direct the LPR output to /dev/tty); therefore, for files attached in the APPEND mode, seeking to the end of file should be performed instead, or the error condition should be handled gracefully.

**Comment by leobru** [comment]
Perhaps, when the file is not seekable,  "-a" should be implied?

**Comment by markpizz** [comment]
You had said (I'm not sure where):

>Perhaps, when the file is not seekable, "-a" should be implied?

-a only has meaning at attach time.  

Seeking is done on Sequential files before execution starts (or restarts after STEP or similar).  This exists since the UNIT->pos variable is usually represented by a simh REGister (often named POS), and various documents specifically describe that a Sequential file's position can be updated by a user changing the POS variable to a desired value.

**Comment by leobru** [comment]
I see, thank you. Then the help message for the `-a` switch "the file being attached will be opened in append mode" is ambiguous because it might as well be understood as opening with `O_APPEND`.
