### ISSUE TITLE
Release build resulted in 12 failed projects because of link error

### ISSUE THREAD

**Issue by Phi-Ho** [simh/simh#985]
- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

Greetings,

Please advise if I missed something.

Under Visual Studio 2019, Debug build was successful. Release build resulted in 12 failed projects because of link error:

LINK : fatal error C1047: The object or library file '..\..\windows-build\lib\Release\\libpng16.lib' was created by a different version of the compiler than other objects like:

..\BIN\NT\Project\simh\TX-0\Win32-Release\display.obj
..\BIN\NT\Project\simh\VAX\Win32-Release\pdp11_cr.obj
..\BIN\NT\Project\simh\MicroVAX2000\Win32-Release\scp.obj

The affected projects are:

Done building project "VAX.vcxproj" -- FAILED.
Done building project "PDP7.vcxproj" -- FAILED.
Done building project "TX-0.vcxproj" -- FAILED.
Done building project "MicroVAX1.vcxproj" -- FAILED.
Done building project "MicroVAX2.vcxproj" -- FAILED.
Done building project "PDP10-KA.vcxproj" -- FAILED.
Done building project "PDP6.vcxproj" -- FAILED.
Done building project "PDP10-KI.vcxproj" -- FAILED.
Done building project "PDP1.vcxproj" -- FAILED.
Done building project "MicroVAX2000.vcxproj" -- FAILED.
Done building project "VAXstation3100M76.vcxproj" -- FAILED.
Done building project "VAXstation3100M38.vcxproj" -- FAILED.
Done building project "VAXstation3100M30.vcxproj" -- FAILED.
Done building project "PDP11.vcxproj" -- FAILED.
Done building project "imlac.vcxproj" -- FAILED.
Done building project "tt2500.vcxproj" -- FAILED.

Regards,

phiho

**Comment by markpizz** [comment]
The problem here relate to the fact that the "Latest Visual Studio" version is somewhat of a moving target.  VS2019, being the latest "Visual Studio" version is updated by Microsoft as  time goes on.  All projects built using VS2019 when that specific support was added, but new installations indeed have the build problems you identify.

The easiest way to build the windows binaries is to build with a stable (unchanging) tool chain.  The simplest of these is to use Visual Studio 2008 since that is the minimal baseline support.  Details of how to download this version of Visual Studio can be found in the file "Visual Studio Projects\0ReadMe_Projects.txt".  VS2008 can co-exist side-by-side with VS2019 without any problems.

**Comment by pghardy** [comment]
To alleviate these building problems (which I also reported on SimH list), why not set up an automated system to ensure that the github downloadable Windows development binaries are rebuilt weekly (as advertised), so people don’t need to fight through rebuilding from sources themselves?

 

Why haven’t they been rebuilt since June 2020?

 

 

-- 

Paul  Hardy

web: www.paulhardy.net <http://www.paulhardy.net/>

**Comment by markpizz** [comment]
The concept of having everything be "usable" depends on the degrees of problems that are being worked (slowly) at any one time.  Recently things have sort of been in flux and my gut says "not quite ready for prime time".  During different phases of activity in this repo, things may be very stable/usable for many months, but distinctly less so during other times.  This is one of those down times and sometimes builds aren't posted since changes aren't functionally relevant.  
I'm in the middle of some significant rework right now, so I don't expect to post a new build until that is done which I expect in less than a weeks time.

Meanwhile, the build problem you're reporting is in the Release build.  The Debug builds actually build cleanly which I'm surprised about.  In any case, they may not run as fast as cleanly built Release versions, but they will function quite well...

**Comment by pghardy** [comment]
Mark Pizzolato said at the beginning of January:

> I'm in the middle of some significant rework right now, so I don't expect to post a new build until that is done which I expect in less than a weeks’ time.

 

Has a (simulated) week passed yet?  The Windows binaries are eight months old now.

 

-- 

Paul  Hardy

web:  <http://www.pghardy.net> www.pghardy.net

**Comment by pghardy** [comment]
The Windows binaries are a year old this week. So today I  jumped through all the hoops to install the source and support components and build SimH local from today’s sources, only to get an error running SimH Vaxstation 3100M38  saying; “SIMH has encountered a bug in SDL2.  An upgrade to SDL2 version 2.0.14 should fix this problem”. However,  the Windows-build download on GitHub only includes 2.0.10.

 

Please can we have a mechanism for keeping the windows binaries, and the windows  build components reasonably up to date?

 

-- 

Paul  Hardy

web:  <http://www.pghardy.net> www.pghardy.net 

 


Sent: 12 February 2021 16:24
To: 'simh/simh' ***@***.***>; 'simh/simh' ***@***.***>
Subject: RE: [simh/simh] Release build resulted in 12 failed projects because of link error (#985)

 

Mark Pizzolato said at the beginning of January:

> I'm in the middle of some significant rework right now, so I don't expect to post a new build until that is done which I expect in less than a weeks’ time.

 

Has a (simulated) week passed yet?  The Windows binaries are eight months old now.

 

-- 

Paul  Hardy

web:  <http://www.pghardy.net> www.pghardy.net

**Comment by markpizz** [comment]
The release builds now are clean using VS2008 thru VS2022.  The latest/last version of VS2019 will build them cleanly now as well.  VS2022 might run into a similar problem if updates to that may change the compatibility of the binaries.  We'll see if/when that happens.
