### ISSUE TITLE
Enhancement proposal:  Extend help on VAX/PDP Ethernet devices XU and XQ command 

### ISSUE THREAD

**Issue by vaxorcist** [simh/simh#993]
- #### Context
Recent help on VAX/PDP Ethernet devices XU and XQ command is incomplete and confusing.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
State as of now:
```
help xu
...
set XU THROTTLE=DISABLED|TIME=n{;BURST=n{;DELAY=n}}
                              	Display transmit throttle configuration
...
```
- #### how you built the simulator or that you're using prebuilt binaries
cloned from github

- #### the expected behavior and the actual behavior
Enhancements proposed:
- Explain meaning and usage of parameters:
  - `<TIME>`
  - `<BURST>`
  - `<DELAY>` 
- Give advice on reasonable parameter settings
- Name default parameter values
- Add command `<show XU>` (Help shown, but command missing)

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by vaxorcist** [comment]
**Correction**
The help on the XQ device is better than that on the XU device:
```
HELP XQ CONF SET THROTTLE
...
Throttling is configured with the SET XQ THROTTLE commands:

    sim> SET XQ THROTTLE=DISABLE
    sim> SET XQ THROTTLE=ON
    sim> SET XQ THROTTLE=TIME=n;BURST=p;DELAY=t

TIME specifies the number of milliseconds between successive packet
transmissions which will trigger throttling.
BURST specifies the number of successive packets which each are less than
the TIME gap that will cause a delay in sending subsequent packets.
DELAY specifies the number of milliseconds which a throttled packet will
be delayed prior to its transmission.
```
Although there is an explanation of the throttle parameters here,
some advice on reasonable parameter settings as well as the default parameter values is still missing.

**Comment by markpizz** [comment]
This functionality you are asking about exists, and the general algorithm that implements it, due to the fact that Johnny Billiquist long had (has) a software Ethernet bridge which existed to support HECnet.  His observations that modern hardware AND modern simulator software can sometimes overrun original legacy hardware on local LANs.  The original systems ran at a fraction of 10Mbit and often had small/single packet buffers for incoming traffic which need to be digested before subsequent packets can arrive in the hardware.  Without reasonable interpacket delays, the receiving network device (DEQNA or other NIC) and/or its host  (Real PDP11 and friends) could experience excessive packet loss/corruption due to buffers in the receiving network device being overrun.

Reasonable settings are not to enable this feature in most circumstances unless you are talking to real hardware with slow network interfaces.  This is the whole story.  

I'll be glad to enhance the XQ/XU HELP language to clarify things.    Please propose specific changes.

**Comment by markpizz** [comment]
Please look at the latest and close this issue if things look good.
